<?php
//$dir='ASC';
 $order=$this->order;
 $dir = ($order!='default' && $order =='ASC')?'DESC':'ASC';
?>
<div id="priority_popup" style="display:none;"></div>
<section class="w-48 fr ch-home-form">
							 <table class="priority-list" width="100%">
								 <tr>
									 <th>&nbsp;</th>
									 <th><a href="javascript:void(0)" onclick="showPriorityList('<?php echo $this->select_build_id;?>','<?php echo $dir;?>')">Priority Name <?php if($order!='default'){?> <span class="<?php echo $order?>">00</span><?php }?></a></th>
									 <th>Priority Description</th>
									 <th>Active</th>
									 <th>Action</th>
								 </tr>
								 <?php 
								      if(!empty($this->priorityDetail)){
								        foreach($this->priorityDetail as $pri_detail){?>
											<tr id="show_priority_id_<?php echo $pri_detail['pid']?>" class="show-priority">
											    <td><div class="open_plus" id="open_div_<?php echo $pri_detail['pid'];?>"><a href="javascript:void(0);" id="<?php echo $pri_detail['pid'];?>" onClick="return showPriorityScheduleList(<?php echo $pri_detail['pid'];?>,'')";><?php echo '&nbsp;&nbsp;';?></a></div></div></td>
												<td><?php echo $pri_detail['priorityName']?></td>
												<td><?php echo $pri_detail['priorityDescription']?></td>
												<td><?php echo ($pri_detail['status'])?'Yes':'No'?></td>
												<td><div class="col02 coladdlastcol lastcol edit_delete_icon"><a href="javascript:void(0);" onclick="showEditPriority('<?php echo $pri_detail['pid']?>')"  data-id="<?php echo $pri_detail['pid']?>" title="Edit"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a> <a href="javascript:void(0);" onclick="deletePriority('<?php echo $pri_detail['pid']?>')" data-id="<?php echo $pri_detail['pid']?>" title="Delete"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a></div></td>
											</tr>
											<tr id="edit_priority_id_<?php echo $pri_detail['pid']?>" style="display:none" class="edit-priority">
											    <td><div class="open_plus" id="open_div_<?php echo $pri_detail['pid'];?>"><a href="javascript:void(0);" id="<?php echo $pri_detail['pid'];?>" onClick="return showPriorityScheduleList(<?php echo $pri_detail['pid'];?>,'')";><?php echo '&nbsp;&nbsp;';?></a></div></div></td>
											    <td><input type="text" value="<?php echo $pri_detail['priorityName']?>" name="priority_name" id="priority_name_<?php echo $pri_detail['pid']?>"/></td>
												<td><input type="text" value="<?php echo $pri_detail['priorityDescription']?>" name="priority_description" id="priority_description_<?php echo $pri_detail['pid']?>"/></td>
												<td>
													<select name="status" id="status_<?php echo $pri_detail['pid']?>">
												      <option value="1" <?php if($pri_detail['status']==1) echo 'selected';?>>Yes</option>
												      <option value="0" <?php if($pri_detail['status']==0) echo 'selected';?> >No</option>
												   </select>
												</td>
												<td><div class="col02 coladdlastcol lastcol yesnotooltips"><a href="javascript:void(0);" onclick="editPriority('<?php echo $pri_detail['pid']?>')" data-id="<?php echo $pri_detail['pid']?>" class="editcmpny" title="Save"><img src="<?php echo BASEURL . 'public/images/yes_icon.png'?>" /></a><a href="javascript:void(0);" onclick="hideEditPriority('<?php echo $pri_detail['pid']?>')" data-id="<?php echo $pri_detail['pid']?>" class="hideeditcmpny" title="Cancel"><img src="<?php echo BASEURL . 'public/images/no_icon.png'?>" /></a></div></td>
											</tr>
											<tr id="tr_schecdule-<?php echo $pri_detail['pid']?>" class="show-tr-schlist" style="display:none">
												<td>&nbsp;</td>
												<td colspan="4" class="margin_padding_none" id="show_priority_schedule_<?php echo $pri_detail['pid']?>"></td>
											</tr>
								  <?php }?>
                                    <?php 
										/*
										 pagination code. 
										*/
										?>  										
										 <input type="hidden" name="priority_page" id="priority_page" value="<?php echo $this->page;?>"/>
										 								  
								  <?php }else{ ?>
									     <tr>
											 <td colspan="5">
												 No priority created. Pease create new priority!!!
											 </td>
									     </tr>
									  <?php }?>
									  <tr id="add-priority-td" style="display:none">
										  <td colspan="5">									  
									       <div class="priority_block_main">			  
									      <div id="priority-form" class="priority_block">
											  <section class="consol_form_head">
													<h3>Add New Priority</h3>
											   </section>
											   <section class="w-48 fr ch-home-form ad-ptform">
											      <form name="addNewPriority">
													  <input type="hidden" name="actionType" value="insert">
														<input type="hidden" name="building_id" id="building_id" value='<?php echo $this->select_build_id;?>'>
														<?php /*<div class="row">
															<label>Id* :</label>
															<span class="prioNumErr" id="priority-number-error"></span> 
															<input type="text" value="<?php echo $this->priorityDetail['id']?>" id="pid" 
																   name="data[pid]" readonly="readonly">														  
														</div>*/?>
														<div class="row">
															<label>Priority Name <span class="required">*</span> :</label>
															<span class="priNameErr" id="priority-name-error"></span> 
															<input type="text" id="priority_name" name="priorityName" value="">
														</div>
														<div class="row">
														   <label>Priority Description<span class="required">*</span> :</label> 
														   <span class="priDescErr" id="priority-description-error"></span>
														   <input type="text" id="priority_description" name="priorityDescription"  value="">
														</div>
														<div class="row">
														<label>Active<span class="required">*</span> :</label> 
														<select name="status" id="status" class="status">
															<option value="1">Yes</option>
															<option value="0">No</option>
														</select>
														</div>
														
														
														 <div class="confirmBtn">
															<input type="reset" value="Reset" name="reset" class="cancel"/>
															<input type="button" value="Save" name="next" id="save_priority" class="confirm savePriority" onclick="return addPriority()"/>
															<input type="button" value="Cancel" name="cancel" class="cancel" onclick="hidePriorityForm()"/>
														</div>
											      </form>
											   </section>    
									      </div>
                                          </div>
									      </td>
									  </tr>
									  <tr>
										  <td colspan="5" class="add_record"><a href="javascript:void(0)" onclick="showPriorityForm()"><span>Add New Record</span></a></td>
									  </tr>	
								 </table>
							</section>                          
</div>
