<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/building.js');
/*
 * Company listing section
 */
   $order = $this->order;
   $dir = $this->dir;
   $cndir = 'ASC';
   $andir = 'ASC';
   $sdir = 'ASC';
   if($order=='companyName')
      $cndir = ($dir=='ASC')?'DESC':'ASC';
   else if($order=='acnum')
      $andir = ($dir=='ASC')?'DESC':'ASC';
   else if($order=='status')
      $sdir = ($dir=='ASC')?'DESC':'ASC';
?>
<div id="msg" class="welcome_text"></div>
<div class="panel-body" id="companyListData">
      <div class="table-responsive">
	<?php if(count($this->companyListing)>0 && !empty($this->companyListing)){ ?>
	<div class="combuilding-infromation" id="combuilding_info">
     <div id="combuilding_popup" style="display:none;"></div>	
   <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer">
	   <thead>
                        <tr>
							<th>&nbsp;</th>
							<th><a href="<?php echo BASEURL.'building/index/order/companyName/dir/'.$cndir?>"
                           class="<?php if($order=='companyName') echo $dir; else echo 'sorting';?>">Company Name</a></th>
                          <th><a href="<?php echo BASEURL.'building/index/order/acnum/dir/'.$andir?>"
                            class="<?php if($order=='acnum') echo $dir; else echo 'sorting';?>">Account</a></th>
                                                   
                          <th>Date Activated</th>
                          <th><a href="<?php echo BASEURL.'building/index/order/status/dir/'.$sdir?>"
                           class="<?php if($order=='status') echo $dir; else echo 'sorting';?>">Active</a></th>                         
                         
                        </tr>
                      </thead>
                      
                      <tbody>		
						   <?php $i=1;foreach($this->companyListing as $companydata){
							          if($companydata['status']==1){
							   ?>
							    <tr class="rowGrid <?php if($i%2!==0){?>utr<?php }?> showCompany" id="compID-<?php echo $companydata['cust_id'];?>">
							    <?php /*<td><a href="javascript:void(0)" id="<?php echo $companydata['cust_id'];?>" onClick="return showBuildingList(<?php echo $companydata['cust_id'];?>,'')">
								  <i id="plus_<?php echo $companydata['cust_id'];?>" class="fa fa-plus blackfont_color plus_min_icon"></i></a></td>*/?>
								  <td id="open_div_<?php echo $companydata['cust_id'];?>" class="open_plus"><a href="javascript:void(0);" id="<?php echo $companydata['cust_id'];?>" onClick="showBuildingList(<?php echo $companydata['cust_id'];?>,'')";><?php echo '&nbsp;&nbsp;';?></a></td>
								  <td><?php echo $companydata['companyName'];?></td>
								  <td><?php echo $companydata['corp_account_number'];?></td>
								  <td><?php echo date('M d, Y',strtotime($companydata['activationDate']));?></td>
								  <td><?php if($companydata['status']==1){echo "Yes";}else{echo "No";};?></td>								  
								</tr>
								<tr class="buildingContainer" id="buildingContainer-<?php echo $companydata['cust_id'];?>" style="display:none">
								    <td>&nbsp;</td>
								    <td id="building_list_<?php echo $companydata['cust_id'];?>" colspan="4"></td>
							   </tr>	  			
						 
						  <?php $i++;}} ?>
		         </tbody>
		  </table>
			<div class="fade_default_opt" id="fd_dft_div" style="display:none">	
				<a href="#show_edit_form" id="show_edit_form_href" class="modalbox">&nbsp;</a>	
				<div id="show_edit_form" class="bd-dft-cls" style="display:none"></div>
			</div>
    <?php
	/*
	 * pagination code
	 */
	?>
    <?php 
		echo $this->paginationControl($this->companyListing, 'Sliding', 'pagination.phtml');
		?>
		</div>
		<?php
		}else{?>
				 Empty records
	 <?php }?>  	
</div>
<div class="divOverlay" style="display:none;" ></div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
