<?php
    if($this->buildrecord){
		$buildList = $this->buildList;
		$cust_id = $this->cust_id;
?>
<div class="building-list">
			<section class="w-48 fr ch-home-form" id="buildList">
			<table  width="100%" class="table table-striped table-bordered table-hover">
				 <tr>
						<th>Building Name</th>
						<th>Address</th>
						<th>Phone</th>
						<th>City</th>
						<th>State</th>
						<th>Active</th>
						<th>Action</th>											
				</tr>
				<?php
						if(count($buildList) > 0 && !empty($buildList)){
				$i=1;
				$dataString ='';
				foreach($buildList as $bl){
					$st = ($bl["status"] == '1') ?  "Yes" : "No";
					$dataString .= '
						 <tr id="build-'.$bl['build_id'].'">
								<td>'.$bl["buildingName"].'</td>
								<td>'.$bl["address"].'</td>
								<td>'.$bl["phoneNumber"].'</td>
								<td>'.$bl["city"].'</td>
								<td>'.$bl["statename"].'</td>
								<td>'.$st.'</td>
								<td class="border_none edit_delete_icon"><a title="Edit" href="javascript:void(0);" onClick="editBuilding('.$cust_id.','.$bl['build_id'].');"><img src="'. BASEURL . 'public/images/edit.png" /></a>  <a title="Delete" href="javascript:void(0);" onClick="deleteBuilding('.$bl['build_id'].');"><img src="'.BASEURL . 'public/images/delete.png" /></a></td>
						</tr>
						
				'; 				
			
				$i++;}
				echo $dataString;
			}else{
				?><tr>
								<td colspan="7" class="no_record">No Record Found!</td>
						</tr>
		<?php	}?>	

</table></section></div>
<?php
}else
  echo 'Error Showing in Building List';
?>
