<div class="woreport-section">
	 <div class="report-title">
		 <span><h1>Work Order Report</h1></span>
	 </div>
	 <div class="work-order-report">
		  <div class="download-report">
			  <div class="download-button">
			     <input type="button" name="download_csv" value="Download PDF Report" onclick="window.location.href='<?php echo BASEURL.'report/dlworkreport/type/pdf';?>'"/>
			     <input type="button" name="download_csv" value="Download Excel Report" onclick="window.location.href='<?php echo BASEURL.'report/dlworkreport/type/excel';?>'"/>
			   </div>
		  </div>
		  <div class="table-responsive">
                  <div role="grid" class="dataTables_wrapper form-inline" id="dataTables-example_wrapper">
					  <table class="table table-striped table-bordered table-hover dataTable no-footer">
						  <thead>
							  <tr class="rpr-header">
								  <th>Date Received</th>
								  <th>Time Received</th>
								  <th>Work Order#</th>
								  <th>Current Status</th>
								  <th>Category</th>
								  <?php /* <th>Company</th> */?>
								  <th>Building</th>
								  <th>Contact Information</th>
							  </tr>
						  </thead>
						  <?php 
							 if($this->wolist){
								  $ssModel = new Model_ScheduleStatus();
								$status_list = $ssModel->getScheduleStatus();
								$status_array= array();
								foreach($status_list as $sl){
									if($sl['ssID']!=8)
									$status_array[$sl['ssID']] = $sl['title'];
								}
								
								$woModel = new Model_WorkOrder();
								$j=0;
								foreach($this->wolist as $wl){									
									$wodetail = $woModel->getWorkOrderInfo($wl->woId);
									$woData = $wodetail[0];
									$row_class = ($j%2==0)?'even-row':'odd-row';
								 ?>
								 <tr class="<?php echo $row_class;?>">
									 <td><?php echo date("m/d/Y",strtotime($wl->created_at))?></td>
									 <td><?php echo $wl->time_requested?></td>
									  <td><?php echo $wl->woId?></td>
									  <td><?php echo $status_array[$wl->wo_status];?></td>
									  <td><?php echo $wl->categoryName?></td>
									  <?php /*<td><?php echo $wl->tenantName?></td>*/?>
								      <td><?php echo $wl->buildingName?></td>
								      <td rowspan="2">
								          <div class="contact_information">
											  <table width="100%">
											       <tr>
													   <th>Request By:</th>
													   <td><?php echo $woData->firstName.' '.$woData->lastName;?></td>
											       </tr>
											       <tr>
													   <th>Email:</th>
													   <td><?php echo $woData->email;?></td>
											       </tr>
											       <tr>
													   <th>Location:</th>
													   <td><?php echo $woData->tenant_suite;?></td>
											       </tr>
											       <tr>
													   <th>Phone:</th>
													   <td><?php echo $woData->phoneNumber;?></td>
											       </tr>
											  </table>
								          </div>								      
								      </td>
								 </tr>
								 <tr class="<?php echo $row_class;?>">
									 <th>Work Request:</th>
									 <td colspan="5"><p><?php echo $wl->work_order_request;?></p></td>
								 </tr>
								<?php 
								$j++;
								} 
						      }
						  ?>
					  </table>
					   <?php if(count($this->wolist)>0 && !empty($this->wolist)){
					 echo $this->paginationControl($this->wolist, 'Sliding', 'pagination.phtml'); 
					 }?>
				  </div>
		   </div>		  	  
	 </div>
</div>
