<?php    $this->headLink()->appendStylesheet($this->baseUrl() . '/public/tabs.css');
         $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap.css');
         $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap-editable.css');
 ?> 
<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/company.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap-editable.js');


// to check the read,write and no access
$building_info = $this->acessHelper->checkAccess($this->roleId,$this->building_location_id);
/*
 * Company's building section
 */
?>
<div class="container-right" id="companyListData">
    <?php  
       if($this->roleId!=1 && $building_info->is_access == 0 ){   
    if($this->custID!=null && $this->custID && $this->companyListing!='' && $this->companyListing!=false){ 
			?>	
		<div id="contents">
			<ol id="toc">
				<?php 
					$j = 1;
					foreach($this->companyListing as $cb){ ?>
					<li><a href="#page-<?php echo $j; ?>"><span><?php echo $cb['buildingName']; ?></span></a></li>
		
				<?php $j++; } ?>
			</ol>
			<?php			
			$i = 1;
			$pageStr = '';
			$buildingMapper=new  Model_Building();
				foreach($this->companyListing as $cb){
					$buildData = $buildingMapper->getbuildingbyid($cb['build_id']);
					$c = $buildData[0];
					
			?>		
					<div class="content" id="page-<?php echo $i; ?>">

					     <div id="accordion-info-<?php echo $i; ?>">
								<?php // echo $c['build_id']; ?>
								<?php //echo $c['cust_id']; ?>
								<?php //echo $c['buildingName']; ?>
							<?php if($building_info->is_write==1 || $building_info->is_read==1){ ?>	
							   <h3>Building Information</h3>
							    <div id="building-info-div">									   
									    <div class="field_edit_popup">
											<label>Building Name</label><span>:</span>
											<?php echo $c['buildingName'];?>
											<?php /*if($building_info->is_write==1){ ?>
									         <a href="#" class="buiding" id="build-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Name" data-placeholder="Required" data-name="buildingName"><?php echo (!empty($c['buildingName']))?$c['buildingName']:''; ?></a>
									         <?php }
									         else{
									         		echo (!empty($c['buildingName']))?$c['buildingName']:''; 
									          }*/ ?>
									   	</div>
											
										<div class="field_edit_popup"><label>Address</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>
										  <a href="#" class="address" id="addr-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Address" data-placeholder="Required" data-name="address"><?php echo (!empty($c['address']))?$c['address']:''; ?></a>	
									   <?php }
								         else{
								         		echo (!empty($c['address']))?$c['address']:''; 
								          } ?>									
										</div>
										<div class="field_edit_popup"><label>Address2</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>
										   <a href="#" class="address2" id="addr2-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Address" data-name="address2"><?php echo (!empty($c['address2']))?$c['address2']:''; ?></a>
										<?php }
								         else{
								         		echo (!empty($c['address2']))?$c['address2']:''; 
								          } ?>	   
										</div>
																														
										<div class="field_edit_popup"><label>City</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>
										   <a href="#" class="city" id="cit-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building City" data-placeholder="Required" data-name="city"><?php echo (!empty($c['city']))?$c['city']:''; ?></a>
										<?php }
								         else{
								         		echo (!empty($c['city']))?$c['city']:''; 
								          } ?>	   
										</div>
										
										<div class="field_edit_popup"><label>State</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>
										     <a href="#" class="state" id="stat-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building State" data-placeholder="Required" data-name="state"><?php echo (!empty($c['state']))?$c['state']:''; ?></a>
										<?php }
								         else{
								         		echo (!empty($c['state']))?$c['state']:''; 
								          } ?>	     
										</div>
										
										<div class="field_edit_popup"><label>Postal Code</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>
										    <a href="#" class="postal" id="post-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Postal Code" data-placeholder="Required" data-name="postalCode"><?php echo (!empty($c['postalCode']))?$c['postalCode']:''; ?></a>
										<?php }
								         else{
								         		echo (!empty($c['postalCode']))?$c['postalCode']:''; 
								          } ?>    
										</div>
										
										<div class="field_edit_popup phone_field"><label>Phone Number</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>
										     <a href="#" class="phone" id="phon-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Phone" data-placeholder="Required" data-name="phoneNumber"><?php echo (!empty($c['phoneNumber']))?$c['phoneNumber']:''; ?></a>
										<?php }
								         else{
								         		echo (!empty($c['phoneNumber']))?$c['phoneNumber']:''; 
								          } ?>      
										  </div>
										  <div class="field_edit_popup ext_field">   
										     <label>Ext</label> <span>:</span>
										  <?php if($building_info->is_write==1){ ?>   
										     <a href="#" class="phoneExt" id="phoneExt-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Phone Ext"  data-name="phoneExt"><?php echo (!empty($c['phoneExt']))?$c['phoneExt']:''; ?></a>
										  <?php }
								         else{
								         		echo (!empty($c['phoneExt']))?$c['phoneExt']:''; 
								          } ?>   
										</div>
										
										<div class="field_edit_popup"><label>Fax Number</label> <span>:</span>
										<?php if($building_info->is_write==1){ ?>  
										    <a href="#" class="fax" id="fax-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Building Fax" data-placeholder="Required" data-name="faxNumber"><?php echo (!empty($c['faxNumber']))?$c['faxNumber']:''; ?></a>
										 <?php }
								         else{
								         		echo (!empty($c['faxNumber']))?$c['faxNumber']:''; 
								          } ?>    
										</div>
																			
								</div>
							<?php } 
							 if($building_info->is_write==1 || $building_info->is_read==1){ ?>	
								<h3>Billing Information</h3>
								
								<div id="billing-information">
								<?php if($building_info->is_write==1){ ?>
									  <div class="field_edit_popup"><label>Company Name</label> <span>:</span>

									       <a href="#" class="billCompany" id="comp-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Company Name" data-placeholder="Required" data-name="billCompanyName"><?php echo (!empty($c['billCompanyName']))?$c['billCompanyName']:''; ?></a>
									  </div>
										
									  <div class="field_edit_popup"><label>Address</label> <span>:</span>
										 <a href="#" class="billAddress" id="billaddr-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Address" data-placeholder="Required" data-name="billAddress"><?php echo (!empty($c['billAddress']))?$c['billAddress']:''; ?></a>
									  </div>
									  
									   <div class="field_edit_popup"><label>Address2</label> <span>:</span>
										    <a href="#" class="billAddress2" id="billaddr2-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Address" data-placeholder="Required" data-name="billAddress2"><?php echo (!empty($c['billAddress2']))?$c['billAddress2']:''; ?></a>
									   </div>
										
										<div class="field_edit_popup"><label>Suite</label> <span>:</span>
										    <a href="#" class="billSuite" id="billSuite-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Suite" data-placeholder="Required" data-name="billSuite"><?php echo (!empty($c['billSuite']))?$c['billSuite']:''; ?></a>
										</div>
										
										<div class="field_edit_popup"><label>City</label> <span>:</span>
										     <a href="#" class="billCity" id="billCity-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing City" data-placeholder="Required" data-name="billcity"><?php echo (!empty($c['billcity']))?$c['billcity']:''; ?></a>
										</div>
										
										<div class="field_edit_popup"><label>State</label> <span>:</span>

										    <a href="#" class="billState" id="billState-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing State" data-placeholder="Required" data-name="billState"><?php echo (!empty($c['billState']))?$c['billState']:''; ?></a>
										</div>
										
										<div class="field_edit_popup"><label>Postal Code</label> <span>:</span>
										     <a href="#" class="billPostal" id="billPostal-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Postal Code" data-placeholder="Required" data-name="billPostalCode"><?php echo (!empty($c['billPostalCode']))?$c['billPostalCode']:''; ?></a>
										</div>
										
										<div class="field_edit_popup phone_field"><label>Phone Number</label> <span>:</span>
										    <a href="#" class="billPhone" id="billPhone-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Phone" data-placeholder="Required" data-name="billPhone"><?php echo (!empty($c['billPhone']))?$c['billPhone']:''; ?></a>
										  </div>
										  <div class="field_edit_popup ext_field">  
										    <label>Ext</label> <span>:</span>
										    <a href="#" class="billPhoneExt" id="billPhoneExt-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Phone Ext"  data-name="billPhoneExt"><?php echo (!empty($c['billPhoneExt']))?$c['billPhoneExt']:''; ?></a>
										</div>
										
										<div class="field_edit_popup"><label>Fax Number</label> <span>:</span>
										    <a href="#" class="billFax" id="billFax-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Fax" data-placeholder="Required" data-name="billFax"><?php echo (!empty($c['billFax']))?$c['billFax']:''; ?></a>
										</div>
										
										<div class="field_edit_popup"><label>Attention</label> <span>:</span>
										     <a href="#" class="attention" id="attention-<?php echo $c['build_id']; ?>" data-type="text" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Billing Attention" data-placeholder="Required" data-name="attention"><?php echo (!empty($c['attention']))?$c['attention']:''; ?></a>
										</div>
									<?php } 
								else{?>
									  <div class="field_edit_popup"><label>Company Name</label> <span>:</span>

									  	<?php echo (!empty($c['billCompanyName']))?$c['billCompanyName']:''; ?>
									  </div>
										
									  <div class="field_edit_popup"><label>Address</label> <span>:</span>
										<?php echo (!empty($c['billAddress']))?$c['billAddress']:''; ?>
									  </div>
									  
									   <div class="field_edit_popup"><label>Address2</label> <span>:</span>
										   <?php echo (!empty($c['billAddress2']))?$c['billAddress2']:''; ?>
									   </div>
										
										<div class="field_edit_popup"><label>Suite</label> <span>:</span>
										   <?php echo (!empty($c['billSuite']))?$c['billSuite']:''; ?>
										</div>
										
										<div class="field_edit_popup"><label>City</label> <span>:</span>
										    <?php echo (!empty($c['billcity']))?$c['billcity']:''; ?>
										</div>
										
										<div class="field_edit_popup"><label>State</label> <span>:</span>

										    <?php echo (!empty($c['billState']))?$c['billState']:''; ?>
										</div>
										
										<div class="field_edit_popup"><label>Postal Code</label> <span>:</span>
										     <?php echo (!empty($c['billPostalCode']))?$c['billPostalCode']:''; ?>
										</div>
										
										<div class="field_edit_popup phone_field"><label>Phone Number</label> <span>:</span>
										   <?php echo (!empty($c['billPhone']))?$c['billPhone']:''; ?>
										  </div>
										  <div class="field_edit_popup ext_field">  
										    <label>Ext</label> <span>:</span>
										    <?php echo (!empty($c['billPhoneExt']))?$c['billPhoneExt']:''; ?>
										</div>
										
										<div class="field_edit_popup"><label>Fax Number</label> <span>:</span>
										    <?php echo (!empty($c['billFax']))?$c['billFax']:''; ?>
										</div>
										
										<div class="field_edit_popup"><label>Attention</label> <span>:</span>
										     <?php echo (!empty($c['attention']))?$c['attention']:''; ?>
										</div>
										<?php
										}?>
								</div>
								<?php
									 }
								if($building_info->is_write==1 || $building_info->is_read==1){ ?>
								<h3>Remit to Information</h3>
								<div id="remit-info">
									<?php if($building_info->is_write==1){ ?>
									<div class="field_edit_popup">
										<div class="remit_lbl"><label>Remit to Address<span class="remit_add_span">:</span></label> </div>
									     <div class="reemit-info" style="width:30%;"><a href="#" class="remit_address" id="remit_address-<?php echo $c['build_id']; ?>" data-type="textarea" data-pk="<?php echo $c['build_id']; ?>" data-url="<?php echo $this->baseUrl().'/company/updatebuilding';?>" data-title="Enter Remit to Address" data-placeholder="Required" data-placement="right" data-name="remit_address"><?php echo nl2br((!empty($c['remit_address']))?$c['remit_address']:''); ?></a></div>
									</div>
									<?php
									}
									else{?>
										<div class="field_edit_popup"><label>Remit to Address<span class="remit_add_span">:</span></label> 
										     <?php echo nl2br((!empty($c['remit_address']))?$c['remit_address']:'Empty'); ?>
										</div>
									<?php } ?>
								</div>
								<?php } ?>
						   </div>
					</div>				
			<?php	
					$pageStr .= "'page-{$i}',";
					$i++;
				}
			?>
	  </div>
	  <?php }
	   else{
		   echo 'No Building has assign to you.';
	   }  
	  }else{?>
	    You don't have access for this module.
	  <?php }?>
	  </div>
      <div class="messageBox"></div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<script src="http://blixt.org/media/a/1/tabs-js/activatables.js" type="text/javascript"></script>
<script type="text/javascript">
	activatables('page', [<?php echo $pageStr; ?>]);
	$(function() {
		<?php for( $k=1; $k <= count($this->companyListing);  $k++){ ?>
			$( "#accordion-info-<?php echo $k; ?>" ).accordion({
				heightStyle: "content",
				animate: 1000,
				collapsible: true
			});
		<?php }?>	
	});	
</script>
