<div id="add_build_serv_div">
	<span>Import Template Building Services</span>
	<div class="message">
		<span id="success_msg" class="success"></span>
		<span id="error_msg" class="error"></span>
	</div>
	<div class="service_row">
		  <label>Select Template From List:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="lerror_desc"></span>
			   <select name="select_template" id="select_template" onchange="setServiceTemplate(this.value)">
				   <option value="">Select Template</option>
				   <?php
				        if($this->bsList){
							foreach($this->bsList as $bsl){
							  echo '<option value="'.$bsl->bsid.'">'.$bsl->service_name.'</option>';
						   }
						}
				   ?>
			   </select>
		  </div>			
	</div>
	<div id="load_global_tmp_div">
		<div class="service_row">
		  <label>Service Name:</label>
		  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_name"></span>
				   <input type="text" name="service_name" id="service_name"/>
			  </div>			
		</div>
		<div class="service_row">
			  <label>Unit Of Measure:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_unit"></span>
				   <input type="text" name="unit_measure" id="unit_measure"/>
			  </div>			
		</div>
		<div class="service_row">
			  <label>Cost $:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_cost"></span>
				   <input type="text" name="cost" id="cost" onkeypress="return isNumber(event)" maxlength="6"/>
			  </div>			
		</div>
		<div class="service_row">
			  <label>Minimum Required:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_minimum"></span>
				   <input type="text" name="minimum" id="minimum" onkeypress="return isNumber(event)" maxlength="6"/>
			  </div>			
		</div>
		
		<div class="service_row">
			 <label>Active:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_status"></span>
				   <select name="status" id="status">
					   <option value="1" selected="selected">Yes</option>
					   <option value="0">No</option>
				   </select>
			  </div>
		</div>
	</div>
	<input type="hidden" name="global_template" id="global_template" value="0"/>		
	<div class="buttons">
				   <button type="button" name="save_rate" id="save_rate" value="Save" onclick="saveBuildService('<?php echo $this->bId;?>')">Save</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelServiceTemplate()">Cancel</button>
			  </div>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
