<?php
/*
 * add corresponding js and css 
 * file in the header.
 */
$this->headLink()->appendStylesheet($this->baseUrl() . '/public/tabs.css');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/category.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/emails.js');
$dist_access = $this->acessHelper->checkAccess($this->roleId, $this->dist_location);
$customeAccessmodel = new Model_UserAccess();
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->dist_location);
if ($customeAccessmodeld[0]) {
    $dist_access = $customeAccessmodeld[0];
}
$reportModel = new Model_Report();
$reportDetailLinks = '';
$dashBoardViewsdetails = '';
$dashBoardViews = '';
$woNumberAll = '';
$invoiceAll = '';
$uniqueCostCenterAll = '';
$buildIdReportAll = '';
$batch_number_report = '';
$uniqueCostCenter = '';
$batch_number_reportallbuilding = '';
$buildIdReport = $this->select_build_id;
$woNumberAllbuilding = '';
$invoiceAllbuilding = '';
$batch_number_reportall = '';
$reportDetailLinks = $reportModel->getReport($this->custID, 16);

/* Searching section request data*/
$search_by = '';
    $service_value = '';
    if(!empty($this->search) && isset($this->search['search_by'])){
                    $search_by = $this->search['search_by'];
                    $service_value=$this->search['search_value']; 
    }
?>	


<div class="container-right" id="companyListData">
    <?php
    /*     * *
     * building tabs
     */

    if ($this->roleId != 1 && $dist_access->is_access == 0) {
        if ($this->custID != null && $this->custID && $this->companyListing != '' && $this->companyListing != false) {
            ?>

            <!-- All Report link -->
            <?php
            if ($reportDetailLinks != '') {
                $woReport = new Model_Report();
                $woBatch = new Model_WoBatch();
                foreach ($this->companyListing as $cb) {
                    $uniqueCostCenterAll = $uniqueCostCenterAll . $cb['uniqueCostCenter'] . ',';
                    $buildIdReportAll = $buildIdReportAll . $cb['build_id'] . ',';
                    $batchDetails = $woBatch->showBatch($cb['build_id']);
                    if ($batchDetails != '') {
                        foreach ($batchDetails as $bd) {
                            $batch_number_reportallbuilding = $batch_number_reportallbuilding . $bd['batch_number'] . ',';
                        }
                    }


                    $order = 'woId';
                    $dir = 'DESC';
                    $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                    $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                    if ($wolist != '') {
                        foreach ($wolist as $woNumber) {
                            $woNumberAllbuilding = $woNumberAllbuilding . $woNumber->wo_number . ',';
                        }
                    }
                    if ($invoicelist != '') {
                        foreach ($invoicelist as $invoiceNumber) {
                            $invoiceAllbuilding = $invoiceAllbuilding . $invoiceNumber->wo_number . ',';
                        }
                    }

                    $batchDetails = $woBatch->showBatch($cb['build_id']);

                    if ($batchDetails != '') {
                        foreach ($batchDetails as $bd) {
                            $batch_number_reportall = $batch_number_reportall . $bd['batch_number'] . ',';
                        }
                    }
                }
            }
            ?>

            <!-- End all report Link -->

            <ol id="toc">
                    <?php
                    $j = 1;

                    foreach ($this->companyListing as $cb) {
                        ?>
                    <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/emails/console/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>

                        <!-- selected report Link -->
                        <?php
                        if ($reportDetailLinks != '') {
                            if ($cb['build_id'] == $this->select_build_id) {
                                $uniqueCostCenter = $cb['uniqueCostCenter'];
                                $batchDetails = $woBatch->showBatch($cb['build_id']);
                                $batch_number_report = '';
                                if ($batchDetails != '') {
                                    foreach ($batchDetails as $bd) {
                                        $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
                                    }
                                }
                                $order = 'woId';
                                $dir = 'DESC';
                                $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                                $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                                if ($wolist != '') {
                                    foreach ($wolist as $woNumber) {
                                        $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
                                    }
                                }
                                if ($invoicelist != '') {
                                    foreach ($invoicelist as $invoiceNumber) {
                                        $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
                                    }
                                }
                            }
                        }
                        ?> 

                    </li>

        <?php } ?>
            </ol>

    <?php } ?>
        <!-- Report Link -->
    <?php if ($reportDetailLinks != '') { ?> <div class="clearfix"></div><div class="tabmenu report_tab_menus" ><ul><?php foreach ($reportDetailLinks as $reportvalue) {
        if ($reportvalue->Report_Type == 'Flash') {
				     $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
                }else{
                     $report_type = 'vnsreports/index.php?';
                }
            $reportOption = explode(',', $reportvalue->report_option); ?> <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php if (in_array('[[++user_id]]', $reportOption)) {
                echo '&User=' . $this->userId;
            } ?><?php if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && $uniqueCostCenterAll != '') {
                echo '&Cost_Center_Number=' . rtrim($uniqueCostCenterAll, ',');
            } else if ((in_array('[[++CostCenterNumber]]', $reportOption)) && $uniqueCostCenter != '') {
                echo '&Cost_Center_Number=' . $uniqueCostCenter;
            } ?><?php if ((in_array('[[++KeyBuildingAllBuildings]]', $reportOption)) && $buildIdReportAll != '') {
                echo '&buildkey=' . rtrim($buildIdReportAll, ',');
            } else if ((in_array('[[++KeyBuildingNumber]]', $reportOption)) && $buildIdReport != '') {
                echo '&buildkey=' . $this->select_build_id;
            } ?><?php if (in_array('[[++BatchNumber]]', $reportOption)) {
                if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && (in_array('[[++CostCenterAllBuildings]]', $reportOption))) {
                    echo '&Batch_Number=' . rtrim($batch_number_reportall, ',');
                } else {
                    echo '&Batch_Number=' . rtrim($batch_number_report, ',');
                }
            } ?><?php if ((in_array('[[++WONumber]]', $reportOption))) {
                            if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && (in_array('[[++CostCenterAllBuildings]]', $reportOption))) {
                                echo "&WO_Number=" . rtrim($woNumberAllbuilding, ',');
                            } else {
                                echo "&WO_Number=" . rtrim($woNumberAll, ',');
                            }
                        } ?><?php if ((in_array('[[++InvoiceNumber]]', $reportOption))) {
                        if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && (in_array('[[++CostCenterAllBuildings]]', $reportOption))) {
                            echo '&Invoice_Number=' . rtrim($invoiceAllbuilding, ',');
                        } else {
                            echo '&Invoice_Number=' . rtrim($invoiceAll, ',');
                        }
                    } ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>	

        <div class="content" id="page-content">
            <span class="vendor-heading"><h1>E-Mail Distribution Groups</h1></span>
             <div class="row-limit" style="float: left;margin-top: 12px;">
                    Show:
                    <select id="show_limit" onchange="showlimit();" dir="rtl">
                        <option value="10" <?php echo ($this->show==10?"selected":"");?> >10</option>
                        <option value="25" <?php echo ($this->show==25?"selected":"");?>>25</option>
                        <option value="50" <?php echo ($this->show==50?"selected":"");?>>50</option>
                        <option value="100" <?php echo ($this->show==100?"selected":"");?>>100</option>
                        <option value="all" <?php echo ($this->show=='all'?"selected":"");?>>All</option>
                    </select>
                </div>
             <div id="vendor_search_div">
                        <div id="search_form_div">
                            <div id="search_message"></div>
                             <form name="search_form" id="search_form" action="<?php echo BASEURL.'emails/console/bid/'.$this->select_build_id;?>" method="post">
                                    <div id="form_field"><div style='float:left;'>
                                           <label class='labelcenter' >Search For</label>
                                           </div>
                                           <select name="search_by" id="search_by" onchange="showServiceDropdown(this)">
                                                   <option value="firstName" <?php echo ($search_by=='firstName'?"SELECTED":""); ?> >First Name</option>
                                                    <option value="lastName" <?php echo ($search_by=='lastName'?"SELECTED":""); ?>>Last Name</option>
                                                     <option value="email" <?php echo ($search_by=='email'?"SELECTED":""); ?>>Email</option>
                                            </select>
                                           <div class="text-select-div">
                                           <div id="search_txt" ><input type="text" name="search_value" id="search_value" value="<?php echo stripslashes(htmlentities($service_value)); ?>"/></div>

                                           </div>
                                     </div>
                                     <div class="form-button">
                                              <input type="submit" name="search" id="search" value="Search"/>
                                              <input type="button" name="reset" id="reset" value="Reset" onclick="window.location.href='<?php echo BASEURL.'emails/console/bid/'.$this->select_build_id;?>'"/>
                                     </div>  
                            </form>

                        </div>
                    </div>
            <div id="msg">
                <span class="message">
                    <?php
                    $tm = new Zend_Session_Namespace('email_message');
                    echo $tm->msg;
                    $tm->setExpirationSeconds(1);
                    ?>
                </span>
                <span class="error-txt" style="color:red;"></span>
            </div>
            <input type="hidden" name="building_id" id="building_id" value="<?php echo $this->select_build_id; ?>"/>

            <div id="category_info" class="category-infromation">
                <div style="display:none;" id="category_popup"></div>
                <section class="w-48 fr ch-home-form">
                    <input type="hidden" value="1" id="category_page" name="category_page">
                    <table width="100%" class="category-list">
                        <tbody>
                            <tr>
                                <th>&nbsp;</th>
                                <th>Group Name</th>
                                <th>Active</th>
                                <?php echo ($dist_access->is_write == 1?'<th>Action</th>':'');?>
                            </tr>

    <?php
    $email_group_user_model = new Model_EmailGroupUsers();
    if (!empty($this->email_group)) {
        foreach ($this->email_group as $key => $value) {
            $users = '';

            $users = $email_group_user_model->getGroupUsers($value['id']);
            ?>
                                <input type="hidden" value="<?php echo count($users); ?>" name="group_user_count_<?php echo $value['id']; ?>" id="group_user_count_<?php echo $value['id']; ?>" />

            <?php if ($value['is_default']) { ?>
                                    <tr>
                                        <td>

                                            <div class="open_plus" id="open_div_<?php echo $value['id']; ?>">
                                                <a href="javascript:void(0);" id="<?php echo $value['id']; ?>" onClick="return loadEmailUser(<?php echo $value['id']; ?>,<?php echo $this->select_build_id; ?>)">&nbsp; &nbsp;</a>
                                            </div>
                                            <div class="open_close" id="close_div_<?php echo $value['id']; ?>" style="display:none">
                                                <a href="javascript:void(0);" id="<?php echo $value['id']; ?>" onClick="return hideEmailUser(<?php echo $value['id']; ?>)";><?php echo '&nbsp;&nbsp;'; ?></a>
                                            </div>

                                        </td>
                                        <td><?php echo $value['group_name'] . ' (Send an E-Mail on Every Work Order)'; ?></td>
                                        <td><?php if ($value['active'] == 1) echo "Yes";
                else echo "No"; ?></td>
                                    <?php if ($dist_access->is_write == 1) { ?>
                                            <td>
                                                <a title="Edit" class="modalbox" onclick="javascript:editNewDisGroup('<?php echo BASEURL . 'emails/editemailgroup/gid/' . $value['id'] . '/buildingId/' . $this->select_build_id; ?>');" href="#editNewDisGroup" ><img src="<?php echo BASEURL . 'public/images/edit.png' ?>" /></a>
                                            </td>
                <?php } ?>
                                    </tr>

                                    <tr id="trId_<?php echo $value['id']; ?>" class="tremail-class" style="display:none">
                                        <td>&nbsp;</td>
                                        <td colspan="3" id="loademail_<?php echo $value['id']; ?>" class="tdemail-class"></td>

                                    </tr>

            <?php
            } else {
                ?>

                                    <tr>
                                        <td>

                                            <div class="open_plus" id="open_div_<?php echo $value['id']; ?>">
                                                <a href="javascript:void(0);" id="<?php echo $value['id']; ?>" onClick="return loadEmailUser(<?php echo $value['id']; ?>,<?php echo $this->select_build_id; ?>)">&nbsp; &nbsp;</a>
                                            </div>
                                            <div class="open_close" id="close_div_<?php echo $value['id']; ?>" style="display:none">
                                                <a href="javascript:void(0);" id="<?php echo $value['id']; ?>" onClick="return hideEmailUser(<?php echo $value['id']; ?>)";><?php echo '&nbsp;&nbsp;'; ?></a>
                                            </div>

                                        </td>
                                        <td><?php echo $value['group_name']; ?></td>
                                        <td><?php if ($value['active'] == 1) echo "Yes";
                else echo "No"; ?></td>
                <?php if ($dist_access->is_write == 1) { ?>
                                            <td>

                                                <a title="Edit" class="modalbox" onclick="javascript:editNewDisGroup('<?php echo BASEURL . 'emails/editemailgroup/gid/' . $value['id'] . '/buildingId/' . $this->select_build_id; ?>');" href="#editNewDisGroup" ><img src="<?php echo BASEURL . 'public/images/edit.png' ?>" /></a>
                                                <a href="javascript:void(0);"  title="Delete" onclick="deleteEmailGroup('<?php echo $value['id']; ?>', '<?php echo $this->select_build_id ?>')"><img src="<?php echo BASEURL . 'public/images/delete.png' ?>" /></a> 

                                            </td>
                <?php } ?>
                                    </tr>

                                    <tr id="trId_<?php echo $value['id']; ?>" class="tremail-class" style="display:none">
                                        <td>&nbsp;</td>
                                        <td colspan="3" id="loademail_<?php echo $value['id']; ?>" class="tdemail-class"></td>

                                    </tr>

            <?php }
        }
    }else{
        echo '<tr>
                                        <td>&nbsp;</td>
                                        <td colspan="4"> No priority created. Pease create new priority!!!</td>

                                    </tr>';
    } ?>
        <?php
                    if (count($this->email_group) > 0 && !empty($this->email_group)) {
                        echo '<tr><td colspan="4">';
                        echo $this->paginationControl($this->email_group, 'Sliding', 'pagination.phtml');
                        echo '</td></tr>';                  
                    }
                ?> 

                        </tbody>
                    </table>
                </section>
    <?php if ($dist_access->is_write == 1) { ?>
                    <div class="ad-egroupdv">
                        <a class="modalbox" onclick="javascript:addNewDisGroup('<?php echo $this->baseUrl() . '/emails/addemailgroup/bid/' . $this->select_build_id; ?>');" href="#addNewDisGroup"> Add New Distribution Group </a>
                    </div>
    <?php } ?>		 						 
            </div>

        </div>	

    </div>
<?php } else { ?>
    You don't have access for this module.
<?php } ?>					
</div>

<div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>"><div>

<?php if ($this->groupid) { ?>
            <script type="text/javascript">
                loadEmailUser('<?php echo $this->groupid; ?>', '<?php echo $this->select_build_id; ?>');
            </script>	
<?php } ?>
            <script>
            function showlimit(){
                var data = $("#show_limit").val();
                window.location =baseUrl+"emails/console/show/"+data;
            }
            </script>