<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/ckeditor/ckeditor.js');

echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/ckeditor/adapters/jquery.js');

echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/emails.js');
$roles = $this->companyListing['roles'];
$etemplateAccess = $this->acessHelper->checkAccess($this->roleId, $this->etemplate_location);
/* override access by custom user access if exist */
$customeAccessmodel = new Model_UserAccess();
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->etemplate_location);
if ($customeAccessmodeld[0]) {
    $etemplateAccess = $customeAccessmodeld[0];
}
/* end overriding access */
?>
<div class="container-right">
    <?php if ($this->roleId == 1 || $this->roleId == 9) { ?>
        <section style="z-index:9999" class="w-48 fr ch-home-form">
            <section class="ch-form-header ">
                <h3>Create Email Template </h3>
            </section>
            <div class="gridContainer">
                <div class="tableGrid">
                    <div class="message">
                        <span id="success_msg"></span>
                        <span id="error_msg"></span>
                    </div>             
                    <div id="email_template_div">
                        <form name="emailtemplate" id="template_form" action="<?php echo BASEURL . 'emails/saveemailtemp'; ?>" method="post">
                            <input type="hidden" value="<?php echo $this->build_id; ?>" id="title" class="" name="build_id"> 
                            <input type="hidden" value="8" id="title" class="" name="email_location"> 
                            <div class="row">
                                <label>Title<span class="required">*</span></label><span class="ufirstErr" id="title-error"></span>
                                <div class="email_input">
                                    <input type="text" value="" id="title_name" class="" name="title"> 
                                </div> 
                            </div>
                            <div class="row">
                                <label>Subject<span class="required">*</span></label><span class="ufirstErr" id="subject-error"></span>  <div class="email_input">  <input type="text" value="" id="subject" class="" name="subject">  
                                </div> 
                            </div>
                            <?php if ($this->roleId == 1) { ?>
                                <div class="row">
                                    <label>System Generated<span class="required">*</span></label><span class="ufirstErr" id="system-error"></span>
                                    <div class="email_input">
                                        <input type="radio" name="system_generated" value="1"> Yes
                                        <input type="radio" name="system_generated" value="0" checked="checked"> No
                                    </div> 
                                </div>
                            <?php } else { ?>
                                <input type="radio" name="system_generated" value="0" checked="checked" style='display:none'>
                            <?php } ?>

                            <?php /* <div class="row">
                              <label >Role<span class="required">*</span></label><div class="email_input">
                              <select name="user_role" id="user_role">
                              <?php foreach ($this->roleDetails as $key => $value) { if($value['roleID'] != 1){?>
                              <option value="<?php echo $value['roleID']; ?>">
                              <?php echo $value['title']; ?>
                              </option>
                              <?php }} ?>
                              </select>
                              </div>
                              </div>
                             */ ?>
                            <div class="row_editor">
                                <label style="clear:left;">Content<span class="required">*</span></label>
                                <span class="ufirstErr" id="content-error"></span><div class="et_editor">   
                                    <textarea id="content" name="email_content"></textarea>
                                </div> 
                            </div>

                            <div class="confirmBtn float_none">
                                <input type="button" value="Save" name="save" class="confirm" id="saveEmail">
                                <input type="button" value="Cancel" name="cancel" class="cancel" onclick="window.location.href = '<?php echo BASEURL . 'emails/list' ?>'">
                            </div>
                        </form>  
                    </div>   
                </div>
            </div>
        </section>
        <?php } else if ($this->roleId == 4 || $this->roleId == 2 || $this->roleId == 3 || $this->roleId == 6 || $this->roleId == 9) {
        ?>

        <?php
        $emailModel = new Model_Email();
        if ($this->roleId == 4 || $this->roleId == 2 || $this->roleId == 3 || $this->roleId == 6 || $this->roleId == 9) {
            $emailDetails = $emailModel->loadEmailTemplate('18', '1');
        } else if ($this->roleId == 5) {
            $emailDetails = $emailModel->loadEmailTemplate('24', '1');
        }
 
        ?>
        <section style="z-index:9999" class="w-48 fr ch-home-form">
            <section class="ch-form-header ">
                <h3>Create Email Template </h3>
            </section>
            <div class="gridContainer">
                <div class="tableGrid">
                    <div class="message">
                        <span id="success_msg"></span>
                        <span id="error_msg"></span>
                    </div>             
                    <div id="email_template_div">
                        <form name="emailtemplate" id="template_form" action="<?php echo BASEURL . 'emails/saveemailtemp'; ?>" method="post">
                            <input type="hidden" value="<?php echo $this->build_id; ?>" id="title" class="" name="build_id"> 
                            <input type='hidden' name="role_id" value="<?php echo $this->roleId; ?>" >
                            <?php if ($this->roleId == 4 || $this->roleId == 5 || $this->roleId == 9) { ?>
                                    <input type='hidden' name="email_location" value="8" >
                                <?php } else if ($this->roleId == 5) { ?>
                                    <input type='hidden' name="email_location" value="9" >
                                <?php } ?>
                            <div class="row">
                                <label>Title<span class="required">*</span></label><span class="ufirstErr" id="title-error"></span>
                                <div class="email_input">
                                    <input type="text"  id="title" class="" name="title" value='<?php echo $emailDetails[0]['email_title']; ?>'> 
                                </div> 
                            </div>
                            <div class="row">
                                <label>Subject<span class="required">*</span></label><span class="ufirstErr" id="subject-error"></span>  <div class="email_input">  <input type="text" value="<?php echo $emailDetails[0]['email_subject']; ?>" id="subject" class="" name="subject">  
                                </div> 
                            </div>
                            <?php if ($this->roleId == 1) { ?>
                                <div class="row">
                                    <label>System Generated<span class="required">*</span></label><span class="ufirstErr" id="system-error"></span>
                                    <div class="email_input">
                                        <input type="radio" name="system_generated" value="1"> Yes
                                        <input type="radio" name="system_generated" value="0" checked="checked"> No
                                    </div> 
                                </div>
                            <?php } else { ?>
                                <input type="radio" name="system_generated" value="0" checked="checked" style='display:none'>
                            <?php } ?>


                            <div class="row_editor">
                                <label style="clear:left;">Content<span class="required">*</span></label>
                                <span class="ufirstErr" id="content-error"></span><div class="et_editor">   
                                    <textarea id="content" name="email_content"><?php echo $emailDetails[0]['email_content']; ?></textarea>
                                </div> 
                            </div>

                            <div class="confirmBtn float_none">
                                <input type="button" value="Save" name="save" class="confirm" id="saveEmail">
                                <input type="button" value="Cancel" name="cancel" class="cancel" onclick="window.history.back();">
<!--                                <input type="button" value="Cancel" name="cancel" class="cancel" onclick="window.location.href = '<?php //echo BASEURL . 'emails/list' ?>'">-->
                            </div>
                        </form>  
                    </div>   
                </div>
            </div>
        </section>
    <?php } else { ?>
        You don't have access for this module.
    <?php } ?> 
</div>

<script type="text/javascript">
    CKEDITOR.disableAutoInline = true;

    $(document).ready(function () {
        $('#content').ckeditor(); // Use CKEDITOR.replace() if element is <textarea>.
    });


</script>
