<?php 
 echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/jquery.tokeninput.js');
 $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/token-input.css');
 $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/token-input-facebook.css');
 $etemplateAccess = $this->acessHelper->checkAccess($this->roleId,$this->etemplate_location);
 /*override access by custom user access if exist */
 $customeAccessmodel = new Model_UserAccess();
 $customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId,$this->etemplate_location);
 if($customeAccessmodeld[0]) {
	$etemplateAccess = $customeAccessmodeld[0];
 }
 /* end overriding access */
?>

<div class="container-right">
  <?php if($this->roleId!='0' && $this->roleId!='9' && $etemplateAccess->is_access == 0 && $etemplateAccess->is_write == 1){ ?>
  <section style="z-index:9999" class="w-48 fr ch-home-form">
    <section class="ch-form-header ">
      <h3>Send Email </h3>
    </section>
    <div class="gridContainer">
      <div class="tableGrid send_user_div">
        <div class="message"> <span id="success_msg"><?php echo $this->msg;?></span> <span id="error_msg"><?php echo $this->error;?></span> </div>
        <div>
          <?php 
				 /*foreach($this->user_data as $ud){
					 //var_dump($ud);
					 echo $ud->uid.'-->'.$ud->email.'<br/>';
				 }*/
				 ?>
          <form name="emailtemplate" id="template_form" action="<?php echo BASEURL.'emails/send';?>" method="post">
            <input type="hidden" name="form_key" value="<?php echo $this->form_key?>"/>
            <div class="row">
              <input class="send_user" type="checkbox" name="send_all" id="send_all" value="1" checked="checked" onclick="showSelector(this)"/>
              <label>Send to All user</label>
            </div>
            <div class="row" id="select_building_user" style="display:none">
              <label>Building(s) user</label>
              <input type="text" id="building_user" name="building_user" />
            </div>
            <div class="row">
              <label>Other user</label>
              <span class="ccenterErr" id="send_to_err"></span>
              <textarea style="float:left;" name="send_user" id="send_user" cols="36" rows="5"></textarea>
              <span> Enter email with comma (,) seperated</span> </div>
            <div class="row">
              <label>Select Template<span class="required">*</span></label>
              <span class="ccenterErr" id="template_err"></span>
              <select name="email_template" id="email_template">
                <option value="">Select</option>
                <?php foreach ($this->emailData as $edata){
					      if($edata['system_generated']=='0'){
								   ?>
                <option value="<?php echo $edata['id']?>"><?php echo $edata['email_title']?></option>
                <?php 
			                 }
						}
				 ?>
              </select>
            </div>
            <div class="confirmBtn float_none" style="margin:7% 0 0 31%">
              <input type="button" value="Send" name="save" class="confirm" id="save">
              <input type="reset" value="Reset" name="cancel" class="cancel">
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <?php } else echo 'You don\'t have access for this module.';?>
</div>
<script type="text/javascript">

$(function(){
    $("#save").on("click", function(){
            
            var send_user = $("#send_user").val();
            var email_template = $("#email_template").val();
            var send_all = $('#send_all').prop('checked');
            var building_user = $('#building_user').val();
            var check_send = false;
            //alert(building_user);
            if(!send_all){
				if(building_user.length == 0){
					check_send =true;
				}
			}           
            var isError = false;
            if(send_user.length == 0 && check_send == true) {				
                $("#send_to_err").html("Please enter email-id ");
                isError = true;
            }else {
                 $("#send_to_err").html("");
            }
            
            if(send_user.length != 0 && check_send == true) {
				var user_arr = send_user.split(',');
				for(var i=0; i< user_arr.length; i++ ){
					if(!validateEmail(user_arr[i])){
						$("#send_to_err").html("Please enter valid email-id ");
                         isError = true;
                         return false;
					}
				}
                
            }
            
            if(email_template.length == 0) {
                $("#template_err").html("Please select the email template");
                isError = true;
            } else {
                $("#template_err").html("");
            }           
            
          
            if(!isError) {
				document.getElementById("template_form").submit();             
            } 
        });
});

</script> 
<script type="text/javascript">
        $(document).ready(function() {
            $("#building_user").tokenInput([
               <?php if($this->user_data){ 
               foreach($this->user_data as $ud){ ?>
				   {id: '<?php echo $ud->email?>', name: '<?php echo $ud->email?>'},
				<?php } }?>                
            ],{theme: "facebook"});
        });
        
/*******Show and hide select building user*******/
       function  showSelector(chk){
		   //alert(chk.checked);
		   if(chk.checked)
		      $('#select_building_user').hide();
		    else
		       $('#select_building_user').show(); 
	   }
	   
/*******check email validation *******/	   
	   function validateEmail(sEmail) {
				var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
				if (filter.test(sEmail)) {
					return true;
				}
				else {
					return false;
				}
		 }
</script> 
