<?php echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/module.js'); ?>

<?php
$search_by = '';
$search_value = '';
if (!empty($this->search) && isset($this->search['search_by'])) {
    $search_by = $this->search['search_by'];
    $search_value = $this->search['search_value'];
}
?>

<div class="container-right" id="userinfo-data">
    <?php if ($this->roleId == 1) { ?>
        <div id="contents">
            <div id="page" class="content">

                <span class="vendor-heading"><h1>List of Modules</h1></span>
                <div id="vendor_search_div">
                    <div id="search_form_div">
                        <div id="search_message"></div>
                        <form name="search_form" id="search_form" method="post" onsubmit="return checkSearch(this)">
                            <div id="form_field">
                                <div style='float:left;'>
                                    <label class='labelcenter'>Search For</label>
                                </div>
                                <select name="search_by" id="search_by" >
                                    <option value="module_name" <?php echo ($search_by == 'module_name') ? 'selected' : '' ?> >Module Name</option>

                                </select>

                                <div class="text-select-div">
                                    <div id="search_txt" >
                                        <input type="text" name="search_value" id="search_value" value="<?php echo stripslashes(stripslashes(stripslashes($search_value))); ?>"/>
                                    </div>
                                </div> 

                            </div>
                            <div class="form-button">
                                <input type="submit" name="search" id="search" value="Search"/>
                                <input type="button" name="reset" id="reset" value="Reset" onclick="window.location.href = '<?php echo BASEURL . 'module/index' ?>'"/>
                            </div>  

                        </form>

                    </div>
                </div>

                <div id="vendor_data_div">
                    <span id="module_success" class="success_message" style="color:red;"></span>
                    <span id="module_error" class="success_message" style="color:red;"></span>
                    <table id="vendor_data_table" class="building_table_grid" width="100%">

                        <tr>
                            <th style='width:40px;'>&nbsp;</th>
                            <th><a href="#" >Module Name</a></th>
                            <th style='width:100px; text-align:center;'>Active</th>
                            <th style='width:100px; text-align:center;'>Action</th>

                        </tr>


                        <?php
                        if (isset($this->moduleList) && !empty($this->moduleList))  {
                            foreach ($this->moduleList as $m1) {
                                ?><tr>
                                    <td>
                                        <div class="open_plus" id="open_div_<?php echo $m1['module_id']; ?>" ><a href="javascript:void(0);"  onclick="showModuleDetails('<?php echo $m1['module_id']; ?>')"><?php echo '&nbsp;&nbsp;'; ?></a></div>
                                        <div class="open_close" id="close_div_<?php echo $m1['module_id']; ?>" style="display:none"><a href="javascript:void(0);" id="<?php echo $m1['module_id']; ?>" onClick="hideModuleBuild(<?php echo $m1['module_id']; ?>)";><?php echo '&nbsp;&nbsp;'; ?></a></div>
                                        </div>
                                        </div></td>
                                    <td><?php echo $m1['module_name']; ?></td>
                                    <td><?php echo ($m1['status'] == '1') ? 'Yes' : 'No'; ?></td>
                                    <td>
                                        <?php if ($m1['module_id'] != 1) { ?>
                                            <a href="#" onclick="showEditModule('<?php echo $m1['module_id']; ?>')"  title="Edit"><img src="<?php echo BASEURL . 'public/images/edit.png'; ?>"></a>   <?php } ?>
                                        <?php /* ?>   <a onclick="deleteModule('<?php echo $m1['module_id']; ?>')" title="Delete" href="javascript:void(0);"><img src="<?php echo BASEURL . 'public/images/delete.png'; ?>"></a>  <?php */ ?>
                                    </td> 
                                </tr>
                                <tr id="trId_<?php echo $m1['module_id']; ?>" class="trtenant-class" style="display:none">
                                    <td>&nbsp;</td>
                                    <td id="loadcompany_<?php echo $m1['module_id']; ?>" class="tdtenant-class" colspan="3"></td>
                                </tr>
                                <?php
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="9">No Vendor Exist..</td>
                            </tr>

                        <?php } ?>


                    </table>
                </div>
            </div>
        </div>

        <div class="fade_default_opt" id="fd_dft_div" style="display:none">	
            <a href="#show_module" id="show_module_href" class="modalbox">&nbsp;</a>	
            <div id="show_module" class="bd-dft-cls" style="display:none"></div>
            <a href="#show_edit_form" id="show_edit_form_href" class="modalbox">&nbsp;</a>	
            <div id="show_edit_form" class="bd-dft-cls" style="display:none"></div>
        </div>

        <?php
        if (isset($this->moduleList) && !empty($this->moduleList)) {
            echo $this->paginationControl($this->moduleList, 'Sliding', 'pagination.phtml');
        }
        ?>
    <?php } else { ?> 
        You don't have access for this module.
    <?php } ?>
</div>

<div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>"><div>

