<?php if ($this->roleId == 1) { ?>
<?php $companyData = $this->companyData; ?>
<div class="tuser-list">
    <table width="100%" class="building_table_grid">
        <tr>
			<th style='width:40px;'>&nbsp; </th>
            <th >Company Name</th>	
        </tr>
        <?php if ($companyData) {
            foreach ($companyData as $cv) {
                ?>
                <tr>
					<td ><div class="open_plus2" id="open_div_<?php echo $cv->module_id.'_'.$cv->cust_id; ?>" ><a href="javascript:void(0);"  onclick="showModulebuildings('<?php echo $cv->module_id; ?>', '<?php echo $cv->cust_id; ?>')"><?php echo '&nbsp;&nbsp;'; ?></a></div>
                                    <div class="open_close2" id="close_div_<?php echo $cv->module_id.'_'.$cv->cust_id; ?>" style="display:none"><a href="javascript:void(0);" id="<?php echo $cv->module_id.'_'.$cv->cust_id; ?>" onClick="hideModuleBuild('<?php echo $cv->module_id; ?>', '<?php echo $cv->cust_id; ?>')";><?php echo '&nbsp;&nbsp;'; ?></a></div>
                                    </div>
                                    </div></td>
                    <td ><?php echo $cv->companyName; ?></td>
                 </tr>
				 <tr id="building_trId_<?php echo $cv->module_id.'_'.$cv->cust_id; ?>" class="trbuilding-class" style="display:none">
                                <td>&nbsp;</td>
                                <td id="loadbuilding_<?php echo $cv->module_id.'_'.$cv->cust_id; ?>" class="tdbuilding-class" colspan="3"></td>
                            </tr>
                <?php
            }
        } else {
            echo '<tr><td colspan="7"> No Building access </td></tr>';
        }
        ?>

    </table>
</div>
<?php } else { ?> 
        You don't have access for this module.
    <?php } ?>