<div class="container-right" id="user-Complete">
    <p>Hi <?php echo $this->firstname; ?> <?php echo $this->lastname; ?>,</p>
    <p>A password reset request has been received for your login at <?php echo $this->email; ?>.</p>
    <p>To reset your password, please follow this link: 
        <a href="<?php echo BASEURL."index/resetpassword/id/".$this->passkey?>">
            <?php echo BASEURL."index/resetpassword/id/".$this->passkey?>
        </a>
    </p>
    <p>Thanks!</p>
</div>
