<?php     if(count($this->pagesInRange)>1){  ?>
<div class="pagination cat_page_div">
    <div> 
        <!-- First page link -->
        <?php 
         if (isset($this->previous)): ?>
              <a href="javascript:void(0)" onclick="cschedulePagination('<?php echo $this->first; ?>')">First</a> |
        <?php else: ?>
                <span class="disabled">First</span> |
        <?php endif; ?>
      
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
             <a href="javascript:void(0)" onclick="cschedulePagination('<?php echo $this->previous; ?>')">&lt; Previous</a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="javascript:void(0)" onclick="cschedulePagination('<?php echo $page; ?>')"><?php echo $page; ?></a>
            <?php else: ?>
                <?php echo $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              |<a href="javascript:void(0)" onclick="cschedulePagination('<?php echo $this->next; ?>')"> 
             Next &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Next &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="javascript:void(0)" onclick="cschedulePagination('<?php echo $this->last; ?>')">Last</a>
        <?php else: ?>
            <span class="disabled">Last</span>
        <?php endif; ?>
        &nbsp; Page <?php echo $this->current; ?> of <?php echo $this->last; ?>
        
    </div>
 </div><?php }?>
