<?php  
  if(count($this->pagesInRange)>1){  ?>
<div class="row">
	<div class="pagination_link">
		<ul class="pagination">   
				<!-- First page link -->
				<?php $params =array(); 
							$params['page'] ='' ;
							if(isset($this->tenant_name)) { $params['tenant_name']=$this->tenant_name; } 
							if(isset($this->category_name)) { $params['category_name']=$this->category_name; } 
							if(isset($this->from_date)) { $params['from_date']=$this->from_date; } 
							if(isset($this->to_date)) { $params['to_date']=$this->to_date; } 
				 if (isset($this->previous)): ?>
				 <?php 		$params['page'] =$this->first ; 
							
							?>
					  <li class="paginate_button previous"><a href="<?php echo $this->url($params); ?>">First</a></li>
				<?php else: ?>
						<li class="paginate_button previous disabled"><a href="javascript:void(0)">First</a></li> 
				<?php endif; ?>
			  
				<!-- Previous page link -->
			
				<?php if (isset($this->previous)): ?> <?php $params['page'] =$this->previous ; ?>
					  <li><a href="<?php echo $this->url($params); ?>">Previous</a> </li>
				<?php else: ?>
					<li class="paginate_button previous disabled"><a href="javascript:void(0)"> Previous </a></li>
				<?php endif; ?>
				<!-- Numbered page links -->
				<?php foreach ($this->pagesInRange as $page): ?>
					<?php if ($page != $this->current): ?>
							<?php $params['page'] =$page ; ?>
						<li class="paginate_button"><a href="<?php echo $this->url($params); ?>"><?php echo $page; ?></a></li>
					<?php else: ?>
						<li class="paginate_button disabled"><a href="javascript:void(0)"><?php echo $page; ?></a></li>
					<?php endif; ?>
				<?php endforeach; ?>
				<!-- Next page link -->
				<?php if (isset($this->next)): ?>
						<?php $params['page'] =$this->next ; ?>
					 <li class="paginate_button next"><a href="<?php echo $this->url($params); ?>">Next</a></li>
				<?php else: ?>
					 <li class="paginate_button next disabled"><a href="javascript:void(0)">Next </a></li> 
				<?php endif; ?>
				<!-- Last page link -->
				<?php if (isset($this->next)): ?>
				<?php $params['page'] =$this->last ; ?>
					  <li class="paginate_button"><a href="<?php echo $this->url($params); ?>">Last</a></li>
				<?php else: ?>
					<li class="paginate_button next disabled"><a href="javascript:void(0)">Last</a></li>
				<?php endif; ?>
			
		     </ul>
		 </div>
        <div class="pagination_info">Page <?php echo $this->current; ?> of <?php echo $this->last; ?> </div>
 </div>	
 <?php }?>
