<?php if($this->serviceData) { 
		  $bservice = $this->serviceData[0];		  
		?>	
	<div class="service_row">
		  <label>Service Name:</label>
		  <div class="serv_ibox_row">
			   <span class="field_error" id="serror_name"></span>
			   <input type="text" name="service_name" id="service_name" value="<?php echo $bservice['service_name']?>" readonly="readonly"/>
		  </div>			
	</div>
	<div class="service_row">
		  <label>Unit of Measure:</label>
		  <div class="serv_ibox_row">
			   <span class="field_error" id="serror_unit"></span>
			   <input type="text" name="unit_measure" id="unit_measure" value="<?php echo $bservice['unit_measure']?>" readonly="readonly"/>
		  </div>			
	</div>
	<div class="service_row">
		 <label>Active:</label>
		  <div class="serv_ibox_row">
			   <span class="field_error" id="serror_status"></span>
			   <select name="status" id="status" disabled="disabled ">
				   <option value="1" <?php echo ($bservice['status']==1)?'selected="selected"':'';?>>Yes</option>
				   <option value="0" <?php echo ($bservice['status']==0)?'selected="selected"':'';?>>No</option>
			   </select>
			   <input type="hidden" name="status" id="status" value="<?php echo $bservice['status']; ?>"/>
			   <input type="hidden" name="import_template" id="import_template" value="1"/>
		  </div>
	</div>	
	<div class="service_row">
		  <label>Cost $:</label>
		  <div class="serv_ibox_row">
			   <span class="field_error" id="serror_cost"></span>
			   <input type="text" name="cost" id="cost" onkeypress="return isNumber(event)" maxlength="6" value="<?php echo $bservice['cost']?>"/>
		  </div>			
	</div>	
	<div class="service_row">
		  <label>Minimum Required:</label>
		  <div class="serv_ibox_row">
			   <span class="field_error" id="serror_minimum"></span>
			   <input type="text" name="minimum" id="minimum" onkeypress="return isNumber(event)" maxlength="6" value="<?php echo $bservice['minimum']?>"/>
		  </div>			
	</div>	
	
	 <?php 
   }else{
	   ?>
	   <div class="service_row">
		  <label>Service Name:</label>
		  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_name"></span>
				   <input type="text" name="service_name" id="service_name"/>
			  </div>			
		</div>
		<div class="service_row">
			  <label>Unit Of Measure:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_unit"></span>
				   <input type="text" name="unit_measure" id="unit_measure"/>
			  </div>			
		</div>
		<div class="service_row">
			  <label>Cost $:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_cost"></span>
				   <input type="text" name="cost" id="cost" onkeypress="return isNumber(event)" maxlength="6"/>
			  </div>			
		</div>
		<div class="service_row">
			  <label>Minimum Required:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_minimum"></span>
				   <input type="text" name="minimum" id="minimum" onkeypress="return isNumber(event)" maxlength="6"/>
			  </div>			
		</div>
		
		<div class="service_row">
			 <label>Active:</label>
			  <div class="serv_ibox_row">
				   <span class="field_error" id="serror_status"></span>
				   <select name="status" id="status">
					   <option value="1" selected="selected">Yes</option>
					   <option value="0">No</option>
				   </select>
			  </div>
		</div>
	 <?php  
   }
	 ?>				  

