<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm_task.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/jquery.nestable.js');
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/task.css');

$startdateadj = $this->startdateadjustment;
$taskjobtime = $this->jobtime;
$FreqData = $this->frequency;
$CustomFreq = $this->CustmeFreq;
$TempplatData = $this->templateData;
$reportModel = new Model_Report();
$reportDetailLinks = '';
$dashboard_menu = array(51);
$reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);

?>
<div class="container-right pm-task-view" id="access-matrix">
    <section class="ch-form-header top-header">
        <h3 style="float: left;">Create A New Designation Wizard - Step 2</h3>
        <a style="float: right;" href="<?php echo $this->baseUrl() . '/pm'; ?>">
            <button type="button" class="confirm">Completed</button>
        </a>
    </section>
    <!-- Report Link -->
        <?php if ($reportDetailLinks != '') { ?> <div class="tabmenu" ><ul style="padding:0px;list-style: none;"><?php
            foreach ($reportDetailLinks as $reportvalue) {
                if ($reportvalue->Report_Type == 'Flash') {
                    $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
                } else {
                    $report_type = 'vnsreports/index.php?';
                }
                $reportOption = explode(',', $reportvalue->report_option);
                ?> <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php
                        if ((in_array('[[++VT_Designation_ID]]', $reportOption)) && $this->desig_id != '') {
                            echo '&VT_Designation_ID=' . $this->desig_id;
                        }
                        ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>
    <section class="section-menu">
         <a class="modalbox create_conf "  href="<?php echo $this->baseUrl() . '/pm/createtask/desig_id/'.$this->desig_id; ?>"> 
            <button  style="width: 6%;" class="confirm active"  >Task(s)</button>
        </a>
        <a class="modalbox create_conf "  href="<?php echo $this->baseUrl() . '/pm/createreading/desig_id/'.$this->desig_id; ?>"> 
            <button  style="width: 6%;" class="confirm"  >Reading(s)</button>
        </a>        

<!--        <a class="modalbox create_conf position"  onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/import/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"> 
            <button  style="width: 6%;" class="confirm"  >Import</button>
        </a>-->
        <a class="modalbox create_conf position"  onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/addtask/desig_id/'.$this->desig_id;?>');" href="#CreateNewMultiCon"> 
            <button  style="width: 6%;" class="confirm">Add Task</button>
        </a>

    </section>
 
    <div class="message">
        <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
        <span id="success_msg"></span>
        <span id="error_msg"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form" id="first">
        <section class="ch-form-header">
            <h3 style="float: left;"><?php echo $TempplatData->VT_Template_Name; ?>- Type Designation - <?php echo $TempplatData->VT_TypeDesignation; ?> </h3>
            <!-- view all table column name -->
            <div class="dropdown multiSelect">
                <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary" data-target="#" href="/page.html">
                    View list  <span class="caret"></span>
                </a>
                <?php //print_r($this->listview); ?>
                <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                    <li><input type="checkbox" class="showlistoption" id="1" value="1" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(1,$this->listview)?"checked":""); ?> /><a href="#">Task Instruction</a></li>
                    <li><input type="checkbox" class="showlistoption" id="2" value="2"  onclick="view_update(<?php echo $this->desig_id; ?>);"  <?php echo (in_array(2,$this->listview)?"checked":""); ?> /><a href="#">Frequency</a></li>
                    <li><input type="checkbox" class="showlistoption" id="3" value="3" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(3,$this->listview)?"checked":""); ?> /><a href="#">Start date</a></li>
                    <li><input type="checkbox" class="showlistoption" id="4" value="4" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(4,$this->listview)?"checked":""); ?> /><a href="#">End date</a></li>
                    <li><input type="checkbox" class="showlistoption" id="5" value="5" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(5,$this->listview)?"checked":""); ?> /><a href="#">Seasonal</a></li>
                    <li><input type="checkbox" class="showlistoption" id="6" value="6" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(6,$this->listview)?"checked":""); ?> /><a href="#">Seasonal Start Month</a></li>
                    <li><input type="checkbox" class="showlistoption" id="7" value="7" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(7,$this->listview)?"checked":""); ?> /><a href="#">Seasonal End Month</a></li>
                    <li><input type="checkbox" class="showlistoption" id="8" value="8" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(8,$this->listview)?"checked":""); ?>/><a href="#">Start Date Of Month</a></li>
                    <li><input type="checkbox" class="showlistoption" id="9" value="9" onclick="view_update(<?php echo $this->desig_id; ?>);"  <?php echo (in_array(9,$this->listview)?"checked":""); ?> /><a href="#">Start date Adjustment</a></li>
                    <li><input type="checkbox" class="showlistoption" id="10" value="10" onclick="view_update(<?php echo $this->desig_id; ?>);"  <?php echo (in_array(10,$this->listview)?"checked":""); ?>/><a href="#">Task job Time(Hour)</a></li>
                    <li><input type="checkbox" class="showlistoption" id="11" value="11" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(11,$this->listview)?"checked":""); ?> /><a href="#">Over Time/Off Hour</a></li>
                    <li><input type="checkbox" class="showlistoption" id="12" value="12" onclick="view_update(<?php echo $this->desig_id; ?>);" <?php echo (in_array(12,$this->listview)?"checked":""); ?> /><a href="#">Assign To</a></li>                    
                </ul>
            </div>
            <!--  End filter view -->
        </section>
        <!-- satrt listing  -->
        <section class="ch-form-header" id="viewtask">
        <div id="addcss"></div>
        <div class="dd" id="nestable">
                <ol class="dd-list">
                    <li class="dd-item dd3-item" data-id-root="">
                        <div class="dd3-content tabelHeader">                           
                            <div class="id">Task Order</div>
                            <?php if(in_array(1,$this->listview)): ?>
                                    <div class="id">Task Instruction</div>
                            <?php endif; ?>
                            <?php if(in_array(2,$this->listview)): ?>
                                    <div class="id">Frequency <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskfrequency/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                            <?php endif; ?>
                            <?php if(in_array(3,$this->listview)): ?>
                                    <div class="id">Start date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                             <?php endif; ?>
                             <?php if(in_array(4,$this->listview)): ?>
                                    <div class="id">End date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                             <?php endif; ?>
                              <?php if(in_array(5,$this->listview)): ?>
                                    <div class="id">Seasonal <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                             <?php endif; ?>
                              <?php if(in_array(6,$this->listview)): ?>
                                    <div class="id">Seasonal Start Date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                             <?php endif; ?>
                              <?php if(in_array(7,$this->listview)): ?>
                                    <div class="id">Seasonal End date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                             <?php endif; ?>
                             <?php if(in_array(8,$this->listview)): ?>
                                    <div class="id"><a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdateofmonth/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a>Start Date Of Month </div>
                             <?php endif; ?>
                            <?php if(in_array(9,$this->listview)): ?>
                                     <div class="id"><a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdateadjustment/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a>Start date Adjustment</div>
                            <?php endif; ?>
                            <?php if(in_array(10,$this->listview)): ?>
                                     <div class="id">Task job Time(Hour)</div>
                            <?php endif; ?>
                            <?php if(in_array(11,$this->listview)): ?>
                                     <div class="id">Over Time/Off Hour</div>
                            <?php endif; ?>
                            <?php if(in_array(12,$this->listview)): ?>
                                     <div class="id">Assign To</div>
                            <?php endif; ?>
                            <div class="id"></div>        
                        </div>
                    </li>
                    <?php 
                    $count = 1;
                    //print_r($this->alltask);
                    //die;
                    
                    foreach($this->alltask as $task):  
                        //print_r($task);
                          //  die;
                        ?>
                    
                        <?php 
                        //print_r($task);
                        //echo $task['task'][0]->id;
                        if($task[0]->Frequency_ID!=""){ 
                            
                            foreach($task as $fulltask):?>
                                <li class="dd-item dd3-item" data-id-root="<?php echo $fulltask->Pm_ID; ?>">
                                    <div class="dd-handle dd3-handle">Drag</div>
                                    <div class="dd3-content" style="font-weight: bold;">
                                        <div class="id"><?php echo $count; ?></div> 
                                        <?php
                                        //print_r($fulltask);
                                        if($fulltask->Interval_Value==0){
                                            $frequency = $FreqData[$fulltask->Frequency_ID];
                                        }else{
                                            $frequency = $fulltask->Interval_Value.'   '.$CustomFreq[$fulltask->Frequency_ID];
                                        }
                                        
                                        $taskj = explode(".",$fulltask->Task_jobtime);
                                        $taskjobt = "";
                                        if(!empty($taskj[0]) && $taskj[0]!=0)
                                            $taskjobt .= $taskj[0]."  hours ";
                                        if(!empty($taskj[1]))
                                            $taskjobt .= $taskjobtime['0.'.$taskj[1]];
                                                                                
                                        if(in_array(1,$this->listview))
                                                echo '<div class="id">'.$fulltask->Task_Instruction.'</div>';
                                        if(in_array(2,$this->listview))
                                                echo '<div class="id">'.$frequency.'</div>';
                                        if(in_array(3,$this->listview))
                                                echo '<div class="id">'.$fulltask->Start_date.'</div>';
                                        if(in_array(4,$this->listview))
                                                echo '<div class="id">'.$fulltask->End_date.'</div>';
                                        if(in_array(5,$this->listview))
                                                echo '<div class="id">'.$fulltask->seasonal_task.'</div>';
                                        if(in_array(6,$this->listview))
                                                echo '<div class="id">'.$fulltask->Seasonal_Start_Date.'</div>';
                                        if(in_array(7,$this->listview))
                                                echo '<div class="id">'.$fulltask->Seasonal_End_Date.'</div>';
                                        if(in_array(8,$this->listview))
                                                echo '<div class="id">'.$fulltask->Startdate_month.'</div>';
                                        if(in_array(9,$this->listview))
                                                echo '<div class="id">'.$startdateadj[$fulltask->Sda_ID].'</div>';
                                        if(in_array(10,$this->listview))                                      
                                                echo '<div class="id">'.$taskjobt.'</div>';                                        
                                        if(in_array(11,$this->listview))
                                                echo '<div class="id">'.($fulltask->overtime==0?"No":"Yes").'</div>';
                                        if(in_array(12,$this->listview))
                                                echo '<div class="id">'.($fulltask->assigned_to==1?"Default":"").'</div>';
                                        
                                        ?>
                                        <div class="id">
                                            <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/edittask/desig_id/'.$this->desig_id.'/task_id/'.$fulltask->Pm_ID;?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl();?>/public/images/edit.png"></a>
                                            <a  onclick="deletetask(<?php echo $fulltask->Pm_ID; ?>,<?php echo $this->desig_id; ?>);" ><img src="<?php echo $this->baseUrl();?>/public/images/delete.png"></a>
                                        </div>  
                                    </div>
                                </li>
                        <?php  
                            $count++;
                            endforeach; 
                            }else if($task['name']!=""){
                                //print_r($task);
                                ?>
                        <li class="dd-item dd3-item collapse-table" data-id-subset="<?php echo $task['id']; ?>">
                            <div class="dd-handle dd3-handle">Drag</div>
                            <div class="dd3-content">
                                <div class="id"><?php echo $count; ?></div>
                                 <?php if(in_array(1,$this->listview)): ?>
                                    <div class="id">Task Instruction</div>
                                <?php endif; ?>
                                <?php if(in_array(2,$this->listview)): ?>
                                        <div class="id">Frequency <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskfrequency/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                                <?php endif; ?>
                                <?php if(in_array(3,$this->listview)): ?>
                                        <div class="id">Start date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                                 <?php endif; ?>
                                 <?php if(in_array(4,$this->listview)): ?>
                                        <div class="id">End date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                                 <?php endif; ?>
                                  <?php if(in_array(5,$this->listview)): ?>
                                        <div class="id">Seasonal <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                                 <?php endif; ?>
                                  <?php if(in_array(6,$this->listview)): ?>
                                        <div class="id">Seasonal Start Date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                                 <?php endif; ?>
                                  <?php if(in_array(7,$this->listview)): ?>
                                        <div class="id">Seasonal End date <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdate/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a></div>
                                 <?php endif; ?>
                                 <?php if(in_array(8,$this->listview)): ?>
                                        <div class="id"><a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdateofmonth/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a>Start Date Of Month </div>
                                 <?php endif; ?>
                                <?php if(in_array(9,$this->listview)): ?>
                                         <div class="id"><a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/taskstartdateadjustment/desig_id/'.$this->desig_id; ?>');" href="#CreateNewMultiCon"><span class="glyphicon glyphicon-chevron-down"></span></a>Start date Adjustment</div>
                                <?php endif; ?>
                                <?php if(in_array(10,$this->listview)): ?>
                                         <div class="id">Task job Time(Hour)</div>
                                <?php endif; ?>
                                <?php if(in_array(11,$this->listview)): ?>
                                         <div class="id">Over Time/Off Hour</div>
                                <?php endif; ?>
                                <?php if(in_array(12,$this->listview)): ?>
                                         <div class="id">Assign To</div>
                                <?php endif; ?>
                                <div class="id">
                                    <a onclick="javascript:openpopup('<?php echo $this->baseUrl() . '/pm/editsubset/subset_id/'.$task['id']."/desig_id/".$this->desig_id; ?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl();?>/public/images/edit.png"></a>
                                    <a onclick="deletetask(<?php echo $task['id']; ?>,<?php echo $this->desig_id; ?>);"><img src="<?php echo $this->baseUrl();?>/public/images/delete.png"></a>
                                </div>  
                            </div>
                            <ol class="dd-list">                                    
                                <?php 
                                $countsub = 1;
                                foreach ($task['task'] as $fulltask): ?>                                                
                                    <li class="dd-item dd3-item" data-id="<?php echo $fulltask->id;?>">
                                        <div class="dd-handle dd3-handle">Drag</div>
                                        <div class="dd3-content">
                                        <div class="id" style="text-align:right;"><?php echo $countsub; ?></div>     
                                            <?php
                                        //print_r($fulltask);
                                        if($fulltask->Interval_Value==0){
                                            $frequency = $FreqData[$fulltask->Frequency_ID];
                                        }else{
                                            $frequency = $fulltask->Interval_Value.'   '.$CustomFreq[$fulltask->Frequency_ID];
                                        }
                                        
                                        $taskj = explode(".",$fulltask->Task_jobtime);
                                        $taskjobt = "";
                                        if(!empty($taskj[0]) && $taskj[0]!=0)
                                            $taskjobt .= $taskj[0]."  hours ";
                                        if(!empty($taskj[1]))
                                            $taskjobt .= $taskjobtime['0.'.$taskj[1]];
                                                                                
                                        if(in_array(1,$this->listview))
                                                echo '<div class="id">'.$fulltask->Task_Instruction.'</div>';
                                        if(in_array(2,$this->listview))
                                                echo '<div class="id">'.$frequency.'</div>';
                                        if(in_array(3,$this->listview))
                                                echo '<div class="id">'.$fulltask->Start_date.'</div>';
                                        if(in_array(4,$this->listview))
                                                echo '<div class="id">'.$fulltask->End_date.'</div>';
                                        if(in_array(5,$this->listview))
                                                echo '<div class="id">'.$fulltask->seasonal_task.'</div>';
                                        if(in_array(6,$this->listview))
                                                echo '<div class="id">'.$fulltask->Seasonal_Start_Date.'</div>';
                                        if(in_array(7,$this->listview))
                                                echo '<div class="id">'.$fulltask->Seasonal_End_Date.'</div>';
                                        if(in_array(8,$this->listview))
                                                echo '<div class="id">'.$fulltask->Startdate_month.'</div>';
                                        if(in_array(9,$this->listview))
                                                echo '<div class="id">'.$startdateadj[$fulltask->Sda_ID].'</div>';
                                        if(in_array(10,$this->listview))                                      
                                                echo '<div class="id">'.$taskjobt.'</div>';                                        
                                        if(in_array(11,$this->listview))
                                                echo '<div class="id">'.($fulltask->overtime==0?"No":"Yes").'</div>';
                                        if(in_array(12,$this->listview))
                                                echo '<div class="id">'.($fulltask->assigned_to==1?"Default":"").'</div>';
                                        
                                        ?>
                                        <div class="id">
                                            <a onclick="edittask(<?php echo $fulltask->Pm_ID; ?>,<?php echo $this->desig_id; ?>);"><img src="<?php echo $this->baseUrl();?>/public/images/edit.png"></a>
                                            <a onclick="deletetask(<?php echo $fulltask->Pm_ID; ?>,<?php echo $this->desig_id; ?>);"><img src="<?php echo $this->baseUrl();?>/public/images/delete.png"></a>
                                        </div>                                         
                                        </div>
                                    </li>                                                
                                <?php 
                                $countsub++;
                                endforeach; ?>
                            </ol>
                        </li>
                        <?php 
                        $count++;
                        } ?>
        
                    <?php endforeach; ?>
                </ol>
            </div>
<script>
    $(function() {
        $('#nestable').nestable({
            group: 1,
            maxDepth:2
        })
        .on('change', function(e) {
            var list = e.length ? e : $(e.target);
            console.log(list.nestable('serialize'));
            $('#nestable-output').val(window.JSON.stringify(list.nestable('serialize')));
            //// send data to update ordering
            $('.loader').show();
            //$('.success_message').show();
            $.ajax({    
                type: "POST",
                url: baseUrl + 'pm/updatetaskorder',
                data: {task: window.JSON.stringify(list.nestable('serialize'))},
                success: function (data) {
                    $('.loader').hide();
                    var content = $.parseJSON(data);
                    //////////////////////
                    var list  = "";
                    $("input[type='checkbox']:checked").each(function(){
                        console.log($(this).val());  
                        list += parseInt($(this).val())+","; 
                    });
                    list =list.substring(0,list.length - 1);
                    var all = list.split(',');
                    var ctotal = all.length;
                    console.log("total "+ctotal);
                    cssdata = 94 / (ctotal + 1) ;
                    csscolapsdata = 92.25 / (ctotal + 1) ;
                    var html = ".dd3-content .id{";
                        html += "width : " + cssdata+ "%";
                        html +="}";
                        html += ".collapse-table .dd3-content .id{";
                        html += "width : " + csscolapsdata+ "%";
                        html +="}";
                    //////////////////////////////
                    if (content.status == 'success') {
                    //$('.success_message').html(content.msg); 
                             $.ajax({    
                                    type: "POST",
                                    url: baseUrl + 'pm/viewtask/desig_id/<?php echo $this->desig_id; ?>',
                                    data: {viewlist: list},
                                    success: function (response) {
                                       $("#viewtask").html(response);
                                       //$('.success_message').slideUp(500);
                                       $( "#addcss" ).html( '<style>'+html+'</style>' );
                                    }
                             });
                    } else if (content.status == 'error') {
                        //$('.success_message').html(content.msg);
                        $.ajax({    
                                type: "POST",
                                url: baseUrl + 'pm/viewtask/desig_id/<?php echo $this->desig_id; ?>',
                                data: {viewlist: list},
                                success: function (response) {
                                   $("#viewtask").html(response);
                                   //$('.success_message').slideUp(500);
                                   $( "#addcss" ).html( '<style>'+html+'</style>' );

                                }
                        });
                    }
                }
            });
        });
    });
    </script>
            <!-- Script End -->
        </section>
        <!-- End listing  -->
    </section>



</div>

<div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>"></div>

<style>
    #search_txt > input {
        width: 200px;
        padding: 4px 9px !important;
    }
    input#pmsearch_by {
        margin-left: 32px;
        /* padding-left: 38px; */
        height: 30px;
        width: 184px;
    }
    button.confirm.active {
        background-color: #45e4a8;
    }

</style>
<style>

.multiSelect .dropdown-menu{
	    max-width: 650px!important;
}
.multiSelect ul li{
	display: inline-block;
	padding:5px 10px;
	margin:2px 2px;
	
}
.multiSelect ul li input{
	margin:0;
	vertical-align: bottom;
}
.multiSelect .dropdown-menu>li>a {
    display: inline-block!important;
    padding: 0 5px!important;
    clear: both;
    font-weight: 400;
    line-height: 100%!important;
    color: #333;
    white-space: nowrap;
}
a.modalbox.create_conf.position {
    margin-left: 81%;
}


 
</style>

<script>
    $(function() {
    $('.date-picker').datepicker( {
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        dateFormat: 'MM yy',
        minDate: 0,
        onClose: function(dateText, inst) { 
            
            
            function isDonePressed(){
                            return ($('#ui-datepicker-div').html().indexOf('ui-datepicker-close ui-state-default ui-priority-primary ui-corner-all ui-state-hover') > -1);
                        }

                        if (isDonePressed()){
                            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                            
                            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                                $(this).datepicker('setDate', new Date(year, month, 1));
                                console.log('Done is pressed'+month);
                                month = parseInt(month) + 1;
                                var alldays = new Date(year, month, 0).getDate();
                                console.log("Number of days in selected Days"+alldays);
                                html = "";
                                html +='<option value="lastday" >Last day</option>';
                                for(i=1;i<=alldays;i++){
                                    html+='<option value="'+i+'">'+i+'</option>';
                                }
                                $("#sdom").html(html);
                                
                        }
                        function getformatedays(n){
                            if (n >= 11 && n <= 13) {
                                return "th";
                            }
                            switch (n % 10) {
                                case 1:  return "st";
                                case 2:  return "nd";
                                case 3:  return "rd";
                                default: return "th";
                            }
                        }
            
        }
    });
    
    
});
</script>

<script>
view_all_Task(<?php echo $this->desig_id; ?>);
</script>
