<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm.js');
?>
<div class="container-right">
    <div class="message">               
        <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Create New Template Name </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 158px;" >                        
                    <div class="row">
                        <label> Template Name:<span class="required">*</span></label><span class="ugroupErr" id="location-error"></span>
                        <input type="text" value="" id="templateName" class="" name="templateName" placeholder="Template Name" maxlength="50">
                        <span class="ugroupErr" id="tempate_name_error" style="float: left;margin-left: 276px;"></span>
                    </div>                   
                    <div class="confirmBtn float_none">
                        <input type="hidden" name="template_id" id="template_id" value="" >
                        <input type="button" value="Save" name="save" class="confirm" id='emailsave' onclick="validateequipmenttemplate();">
                        <input type="button" value="Cancel" name="cancel" class="cancel" onclick="canceltemplate();">
                    </div>
                </div>   
            </div>
        </div>
</div>

<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>