<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm.js');
?>
<div class="container-right">
    <div class="message">               
            <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Create New Type Designation Wizard - 1 | Create Designation Name </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 300px">
                    <div id="step1">
                        <div class="row">
                            <label> Select Template:<span class="required">*</span></label><span class="ugroupErr" id="location-error"></span>                            
                            <select name="templateName" id="templateName">
                                <option value=""> Please select Template </option>
                                <?php foreach($this->templats as $temp): ?>
                                    <option value="<?php echo $temp->VT_Template_Name_ID; ?>" ><?php echo $temp->VT_Template_Name; ?></option>
                                <?php  endforeach; ?>
                            </select> 
                            <span class="ugroupErr" id="tempate_name_error" style="float: left;margin-left: 276px;"></span>
                        </div>
                        <div class="row">
                            <label> Type Designation:<span class="required">*</span></label><span class="ugroupErr" id="location-error"></span>
                            <input type="text" value="" id="typedesignation" class="" name="typedesignation" maxlength="30" placeholder="Type Designation"> 
                            <span class="ugroupErr" id="typedesignation_error" style="float: left;margin-left: 276px;"></span>
                        </div>
                        <div class="row">
                            <label> Type Description:</label><span class="ugroupErr" id="location-error"></span>
                            <textarea name="typedescription" id="typedescription"></textarea>
                        </div>
                        <div class="confirmBtn float_none">
                            <input type="hidden" name="typedesination" id="typedesination_id" value="" >
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="canceltemplate();">
                            <input type="button" value="Next" name="save" class="confirm" id='emailsave' onclick="validate_type_designation();">

                            <input type="hidden" value="" id="total">
                        </div>

                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>