<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm_task.js');
$customedata = $this->customedata;

?>
<div class="container-right">
    <div class="message">               
            <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Custom Job Time </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 150px">
                    <div id="step1">
                        <div class="row">
                            <label style="float: none;text-align: -webkit-center;">Hours<span class="required">*</span></label>
                            <input type="number" min="1" name="hours" value="<?php echo $customedata[0]; ?>" id="hours" style="width: 12%;margin-left: -9%;height: 33px;">
                            Minute(s)
                            <select name="minutes" id="minutes" style="width: 28%; margin-left: 15px;">
                                 <?php foreach($this->timejob as $key=>$val){ ?>
                                    <option value="<?php echo $key; ?>" <?php echo ($customedata[0]==$key?"SELECTED":"");?> ><?php echo $val; ?></option>
                                <?php } ?>
                            </select> 
                            <span class="ugroupErr" id="tempate_name_error" style="float: left;margin-left: 276px;"></span>
                        </div>
                        
                        <div class="confirmBtn float_none">
                            <input type="hidden" name="typedesination" id="typedesination_id" value="" >                            
                            <input type="button" value="Save" name="save" class="confirm" id='emailsave' onclick="clonecustometimejob();">
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="canceltemplate();">                            
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>