<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm-equipment.js');
$eqpDetailData = $this->eqpDetailData;

$edittask = $this->taskdata;
//print_r($edittask);
$startdateadj = $this->startdateadjustment;
$frequency = $this->frequency;
$Interval = $this->Interval;
$taskjobtime = $this->jobtime;
$taskjcust = false;
$hours = "";
$Min = "";
//print_r($taskjobtime);
if (!array_key_exists($edittask->Task_jobtime, $taskjobtime)) {
    $taskjcust = true;
    $timejob = explode(".", $edittask->Task_jobtime);
    $hours = $timejob[0];
    $Min = "0." . $timejob[1];
}
$months = array(
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July ',
    'August',
    'September',
    'October',
    'November',
    'December',
);
?>

<div class="container-right task-popup">
    <div class="message">               
        <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form form-inline">
        <section class="ch-form-header ">
            <h3>Edit Start date </h3>
        </section>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label  class="control-label col-sm-3 col-md-3 col-xs-3">Level-Subset</label>
                <select name="level" id="subset_level" class="form-control" disabled="disabled">
                    <option value="0">Root</option>
                    <?php foreach ($this->subset as $subset): ?>
                        <option disabled="disabled" value="<?php echo $subset->AU_Template_Task_ID; ?>" <?php echo ($edittask->Parent_ID == $subset->AU_Template_Task_ID ? "SELECTED" : ""); ?> ><?php echo $subset->Task_Instruction; ?></option>
                    <?php endforeach; ?>
                </select>

            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label  class="control-label col-sm-3 col-md-3 col-xs-3">Task Instruction</label>
                <textarea disabled="disabled" name="task_instruction" class="form-control" id="task_instruction" style="width: 67%!important;"><?php echo $edittask->Task_Instruction; ?> </textarea>
                <span class="task_inst_error error"></span>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Frequency</label>
                <input type="radio" name="freq" id="freq" <?php echo ($edittask->Interval_Value == 1 || $edittask->Interval_Value == 0 ? "Checked" : ""); ?>  onclick="check_freq()" value="1" disabled="disabled" >
                <select name="level" id="frequency" class="form-control" onchange="freqevent();" disabled="disabled">
<?php foreach ($frequency as $key => $val) { ?>
                        <option disabled="disabled" value="<?php echo $key; ?>"  <?php echo ($edittask->AU_Frequency_ID == $key ? "SELECTED" : ""); ?>><?php echo $val; ?></option>
                    <?php } ?>                   
                </select>
                <input type="radio" name="freq" id="freq1"  <?php echo ($edittask->Interval_Value != 1 && $edittask->Interval_Value != 0 ? "Checked" : ""); ?>  onclick="check_freq()" value="2" disabled="disabled"> Perform Task Every 
                <input type="number" onkeypress='return event.charCode > 48 && event.charCode <= 57' id="freq_num" style="width: 70px!important;" name="" min="1" class="form-control" value="<?php echo ($edittask->Interval_Value == 1 ? 1 : $edittask->Interval_Value); ?>" disabled="disabled">
                <select name="level" id="frequency1" class="form-control" onchange="freqevent();" disabled="disabled">
<?php foreach ($Interval as $key => $val) { ?>
                        <option disabled="disabled" value="<?php echo $key; ?>" <?php echo ($edittask->AU_Frequency_ID == $key ? "SELECTED" : ""); ?> disabled="disabled"><?php echo $val; ?></option>
                    <?php } ?>                   
                </select>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Start Date</label>
                <div class="col-md-8 col-sm-8 col-xs-8">
                    <!--    <input type='text' class="form-control" id='datetimepicker4' />-->
                    <input name="startdate" id="startdate" class="date-picker1 form-control"  value="<?php echo $eqpDetailData['Start_date']; ?>" />
                    <input name="endDate" id="endDate" class="date-picker2 form-control" value="<?php echo $edittask->End_date; ?>" disabled="disabled" /> End Date (Optional)
                    <!--<a class="resetenddate" onclick="resetEnd()">Reset EndDate</a>-->
                    <br>
                    <input type="checkbox" name="seasonal" id="seasonal" <?php echo ($edittask->Seasonal_Task == 'Y' ? "Checked" : ""); ?> onclick="seasonal();" disabled="disabled" > Seasonal task (If Checked)<br>
                    <span id="seasonal_section">
                        <span class="left">
                            <label class="control-label">Begin Date</label> 
                            <select name="begDate" id="begDate" class="form-control" disabled="disabled" onchange="begDate();" disabled="disabled">
<?php foreach ($months as $val) { ?>
                                    <option value="<?php echo $val; ?>" <?php echo ($edittask->Seasonal_Start_Date == $val ? "SELECTED" : ""); ?>><?php echo $val; ?></option>
                                <?php } ?>
                            </select>

<!--                            <input name="begDate" readonly="readonly" id="begDate" class="date-picker form-control" value="<?php echo $edittask->Seasonal_Start_Date; ?>" />-->
                        </span>
                        <span class="right">
                            <label class="control-label">Stop Date</label> 
                            <select name="begDate" id="stopDate" class="form-control" disabled="disabled" >
<?php foreach ($months as $val) { ?>
                                    <option value="<?php echo $val; ?>" <?php echo ($edittask->Seasonal_End_Date == $val ? "SELECTED" : ""); ?>><?php echo $val; ?></option>
                                <?php } ?>
                            </select>
<!--                            <input name="stopDate" readonly="readonly" id="stopDate" class="date-picker form-control" value="<?php echo $edittask->Seasonal_End_Date; ?>" />-->
                        </span>
                    </span>
                    <span class="startDate_error error"></span>

                </div>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Day Of Month</label>
<?php
if ($edittask->AU_Frequency_ID > 2) {
    $days = 28;
} else {
    $days = date("t", strtotime($edittask->Start_date));
}
?>
                <select name="level" id="sdom" class="form-control">
                <?php
                for ($i = 1; $i <= $days; $i++):
                    echo '<option value="' . $i . '" ' . ($eqpDetailData['eqp_Startdate_month'] == $i ? "SELECTED" : "") . ' >' . $i . '</option>';
                endfor;
                ?>
                </select> 
                    <?php //echo $edittask->Startdate_month; ?>
                <span id="sdomView" style="display:<?php echo ($edittask->Startdate_month == 'lastday' || $edittask->AU_Frequency_ID > 2 ? "" : "none") ?>;">
                    <input type="checkbox" name="domlast" id="domlast" <?php echo ($edittask->Startdate_month == 'lastday' && $edittask->AU_Frequency_ID > 2 ? "Checked" : "") ?> value="lastday" onclick="lastday();" disabled="disabled" > Last Day
                </span>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Date Adjustment</label>            
                <select name="level" class="form-control" id="startdateadjustment" disabled="disabled">
<?php foreach ($startdateadj as $key => $val) { ?>
                        <option value="<?php echo $key; ?>" <?php echo ($edittask->AU_sda_ID == $key ? "SELECTED" : ""); ?> disabled="disabled"><?php echo $val; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">    
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Job-Time(In Hours)</label>
                <input type="radio" name="jobtime" id="jobtime1" value="1" <?php echo ($taskjcust == false ? "Checked" : ""); ?>  onclick="jobtimeact();" disabled="disabled">
                <select name="level"  class="form-control" id="taskjobtime" onchange="taskjobcheck()"  style="width: 130px!important;" disabled="disabled">
<?php foreach ($taskjobtime as $key => $val) { ?>
                        <option value="<?php echo $key; ?>" <?php echo ($edittask->Task_jobtime == $key ? "SELECTED" : ""); ?> disabled="disabled"><?php echo $val; ?></option>
                    <?php } ?>
                </select>
                <input type="radio" name="jobtime" id="jobtime2" value="1" <?php echo ($taskjcust == true ? "Checked" : ""); ?> onclick="jobtimeact();" disabled="disabled"> Hour(s)
<!--                    <input type="number" onkeypress='return event.charCode > 48 && event.charCode <= 57' min="1" id="custome_hours" style="width:60px!important;" class="form-control" name="custome_hours" value="<?php echo $hours; ?>">-->
                <select name="level"  class="form-control" id="custome_hours" disabled="disabled">
<?php for ($jtime = 1; $jtime <= 59; $jtime++) { ?>
                        <option value="<?php echo $jtime; ?>" <?php echo ($hours == $jtime ? "SELECTED" : ""); ?> ><?php echo $jtime; ?></option>
                    <?php } ?>
                </select>
                Minute(s)                        
                <select name="level"  class="form-control" id="taskjobtime1" onchange="taskjobcheck()"  style="width: 130px!important;" disabled="disabled">
<?php
foreach ($taskjobtime as $key => $val) {
    if ($key >= 1)
        continue;
    ?>
                        <option value="<?php echo $key; ?>" <?php echo ($Min == $key ? "SELECTED" : ""); ?>><?php echo $val; ?></option>
                    <?php } ?>
                </select>

            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Over Time/Off Hours</label>
                <select name="level" id="overtime" class="form-control" disabled="disabled">
                    <option value="0" <?php echo ($edittask->overtime == 0 ? "SELECTED" : ""); ?> disabled="disabled">No</option>
                    <option value="1" <?php echo ($edittask->overtime == 1 ? "SELECTED" : ""); ?> disabled="disabled">YES</option>                
                </select>           
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-md-3 col-xs-3">Assigned To</label>
                <select name="level" id="assignedto" class="form-control">
                    <?php foreach ($this->emailGroup as $emails): ?>
                        <option value="<?php echo $emails['id']; ?>" <?php if ($eqpDetailData['Email_group_ID'] == $emails['id']) {
                        echo 'selected=selected';
                    } ?>><?php echo $emails['group_name']; ?></option>
<?php endforeach; ?>
                </select>
                <input type="hidden" name="action" id="action" value="update">
                <input type="hidden" name="task_id" id="task_id" value="<?php echo $edittask->AU_Template_Task_ID; ?>">
                <input type="hidden" name="desig_id" id="desig_id" value="<?php echo $this->desig_id; ?>">
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
            <button class="confirm" onclick="closepopup();">Cancel</button>
            <button class="confirm" onclick="update_equipmentdetailtask_startdate('<?php echo $eqpDetailData['AU_Equipment_Task_ID']; ?>');">Update & Close</button>
            <!--    <button class="confirm" onclick="validationtask();">Update & New</button>-->
        </div>  
    </section>
</div>
<div id="add_subsetpopup" class="bd-dft-cls" style="display: none;"></div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>">
</div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>
<script>
    $(function () {
        var d = $('#startdate').val();
        d1 = d.split(" ");
        //alert(d1[1]);
        var myDate2 = new Date($('#startdate').val());
        myDate2.setMonth(myDate2.getMonth( ) + 1);

        var result2 = new Date(d1[1], myDate2.getMonth());

        //alert(result2);
        from = $(".date-picker1")
                .datepicker({
                    changeMonth: true,
                    changeYear: true,
                    dateFormat: 'MM yy',
                    minDate: 0,
                    defaultDate: new Date($('.date-picker1').val()),
                    // defaultdate:'12-02-2020',
                    showButtonPanel: true,
                    numberOfMonths: 1,

                    onClose: function (dateText, inst) {
                        //alert(dateText);

                        var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();

                        var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                        var datetime = new Date(year, month, 1);


                        $(this).datepicker('setDate', new Date(year, month, 1));
                        //alert(datetime);
                        var d = new Date(datetime);
                        d.setMonth(d.getMonth( ) + 1);
                        // textbox1 = ( d.getMonth( ) + 1 ) + '/' + d.getDate( ) + '/' + d.getFullYear( );

                        // var dt = getDate( this );
                        //alert(d);
                        month = parseInt(month) + 1;
                        var alldays = new Date(year, month, 0).getDate();
                        console.log("Number of days in selected Days" + alldays);
                        html = "";
                        //html +='<option value="lastday" >Last day</option>';
                        for (i = 1; i <= alldays; i++) {
                            html += '<option value="' + i + '">' + i + '</option>';
                        }

                        // 28 days 

                        html1 = "";
                        //html +='<option value="lastday" >Last day</option>';
                        for (i = 1; i <= 28; i++) {
                            html1 += '<option value="' + i + '">' + i + '</option>';
                        }

                        var Frequency_ID = "";
                        if ($("#freq:checked").length === 1) {
                            Frequency_ID = $("#frequency").val();
                        } else {
                            Frequency_ID = $("#frequency1").val();
                        }

                        //alert(Frequency_ID);
                        if (Frequency_ID < 3) {
                            $("#sdom").html(html);
                            $("#sdomView").hide();
                            $("#sdom").attr("disabled", false);
                        } else {
                            $("#sdom").html(html1);
                            $("#sdomView").show();
                        }

                        to.datepicker("option", "minDate", d);
                    }
                }),
                to = $(".date-picker2").datepicker({

            changeMonth: true,
            changeYear: true,
            dateFormat: 'MM yy',
            showButtonPanel: true,
            numberOfMonths: 1,
            //minDate : new Date($('#startDate').val()),
            minDate: new Date(result2),
            //defaultDate: new Date($('.date-picker1').val()),
            //minDate:0,
            onClose: function (dateText, inst) {
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();

                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
                //var datetime =  new Date(year, month, 1);
                //alert(datetime);
                //from.datepicker( "option", "maxDate", datetime );
            }
        });

        $(".date-picker2").datepicker({

            changeMonth: true,
            changeYear: true,
            dateFormat: 'MM yy',
            showButtonPanel: true,
            numberOfMonths: 1,
            //minDate : new Date($('#startDate').val()),
            minDate: new Date(result2),
            //defaultDate: new Date($('.date-picker1').val()),
            //minDate:0,
            onClose: function (dateText, inst) {
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();

                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));

            }
        });




        function getDate(element) {
            var date;
            try {
                date = $.datepicker.parseDate(dateFormat, element.value);
            } catch (error) {
                date = null;
            }

            return date;
        }

    });



    function freqevent() {
        // 28 days 

        var month = $("#startdate").val();
        var dob = month.split(" ");
        //var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
        // console.log(dob);
        var date = new Date(), y = dob[1].trim(), m = dob[0].trim();
        var namenumber = new Date(Date.parse(m + " 1, " + y)).getMonth() + 1;
        // alert(namenumber);
        //var firstDay = new Date("", m, 1);
        var lastDay = new Date(y, namenumber + 1, 0).getDate();
        // alert(lastDay);

        html = "";

        for (i = 1; i <= lastDay; i++) {
            html += '<option value="' + i + '">' + i + '</option>';
        }

        // 28 days
        html1 = "";
        //html +='<option value="lastday" >Last day</option>';
        for (i = 1; i <= 28; i++) {
            html1 += '<option value="' + i + '">' + i + '</option>';
        }

        var Frequency_ID = "";
        if ($("#freq:checked").length === 1) {
            Frequency_ID = $("#frequency").val();
        } else {
            Frequency_ID = $("#frequency1").val();
        }

        //alert(html);
        if (Frequency_ID < 3) {
            $("#sdom").html(html);
            $("#sdomView").hide();
            $("#sdom").attr("disabled", false);
        } else {
            $("#sdom").html(html1);
            $("#sdomView").show();
        }
    }

    function getformatedays(n) {
        if (n >= 11 && n <= 13) {
            return "th";
        }
        switch (n % 10) {
            case 1:
                return "st";
            case 2:
                return "nd";
            case 3:
                return "rd";
            default:
                return "th";
        }
    }

</script>
<style>

    span.left {
        width: 39%;
    }
    input#begDate {
        width: 100% !important;
    }
    .ch-home-form .form-group{
        width:100%;
        margin: 8px 0;
    }
    .ch-home-form .form-group #startdate{
        width: 130px !important;
    }
    .ch-home-form .form-group #endDate{
        width: 130px !important;
    }
    .ch-home-form .form-group .form-control{
        width: auto!important;
        display: inline-block;
    }
    .ch-home-form .left{
        float: left;
        margin: 0;
    }
    .ch-home-form .right{
        float: right;
        margin: 0;
    }
    .ch-home-form .left label, .ch-home-form .right label{
        width: 100%
    }

    table.ui-datepicker-calendar {
        display: none;
    }

    #startdate[readonly]{
        cursor: auto !important; 
        background-color: white !important; 
        opacity: 1 !important; 
    }

    #endDate[readonly]{
        cursor: auto !important; 
        background-color: white !important; 
        opacity: 1 !important; 
    }
    #begDate[readonly]{
        cursor: auto !important; 
        background-color: white !important; 
        opacity: 1 !important; 
    }

    #stopDate[readonly]{
        cursor: auto !important; 
        background-color: white !important; 
        opacity: 1 !important; 
    }
    #custome_hours[readonly]{
        cursor: auto !important; 
        background-color: white !important; 
        opacity: 1 !important; 
    }

    #freq_num[readonly]{
        cursor: auto !important; 
        background-color: white !important; 
        opacity: 1 !important; 
    }
    .resetenddate{
        margin-left: 273px;
        border: 1px solid green;
        background: green;
        color: white;
        padding: 1px 7px 2px 6px;
    }
</style>
<script>
    function resetEnd() {
        $("#endDate").val("");
    }
    check_freq();
    jobtimeact();
    seasonal();
    //freqevent();
    lastday();
</script>