<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm_task.js');
$subset = $this->subsetdata;
//print_r($subset);
?>
<div class="container-right">
    <div class="message">               
        <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Update Level – Subset </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 158px;" >                        
                    <div class="row">
                        <label> Subset Name:<span class="required">*</span></label><span class="ugroupErr" id="location-error"></span>
                        <input type="text"  id="subsetname" class="" name="subsetname" placeholder="Subset Name" value="<?php echo $subset->Task_Instruction; ?> ">
                        <span class="ugroupErr" id="tempate_name_error" style="float: left;margin-left: 276px;"></span>
                    </div>                   
                    <div class="confirmBtn float_none">
                        <input type="hidden" name="subsetname_id" id="subsetname_id" value="<?php echo $subset->VT_Template_Task_ID; ?>" >
                        <input type="hidden" name="desig_id" id="desig_id" value="<?php echo $this->desig_id; ?>" >
                        <input type="button" value="Update" name="save" class="confirm" id='emailsave' onclick="validatesubset();">
                        <input type="button" value="Cancel" name="cancel" class="cancel" onclick="closepopup();">
                    </div>
                </div>   
            </div>
        </div>
</div>

<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
