<?php
//echo '<pre>';
//print_r($this->equipmentList);
?>
<style>
    /*//////////////////////////////////////////////////////////////////
[ RESTYLE TAG ]*/
    * {
        margin: 0px; 
        padding: 0px; 
        box-sizing: border-box;
    }


    /*//////////////////////////////////////////////////////////////////
    [ Table ]*/

    .limiter {
        width: 100%;
        margin: 0 auto;
    }

    .container-table100 {
        width: 100%;
        min-height: 100vh;
        background: #d1d1d1;

        display: -webkit-box;
        display: -webkit-flex;
        display: -moz-box;
        display: -ms-flexbox;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        padding: 33px 30px;
    }

    .wrap-table100 {
        width: 1170px;
    }

    .table100 
    {
    }

    /*//////////////////////////////////////////////////////////////////
    [ Table ]*/
    table {
        width: 100%;
        /*background-color: #fff;*/
    }

    th, td {
        font-weight: unset;
        padding-right: 10px;
    }

    .column100 {

        padding-left: 25px;
    }

    .column100.column1 {

    }

    .row100.head th {
        padding: 14px;
    }

    .row100 td {
        padding: 2px;
        border-bottom: 0px;
        border-top: 1px solid #ccc;
        border-left: 1px solid #ccc;
        border-right: 1px solid #ccc;

    }


    /*==================================================================
    
    [ Ver2 ]*/
    .table100.ver2 td {
        font-size: 14px;
        color: #808080;
        line-height: 1.4;
    }

    .table100.ver2 th {
        font-size: 12px;
        color: #fff;
        line-height: 1.4;
        text-transform: uppercase;
        background-color: #333333;
    }

    .table100.ver2 .row100:hover td {

    }

    .table100.ver2 .hov-column-ver2 {

    }

    .table100.ver2 .hov-column-head-ver2 {
        background-color: #484848 !important;
    }

    .table100.ver2 .row100 td:hover {

    }

    .eqpment-box
    {
        margin-top: 30px;
        margin-bottom: 30px;	
    }

    /*==================================================================
    [ Ver2 ]*/

    .table100.ver2 td {
        color: #000;
        line-height: 1.4;

    }

    .table100.ver2 th {

        color: #000;
        line-height: 1.4;
        text-transform:none;
        background-color: #2a6496;
        border-right: 1px solid #ccc;
    }

    .table100.ver2 .row100:hover td {

    }

    .table100.ver2 .hov-column-ver2 {
        background-color: #83d160;
        color: #fff;
    }

    .table100.ver2 .hov-column-head-ver2 {
        background-color: #484848 !important;
    }

    .table100.ver2 .row100 td:hover {

    }

    .heading-main-equipmnt
    {
        background-color: #34495e;
        color: #fff;
        padding: 9px 8px;
        border-bottom: 0px solid #ccc;
    }

    .heading-sub-equipmnt
    {
        background-color: #2a6496;
        color: #fff;
        padding: 5px 3px;
    }

    .btn-csttm
    {
        border-radius:0px;
        font-style: italic;

    }


    .search-box-main-row
    {
        padding-bottom: 20px !important;
    }

    .bttons-view-right
    {
        text-align: right;
        right: 0px;
        padding-right: 0px;
    }

    .input-csttm
    {
        border-radius:0px;	
    }

    .serch-text-style
    {
        font-weight:600;
    }

    .border-left-gray
    {
        border-left: 1px solid #ccc;
    }

    .border-left-0
    {
        border-left: 0px solid #ccc;
    }


    .border-right-0
    {
        border-right:0px;
    }

    .border-bottom-0
    {
        border-bottom:0px;
    }

    .fa-icon i
    {
        font-size:14px;
        padding-right: 0px;
    }

    .row100 th {
        padding: 5px 3px;
        text-align: center;
    }

    .background-collr
    {

    }

    .padd-0{
        padding:0px !important;
    }

    .sub-bg-bckgrnd
    {
        background-color:#92cddc;
    }

    .sub-bg-bckgrnd-light
    {
        background-color:#dbeef3;
    }

    .border-corner
    {
        border-left: 0 !important;
        border-top: 0 !important;
        border-bottom: 0 !important;
    }

    .border-corner-1
    {
        border-right: 0 !important;
        border-top: 0 !important;
        border-bottom: 0 !important;
    }

    .heading-tr
    {
        background-color: #fff !important;  
    }

    .input-csttm-padd-0
    {
        margin:0px !important; 
    }

    .heading-sub-equipmnt .arrow-shrting{

    }
    .arrow-shrting
    {
        color:#fff;
        padding-left: 10px;
    }

    .colm-new01
    {
        width:4%;  
    }

    .colm-new02
    {
        width:2%;  
    }

    .colm-new03
    {
        width:8%;  
    }

    .colm-new04
    {
        width:8%;  
    }

    .colm-new05
    {
        width:10%;  
    }

    .colm-new06
    {
        width:25%;  
    }

    .colm-new07
    {
        width:25%;  
    }

    .colm-new03-th
    {
        width: 8%;    
    }

    .table100.ver2 td {
        padding-right: 0px;
    }

    .equp-sub-box
    {
        width: 12% !important;   
    }

    .blue-bg
    {
        background-color: #92cddc !important; 
    }
    .right-x{
        border: 1px solid #ccc;;
    }
    .common-wrap input[type="text"]{
        width: 100%;
    }
    .common-wrap  select {
        width: 100%;
    }
    .common-btn { text-align: left; }
    .modified_btn button{ background: #06af8f; color:#000; font-weight: bold;  padding: 3px 10px; border-radius: 3px; box-shadow: 2px 2px 5px #ccc; 
                          border: none; font-size: 16px !important; line-height: 1;}
    .border-none td {border:0;}
    td.column100.column2.colm-new02.fa-icon {text-align: center;}
    td.border-left-0 {padding: 0px 5px !important;}
    .table100.ver2 th {color: #fff;}
    .border-wrap { border-bottom:1px solid #ccc; }
    @media screen and (max-width: 1500px) {
        /*.bttons-view-right .btn { display: block;
                                  width: 100%;
                                  margin-bottom: 5px; }*/

    }
    @media screen and (max-width: 767px) {
        #page-wrapper { margin: 0px; }

    }


</style>


<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm-equipment.js');

$userRoleID = Zend_Auth::getInstance()->getStorage()->read()->role_id;
$userId = Zend_Auth::getInstance()->getStorage()->read()->uid;
$customeAccessmodelll = new Model_UserAccess();
$actionnHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('Access');
$accarray =array(2,3,4,6);
$WorkOrders = true;
if(in_array($userRoleID, $accarray)){
    $WorkOrdersss =  $actionnHelper->checkAccess($userRoleID, 30);
    $customeAccessmodeld = $customeAccessmodelll->getUserCustomAccess($userId, 30);
    if ($customeAccessmodeld[0]) {
        $WorkOrdersss = $customeAccessmodeld[0];
    }
    if($WorkOrdersss->is_write == 0){
        $WorkOrders = false;
    }
}

/*echo '<pre>';
print_r($this->equipmentList);
die('ddd');*/
$reportModel = new Model_Report();
$reportDetailLinks = '';

function buildTree(array $elements, $parentId = 0) {
    $branch = array();
    foreach ($elements as $element) {
        if ($element['Parent_ID'] == $parentId) {
            $children = buildTree($elements, $element['AU_Template_Task_ID']);
            if ($children) {
                $element['children'] = $children;
            }
            $branch[] = $element;
        }
    }
    return $branch;
}

$equipment = new Model_PmTemplate();
$moduleMapper = new Model_UserBuildingModule();
$moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 3);
$buildhasAccess = array();
if ($moduleAccess) {
    foreach ($moduleAccess as $moduleAccessVal) {
        $buildhasAccess[] = $moduleAccessVal->module_id;
    }
}

$dashboard_menu = array(41);
if (in_array(3, $buildhasAccess)) {
    
    $reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);            
} else {
    $reportDetailLinks = false;
}

$dashboard_menu = array(42);
if (in_array(3, $buildhasAccess)) {
    
    $equipmentNameLinks = $reportModel->getReport($this->custID, $dashboard_menu);            
} else {
    $equipmentNameLinks = false;
}

$dashboard_menu = array(43);
if (in_array(3, $buildhasAccess)) {
    
    $floorUnitLinks = $reportModel->getReport($this->custID, $dashboard_menu);            
} else {
    $floorUnitLinks = false;
}

$result = array();
foreach ($this->equipmentList as $element) {
    $result[$element['equipmentnameid']][] = $element;
}
foreach($result as $wholeequipmentnameid){
    $wholeequipmentnameids .= $wholeequipmentnameid[0]['equipmentnameid'];
    $wholeequipmentnameids .= ',';    
    foreach($wholeequipmentnameid as $floorUnit){                
        $floors .= $floorUnit['Floor'];
        $floors .= ',';
        $units .= $floorUnit['Unit'];
        $units .= ',';        
    }   
}
// For short Text
function shorter($text, $chars_limit)
{
    // Check if length is larger than the character limit
    if (strlen($text) > $chars_limit)
    {
        // If so, cut the string at the character limit
        $new_text = substr($text, 0, $chars_limit);
        // Trim off white space
        $new_text = trim($new_text);
        // Add at end of text ...
        return $new_text . "...";
    }
    // If not just return the text as is
    else
    {
    return $text;
    }
}

function unique_multidim_array($array, $key) {
                                    $temp_array = array();
                                    $i = 0;
                                    $key_array = array();

                                    foreach ($array as $val) {
                                        if (!in_array($val[$key], $key_array)) {
                                            $key_array[$i] = $val[$key];
                                            $temp_array[$i] = $val;
                                        }
                                        $i++;
                                    }
                                    return $temp_array;
                                }

                                $equipmentName = unique_multidim_array($this->equipmentList, 'AU_Equipment_Name');

?>
<div class="fdw" id="access-matrix">
    <ol id="toc">

        <?php
        $j = 1;
        //print_r($this->companyListing);
        //die;

        foreach ($this->companyListing as $cb) {
            if ($cb['build_id'] == $this->select_build_id) {
                    $uniqueCostCenter = $cb['uniqueCostCenter'];
                }
            ?>
            <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/pm/equipment/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>
                <?php /*
                if ($reportDetailLinks != '') {
                    if ($cb['build_id'] == $this->select_build_id) {
                        $uniqueCostCenter = $cb['uniqueCostCenter'];
                        $batchDetails = $woBatch->showBatch($cb['build_id']);
                        $batch_number_report = '';
                        if ($batchDetails != '') {
                            foreach ($batchDetails as $bd) {
                                $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
                            }
                        }
                        $order = 'woId';
                        $dir = 'DESC';
                        $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                        $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                        if ($wolist != '') {
                            foreach ($wolist as $woNumber) {
                                $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
                            }
                        }
                        if ($invoicelist != '') {
                            foreach ($invoicelist as $invoiceNumber) {
                                $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
                            }
                        }
                    }
                }*/
                ?> 
            </li>

        <?php } ?>

    </ol>


    <!-- Report Link -->
        <?php if ($reportDetailLinks != '') { ?> <div class="tabmenu" ><ul style="padding:0px;list-style: none;"><?php
            foreach ($reportDetailLinks as $reportvalue) {
                if ($reportvalue->Report_Type == 'Flash') {
                    $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
                } else {
                    $report_type = 'vnsreports/index.php?';
                }
                $reportOption = explode(',', $reportvalue->report_option);
                ?> <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php
                if (in_array('[[++user_id]]', $reportOption)) {
                    echo '&User=' . $this->userId;
                }
                ?><?php
                        if ((in_array('[[++CostCenterNumber]]', $reportOption)) && $uniqueCostCenter != '') {
                            echo '&Cost_Center_Number=' . $uniqueCostCenter;
                        }
                        ?><?php
                        if ((in_array('[[++KeyBuildingNumber]]', $reportOption)) && $this->select_build_id != '') {
                            echo '&buildkey=' . $this->select_build_id;
                        }
                        ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>

    <?php if (in_array(3, $buildhasAccess)) { ?>
        <div class="pull-right pm-work-order-option"><!--<a href="#" class="btn btn-csttm btn-success">PM Work Order Options</a>-->
            <a class="modalbox create_conf " id="addequp" onclick="javascript:pmSetupAndOption('<?php echo $this->baseUrl() . '/pm/pmsetupoptions/buiild_id/' . $this->select_build_id; ?>');" href="#CreateNewMultiCon"> 
                <button class="confirm">PM Work Order Options</button>
            </a></div>
        <div class="clearfix"></div>
        <section>
        <?php if($WorkOrders){ ?>
            <a class="modalbox create_conf " id="add_equp" onclick="javascript:addequipment('<?php echo $this->baseUrl() . '/pm/addequipment'; ?>');" href="#CreateNewMultiCon"> 
                <button class="confirm"  >Add Equipment</button>
            </a>
            <a class="modalbox create_conf " id="add_multipleequp" onclick="javascript:addequipment('<?php echo $this->baseUrl() . '/pm/addmultipleequipment'; ?>');" href="#CreateNewMultiCon"> 
                <button class="confirm">Add Multiple Equipment of same type</button>
            </a>

            <?php
            if ($this->nooftask > 0 || $this->noofreading > 0) {
                ?>
                <a class="modalbox create_conf pull-right modified_btn" id="add_equp" href="<?php echo $this->baseUrl() . '/pm/modifiedequipmentlist'; ?>"> 
                    <button class="confirm">Modified Equipment List</button>
                </a>
                <?php
            }}
            ?>            

        </section>

        <!-- Main part of Equipment List start --> 
        <div class="eqpment-box">
            <div class="row search-box-main-row">
                <div class="col-sm-12 col-xs-12 col-md-12 col-lg-8 controls bttons-view-right">
                    <form method="post" name="fsearh" id="fsearch" action="">
                        <table>
                            <tbody>
                                <tr>
                                    <td class="showing-drop-wrap" >
                                        <lable class="ser_sp">Show</lable>
                            <select id="show_limit" onchange="showlimit();" name="show_limit" style="width:100px !important;" >
                                <option value="5" <?php echo ($this->show == 5 ? "selected" : ""); ?> >5</option>
                                <option value="10" <?php echo ($this->show == 10 ? "selected" : ""); ?> >10</option>                                
                                <option value="25" <?php echo ($this->show == 25 ? "selected" : ""); ?>>25</option>
                                <option value="50" <?php echo ($this->show == 50 ? "selected" : ""); ?>>50</option>
                                <option value="100" <?php echo ($this->show == 100 ? "selected" : ""); ?>>100</option>
                                <!--<option value="all" <?php //echo ($this->show == 1000 ? "selected" : "");    ?>>All</option>-->
                            </select>
                                    </td>
                                    <td class="serch-text-style">
                                        <p>Search For</p>
                                    </td>
                                    <td class="common-wrap">
                                        <!--<input type="text" placeholder="Equipment Name" list="browsers" name="eqname" id="eqname" class="form-control input-csttm input-csttm-padd-0" />
                                        <datalist id="browsers">

                                        <?php //foreach ($this->AllEquipment as $equip):  ?>
                                                <option  id="<?php //echo $equip->AU_Equipment_Name_ID;    ?>" value="<?php //echo $equip->AU_Equipment_Name;    ?>">
                                        <?php //endforeach;  ?>
                                        </datalist>-->
                                        <select class="form-control input-csttm input-csttm-padd-0" name="eqname" id="eqname" onchange="searchfor();">
                                            <?php $getEquipmentNameList1 = $this->getEquipmentNameList;
											foreach ($getEquipmentNameList1 as $equip): ?>
                                                <option  id="<?php echo $equip['equipmentnameid']; ?>" <?php echo (isset($_COOKIE['eqname']) && $_COOKIE['eqname']==$equip['AU_Equipment_Name'])?"selected=selected":'';?> value="<?php echo $equip['AU_Equipment_Name']; ?>"><?php echo $equip['AU_Equipment_Name']; ?></option>
                                            <?php endforeach; ?>


                                        </select>
                                    </td>
                                    <td class="common-wrap" >
                                        <input type="text" name="eqparts" list="typehintvalue" id="eqparts" class="form-control input-csttm input-csttm-padd-0" autocomplete="off"  />
                                        <datalist id="typehintvalue"></datalist>
                                    </td>
                                    <td class="common-btn" >       
                                        <a id="btn-login"  href="<?php echo $this->baseUrl() . '/pm/resetfilter'; ?>" class="btn btn-csttm btn-success">Reset</a>
                                        <!--<input class="btn btn-csttm btn-success" type="button" onclick="resetForm()" value="Reset">-->
                                        <!--<a id="btn-fblogin" href="#" class="btn btn-csttm btn-success">Search</a>-->
                                        <input type="button" class="btn btn-csttm btn-success" onclick="searchData();" value="Search" /> 
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="col-sm-12 col-sm-12 col-md-12 col-lg-4 controls bttons-view-right">
                    <a id="" href="<?php echo $this->baseUrl() . '/pm/equipment'; ?>" class="btn btn-csttm btn-success">Reset View</a>
                    <a id="" href="#" onclick="expandAll();" class="btn btn-csttm btn-success">Expand All</a>
                    <a id="" href="#" onclick="collapseall();" class="btn btn-csttm btn-success">Collapse All</a>
                </div>
            </div>
            <div class="row">
                <div class="table100 border-wrap ver2 m-b-110">
                    <div class="heading-main-equipmnt">Equipment List</div>
                    <div class="heading-sub-equipmnt">Equipment Name<span><a href="#" id="sortingid" onclick="sortingequipmentname();"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvalue" id="sortingvalue"></a></span></div>
                    <div id="sortequipmentname">
                        <div class="table-responsive">
                        <table data-vertable="ver2" id="example" class="table-bordered">
                            <tbody>
                                <?php                               

                                foreach ($equipmentName as $val) {
                                    ?>

                                    <tr class="row100 heading-tr right-x">
                                        <td  colspan="7" class="column100 column1 border-right-0" data-column=""><a href="#" id="<?php echo $val['AU_Equipment_Name']; ?>" onclick="expandEquipmentDeail(this.id);" ><?php echo $val['AU_Equipment_Name']; ?></a>
                                            <span class="td-span">
                                                <?php
            foreach ($equipmentNameLinks as $reportvalue) {
                $reportOptions = explode(',', $reportvalue->report_option);
                if ($reportvalue->Report_Type == 'Flash') {

                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }

                    if ((in_array('[[++AU_Equipment_Name_ID]]', $reportOptions)) && $val['AU_Equipment_Name_ID'] != '') {
                        $key = array_search('[[++AU_Equipment_Name_ID]]', $reportOptions);
                        $auEquipmentNameID = str_replace('[[++AU_Equipment_Name_ID]]', $val['equipmentnameid'], $reportOptions[$key]);
                    }

                    $print_url = $this->baseUrl() . '/reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&userID=' . $userID. '&AU_Equipment_Name_ID='.$auEquipmentNameID;
                } else {


                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }
                    
                    if ((in_array('[[++AU_Equipment_Name_ID]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++AU_Equipment_Name_ID]]', $reportOptions);
                        $auEquipmentNameID = str_replace('[[++AU_Equipment_Name_ID]]', $val['equipmentnameid'], $reportOptions[$key]);
                    }                   

                        $print_url = $this->baseUrl() . '/vnsreports/index.php?report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&User=' . $userID . '&AU_Equipment_Name_ID='.$auEquipmentNameID;
                    
                }
            }
            ?>
                                                
                                                <a <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo $print_url ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/printer.png" style="width:18px;"></a>
                                                <?php if($WorkOrders){ ?>
                                                <a  onclick="javascript:addequipment('<?php echo $this->baseUrl() . '/pm/updateequipmentname/equipment_id/' . $val['equipmentnameid']; ?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png" ></a> <?php } ?> </span>
                                        </td>

                                    </tr>

                                    <tr class="collapseall" id="eqid<?php echo $val['AU_Equipment_Name']; ?>"><td id="mno<?php echo $val['equipmentnameid']; ?>"><table><tr class="row100">
                                                    <th   colspan="2"  class="column100 column1 colm-new01" data-column=""></th>
                                                    <th class="column100 column3 colm-new03-th  " data-column="">Floor <span><a href="#<?php echo $val['equipmentnameid']; ?>" id="sortingidbyfloor" onclick="sortingbyfloor('floor', '<?php echo $val['equipmentnameid']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvaluebyfloor" id="sortingvaluebyfloor"></a></span></th>
                                                    <th class="column100 column4 colm-new04 " data-column="">Unit <span><a href="#<?php echo $val['equipmentnameid']; ?>" id="sortingidbyunit" onclick="sortingbyunit('unit', '<?php echo $val['equipmentnameid']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvaluebyunit" id="sortingvaluebyunit"></a></span></th>
                                                    <th class="column100 column5 colm-new05 " data-column="">Make/ Model</th>
                                                    <th class="column100 column6 colm-new06" data-column="">Location<span><a href="#<?php echo $val['equipmentnameid']; ?>" id="sortingidbylocation" onclick="sortingbylocation('location', '<?php echo $val['equipmentnameid']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvaluebylocation" id="sortingvaluebylocation"></a></span></th>
                                                    <th class="column100 column7 colm-new07" data-column="">Template</th>
                                                    <th class="column100 column8 " data-column=""></th>
                                                </tr>
                                                <?php
                                                $total = count($this->equipmentList);
                                                foreach ($this->equipmentList as $vals) {
                                                    $total -= 1;
                                                    ?>
                                                    <?php if ($val['AU_Equipment_Name'] === $vals['AU_Equipment_Name']) {
                                                        ?>
                                                        <tr><td colspan="8"><table><tr class="row100 <?php
                                                                    if ($total == 0) {
                                                                        echo 'right-x';
                                                                    }
                                                                    ?>">
                                                                        <td class="column100 column1 colm-new01" data-column=""></td>
                                                                        <td class="column100 column2 colm-new02 fa-icon" data-column=""><a href="#<?php echo $vals['AU_Equipment_Detail_ID']; ?>" class="show_hide" onclick="plusminus(this.id);" id="plus<?php echo $vals['AU_Equipment_Detail_ID']; ?>"><i class="fa fa fa-plus-circle" aria-hidden="true"></i></a></td>
                                                                        <td class="column100 column3 colm-new03" data-column=""><?php echo $vals['Floor']; ?></td>
                                                                        <td class="column100 column4 colm-new04" data-column=""><?php echo $vals['Unit']; ?></td>
                                                                        <td class="column100 column5 colm-new05" data-column=""><?php echo shorter($vals['Make Model'], 15); ?></td>
                                                                        <td class="column100 column6 colm-new06" data-column=""><?php echo $vals['Location']; ?></td>
                                                                        <td class="column100 column7 colm-new07" data-column=""><?php echo $vals['Template']; ?></td>
                                                                        <td class="column100 column8 colm-new08 fa-icon text-center" data-column="">
                                                                            <span class="td-inner-span">
                                                                                <?php
            foreach ($floorUnitLinks as $reportvalue) {
                $reportOptions = explode(',', $reportvalue->report_option);
                if ($reportvalue->Report_Type == 'Flash') {

                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }

                    if ((in_array('[[++AU_Equipment_Detail_ID]]', $reportOptions)) && $val['AU_Equipment_Detail_ID'] != '') {
                        $key = array_search('[[++AU_Equipment_Detail_ID]]', $reportOptions);
                        $auEquipmentDetailID = str_replace('[[++AU_Equipment_Detail_ID]]', $vals['AU_Equipment_Detail_ID'], $reportOptions[$key]);
                    }

                    $print_url = $this->baseUrl() . '/reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&userID=' . $userID. '&AU_Equipment_Detail_ID='.$auEquipmentDetailID;
                } else {


                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }
                    
                    if ((in_array('[[++AU_Equipment_Detail_ID]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++AU_Equipment_Detail_ID]]', $reportOptions);
                        $auEquipmentDetailID = str_replace('[[++AU_Equipment_Detail_ID]]', $vals['AU_Equipment_Detail_ID'], $reportOptions[$key]);
                    }                   

                        $print_url = $this->baseUrl() . '/vnsreports/index.php?report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&User=' . $userID . '&AU_Equipment_Detail_ID='.$auEquipmentDetailID;
                    
                }
            }
            ?>
                                                                                
                                                                                <a <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo $print_url ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/printer.png" style="width:18px;"></a>
                                                                            <?php if($WorkOrders){ ?>
                                                                            <a class="dyn" onclick="javascript:addequipment('<?php echo $this->baseUrl() . '/pm/editequipment/eqp_detail_id/' . $vals['AU_Equipment_Detail_ID']; ?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png" ></a> <?php } ?>
                                                                            </span>
                                                                        </td>
                                                                    </tr>

                                                                    <tr class="slidingDiv" id="xyzplus<?php echo $vals['AU_Equipment_Detail_ID']; ?>">
                                                                        <td colspan="8">
                                                                            <table>
                                                                                <tr class="row100">
                                                                                    <td class="column100 column1 equp-sub-box" data-column="">&nbsp;</td>
                                                                                    <td colspan="7" class="column100 column2" data-column="">
                                                                                        <a href="<?php echo $this->baseUrl() . '/pm/createequipmentdetailtask/eqp_detail_id/' . $vals['AU_Equipment_Detail_ID'] . '/eqp_name/' . $val['AU_Equipment_Name'] . '/temp/' . $vals['Template']; ?>"><?php echo $val['AU_Equipment_Name']; ?> - Type Designation - <?php echo $vals['Template']; ?> | Note - <?php echo $vals['Notes']; ?></a>
                                                                                    </td>
                                                                                   <!-- <td class="column100 column1" data-column="">&nbsp;</td>-->
                                                                                </tr>
                                                                                <tr class="row100 right-x">
                                                                                    <?php
                                                                                    $multipleManualPDF = $equipment->getEquipmentManualById($vals['AU_Equipment_Detail_ID']);
                                                                                    
                                                                                    ?>
                                                                                    <td class="column100 column1 multipdf-list" data-column="">
                                                                                        <ul>
                                                                                            <?php
                                                                                            if($vals['Equipment_Manual']!=''){
                                                                                                ?>
                                                                                            <li><i class="fa fa-file-pdf-o pdf-icon-color" aria-hidden="true"></i> <a target='_blank' href="<?php echo $this->baseUrl() . '/public/pm/' . $vals['Equipment_Manual']; ?>"><?php echo shorter($vals['Equipment_Manual'], 18); ?></a></li>
                                                                                            <?php
                                                                                                
                                                                                            }
                                                                                            ?>
                                                                                           
                                                                                            
                                                                                            <?php foreach($multipleManualPDF as $pdf){
                                                                                            ?>
                                                                                            <li><i class="fa fa-file-pdf-o pdf-icon-color" aria-hidden="true"></i> <a target="_blank" href="<?php echo $this->baseUrl() . '/public/pm/' . $pdf->Equipment_Manual; ?>"><?php echo shorter($pdf->Equipment_Manual, 18); ?></a></li>
                                                                                            <?php                                                                                            
                                                                                        }
                                                                                        ?>
                                                                                        </ul>
                                                                                            
                                                                                    </td>
                                                                                    <td colspan="6" class="column100 column2 padd-0" data-column="">
                                                                                        <table class="background-collr" width="100%" border="0">
                                                                                            <tbody>
                                                                                                <tr  class="row100">
                                                                                                    <th>Task - Order </th>
                                                                                                    <th>  Task Instruction </th>
                                                                                                    <th>Frequency</th>
                                                                                                    <th> Next Start Date </th>
                                                                                                    <th>Start Day of Month</th>
                                                                                                    <th>Start Date Adjustment</th>
                                                                                                    <th class="border-right-0">Assigned to</th>
                                                                                                    <th></th>
                                                                                                    <th></th>
                                                                                                </tr>

                                                                                                <?php
                                                                                                if (!empty($vals['AU_Equipment_Detail_ID'])) {
                                                                                                    $equipmentDetailId = $vals['AU_Equipment_Detail_ID'];
                                                                                                    $results = $equipment->getTemplateTask($equipmentDetailId);
                                                                                                    if (count($results) > 0) {
                                                                                                        $tree = buildTree($results);
                                                                                                        /**
                                                                                                         * This is for sorting purpose
                                                                                                         */
                                                                                                        $mainArray = array();
                                                                                                        $mergeArray = array();
                                                                                                        foreach ($tree as $treeval) {
                                                                                                            if ((empty($treeval['AU_Frequency_ID']) && (sizeof($treeval['children']) == 0))) {
                                                                                                                $mergeArray[] = $treeval;
                                                                                                            } else {
                                                                                                                $mainArray[] = $treeval;
                                                                                                            }
                                                                                                        }
                                                                                                        $finalArray = array_merge($mainArray, $mergeArray);
                                                                                                        $tree = $finalArray;
                                                                                                    } else {
                                                                                                        $tree = array();
                                                                                                    }
                                                                                                }

                                                                                                for ($i = 1; $i <= count($tree); $i++) {
                                                                                                    if (array_key_exists("children", $tree[$i - 1]) || $tree[$i - 1]['AU_Frequency_ID'] == '') {
                                                                                                        ?>
                                                                                                        <tr class="row100 sub-bg-bckgrnd">
                                                                                                            <td class="border-left-0 fa-icon"><?php echo $i; ?> <i class="fa fa fa-minus-circle pull-right" aria-hidden="true"></i></td>
                                                                                                            <td><?php echo $tree[$i - 1]['Task_Instruction'] ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['Frequency_name'] ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['Start_date'] ?></td>
                                                                                                            <td><?php
                                                                                if (empty($tree[$i - 1]['eqp_Startdate_month'])) {
                                                                                    $startDateMonth = $tree[$i - 1]['Startdate_month'];
                                                                                } else {
                                                                                    $startDateMonth = $tree[$i - 1]['eqp_Startdate_month'];
                                                                                }

                                                                                echo $startDateMonth;
                                                                                                        ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['startdateadj_name'] ?></td>
                                                                                                            <td class="border-right-0" colspan="2"><?php echo $tree[$i - 1]['group_name'] ?></td>
                                                                                                        </tr>
                                                                                                        <?php
                                                                                                        for ($k = 1; $k <= count($tree[$i - 1]['children']); $k++) {
                                                                                                            ?>
                                                                                                            <tr class="row100 sub-bg-bckgrnd-light">
                                                                                                                <td class="border-left-0">
                                                                                                                    <table class="background-collr" width="100%" border="0">
                                                                                                                        <tbody>
                                                                                                                            <tr class="row100 border-none">
                                                                                                                                <td class="border-corner">&nbsp;</td>
                                                                                                                                <td class="border-corner-1"><?php echo $k; ?></td>
                                                                                                                            </tr>
                                                                                                                        </tbody>
                                                                                                                    </table
                                                                                                                </td>
                                                                                                                <td><?php echo $tree[$i - 1]['children'][$k - 1]['Task_Instruction']; ?></td>
                                                                                                                <td><?php echo $tree[$i - 1]['children'][$k - 1]['Frequency_name']; ?></td>
                                                                                                                <td><?php echo $tree[$i - 1]['children'][$k - 1]['Start_date']; ?></td>
                                                                                                                <td><?php
                                                                                if (empty($tree[$i - 1]['children'][$k - 1]['eqp_Startdate_month'])) {
                                                                                    $startDateMonth = $tree[$i - 1]['children'][$k - 1]['Startdate_month'];
                                                                                } else {
                                                                                    $startDateMonth = $tree[$i - 1]['children'][$k - 1]['eqp_Startdate_month'];
                                                                                }
                                                                                echo $startDateMonth;
                                                                                                            ?></td>
                                                                                                                <td><?php echo $tree[$i - 1]['children'][$k - 1]['startdateadj_name']; ?></td>
                                                                                                                <td class="border-right-0" colspan="2"><?php echo $tree[$i - 1]['children'][$k - 1]['group_name']; ?></td>
                                                                                                            </tr>
                                                                                                            <?php
                                                                                                        }
                                                                                                        ?>

                                                                                                        <?php
                                                                                                    } else {
                                                                                                        ?>
                                                                                                        <tr class="row100 right-x">
                                                                                                            <td class="border-left-0 "><?php echo $i; ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['Task_Instruction']; ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['Frequency_name']; ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['Start_date']; ?></td>
                                                                                                            <td><?php
                                                                                if (empty($tree[$i - 1]['eqp_Startdate_month'])) {
                                                                                    $startDateMonth = $tree[$i - 1]['Startdate_month'];
                                                                                } else {
                                                                                    $startDateMonth = $tree[$i - 1]['eqp_Startdate_month'];
                                                                                }
                                                                                echo $startDateMonth;
                                                                                                        ?></td>
                                                                                                            <td><?php echo $tree[$i - 1]['startdateadj_name']; ?></td>
                                                                                                            <td class="border-right-0" colspan="2"><?php echo $tree[$i - 1]['group_name']; ?></td>
                                                                                                            <td><a onclick="javascript:openpopup('<?php echo $this->baseUrl(); ?>/pm/editequipmentdetailtask/eqp_detail_id/<?php echo $vals['AU_Equipment_Detail_ID']; ?>/subset_id/<?php echo $tree[$i - 1]['AU_Template_Task_ID']; ?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png"></a></td>
                                                                                                        </tr>
                                                                                                        <?php
                                                                                                    }
                                                                                                }
                                                                                                ?>

                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                    <!--<td class="column100 column1" data-column="">&nbsp;</td>-->
                                                                                </tr> 
                                                                            </table>
                                                                        </td>
                                                                    </tr></table></td></tr>
                                                        <?php
                                                    }
                                                }
                                                ?></table></td></tr>
                                                            <?php
                                            }
                                            ?>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
            <?php 
if (isset($this->equipmentList) && !empty($this->equipmentList)) {
    echo $this->paginationControl($this->equipmentList, 'Sliding', 'pagination.phtml');
}
?> 
        </div>
        <?php
    } else {
        echo '<div class="clearfix"> </div>';
        echo 'This Building does not have the access of this module.';
    }
    ?>

    <!-- Main part of Equipemtn List End -->
</div>

<div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>">
    <script>
        function showlimit() {        
        var limit = $("#show_limit").val();
        window.location = baseUrl + 'pm/equipment/show/' + limit;
    }
    setTimeout(function () {
        var eqparts = '<?php echo (isset($_COOKIE['eqparts']) && !empty($_COOKIE['eqparts']))?$_COOKIE['eqparts']:'';?>';
        $('#eqparts').val(eqparts);
    }, 600);
    </script>



