
<div class="container-right">
    <div class="message">               
            <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Import Template data </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 200px">
                    <div>                        
                        <div>
                            <label>List Of Template Designation :</label> 
                            <span class="ugroupErr" id="location-error"></span>                            
                            <select name="designation" id="designation">
                                <?php foreach($this->designation as $desing){
                                    echo '<option value="'.$desing->AU_Template_Designation_ID.'">'.$desing->AU_TypeDesignation.'</option>';
                                } ?>
                            </select>                            
                        </div>
                        <span class="ugroupErr" id="error_noofday"></span>
                        <div class="confirmBtn float_none">
                            <input type="button" value="Import" name="save" class="confirm" id='emailsave' onclick="importequipmenttemplateApply(<?php echo $this->desig_id ?>);">
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="cancelsubsetpopup();">                            
                            <input type="hidden" value="" id="total">
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>