<?php
$task = $this->taskdata;
$reading = $this->readingdata;
//echo '<pre>';
//print_r($task);
?>

                            <div class="task-reading-butttn">
                                <?php if(!empty($task) && !empty($reading)){ ?>
                                    <button class="confirm active" id="task-btn-change" onclick="view_task_section_change();"> Task </button>
                                    <button class="confirm" id="reading-btn-change" onclick="view_reading_section_change();"> Reading </button>
                                <?php } else if(!empty($task)){ ?>
                                    <button class="confirm active" id="task-btn-change" onclick="view_task_section_change();"> Task </button>
                                    <?php
                                }else if(!empty($reading)){
                                    ?>
                                    <button class="confirm" id="reading-btn-change" onclick="view_reading_section_change();"> Reading </button>
                                    <?php                                    
                                }else{
                                    echo '<div style="text-align: center;">Data are not available!</div>';
                                }
                                ?>
                            </div>
                    <?php if(!empty($task)): ?>
                            <div class="details-view scroll-y" id="task-content-change">
                                <table border="1" style="border:1px solid #ccc;">
                                    <tr class="heading-text">
                                        <td>Task Order</td>
                                        <td class="td-left-text">Task Instruction</td>                                
                                        <td class="td-left-text">Start Date
                                            <a onclick="javascript:openpopup('<?php echo $this->baseUrl(); ?>/pm/equipmenttaskstartdateroot/desig_id/<?php echo $this->desig_id; ?>');" href="#CreateNewMultiCon">
                                                <span class="glyphicon glyphicon-chevron-down"></span>
                                            </a>
                                        </td>                                
                                        <td class="td-left-text">Assignto
                                            <a onclick="javascript:openpopup('<?php echo $this->baseUrl(); ?>/pm/equipmenttaskassigntoroot/desig_id/<?php echo $this->desig_id; ?>');" href="#CreateNewMultiCon">
                                                <span class="glyphicon glyphicon-chevron-down"></span>
                                            </a>
                                        </td>                                
                                    </tr>
                                   <?php 
                                   $i=1;
                                   foreach($task as $data):
                                     if(!empty($data['task'])){
                                           echo '<tr class="subset">
                                                    <td>'.$i.'<i class="fa fa-minus-circle fa-minus-circle-custm" aria-hidden="true"></i></td>
                                                    <td class="td-left-text">'.substr($data['name'],0,50).'</td>
                                                    <td class="td-left-text"> startdate
                                                        <a onclick="javascript:openpopup(\''.$this->baseUrl().'/pm/equipmenttaskstartdatesubset/desig_id/'.$this->desig_id.'/subset_id/'.$data['id'].'\');" href="#CreateNewMultiCon">
                                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                                        </a>
                                                    </td>
                                                    <td class="td-left-text">Assignto
                                                        <a onclick="javascript:openpopup(\''.$this->baseUrl().'/pm/equipmenttaskassigntosubset/desig_id/'.$this->desig_id.'/subset_id/'.$data['id'].'\');" href="#CreateNewMultiCon">
                                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                                        </a>
                                                    </td>
                                                </tr>';
                                                    $j=1;
                                                foreach($data['task'] as $data2):
                                                    if(!empty($data2->Start_Date)){
                                                        $equDate = $data2->Start_Date;                                                        
                                                    }else{
                                                        $equDate = $data2->Start_date;
                                                        
                                                    }
                                                    //print_r($data2);
                                                    echo    '<tr>';    
                                                    echo    '<td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td></td>
                                                                       <td class="color-text-blue border-bottom-cusstm border-left-cusstm">'.$j.'</td>  
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                            <td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td class="td-left-text color-text-blue border-bottom-cusstm ">'.substr($data2->Task_Instruction,0,50).'</td>
                                                                    </tr>                                                
                                                                </table>
                                                            </td>
                                                            <td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td class="td-left-text color-text-blue border-bottom-cusstm ">'.$equDate.'</td>
                                                                    </tr>                                                
                                                                </table>
                                                            </td>
                                                            <td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td class="td-left-text color-text-blue border-bottom-cusstm ">'.substr($data2->group_name,0,50).'</td>
                                                                    </tr>                                                
                                                                </table>
                                                            </td>
                                                            ';
                                                        $j++;
                                                    echo   '</tr>';       
                                                endforeach;      
                                     }else if(array_key_exists('task', $data)) {
                                         //print_r($data);
                                          echo '<tr class="subset">
                                                    <td>'.$i.'<i class="fa fa-minus-circle fa-minus-circle-custm" aria-hidden="true"></i></td>
                                                    <td class="td-left-text">'.substr($data['name'],0,50).'</td>
                                                    <td class="td-left-text"></td>
                                                    <td class="td-left-text"></td>
                                                </tr>';
                                     } else{
                                            foreach($data as $data1):
                                                if(!empty($data1->Start_Date)){
                                                        $equDate = $data1->Start_Date;                                                        
                                                    }else{
                                                        $equDate = $data1->Start_date;
                                                        
                                                    }
                                          echo  '<tr>
                                                    <td>'.$i.'</td>
                                                    <td class="td-left-text">'.substr($data1->Task_Instruction,0,50).'</td>
                                                    <td class="td-left-text">'.$equDate.'</td>
                                                    <td class="td-left-text">'.substr($data1->group_name,0,50).'</td>
                                                </tr>';
                                             endforeach;
                                     }
                                    $i++;
                                    endforeach; ?>
                                </table>
                            </div>
                <?php endif; ?>

                <?php if(!empty($reading)): ?>
<div class="details-view scroll-y" id="reading-content-change" style="display:none;">
                                <table border="1" style="border:1px solid #ccc;">
                                    <tr class="heading-text">
                                        <td>Reading Order</td>
                                        <td class="td-left-text">Reading Instruction</td>                                
                                         <td class="td-left-text">Start Date
                                            <a onclick="javascript:openpopup('<?php echo $this->baseUrl(); ?>/pm/equipmentreadingstartdateroot/desig_id/<?php echo $this->desig_id; ?>');" href="#CreateNewMultiCon">
                                                <span class="glyphicon glyphicon-chevron-down"></span>
                                            </a>
                                        </td>                                
                                        <td class="td-left-text">Assignto
                                            <a onclick="javascript:openpopup('<?php echo $this->baseUrl(); ?>/pm/equipmentreadingassigntoroot/desig_id/<?php echo $this->desig_id; ?>');" href="#CreateNewMultiCon">
                                                <span class="glyphicon glyphicon-chevron-down"></span>
                                            </a>
                                        </td>                                
                                    </tr>
                                   <?php 
                                   $i=1;
                                   foreach($reading as $data):
                                      //print_r($data); 
                                     if(!empty($data['task'])){
                                         echo '<tr class="subset">
                                                    <td>'.$i.'<i class="fa fa-minus-circle fa-minus-circle-custm" aria-hidden="true"></i></td>
                                                    <td class="td-left-text">'.substr($data['name'],0,50).'</td>
                                                    <td class="td-left-text"> startdate
                                                        <a onclick="javascript:openpopup(\''.$this->baseUrl().'/pm/equipmentreadingstartdatesubset/desig_id/'.$this->desig_id.'/subset_id/'.$data['id'].'\');" href="#CreateNewMultiCon">
                                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                                        </a>
                                                    </td>
                                                    <td class="td-left-text">Assignto
                                                        <a onclick="javascript:openpopup(\''.$this->baseUrl().'/pm/equipmentreadingassigntosubset/desig_id/'.$this->desig_id.'/subset_id/'.$data['id'].'\');" href="#CreateNewMultiCon">
                                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                                        </a>
                                                    </td>
                                                </tr>';
                                                    $j=1;
                                                foreach($data['task'] as $data2):
                                                   if(!empty($data2->Start_Date)){
                                                        $equDate = $data2->Start_Date;                                                        
                                                    }else{
                                                        $equDate = $data2->Start_date;
                                                        
                                                    }
                                                    echo    '<tr>';    
                                                    echo    '<td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td></td>
                                                                       <td class="color-text-blue border-bottom-cusstm border-left-cusstm">'.$j.'</td>  
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                            <td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td class="td-left-text color-text-blue border-bottom-cusstm ">'.substr($data2->Reading_Instruction,0,50).'</td>
                                                                    </tr>                                                
                                                                </table>
                                                            </td>
                                                            <td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td class="td-left-text color-text-blue border-bottom-cusstm ">'.$equDate.'</td>
                                                                    </tr>                                                
                                                                </table>
                                                            </td>
                                                            <td style="padding:0px;">
                                                                <table> 
                                                                   <tr>
                                                                       <td class="td-left-text color-text-blue border-bottom-cusstm ">'.substr($data2->group_name,0,50).'</td>
                                                                    </tr>                                                
                                                                </table>
                                                            </td>';
                                                        $j++;
                                                    echo   '</tr>';       
                                                endforeach;      
                                     }else if(array_key_exists('task', $data)) {
                                         //print_r($data);
                                          echo '<tr class="subset">
                                                    <td>'.$i.'<i class="fa fa-minus-circle fa-minus-circle-custm" aria-hidden="true"></i></td>
                                                    <td class="td-left-text">'.substr($data['name'],0,50).'</td>
                                                    <td class="td-left-text"></td>
                                                    <td class="td-left-text"></td>
                                                </tr>';
                                     }else{
                                            foreach($data as $data1):
                                                if(!empty($data1->Start_Date)){
                                                        $equDate = $data1->Start_Date;                                                        
                                                    }else{
                                                        $equDate = $data1->Start_date;
                                                        
                                                    }
                                          echo  '<tr>
                                                    <td>'.$i.'</td>
                                                    <td class="td-left-text">'.substr($data1->Reading_Instruction,0,50).'</td>
                                                        <td class="td-left-text">'.$equDate.'</td>
                                                            <td class="td-left-text">'.substr($data1->group_name,0,50).'</td>
                                                </tr>';
                                             endforeach;
                                     }
                                    $i++;
                                    endforeach; ?>
                                </table>
                            </div>
                <?php endif; ?>
<style>
.left_box{
    padding-left: 12%;
    padding-top: 10%;
    padding-bottom: 10%;
}

.left_box table{
    width: 100%;
    overflow-y: scroll;
}

.left_box table tbody{
    height: 200px;
    display: inline-block;
    width: 100%;
    overflow: auto;
}

.left_box table tbody td{
    width: 100%;
}


.right_box
{
  padding-top: 10%;
  padding-bottom: 10%;  
}


.task-reading-butttn
{
    margin-top: 2%;
}

.details-view
{
    
}

.details-view table td
{
  padding:5px;
  text-align: center;
}

.details-view table th
{

  text-align: center;
}

.td-left-text
{
    text-align: left !important;
}

.details-view
{
  margin-top:0px;
  margin-bottom:40px;
}

.heading-text {
    background-color: #ccc;
    color: #000;
    font-weight: 500;
}

.sub-task-text {
    background-color: lightblue;
}

.color-text-blue {
    background-color:#F0F8FF;
}

.subset-table-td{
 padding-top: 0px !important; 
 padding-bottom: 0px !important;
}


.border-bottom-cusstm
{
    border-bottom: 1px solid #ccc;
}

.border-left-cusstm
{
    border-left: 1px solid #ccc;
}

.fa-minus-circle-custm
{
   float: right;
   padding-top: 4px;
}

.fa-pluse-circle-custm
{
   float: right;
   padding-top: 4px;
}

</style>

<script> 
    

function view_task_section_change(){
        $("#reading-content-change").hide();
        $("#task-content-change").show();
       $("#reading-btn-change").removeClass("active");
       $("#task-btn-change").addClass("active");
}

function view_reading_section_change(){
      $("#task-content-change").hide();
      $("#reading-content-change").show();
       $("#task-btn-change").removeClass("active");
       $("#reading-btn-change").addClass("active");
}

</script>