<?php
echo $this->headScript()->appendFile(BASEURL . '/public/js/pm-complete-workorder.js');

$reportModel = new Model_Report();
$reportDetailLinks = '';
$equipment = new Model_PmTemplate();
$moduleMapper = new Model_UserBuildingModule();
$moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 3);
$buildhasAccess = array();
if ($moduleAccess) {
    foreach ($moduleAccess as $moduleAccessVal) {
        $buildhasAccess[] = $moduleAccessVal->module_id;
    }
}

$dashboard_menu = array(40);
if (in_array(3, $buildhasAccess)) {
    $reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);
        
} else {
    $reportDetailLinks = false;
}


?>
<div class="fdw pmsc" id="access-matrix">
    <ol id="toc" class="pm-work-order-toc-list pm-work-coustm">
        <?php
        foreach ($this->companyListing as $cb) {
            if ($cb['build_id'] == $this->select_build_id) {
                    $uniqueCostCenter = $cb['uniqueCostCenter'];
                }
            ?>
            <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/pm/pmcompletewo/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>
                <?php
               /* if ($reportDetailLinks != '') {
                    if ($cb['build_id'] == $this->select_build_id) {
                        $uniqueCostCenter = $cb['uniqueCostCenter'];
                        $batchDetails = $woBatch->showBatch($cb['build_id']);
                        $batch_number_report = '';
                        if ($batchDetails != '') {
                            foreach ($batchDetails as $bd) {
                                $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
                            }
                        }
                        $order = 'woId';
                        $dir = 'DESC';
                        $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                        $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                        if ($wolist != '') {
                            foreach ($wolist as $woNumber) {
                                $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
                            }
                        }
                        if ($invoicelist != '') {
                            foreach ($invoicelist as $invoiceNumber) {
                                $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
                            }
                        }
                    }
                }*/
                ?> 
            </li>

        <?php } ?>
    </ol>
    <!-- Report Link -->
        <?php if ($reportDetailLinks != '') { ?> <div class="tabmenu pm-menu" ><ul style="padding:0px;list-style: none;"><?php
            foreach ($reportDetailLinks as $reportvalue) {
                if ($reportvalue->Report_Type == 'Flash') {
                    $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
                } else {
                    $report_type = 'vnsreports/index.php?';
                }
                $reportOption = explode(',', $reportvalue->report_option);
                ?> <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php
                if (in_array('[[++user_id]]', $reportOption)) {
                    echo '&User=' . $this->userId;
                }
                ?><?php
                        if ((in_array('[[++CostCenterNumber]]', $reportOption)) && $uniqueCostCenter != '') {
                            echo '&Cost_Center_Number=' . $uniqueCostCenter;
                        }
                        ?><?php
                        if ((in_array('[[++KeyBuildingNumber]]', $reportOption)) && $this->select_build_id != '') {
                            echo '&buildkey=' . $this->select_build_id;
                        }
                        ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>
    <?php if (in_array(3, $buildhasAccess)) { ?>
        <div class="pull-right pm-order-btn"><!--<a href="#" class="btn btn-csttm btn-success">PM Work Order Options</a>-->
            <a class="modalbox create_conf " id="add_equp" onclick="javascript:pmSetupAndOption('<?php echo $this->baseUrl() . '/pm/pmsetupoptions/buiild_id/' . $this->select_build_id; ?>');" href="#CreateNewMultiCon"> 
                <button class="confirm pm-work-order-option">PM Work Order Options</button>
            </a>
        </div>
        <div class="clearfix"></div> 
        <div class="pm-complete-work-order pm-sc-ps-dc">
            <div class="pm-date-modify-box">
                <div class="row">
                    <div class="complete-pm-header-box">
                        Complete PM Open Work Orders - <span class="view-point"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 no-pad">
                        <form class="form-inline" onsubmit="return false">
                            <div class="form-group pm-select-box">
                                <label for=""><strong>PM WO Number</strong></label>
                                <select class="form-control" name="pmwonumber" id="pmwonumber">
                                    <option value="">Select PM WO Number</option>
                                    <?php
                                    
                                   /* foreach ($this->pmWoNumbr as $wonum) {
                                        
                                        ?>
                                        <option value="<?php echo $wonum['WO_Number'].','.$wonum['Reading_Task']; ?>" <?php if($wonum['WO_Number']==$this->completewo && $wonum['Reading_Task']==$this->completeRadingTask){ echo 'selected=selected'; } ?> >
                                            <?php
                                            if (in_array($wonum['WO_Number'], $duplicate)) {
                                                echo $wonum['WO_Number'].'('.$wonum['Reading_Task'].')';
                                            } else {
                                                echo $wonum['WO_Number'];
                                            }
                                             ?></option>
                                        <?php
                                    }*/
                                    
                                    foreach ($this->pmWoNumbr as $wonum) {
                                        
                                        ?>
                                        <option value="<?php echo $wonum->PM_WO_Number; ?>" <?php if($this->completewo==$wonum->PM_WO_Number){ echo 'selected=selected'; }?>><?php echo $wonum->PM_WO_Number; ?></option>
                                        <?php
                                    }
                                    
                                    ?>

                                </select>
                                <!--<input type="hidden" name="pmreadingtask" id="pmreadingtask" value="<?php //echo $this->completeRadingTask; ?>" />-->
                            </div>
                            <div class="form-group double-btn-group">
                                <a id="btn-login" href="<?php echo $this->baseUrl() . '/pm/pmcompletewo'; ?>" class="btn btn-csttm btn-success">Reset</a>
                                <input type="submit" class="btn btn-csttm btn-success" id="listComplete" onclick="searchData();" value="Search" />  
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row" id="pmcompletewo">
                    
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="clearfix"></div> 
            <?php
        } else {
            echo '<div class="clearfix"> </div>';
            echo 'This Building does not have the access of this module.';
        }
        ?>
    </div>
    <div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>"></div>
</div>
<script>
    $(document).ready(function(){
        $("#listComplete").trigger("click");
    });
    
</script>
