<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm-complete-workorder.js');
?>
<div class="container-right">
    <div class="message">               
        <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Date Completed - Group Modification </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 225px">
                    <div>                        
                        <div class="form-group date-box date-wrap">
                            <label for="">Date Completed:</label>
                            <input type="text" class="form-control date-picker" id="completedDate" name="completedDate" value="" autocomplete="off" >

                        </div>
                        <span class="ugroupErr" id="error_startdate"></span>

                        <div class="confirmBtn float_none">

                            <input type="button" value="Apply" name="save" class="confirm" id='emailsave' onclick="updateCompletedDate('<?php echo $this->reading_task; ?>');">
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="closepopup();">                            

                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>"></div>