<style>
    body { background: #fff; }
    .dynamicclass { padding-bottom: 20px; overflow: hidden; }
    .heading-2 {padding: 0;margin-bottom: 15px;margin-top: 0;}   
    .heading-2 span {font-size: 14px;padding: 5px; color:#fff}    
    .form-c ul {list-style:none; padding:10px;margin:0}
    .form-c ul li { margin-bottom:10px;}
    .form-c label {float: left;}
    .form-c .form-cont {float: left;margin-left: 10px;}
    .form-c input {margin:0 10px}
    .form-c .form-cont ul li input {margin-right:10px;}
    .form-c .form-cont input {margin:0;}
    .form-c .form-cont p {margin-bottom:5px;min-height: 20px;}
    .form-c li {overflow: hidden;}
    .form-c li p {margin:0;}
    .form-c h3 { margin-top:0;}
    .form-c>ul {padding: 20px;}
    .form-c .flex-divi {display: flex;}
    .form-c .flex-divi .daily-weekly {flex:1;}
    .daily-weekly.fix-w {max-width: 115px;}
    .flex-sp {padding:0 38px}
</style>
<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm-workorder.js');
?>
<section class="ch-form-header">
    <h3 class="text-center">Manually Generate WO's </h3>         
  <div class="container">

      <form class="form-inline pd" onsubmit="return false">
          <h6 class="text-center text-danger" id="building_error"></h6>
    <div class="form-group col-sm-6">
      <label for="focusedInput">Select Date</label>
      <input type="text" class="form-control date-picker date-modal" id="wogenerateddate" name="wogenerateddate" autocomplete="off">
    </div>
    <div class="form-group col-sm-6">
        <div class="flr">
        <input type="submit" class="btn btn-success" value="Generate WO's" onclick="validate_generatewo();">
        <button class="confirm btn btn-success" onclick="closepopup();">Cancel</button>
        </div>
    </div>
   
  </form>
  <table class="table table-bordered mgt">
    <thead class="thead-bg">
      <tr>
        <th>Date Created</th>
        <th>Created By</th>
        <th>Work Orders Generated Date</th>
      </tr>
    </thead>
    <tbody>
        <?php
        if(!empty($this->manuallyGenerateWO)){
            foreach($this->manuallyGenerateWO as $mngwo){
            ?>        
                <tr>
                <td><?php echo date('F d, Y', strtotime($mngwo->dateCreated)); ?></td>
                <td><?php echo $mngwo->createdBy; ?></td>
                <td><?php echo date('F d, Y', strtotime($mngwo->woGeneratedDate)); ?></td>
                </tr>
            <?php
            }
        }
        ?>      
    </tbody>
  </table>
</div>

</section>










