<style>   
    /*//////////////////////////////////////////////////////////////////
    [ Table ]*/
    table {
        width: 100%;
        background-color: #fff;
    }

    th, td {
        font-weight: unset;
        padding-right: 10px;
    }



    /*==================================================================
    
    [ Ver2 ]*/
    .table100.ver2 td {
        font-size: 14px;
        color: #808080;
        line-height: 1.4;
    }

    .table100.ver2 th {
        font-size: 12px;
        color: #fff;
        line-height: 1.4;
        text-transform: uppercase;
        background-color: #2a6496;
    }

    .table100.ver2 .row100:hover td {

    }

    .table100.ver2 .hov-column-ver2 {

    }

    .table100.ver2 .hov-column-head-ver2 {
        background-color: #484848 !important;
    }

    .table100.ver2 .row100 td:hover {

    }

    .eqpment-box
    {
        margin-top: 30px;
        margin-bottom: 30px;	
    }

    /*==================================================================
    [ Ver2 ]*/

    .table100.ver2 td {
        color: #000;
        line-height: 1.4;

    }

    .table100.ver2 th {

        color: #000;
        line-height: 1.4;
        text-transform:none;
        background-color: #2a6496;
        border-right: 1px solid #ccc;
    }

    .table100.ver2 .row100:hover td {

    }

    .table100.ver2 .hov-column-ver2 {
        background-color: #83d160;
        color: #fff;
    }

    .table100.ver2 .hov-column-head-ver2 {
        background-color: #484848 !important;
    }

    .table100.ver2 .row100 td:hover {

    }

    .heading-main-equipmnt
    {
        background-color: #34495e;
        color: #fff;
        padding: 9px 8px;
        border-bottom: 0px solid #ccc;
    }

    .heading-sub-equipmnt
    {
        background-color: #2a6496;
        color: #fff;
        padding: 5px 3px;
    }

    .btn-csttm
    {
        border-radius:0px;
        font-style: italic;

    }


    .search-box-main-row
    {
        padding-bottom: 20px !important;
    }

    .bttons-view-right
    {
        text-align: right;
        right: 0px;
        padding-right: 0px;
    }

    .input-csttm
    {
        border-radius:0px;	
    }

    .serch-text-style
    {
        font-weight:600;
    }

    .border-left-gray
    {
        border-left: 1px solid #ccc;
    }

    .border-left-0
    {
        border-left: 0px solid #ccc;
    }


    .border-right-0
    {
        border-right:0px;
    }

    .border-bottom-0
    {
        border-bottom:0px;
    }

    .fa-icon i
    {
        font-size:16px;
        padding-right: 8px;
    }

    .row100 th {
        padding: 10px;
        text-align: center;
    }

    .background-collr
    {

    }

    .padd-0{
        padding:0px !important;
    }

    .sub-bg-bckgrnd
    {
        background-color:#92cddc;
    }

    .sub-bg-bckgrnd-light
    {
        background-color:#dbeef3;
    }

    .border-corner
    {
        border-left: 0 !important;
        border-top: 0 !important;
        border-bottom: 0 !important;
    }

    .border-corner-1
    {
        border-right: 0 !important;
        border-top: 0 !important;
        border-bottom: 0 !important;
    }

    .heading-tr
    {
        background-color: #fff !important;  
    }

    .input-csttm-padd-0
    {
        margin:0px !important; 
    }

    .heading-sub-equipmnt .arrow-shrting{

    }
    .arrow-shrting
    {
        color:#fff;
        padding-left: 10px;
    }

    .colm-new01
    {
        width:4%;  
    }

    .colm-new02
    {
        width:5%;  
    }

    .colm-new03
    {
        width:10%;  
    }

    .colm-new04
    {
        width:10%;  
    }

    .colm-new05
    {
        width:10%;  
    }

    .colm-new06
    {
        width:25%;  
    }

    .colm-new07
    {
        width:25%;  
    }

    .colm-new03-th
    {
        width: 15%;    
    }

    .table100.ver2 td {
        padding:2px 0px;
    }

    .equp-sub-box
    {
        width: 12% !important;   
    }

    .blue-bg
    {
        background-color: #92cddc !important; 
    }
    .right-x{
        border: 1px solid #ccc;;
    }
    .common-wrap input[type="text"]{
        width: 100%;
    }
    .common-wrap  select {
        width: 100%;
    }
    .common-btn { text-align: left; }
    .modified_btn button{ background: #06af8f; color:#000; font-weight: bold;  padding: 3px 10px; border-radius: 3px; box-shadow: 2px 2px 5px #ccc; 
                          border: none; font-size: 16px !important; line-height: 1;}
    a.dyn img {
        width: 18px;
    }
    @media screen and (max-width: 1500px) {
        .bttons-view-right .btn { display: block;
                                  width: 100%;
                                  margin-bottom: 5px; }

    }
    @media screen and (max-width: 767px) {
        #page-wrapper { margin: 0px; }

    }

</style>
<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm-workorder.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/emails.js');


$userRoleID = Zend_Auth::getInstance()->getStorage()->read()->role_id;
$userId = Zend_Auth::getInstance()->getStorage()->read()->uid;
$customeAccessmodelll = new Model_UserAccess();
$actionnHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('Access');
$accarray =array(2,3,4,6);
$WorkOrders = true;
if(in_array($userRoleID, $accarray)){
    $WorkOrdersss =  $actionnHelper->checkAccess($userRoleID, 27);
    $customeAccessmodeld = $customeAccessmodelll->getUserCustomAccess($userId, 27);
    if ($customeAccessmodeld[0]) {
        $WorkOrdersss = $customeAccessmodeld[0];
    }
    if($WorkOrdersss->is_write == 0){
        $WorkOrders = false;
    }
}
//echo $WorkOrders;
$reportModel = new Model_Report();
$reportDetailLinks = '';

$equipment = new Model_PmTemplate();
$moduleMapper = new Model_UserBuildingModule();
$moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 3);
$buildhasAccess = array();
if ($moduleAccess) {
    foreach ($moduleAccess as $moduleAccessVal) {
        $buildhasAccess[] = $moduleAccessVal->module_id;
    }
}


$dashboard_menu = array(38);
if (in_array(3, $buildhasAccess)) {
    $reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);
} else {
    $reportDetailLinks = false;
}

$dashboard_menu = array(39);
if (in_array(3, $buildhasAccess)) {
    $printerLinks = $reportModel->getReport($this->custID, $dashboard_menu);
} else {
    $printerLinks = false;
}

function unique_multidim_array($array, $key) {
    $temp_array = array();
    $i = 0;
    $key_array = array();

    foreach ($array as $val) {
        if (!in_array($val[$key], $key_array)) {
            $key_array[$i] = $val[$key];
            $temp_array[$i] = $val;
        }
        $i++;
    }
    return $temp_array;
}
?>
<div class="fdw" id="access-matrix">
    <ol id="toc" class="pm-work-order-toc-list">
<?php
foreach ($this->companyListing as $cb) {
    if ($cb['build_id'] == $this->select_build_id) {
        $uniqueCostCenter = $cb['uniqueCostCenter'];
    }
    ?>
            <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/pm/pmworkorder/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>
            <?php /*
              if ($reportDetailLinks != '') {
              if ($cb['build_id'] == $this->select_build_id) {
              $uniqueCostCenter = $cb['uniqueCostCenter'];
              $batchDetails = $woBatch->showBatch($cb['build_id']);
              $batch_number_report = '';
              if ($batchDetails != '') {
              foreach ($batchDetails as $bd) {
              $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
              }
              }
              $order = 'woId';
              $dir = 'DESC';
              $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
              $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
              if ($wolist != '') {
              foreach ($wolist as $woNumber) {
              $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
              }
              }
              if ($invoicelist != '') {
              foreach ($invoicelist as $invoiceNumber) {
              $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
              }
              }
              }
              } */
            ?> 
            </li>

<?php } ?>
    </ol>

    <!-- Report Link -->
<?php if ($reportDetailLinks != '') { ?> <div class="tabmenu" ><ul style="padding:0px;list-style: none;"><?php
    foreach ($reportDetailLinks as $reportvalue) {
        if ($reportvalue->Report_Type == 'Flash') {
            $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
        } else {
            $report_type = 'vnsreports/index.php?';
        }
        $reportOption = explode(',', $reportvalue->report_option);
        ?> <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php
            if (in_array('[[++user_id]]', $reportOption)) {
                echo '&User=' . $this->userId;
            }
            ?><?php
                    if ((in_array('[[++CostCenterNumber]]', $reportOption)) && $uniqueCostCenter != '') {
                        echo '&Cost_Center_Number=' . $uniqueCostCenter;
                    }
                    ?><?php
                    if ((in_array('[[++KeyBuildingNumber]]', $reportOption)) && $this->select_build_id != '') {
                        echo '&buildkey=' . $this->select_build_id;
                    }
                    ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>

        <?php if (in_array(3, $buildhasAccess)) {  ?>
        
        <div class="pull-right pm-work-order-option"><!--<a href="#" class="btn btn-csttm btn-success">PM Work Order Options</a>-->
        <?php if($this->email_group){ ?>
            <a class="modalbox create_conf " id="add_equp" onclick="javascript:editNewDisGroup('<?php echo BASEURL . 'emails/editemailgroup/gid/' . $this->email_group[0]['id'] . '/buildingId/' . $this->select_build_id; ?>');" href="#editNewDisGroup"> 
                <button class="confirm">PM Work Order Email Template</button>
            </a>
        <?php }else{?>
            <a class="modalbox" onclick="javascript:addNewDisGroup('<?php echo $this->baseUrl() . '/emails/addemailgroup/bid/' . $this->select_build_id; ?>/controllerName/PM');" href="#addNewDisGroup"> 
                      <button class="confirm">PM Work Order Email Template</button>
            </a>
        <?php } ?>
            <a class="modalbox create_conf " id="add_equp" onclick="javascript:pmSetupAndOption('<?php echo $this->baseUrl() . '/pm/pmsetupoptions/buiild_id/' . $this->select_build_id; ?>');" href="#CreateNewMultiCon"> 
                <button class="confirm">PM Work Order Options</button>
            </a>
        </div>

        <!-- Main part of Equipment List start --> 
        <div class="eqpment-box">
            <div class="row search-box-main-row">
                <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12 controls bttons-view-right">
                    <form onsubmit="return false">
                       
                        <table>
                            <tbody>
                                <tr>
                                    <td class="showing-drop-wrap" >
                                        <lable class="ser_sp">Show</lable>
                            <select id="show_limit" onchange="showlimit();" name="show_limit" style="width:100px !important;" >
                                <option value="5" <?php echo ($this->show == 5 ? "selected" : ""); ?> >5</option>
                                <option value="10" <?php echo ($this->show == 10 ? "selected" : ""); ?> >10</option>                                
                                <option value="25" <?php echo ($this->show == 25 ? "selected" : ""); ?>>25</option>
                                <option value="50" <?php echo ($this->show == 50 ? "selected" : ""); ?>>50</option>
                                <option value="100" <?php echo ($this->show == 100 ? "selected" : ""); ?>>100</option>
                                <!--<option value="all" <?php //echo ($this->show == 1000 ? "selected" : "");    ?>>All</option>-->
                            </select>
                                    </td>
                                    <td class="serch-text-style">
                                        <p>Search For</p>
                                    </td>
                                    <td class="common-wrap">
                                        <select class="form-control input-csttm input-csttm-padd-0" name="eqname" id="eqname" onchange="searchfor();">
                                            <option  id="" value="0">Select From List</option>                                        
                                            <option  id="wonumber" value="1">Work Order Number</option>
                                            <option  id="woequipment" value="2">Equipment</option>
                                            <option  id="wofloor" value="3">Floor</option>
                                            <option  id="wounit" value="4">Unit</option>
                                            <option  id="wolocation" value="5">Location</option>
                                        </select>
                                    </td>
                                    <td class="common-wrap" >
                                        <input type="text" name="eqparts" list="typehintvalue" id="eqparts" class="form-control input-csttm input-csttm-padd-0" autocomplete="off" />
                                        <datalist id="typehintvalue"></datalist>
                                    </td>
                                    <td class="common-btn" >       
                                        <a id="btn-login" href="<?php echo $this->baseUrl() . '/pm/pmworkorder'; ?>" class="btn btn-csttm btn-success">Reset</a>
                                        <!--<input class="btn btn-csttm btn-success" type="button" onclick="resetForm()" value="Reset">-->
                                        <!--<a id="btn-fblogin" href="#" class="btn btn-csttm btn-success">Search</a>-->
                                        <input type="submit" class="btn btn-csttm btn-success" onclick="searchData();" value="Search" /> 
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3 col-xs-12">
                    <a id="byequipment" type="button" class="btn btn-csttm btn-success group-btn-custom" href="<?php echo $this->baseUrl() . '/pm/pmworkorder'; ?>">By Equipment</a>
                    <a id="bywonumber" type="button" class="btn btn-csttm btn-success" href="<?php echo $this->baseUrl() . '/pm/pmworkorderbynumber'; ?>">WO Number</a>
                    
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3 col-xs-12 controls bttons-view-right">
                    <?php 
                    if($WorkOrders){
                    if(!empty($this->pmCompleteJobTime->PM_Auto_Create_Jobs) && $this->pmCompleteJobTime->PM_Auto_Create_Jobs=='N'){
                        ?>
                    <a id="xtrigManualCreateWO" class="modalbox create_conf confirm manual-popup" onclick="javascript:pmSetupAndOption('<?php echo $this->baseUrl() . '/pm/pmmanuallycreatewo/buiild_id/' . $this->select_build_id; ?>');" href="#CreateNewMultiCon"> 
                 Manually Create WO’s</a>
                    <?php                        
                    }}
                    ?>
                    
                    <a id="expandall" href="#" onclick="expandAll();" class="btn btn-csttm btn-success group-btn-custom">Expand All</a>
                    <a id=collapseall" href="#" onclick="collapseall();" class="btn btn-csttm btn-success">Collapse All</a>
                </div>
            </div>
            <div class="row" id="by_quipment">
                <div class="table100 ver2 m-b-110">
                    <div class="heading-main-equipmnt">PM Work Order List</div>
                    <div class="heading-sub-equipmnt">Listed by Equipment (A-Z)<span><a href="#" id="sortingid" onclick="sortingequipmentname();"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvalue" id="sortingvalue"></a></span></div>
                    <div class="clearfix"></div>


                    <div id="pm-work-cta" class="pm-work-tbl">
    <?php
    $equipmentName = unique_multidim_array($this->workorderList, 'AU_Equipment_Name');
    foreach ($equipmentName as $equipment) {
        ?>                  <div class="table-responsive">         
                            <table id="air_handling-unit" class="table table-bordered">
                                <tr class="colorblue"><td>&nbsp;<a href="#<?php echo $equipment['AU_Equipment_Name_ID']; ?>" class="show_hide" onclick="plusminus(this.id);" id="plus<?php echo $equipment['AU_Equipment_Name_ID']; ?>"><i class="fa fa fa-minus-circle" aria-hidden="true"></i></a>&nbsp;<?php echo $equipment['AU_Equipment_Name']; ?></td></tr>
                                <tr class="collapseall" id="xyzplus<?php echo $equipment['AU_Equipment_Name_ID']; ?>">
                                    <td class="td-bg-clr" id="mno<?php echo $equipment['AU_Equipment_Name_ID']; ?>">
                                        <div class="tble-left-gp">
                                            <table class="table table-bordered text-center">
                                                <thead>
                                                    <tr>
                                                        <th class="w_180">Floor<span><a href="#<?php echo $equipment['AU_Equipment_Name_ID']; ?>" id="sortingidbyfloor" onclick="sortingbyfloor('floor', '<?php echo $equipment['AU_Equipment_Name_ID']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="0" name="sortingvaluebyfloor" id="sortingvaluebyfloor-<?php echo $equipment['AU_Equipment_Name_ID']; ?>"></a></span></th>
                                                        <th class="w_180">Unit<span><a href="#<?php echo $equipment['AU_Equipment_Name_ID']; ?>" id="sortingidbyunit" onclick="sortingbyunit('unit', '<?php echo $equipment['AU_Equipment_Name_ID']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="0" name="sortingvaluebyunit" id="sortingvaluebyunit-<?php echo $equipment['AU_Equipment_Name_ID']; ?>"></a></span></th>
                                                        <th class="w_180">Work Order Number<span><a href="#<?php echo $equipment['AU_Equipment_Name_ID']; ?>" id="sortingidbywo" onclick="sortingbywo('wo', '<?php echo $equipment['AU_Equipment_Name_ID']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="0" name="sortingvaluebywo" id="sortingvaluebywo-<?php echo $equipment['AU_Equipment_Name_ID']; ?>"></a></span></th>
                                                        <th>Location</th>
                                                        <th class="w_130">Task or Reading</th>
                                                        <th class="w_130">Print</th>
                                                        <th class="w_130">Complete</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
        <?php
        foreach ($this->workorderList as $detail) {
            if ($detail['AU_Equipment_Name_ID'] == $equipment['AU_Equipment_Name_ID']) {
                ?>
                                                            <tr>
                                                                <td><a href="<?php echo $this->baseUrl(); ?>/pm/pmcompletewo/wo_number/<?php echo $detail['WO_Number']; ?>"><?php echo $detail['Equipment_Floor']; ?></a></td>
                                                                <td><a href="<?php echo $this->baseUrl(); ?>/pm/pmcompletewo/wo_number/<?php echo $detail['WO_Number']; ?>"><?php echo $detail['Equipment_Unit']; ?></a></td>
                                                                <td><a href="<?php echo $this->baseUrl(); ?>/pm/pmcompletewo/wo_number/<?php echo $detail['WO_Number']; ?>"><?php echo $detail['WO_Number']; ?></a></td>
                                                                <td><?php echo $detail['Equipment_Location']; ?></td>
                                                                <td>                                                      
                                                                    <a class="dyn" href="#">
                <?php
                if ($detail['Reading_Task'] == 'T') {
                    ?>
                                                                            <img src="<?php echo $this->baseUrl(); ?>/public/images/task.png">
                                                                            <?php
                                                                        } else if ($detail['Reading_Task'] == 'R') {
                                                                            ?>
                                                                            <img src="<?php echo $this->baseUrl(); ?>/public/images/reading.png">
                                                                            <?php
                                                                        }
                                                                        ?>
                                                                    </a></td>
                                                                <td><!--<a target="_blank" href="#"><img src="<?php echo $this->baseUrl(); ?>/public/images/printer.png" style="width:18px;"></a>-->
                <?php
                foreach ($printerLinks as $reportvalue) {
                    $reportOptions = explode(',', $reportvalue->report_option);
                    if ($reportvalue->Report_Type == 'Flash') {

                        if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                            $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                            $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                        }

                        if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                            $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                            $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                        }
                        if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                            $key = array_search('[[++user_id]]', $reportOptions);
                            $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                        }

                        if ((in_array('[[++PM_WO_Number]]', $reportOptions)) && $detail['WO_Number'] != '') {
                            $key = array_search('[[++PM_WO_Number]]', $reportOptions);
                            $pmWONumber = str_replace('[[++PM_WO_Number]]', $detail['WO_Number'], $reportOptions[$key]);
                        }

                        $print_url = $this->baseUrl() . '/reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&userID=' . $userID . '&PM_WO_Number=' . $pmWONumber;
                    } else {


                        if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                            $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                            $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                        }

                        if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                            $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                            $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                        }
                        if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                            $key = array_search('[[++user_id]]', $reportOptions);
                            $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                        }

                        if ((in_array('[[++PM_WO_Number]]', $reportOptions)) && $detail['WO_Number'] != '') {
                            $key = array_search('[[++PM_WO_Number]]', $reportOptions);
                            $pmWONumber = str_replace('[[++PM_WO_Number]]', $detail['WO_Number'], $reportOptions[$key]);
                        }

                        $print_url = $this->baseUrl() . '/vnsreports/index.php?report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&User=' . $userID . '&PM_WO_Number=' . $pmWONumber;
                    }
                }
                ?>
                                                                    <a <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo $print_url ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/printer.png" style="width:18px;"></a>

                                                                <td><a href="<?php echo $this->baseUrl(); ?>/pm/pmcompletewo/wo_number/<?php echo $detail['WO_Number']; ?>/reading_task/<?php echo $detail['Reading_Task']; ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/complete.png" style="width:18px;"></a></td>
                                                            </tr>
                <?php
            }
            ?>

                                                        <?php
                                                    }
                                                    ?>                                               

                                                </tbody>
                                            </table>      
                                        </div>                                            
                                    </td>
                                </tr>
                            </table>
            </div>
        <?php
    }
    ?>                                             

                        <div class="clearfix"></div>
                    </div>
                </div>
                <?php
if (isset($this->workorderList) && !empty($this->workorderList)) {
    echo $this->paginationControl($this->workorderList, 'Sliding', 'pagination.phtml');
}
?> 
            </div>

    <?php
} else {
    echo '<div class="clearfix"> </div>';
    echo 'This Building does not have the access of this module.';
}
?>
        <!-- Main part of Equipemtn List End -->
    </div>

    <div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>">
        <script>
        function showlimit() {        
        var limit = $("#show_limit").val();
        window.location = baseUrl + 'pm/pmworkorder/show/' + limit;
    }
    </script>



