<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm_reading.js');
?>
<div class="container-right">
    <div class="message">               
            <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Reading value Subset - Group Modification </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 200px">
                    <div>                        
                        <div>
                            <label>Enter New Reading Value </label> 
                            <span class="ugroupErr" id="location-error"></span>                            
                            <input type="number" onkeypress='return float_validation_three(event, this.value);' id="readingvalue" name="readingvalue" min="1">
                          
                        </div>
                        <span class="ugroupErr" id="error_startdate"></span>
                        <div class="confirmBtn float_none">
                            <input type="hidden" name="typedesination" id="parent_id" value="<?php echo $this->parent_id; ?>" >
                            <input type="button" value="Apply" name="save" class="confirm" id='emailsave' onclick="update_readingsubset_readingvalue(<?php echo $this->desig_id ?>);">
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="closepopup();">                            
                            <input type="hidden" value="" id="total">
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>