<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm_reading.js');
?>
<div class="container-right">
    <div class="message">               
            <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Frequency - Group Modification </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 200px">
                    <div>                        
<!--                        <div>
                            <label>Every</label> 
                            <span class="ugroupErr" id="location-error"></span>                            
                            <input type="number"  onkeypress='return event.charCode > 48 && event.charCode <= 57' id="noofday" name="noofday" min="1">
                            <select name="type" id="type">
                                <?php
                                //foreach ($this->CustFreq as $key=>$val){
                               //     echo '<option value="'.$key.'">'.$val.'</option>';
                               // }
                                ?>
                            </select>                            
                        </div>
                        <span class="ugroupErr" id="error_noofday"></span>
                        <div class="row">
                            <input type="checkbox" name="includesubset"  id="includesubset" value="1"> Check to include all subset
                        </div>-->
                        <div class="ch-home-form-new">
                            <div style="z-index:9999" class="w-48 fr form-inline">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label col-sm-3 col-md-3 col-xs-3">Frequency</label>
                                        <input type="radio" name="freq" id="freq" checked="checked"  onclick="check_freq()" value="1" >
                                        <select name="level" id="frequency" class="form-control"  >
                                            <?php foreach($this->Freq as $key=>$val){ ?>
                                                <option value="<?php echo $key; ?>" <?php echo ($key==3?"Selected":""); ?> ><?php echo $val; ?></option>
                                            <?php } ?>                   
                                        </select>
                                        <input type="radio" name="freq" id="freq1" onclick="check_freq()" value="2"  > Perform Task Every 
                                        <input type="number" onkeypress='return event.charCode > 48 && event.charCode <= 57' id="freq_num" max="59" style="width: 70px !important;" min="1" class="form-control" value="1">
                                        <select name="level" id="frequency1" class="form-control" onchange="return freqevent();" >
                                            <?php foreach($this->CustFreq as $key=>$val){ ?>
                                                <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
                                            <?php } ?>                   
                                        </select>
                                    </div>
                                    <div class="row">
                                        <input type="checkbox" name="includesubset"  id="includesubset" value="1"> Check to include all subset
                                    </div>
                                </div>
                            </div>
                        </div>
                        <style>
                                .ch-home-form-new .form-group .form-control {
                                    width: auto!important;
                                    display: inline-block;
                                }
                                .ch-home-form-new input[type=radio], .ch-home-form-new input[type=checkbox] {
                                                                                                                margin-top:0px;
                                                                                                            }
                        </style>
                        
                        <div class="confirmBtn float_none">
                            <input type="hidden" name="typedesination" id="typedesination_id" value="" >
                            <input type="button" value="Apply" name="save" class="confirm" id='emailsave' onclick="update_readingroot_frequency(<?php echo $this->desig_id ?>);">
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="closepopup();">                            
                            <input type="hidden" value="" id="total">
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>
        
