<?php
$reportModel = new Model_Report();
$reportDetailLinks = '';
function buildTree(array $elements, $parentId = 0) {
    $branch = array();
    foreach ($elements as $element) {
        if ($element['Parent_ID'] == $parentId) {
            $children = buildTree($elements, $element['AU_Template_Task_ID']);
            if ($children) {
                $element['children'] = $children;
            }
            $branch[] = $element;
        }
    }
    return $branch;
}
$equipment = new Model_PmTemplate();
$moduleMapper = new Model_UserBuildingModule();
$moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 3);
$buildhasAccess = array();
if ($moduleAccess) {
    foreach ($moduleAccess as $moduleAccessVal) {
        $buildhasAccess[] = $moduleAccessVal->module_id;
    }
}
foreach ($this->companyListing as $cb) {
            if ($cb['build_id'] == $this->select_build_id) {
                    $uniqueCostCenter = $cb['uniqueCostCenter'];
                }
}

$dashboard_menu = array(41);
if (in_array(3, $buildhasAccess)) {
    
    $reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);            
} else {
    $reportDetailLinks = false;
}

$dashboard_menu = array(42);
if (in_array(3, $buildhasAccess)) {
    
    $equipmentNameLinks = $reportModel->getReport($this->custID, $dashboard_menu);            
} else {
    $equipmentNameLinks = false;
}

$dashboard_menu = array(43);
if (in_array(3, $buildhasAccess)) {
    
    $floorUnitLinks = $reportModel->getReport($this->custID, $dashboard_menu);            
} else {
    $floorUnitLinks = false;
}
$equipment = new Model_PmTemplate();
?>
<div class="table-responsive">
<table data-vertable="ver2" id="example" class="table-bordered">
    <tbody>
        <?php

        function unique_multidim_array($array, $key) {
            $temp_array = array();
            $i = 0;
            $key_array = array();

            foreach ($array as $val) {
                if (!in_array($val[$key], $key_array)) {
                    $key_array[$i] = $val[$key];
                    $temp_array[$i] = $val;
                }
                $i++;
            }
            return $temp_array;
        }

        $equipmentName = unique_multidim_array($this->equipmentList, 'AU_Equipment_Name');

        if (!empty($this->equipmentList)) {


            foreach ($equipmentName as $val) {
                ?>

                <tr class="row100 heading-tr right-x">
                    <td  colspan="7" class="column100 column1 border-right-0" data-column=""><a href="#<?php echo $val['AU_Equipment_Name']; ?>" id="<?php echo $val['AU_Equipment_Name']; ?>" onclick="expandEquipmentDeail(this.id);" ><?php echo $val['AU_Equipment_Name']; ?></a>
                        <span class="td-span">
                                                <?php
            foreach ($equipmentNameLinks as $reportvalue) {
                $reportOptions = explode(',', $reportvalue->report_option);
                if ($reportvalue->Report_Type == 'Flash') {

                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }

                    if ((in_array('[[++AU_Equipment_Name_ID]]', $reportOptions)) && $val['AU_Equipment_Name_ID'] != '') {
                        $key = array_search('[[++AU_Equipment_Name_ID]]', $reportOptions);
                        $auEquipmentNameID = str_replace('[[++AU_Equipment_Name_ID]]', $val['equipmentnameid'], $reportOptions[$key]);
                    }

                    $print_url = $this->baseUrl() . '/reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&userID=' . $userID. '&AU_Equipment_Name_ID='.$auEquipmentNameID;
                } else {


                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }
                    
                    if ((in_array('[[++AU_Equipment_Name_ID]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++AU_Equipment_Name_ID]]', $reportOptions);
                        $auEquipmentNameID = str_replace('[[++AU_Equipment_Name_ID]]', $val['equipmentnameid'], $reportOptions[$key]);
                    }                   

                        $print_url = $this->baseUrl() . '/vnsreports/index.php?report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&User=' . $userID . '&AU_Equipment_Name_ID='.$auEquipmentNameID;
                    
                }
            }
            ?>
                                                
                                                <a <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo $print_url ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/printer.png" style="width:18px;"></a>
                                                <a style="float:right; margin-right: 15px;" onclick="javascript:addequipment('<?php echo $this->baseUrl() . '/pm/updateequipmentname/equipment_id/' . $val['equipmentnameid']; ?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png" ></a></span> 
                    </td>
                    <!--<td class="column100 column8 border-left-gray fa-icon" data-column="">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> <i class="fa fa-trash"></i>
                        <a onclick="javascript:edittemplete('<?php //echo $this->baseUrl() . '/pm/updateequipmentname/equipment_id/' . $val['AU_Equipment_Name_ID'];   ?>');" href="#CreateNewMultiCon"><img src="<?php //echo $this->baseUrl();   ?>/public/images/edit.png" ></a> 
                        <a  onclick="deleteequipmentname(<?php //echo $val['AU_Equipment_Name_ID'];   ?>)"><img src="<?php echo $this->baseUrl(); ?>/public/images/delete.png"></a>
                    </td>-->
                </tr>

                <tr class="collapseall" id="eqid<?php echo $val['AU_Equipment_Name']; ?>"><td id="mno<?php echo $val['equipmentnameid']; ?>"><table><tr class="row100">
                                <th   colspan="2"  class="column100 column1 colm-new01" data-column=""></th>
                                <th class="column100 column3 colm-new03-th  " data-column="">Floor <span><a href="#" id="sortingidbyfloor" onclick="sortingbyfloor('floor', '<?php echo $val['equipmentnameid']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvaluebyfloor" id="sortingvaluebyfloor"></a></span></th>
                                <th class="column100 column4 colm-new04 " data-column="">Unit <span><a href="#" id="sortingidbyunit" onclick="sortingbyunit('unit', '<?php echo $val['equipmentnameid']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvaluebyunit" id="sortingvaluebyunit"></a></span></th>
                                <th class="column100 column5 colm-new05 " data-column="">Make/ Model</th>
                                <th class="column100 column6 colm-new06" data-column="">Location<span><a href="#" id="sortingidbylocation" onclick="sortingbylocation('location', '<?php echo $val['equipmentnameid']; ?>');"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvaluebylocation" id="sortingvaluebylocation"></a></span></th>
                                <th class="column100 column7 colm-new07" data-column="">Template</th>
                                <th class="column100 column8 " data-column=""></th>
                            </tr>
                            <?php
                            $total = count($this->equipmentList);
                            foreach ($this->equipmentList as $vals) {
                                $total -= 1;
                                ?>
                                <?php if ($val['AU_Equipment_Name'] === $vals['AU_Equipment_Name']) { ?>

                                    <tr id="xyz"><td colspan="8"><table><tr class="row100 <?php
                                                if ($total == 0) {
                                                    echo 'right-x';
                                                }
                                                ?>">
                                                    <td class="column100 column1 colm-new01" data-column=""></td>
                                                    <td class="column100 column2 colm-new02 fa-icon" data-column=""><a href="#<?php echo $vals['AU_Equipment_Detail_ID']; ?>" class="show_hide" onclick="plusminus(this.id);" id="plus<?php echo $vals['AU_Equipment_Detail_ID']; ?>"><i class="fa fa fa-plus-circle" aria-hidden="true"></i></a></td>
                                                    <td class="column100 column3 colm-new03" data-column=""><?php echo $vals['Floor']; ?></td>
                                                    <td class="column100 column4 colm-new04" data-column=""><?php echo $vals['Unit']; ?></td>
                                                    <td class="column100 column5 colm-new05" data-column=""><?php echo $vals['MakeModel']; ?></td>
                                                    <td class="column100 column6 colm-new06" data-column=""><?php echo $vals['Location']; ?></td>
                                                    <td class="column100 column7 colm-new07" data-column=""><?php echo $vals['Template']; ?></td>
                                                    <td class="column100 column8 colm-new08 fa-icon text-center" data-column="">
                                                        <span class="td-inner-span">
                                                                                <?php
            foreach ($floorUnitLinks as $reportvalue) {
                $reportOptions = explode(',', $reportvalue->report_option);
                if ($reportvalue->Report_Type == 'Flash') {

                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }

                    if ((in_array('[[++AU_Equipment_Detail_ID]]', $reportOptions)) && $val['AU_Equipment_Detail_ID'] != '') {
                        $key = array_search('[[++AU_Equipment_Detail_ID]]', $reportOptions);
                        $auEquipmentDetailID = str_replace('[[++AU_Equipment_Detail_ID]]', $vals['AU_Equipment_Detail_ID'], $reportOptions[$key]);
                    }

                    $print_url = $this->baseUrl() . '/reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&userID=' . $userID. '&AU_Equipment_Detail_ID='.$auEquipmentDetailID;
                } else {


                    if ((in_array('[[++CostCenterNumber]]', $reportOptions)) && $uniqueCostCenter != '') {
                        $key = array_search('[[++CostCenterNumber]]', $reportOptions);
                        $costCenterNumber = str_replace('[[++CostCenterNumber]]', $uniqueCostCenter, $reportOptions[$key]);
                    }

                    if ((in_array('[[++KeyBuildingNumber]]', $reportOptions)) && $this->select_build_id != '') {
                        $key = array_search('[[++KeyBuildingNumber]]', $reportOptions);
                        $buildingID = str_replace('[[++KeyBuildingNumber]]', $this->select_build_id, $reportOptions[$key]);
                    }
                    if ((in_array('[[++user_id]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++user_id]]', $reportOptions);
                        $userID = str_replace('[[++user_id]]', $this->userId, $reportOptions[$key]);
                    }
                    
                    if ((in_array('[[++AU_Equipment_Detail_ID]]', $reportOptions)) && $this->userId != '') {
                        $key = array_search('[[++AU_Equipment_Detail_ID]]', $reportOptions);
                        $auEquipmentDetailID = str_replace('[[++AU_Equipment_Detail_ID]]', $vals['AU_Equipment_Detail_ID'], $reportOptions[$key]);
                    }                   

                        $print_url = $this->baseUrl() . '/vnsreports/index.php?report_key=' . $reportvalue->report_mrt . '&Cost_Center_Number=' . $costCenterNumber . ' &buildkey=' . $buildingID . '&User=' . $userID . '&AU_Equipment_Detail_ID='.$auEquipmentDetailID;
                    
                }
            }
            ?>
                                                                                
                                                                                <a <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo $print_url ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/printer.png" style="width:18px;"></a>
                                                                                <a class="dyn" onclick="javascript:addequipment('<?php echo $this->baseUrl() . '/pm/editequipment/eqp_detail_id/' . $vals['AU_Equipment_Detail_ID']; ?>');" href="#CreateNewMultiCon"><img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png" ></a></span>
                                                    </td>
                                                </tr>

                                                <tr class="slidingDiv" id="xyzplus<?php echo $vals['AU_Equipment_Detail_ID']; ?>">
                                                    <td colspan="8">
                                                        <table>
                                                            <tr class="row100">
                                                                <td class="column100 column1 equp-sub-box" data-column="">&nbsp;</td>
                                                                <td colspan="7" class="column100 column2" data-column="">
                                                                    <a href="<?php echo $this->baseUrl() . '/pm/createequipmentdetailtask/eqp_detail_id/' . $vals['AU_Equipment_Detail_ID'] . '/eqp_name/' . $val['AU_Equipment_Name'] . '/temp/' . $vals['Template']; ?>"><?php echo $val['AU_Equipment_Name']; ?> - Type Designation - <?php echo $vals['Template']; ?> | Note - <?php echo $vals['Notes']; ?></a>
                                                                </td>
                                                               <!-- <td class="column100 column1" data-column="">&nbsp;</td>-->
                                                            </tr>
                                                            <tr class="row100 right-x">
                                                                <?php
                                                                                    $multipleManualPDF = $equipment->getEquipmentManualById($vals['AU_Equipment_Detail_ID']);
                                                                                    
                                                                                    ?>
                                                                                    <td class="column100 column1 multipdf-list" data-column="">
                                                                                        <ul>
                                                                                            <li><a target='_blank' href="<?php echo $this->baseUrl() . '/public/pm/' . $vals['Equipment_Manual']; ?>"><?php echo $vals['Equipment_Manual'];?></a></li>
                                                                                            <?php foreach($multipleManualPDF as $pdf){
                                                                                            ?>
                                                                                            <li><a target="_blank" href="<?php echo $this->baseUrl() . '/public/pm/' . $pdf->Equipment_Manual; ?>"><?php echo $pdf->Equipment_Manual; ?></a></li>
                                                                                            <?php                                                                                            
                                                                                        }
                                                                                        ?>
                                                                                        </ul>
                                                                                            
                                                                                    </td>
                                                                <td colspan="6" class="column100 column2 padd-0" data-column="">
                                                                    <table class="background-collr" width="100%" border="0">
                                                                        <tbody>
                                                                            <tr  class="row100">
                                                                                <th>Task - Order </th>
                                                                                <th>  Task Instruction </th>
                                                                                <th>Frequency</th>
                                                                                <th> Next Start Date </th>
                                                                                <th>Start Day of Month</th>
                                                                                <th>Start Date Adjustment</th>
                                                                                <th class="border-right-0">Assigned to</th>
                                                                                <th></th>
                                                                            </tr>

                                                                            <?php
                                                                            if (!empty($vals['AU_Equipment_Detail_ID'])) {
                                                                                                    $equipmentDetailId = $vals['AU_Equipment_Detail_ID'];
                                                                                                    $results = $equipment->getTemplateTask($equipmentDetailId);
                                                                                                    if (count($results) > 0) {
                                                                                                        $tree = buildTree($results);
                                                                                                        /**
                                                                                                         * This is for sorting purpose
                                                                                                         */
                                                                                                        $mainArray = array();
                                                                                                        $mergeArray = array();
                                                                                                        foreach ($tree as $treeval) {
                                                                                                            if ((empty($treeval['AU_Frequency_ID']) && (sizeof($treeval['children']) == 0))) {
                                                                                                                $mergeArray[] = $treeval;
                                                                                                            } else {
                                                                                                                $mainArray[] = $treeval;
                                                                                                            }
                                                                                                        }
                                                                                                        $finalArray = array_merge($mainArray, $mergeArray);
                                                                                                        $tree = $finalArray;
                                                                                                    } else {
                                                                                                        $tree = array();
                                                                                                    }
                                                                                                }
                                                                            for ($i = 1; $i <= count($tree); $i++) {
                                                                                if (array_key_exists("children", $tree[$i - 1]) || $tree[$i - 1]['AU_Frequency_ID'] == '') {
                                                                                    ?>
                                                                                    <tr class="row100 sub-bg-bckgrnd">
                                                                                        <td class="border-left-0 fa-icon"><?php echo $i; ?> <i class="fa fa fa-minus-circle pull-right" aria-hidden="true"></i></td>
                                                                                        <td><?php echo $tree[$i - 1]['Task_Instruction'] ?></td>
                                                                                        <td><?php echo $tree[$i - 1]['Frequency_name'] ?></td>
                                                                                        <td><?php echo $tree[$i - 1]['Start_date'] ?></td>
                                                                                        <td><?php
                                                                                        if(empty($tree[$i - 1]['eqp_Startdate_month'])){
                                                                                            echo $tree[$i - 1]['Startdate_month'];
                                                                                        }else{
                                                                                            echo $tree[$i - 1]['eqp_Startdate_month'];
                                                                                        }?></td>
                                                                                        <td><?php echo $tree[$i - 1]['startdateadj_name'] ?></td>
                                                                                        <td class="border-right-0" colspan="2"><?php echo $tree[$i - 1]['group_name'] ?></td>
                                                                                    </tr>
                                                                                    <?php
                                                                                    for ($k = 1; $k <= count($tree[$i - 1]['children']); $k++) {
                                                                                        ?>
                                                                                        <tr class="row100 sub-bg-bckgrnd-light">
                                                                                            <td class="border-left-0">
                                                                                                <table class="background-collr" width="100%" border="0">
                                                                                                    <tbody>
                                                                                                        <tr class="row100 border-none">
                                                                                                            <td class="border-corner">&nbsp;</td>
                                                                                                            <td class="border-corner-1"><?php echo $k; ?></td>
                                                                                                        </tr>
                                                                                                    </tbody>
                                                                                                </table
                                                                                            </td>
                                                                                            <td><?php echo $tree[$i - 1]['children'][$k - 1]['Task_Instruction']; ?></td>
                                                                                            <td><?php echo $tree[$i - 1]['children'][$k - 1]['Frequency_name']; ?></td>
                                                                                            <td><?php echo $tree[$i - 1]['children'][$k - 1]['Start_date']; ?></td>
                                                                                            <td><?php
                                                                                            if(empty($tree[$i - 1]['children'][$k - 1]['eqp_Startdate_month'])){
                                                                                                echo $tree[$i - 1]['children'][$k - 1]['Startdate_month'];
                                                                                            }else{
                                                                                                echo $tree[$i - 1]['children'][$k - 1]['eqp_Startdate_month'];
                                                                                            }?></td>
                                                                                            <td><?php echo $tree[$i - 1]['children'][$k - 1]['startdateadj_name']; ?></td>
                                                                                            <td class="border-right-0" colspan="2"><?php echo $tree[$i - 1]['children'][$k - 1]['group_name']; ?></td>
                                                                                        </tr>
                                                                                        <?php
                                                                                    }
                                                                                    ?>

                                                                                    <?php
                                                                                } else {
                                                                                    ?>
                                                                                    <tr class="row100 right-x">
                                                                                        <td class="border-left-0 "><?php echo $i; ?></td>
                                                                                        <td><?php echo $tree[$i - 1]['Task_Instruction']; ?></td>
                                                                                        <td><?php echo $tree[$i - 1]['Frequency_name']; ?></td>
                                                                                        <td><?php echo $tree[$i - 1]['Start_date']; ?></td>
                                                                                        <td><?php
                                                                                        if(empty($tree[$i - 1]['eqp_Startdate_month'])){
                                                                                            echo $tree[$i - 1]['Startdate_month'];
                                                                                        }else{
                                                                                            echo $tree[$i - 1]['eqp_Startdate_month'];
                                                                                        }?></td>
                                                                                        <td><?php echo $tree[$i - 1]['startdateadj_name']; ?></td>
                                                                                        <td class="border-right-0" colspan="2"><?php echo $tree[$i - 1]['group_name']; ?></td>
                                                                                    </tr>
                                                                                    <?php
                                                                                }
                                                                            }
                                                                            ?>

                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                                <!--<td class="column100 column1" data-column="">&nbsp;</td>-->
                                                            </tr> 
                                                        </table>
                                                    </td>
                                                </tr></table></td></tr>
                                    <?php
                                            }
                                        }
                                        ?></table></td></tr>
                            <?php
                        }
                    } else {
                        echo '<span>Sorry no found!</span>';
                    }
                    ?>
    </tbody>
</table> 
</div>

<script>
    $(document).ready(function () {
        $(".slidingDiv").hide();

    });

</script>