<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm_task.js');
?>
<div class="container-right">
    <div class="message">               
            <span class="error-txt" style="color:red; text-align:center;"></span>
    </div>
    <section style="z-index:9999" class="w-48 fr ch-home-form">
        <section class="ch-form-header ">
            <h3>Start Date of Month- Group Modification </h3>
        </section>
        <div class="room-setup">
            <div class="tableGrid list_tableGrid my_table_grid">
                <div class="message">
                    <div class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>				  			
                    <span id="success_msg"></span>
                    <span id="error_msg"></span>
                </div>
                <div class="container" style="height: 200px">
                    <div>                        
                        <div>
                            <span class="ugroupErr" id="location-error"></span>                            

                            <select name="level" id="startdateofmonth">
                                <?php
                                for($i=1;$i<=28;$i++):
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                endfor;
                                ?>
                            </select>
                        </div>
                        <span class="ugroupErr" id="error_startdate"></span>
                        <div class="row">
                            <input type="checkbox" name="includesubset"  id="includesubset" value="1"> Check to include all subsets
                        </div>
                        <div class="confirmBtn float_none">
                            <input type="hidden" name="typedesination" id="typedesination_id" value="" >
                            <input type="button" value="Apply" name="save" class="confirm" id='emailsave' onclick="update_equipmenttemplate_taskroot_startdateofmonth(<?php echo $this->desig_id ?>);">
                            <input type="button" value="Cancel" name="cancel" class="cancel" onclick="closepopup();">                            
                            <input type="hidden" value="" id="total">
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </section>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<div class="fade_default_opt" id="fd_dft_div" style="display:none">
    <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
    <div id="file_form" class="bd-dft-cls" style="display:none"></div>
</div>
        <style>
            
            .ui-datepicker table {
                display: none !important;
            }
            .hasDatepicker{
                width:25% !important;
            }
        </style>
    <script>

//    var $date = "<?php echo $edittask->start_date; ?>";
//    var dataarray = $date.split(" ");
//    var month = convertMonthNameToNumber(dataarray[0]);
//    var alldays = new Date(dataarray[1], month, 0).getDate();
//    console.log("Number of days in selected Days"+alldays);
    html = "";
    html +='<option value="lastday" >Last day</option>';
    for(i=1;i<=31;i++){
        html+='<option value="'+i+getformatedays(i)+'">'+i+getformatedays(i)+'</option>';
    }
   // $("#startdateofmonth").html(html);

    function convertMonthNameToNumber(monthName) {
        var myDate = new Date(monthName + " 1, 2000");
        var monthDigit = myDate.getMonth();
        return isNaN(monthDigit) ? 0 : (monthDigit + 1);
    }
   function getformatedays(n){
                            if (n >= 11 && n <= 13) {
                                return "th";
                            }
                            switch (n % 10) {
                                case 1:  return "st";
                                case 2:  return "nd";
                                case 3:  return "rd";
                                default: return "th";
                            }
                        }
   
</script>
