<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/material.js');
?>
<?php
	$this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap.css');
	$this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap-editable.css');
	echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap.js');
	echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap-editable.js');
	$sarray = array();
	$servModel = new Model_Services();
	$serviceList = $servModel->getServices();
	$search_by = '';
	$search_value='';
	$service_value ='';
	if(!empty($this->search) && isset($this->search['search_by'])){
		$search_by = $this->search['search_by'];
		if($search_by!='service' && $search_by!='vendor')
	       $search_value=$this->search['search_value'];
	     else 
	      $service_value=$this->search['search_value']; 
	}
$vendor_array = array();	
$vendorMapper = new Model_Vendor();
$vendorlist = $vendorMapper->getVendorListByBid($this->select_build_id);
if($vendorlist){	
	foreach($vendorlist as $vl){
		$vendor_array[$vl['vid']]=$vl['company_name'];
	}
}

$material_access = $this->acessHelper->checkAccess($this->roleId,$this->material_location);
?>
<div class="container-right" id="userinfo-data">
	 <?php 
       if($this->roleId!=1 && $material_access->is_access == 0){ 
           if($this->custID!=null && $this->custID && $this->companyListing!='' && $this->companyListing!=false){
			       $order = $this->order;
				   $dir = $this->dir;
				   $ddir= 'ASC';
				   $sdir = 'ASC';
				   $vdir = 'ASC';
				   $pdir = 'ASC';
				   $mdir = 'ASC';
				   $gdir = 'ASC';
				  if($order=='description')
					  $ddir = ($dir=='ASC')?'DESC':'ASC';
			     else if($order=='service')
					  $sdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='vendor')
					  $vdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='vendor_part')
					  $pdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='manufacturer')
					  $mdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='mfg')
					  $gdir = ($dir=='ASC')?'DESC':'ASC';  	  
					  
				$url = BASEURL.'material/index/bid/'.$this->select_build_id;	  
			   ?>
			  <div id="contents">
					<ol id="toc">
						<?php
						    $sarray = array();
						    $servModel = new Model_Services();
						    $serviceList = $servModel->getServices();
						    foreach($serviceList as $sl){
								$sarray[$sl['sid']]=$sl['service'];
							}
							$j = 1;
							foreach($this->companyListing as $cb){ ?>					
							<li><a href="<?php echo $this->baseUrl().'/material/index/bid/'.$cb['build_id']; ?>" <?php if($cb['build_id']==$this->select_build_id) echo 'class="active"';?>><span><?php echo $cb['buildingName']; ?></span></a></li>
						<?php $j++; } ?>
					</ol>
					<div id="page" class="content">
					     <span class="material-heading"><h1>Material Console</h1></span>
					     <div id="material_search_div">
							 <div id="search_form_div">
								 <div id="search_message"></div>
								 <form name="search_form" id="search_form" method="post" onsubmit="return checkSearch(this)">
									 <div id="form_field">
								        <label>Search For</label>
								        <select name="search_by" id="search_by" onchange="showSVDropdown(this)">
											<option value="description" <?php echo ($search_by=='description')?'selected':''?>>Description</option>
											<option value="service" <?php echo ($search_by=='service')?'selected':''?>>Service</option>
											<option value="vendor" <?php echo ($search_by=='vendor')?'selected':''?>>Vendor</option>
											<option value="vendor_part" <?php echo ($search_by=='vendor_part')?'selected':''?>>Part No.</option>
											<option value="manufacturer" <?php echo ($search_by=='manufacturer')?'selected':''?>>Manufacturer</option>
											<option value="mfg" <?php echo ($search_by=='mfg')?'selected':''?>>MFG No.</option>
								        </select>
                                        <div class="text-select-div">
								        <div id="search_txt" <?php if($search_by=='service' || $search_by=='vendor') echo 'style="display:none"';?>><input type="text" name="search_value" id="search_value" value="<?php echo $search_value;?>"/></div>
								        <div id="service_select" <?php if($search_by!='service') echo 'style="display:none"';?>>
											 <select name="service_value" id="service_value">
												 <option value="">Select Services</option>
													<?php 
													   if($serviceList){
															foreach ($serviceList as  $service) {											
																  echo '<option value="'.$service['sid'].'"';
																  echo ($service_value==$service['sid'])?'selected':'';
																   echo '>'.$service['service'].'</option>';				   
															}
														}
													?>
											 </select>
								        </div>
								        <div id="vendor_select" <?php if($search_by!='vendor') echo 'style="display:none"';?>>
											 <select name="vendor_value" id="vendor_value">
												 <option value="">Select Vendor</option>
													<?php 
													   if($vendorlist){
															foreach ($vendorlist as  $vl) {											
																  echo '<option value="'.$vl['vid'].'"';
																  echo ($service_value==$vl['vid'])?'selected':'';
																   echo '>'.$vl['company_name'].'</option>';				   
															}
														}
													?>
											 </select>
								        </div>
                                        </div>
								      </div>
								      <div class="form-button">
								           <input type="submit" name="search" id="search" value="Search"/>
								           <input type="button" name="reset" id="reset" value="Reset" onclick="window.location.href='<?php echo BASEURL.'material/index/bid/'.$this->select_build_id;?>'"/>
								      </div>  
								 </form>
								 
							 </div>
					     </div>
					     <div id="message">
					        <span class="success_message"></span>
					        <span class="error-txt"></span>
					     </div>
					     <div id="vendor_data_div">
							 <table id="vendor_data_table" class="building_table_grid" width="100%">
								 <tr>
									 <th>&nbsp;</th>
									 <th><a href="<?php echo $url.'/order/description/dir/'.$ddir?>" 
                          class="<?php if($order=='description') echo $ddir; else echo 'sorting';?>">Description</a></th>
									 <th><a href="<?php echo $url.'/order/service/dir/'.$sdir?>" 
                          class="<?php if($order=='service') echo $sdir; else echo 'sorting';?>">Service</a></th>
                                     <th>Mark-up</th>
									 <th><a href="<?php echo $url.'/order/vendor/dir/'.$vdir?>" 
                          class="<?php if($order=='vendor') echo $vdir; else echo 'sorting';?>">Prefered Vendor</a></th>
									 <th><a href="<?php echo $url.'/order/vendor_part/dir/'.$pdir?>" 
                          class="<?php if($order=='vendor_part') echo $pdir; else echo 'sorting';?>">Vendor Part#</a></th>
									 <th><a href="<?php echo $url.'/order/manufacturer/dir/'.$mdir?>" 
                          class="<?php if($order=='manufacturer') echo $mdir; else echo 'sorting';?>">Manufacturer</a></th>
									 <th><a href="<?php echo $url.'/order/mfg/dir/'.$gdir?>" 
                          class="<?php if($order=='mfg') echo $gdir; else echo 'sorting';?>">MFG#</a></th>									 
								 </tr>
								 <?php if($this->materialList){
									    foreach($this->materialList as $ml){
											$mid = $ml['mid'];
											?>
										<tr>
											<td><div class="open_plus" id="open_div_<?php echo $mid;?>"><a href="javascript:void(0);" id="<?php echo $mid;?>" onClick="loadMaterial(<?php echo $mid;?>)";><?php echo '&nbsp;&nbsp;';?></a></div></div>
						                       <div class="open_close" id="close_div_<?php echo $mid;?>" style="display:none"><a href="javascript:void(0);" id="<?php echo $mid;?>" onClick="hideMaterial(<?php echo $mid;?>)";><?php echo '&nbsp;&nbsp;';?></a></div></div></td>
											<td><?php echo $ml['description']?></td>
											<td><?php echo $sarray[$ml['service']]?></td>
											<td><?php echo ($ml['markup']!='')?$ml['markup']:'0';?>%</td>
											<td><?php echo $vendor_array[$ml['vendor']]?></td>
											<td><?php echo $ml['vendor_part']?></td>
											<td><?php echo $ml['manufacturer']?></td>
											<td><?php echo $ml['mfg']?></td>
										</tr>
										<tr id="material_tr_<?php echo $mid;?>" class="trmaterial-class" style="display:none">
											<td>&nbsp;</td>
											<td id="material_data_<?php echo $mid;?>" colspan="7" class="tdmaterial-class"></td>
										</tr>	
									   <?php
								        }
									 }else {?>
								<tr>
									<td colspan="8">No Material's Data Exist..</td>
								</tr>		 
								 <?php }?>
								 <?php if($material_access->is_write==1){?>		 
								 <tr>
									 <th colspan="8" style="text-align:left"><a href="<?php echo $this->baseUrl().'/material/creatematerial/bid/'.$this->select_build_id; ?>">Add New</a></th>
								 </tr>
								 <?php }?>
							 </table>
					     </div>
					</div>
				</div>
			    <input type="hidden" name="building_id" id="building_id" value="<?php echo $this->select_build_id;?>"/>
			<?php }
		   else{
			   echo 'No Building has assign to you.';
		   }  
		  }else{?>
			You don't have access for this module.
		  <?php }?>
</div>
<?php if($this->mId){?>
<script type="text/javascript">
	loadMaterial('<?php echo $this->mId;?>');
</script>	
<?php }?>        			
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
