<?php 
    define('FORGOT_PASSWORD', "FORGOT PASSWORD");
    define('CANT_SIGNIN', "Can't sign in?");
    define('FORGET_YOUR_PASSWORD', "Forgot your password?");
    define('FORGET_PASSWORD_MESSAGE', "Enter your email address below and we 
        will send you password reset instruction");
    define('ENTER_EMAIL_ADDRESS', "Email Address : ");
    define('SPAN_FILTER_NOTE_LABEL', "A note about spam filters");
    define('SPAN_FILTER_NOTE', " If you do not get email from within a few minutes please be sure to check your spam filter. The email will be comming from Vision Work Order");
    define('SEND_RESET_INSTRUCTION', "Send me reset instruction");
?>
<script>
$(document).ready(function()
{
	$('#resetsubmit').click(function(){
		var email_id = $('#email-address').val();
		if(email_id=='')
		{
			$('.uemailErr').html("Please enter email-address.");
			$('#email-address').addClass('inputErr');
			$('#email-address').focus();
			return false;	  
		}
		
		if(email_id!=''){			
			if(!validateEmail(email_id)){
				$('.uemailErr').html("Please enter valid email-address.");
				$('#email-address').addClass('inputErr');
				$('#email-address').focus();
				return false;
			}
		}
	});
});

function validateEmail(sEmail) {
	    var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
	    if (filter.test(sEmail)) {
	        return true;
	    }
	    else {
	        return false;
	    }
 }	
</script>
<div class="login_form">
        <span class="companyLogo">
	<img src="<?php echo BASEURL.'public/images/vt_logo.png'?>" width="250">
</span>
<div class="index_lform">
<h1>FORGOT PASSWORD</h1>      
        <span class="error_msg"><?php if(!empty($this->forgetDetail['message'])){echo $this->forgetDetail['message'];}?></span>
		<span  class="forgot_welcome_text">
                    <?php 
                    if(isset($this->forgetDetail['success']) && !empty($this->forgetDetail['success'])){
                        echo $this->forgetDetail['success'];                        
                    }?></span>
        <form action="" id="forgetpassword" method="post" enctype="multipart/form-data">
			
			<div class="content" id="forgetpassword">
				<div class="login_form_forgetpassword">
					<div class="forgot_form"><?php echo FORGET_PASSWORD_MESSAGE;?></div>
					<div id="forgetpassword_field">
						<label><?php echo ENTER_EMAIL_ADDRESS;?></label>
						<span class="uemailErr"></span>
						<input type="text" name="email" value="" id="email-address" class="forgot_box" placeholder="E-mail Address"/>
					</div>
					<div id="forgetpassword_field" class="log_btn">
                                            <div> 
                                                <input type="submit" name="submit" id="resetsubmit" class="confirm" value="Submit" />
                                            </div>
                                            <div style="position: fixed;">
                                                <a href="<?php echo BASEURL; ?>" style=" width: 70px;background-color: #2ecc71;padding: 8px 8px; border: none;float: right;color: #fff;cursor: pointer; border: 1px solid #000;text-align: center;" > Home</a>
                                            </div>
                                                
					</div>                                        
					<hr>
					<div id="forgetpassword_field">
						<p><?php echo SPAN_FILTER_NOTE_LABEL;?></p>
						<p><?php echo SPAN_FILTER_NOTE;?></p>
					</div>
				</div>
			</div>
			
			
			<div>
				<table width="100%" style="margin:0 auto;">
					<!--<tr>
						<td colspan="2"><strong><?php echo CANT_SIGNIN . FORGET_YOUR_PASSWORD;?></strong></td>
					</tr>-->
					 
					 
					 
				</table>
            </div>
        </form>
     </div>
 </div>
<style>
    span.forgot_welcome_text {
        margin-left: 177px;
        font-weight: bold;
        color: red !important;
    }    
</style>


