<div class="login_form">

<div class="index_lform">
		   <h1>RESET PASSWORD</h1>  
		   <p><a href="<?php echo BASEURL ; ?>">Return to site home page</a></p>
		  	   

	<?php if(!empty($this->message)){ ?>
				<div class="success-msg"><?php echo $this->message; ?></div>
	<?php }
	    
	     if(!empty($this->warn_msg)){
			?>
			<div class="error-msg" ><?php echo $this->warn_msg; ?></div>
			<?php 
	      } 
	      if($this->login_url==true){
			?>
			<div class="loging-url"><a href="<?php echo BASEURL ; ?>">Go your login page.</a></div>
			<?php 
	      }
	      
	      if($this->form_status){
	     ?>		   
		   <form action="" id="resetpassword" method="post" onsubmit="return vailidateForm(this)"/>
           
           <div>
				<table width="100%" style="margin:0 auto;">
					<tr>
						<td><label>New password</label>	</td>
                        <td><span class="newpwdErr" style = "color:#f00;"></span>				 
					 	<input type="password" name="reset" value="" id="reset" class="inp_box" autofocus="true"/>
                        </td>
					</tr>
                    <tr>
                    <td><label>Confirm password</label>	</td>
                    <td> <span class="repwdErr"></span>				 
					 <input type="password" name="repwd" value="" id="repwd" class="inp_box"/></td>
                    </tr>
                    
                    <tr>
                    <td></td>
                    <td class="log_btn"> <input type="submit" name="submit" id="resetsubmit" class="resetbtn" value="RESET" disabled ></td>
                    </tr>
                    
                   
                </table>
		  
				<div class="reset-password-guide">
				    <span>Note:</span> Password must contain atleast one Upper letter, small letter, digit, special character and should be minimum 8 character.
				</div>
		   </div>
		   </form>
		   <?php }?>
	  </div>
 </div>
<script type="text/javascript">
	function vailidateForm(f){
		var pass = f.reset.value;
		var confpass = f.repwd.value;
		if(pass==''){
			$('.newpwdErr').html('Please enter your reset password.');
			$('#reset').addClass('inputErr');
			return false;
		}else{
			$('.newpwdErr').html('');
			$('#reset').removeClass('inputErr');
		}
		
		if(pass!=''){
			var decimal=  /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,15}$/;
			if(!pass.match(decimal))   
			{   
				$('.newpwdErr').html("Your password does not meet the minimum requirements. See the NOTE below."); 
				
				$('#reset').addClass('inputErr');  
				return false;  
			}else{
				$('.newpwdErr').html('');
			    $('#reset').removeClass('inputErr');
			}  
		}
		
		if(confpass==''){
		   $('.repwdErr').html('Please enter confirm password.');
		   $('#repwd').addClass('inputErr');
			return false;
		}else{
			$('.repwdErr').html('');
			$('#repwd').removeClass('inputErr');
		}
		
		if(confpass!=pass){
		   $('.repwdErr').html('Confirm password are not matching to new password.');
		   $('#repwd').addClass('inputErr');
		   return false;
		}else{
			return true;
		}
		
	}
$(document).ready(function(){
	$("#repwd").keyup(function(){

		if($(this).val() != '' && $("#reset").val()!='') {			
			$("#resetsubmit").removeAttr('disabled');
			$("#resetsubmit").removeClass('resetbtn');

		}else{			
			$("#resetsubmit").attr('disabled','disabled');
			$("#resetsubmit").addClass('resetbtn');
		}
	});
	
	$("#reset").keyup(function(){

		if($(this).val() != '' && $("#repwd").val()!='') {
			$("#resetsubmit").removeAttr('disabled');
			$("#resetsubmit").removeClass('resetbtn');

		}else{
			
			$("#resetsubmit").attr('disabled','disabled');			
			$("#resetsubmit").addClass('resetbtn');
		}
	});
});
</script>
