<?php	
	 $bsModel = new Model_BuildService();
	 $bsList = $bsModel->getActiveBuildServiceByBId($this->bId);	
?>
<script type="text/javascript">
	var bs_charge = [];
	var bs_minimum = [];
	<?php 
	     if($bsList){
			 foreach($bsList as $bsl){
			 ?>
				 bs_charge['<?php echo $bsl['bsid'];?>'] = '<?php echo $bsl['cost'];?>';
				 bs_minimum['<?php echo $bsl['bsid'];?>'] = '<?php echo $bsl['minimum'];?>';
			<?php
			 }
		 }
	?>
</script>
<div id="ct_bservice_fm_div">
	<span class="form_title">Add New Building Services Charge(s)</span>	
	<div class="message">
		<span id="success_msg" class="success"></span>
		<span id="error_msg" class="error"></span>
	</div>
	<div id="bservice_form_ data">
		 <div class="cw_row">
			 <label>Service</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_service"></span>
				 <select name="service" id="service" onchange="setBServCharge(this.value)">
					 <option value="">-- Select --</option>
					 <?php
					 if($bsList){ 
					     foreach ($bsList as  $bsl) { ?>
							<option value="<?php echo $bsl['bsid']; ?>">
								<?php echo $bsl['service_name']; ?>
							</option>
					<?php }
					} ?>
				 </select>
			 </div>
		 </div>
		 <div class="cw_row">
			  <label>Charge ($)</label>
			  <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_charge"></span>				 
					   <input type="text" name="charge" id="charge" onkeypress="return isNumber(event)">			 
			  </div>
		 </div>
		 <div class="cw_row">
			  <label>Amount Requested</label>
			  <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_amount"></span>				 
					   <input type="text" name="amount_requested" id="amount_requested" onkeypress="return isNumber(event)">			 
			  </div>
		 </div>		 
		 <div class="cw_row">
			 <label>Comment (Optional)</label>
			 <div class="cw-ibox-row">				 
				   <textarea name="comment" id="comment" rows="5" cols="45"></textarea>
			 </div>
		 </div>
	</div>
	<div class="buttons">
				   <button type="button" name="save_labor" id="save_bdservice" value="Save" onclick="saveBServiceData('<?php echo $this->woId;?>')">Save</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelBService()">Cancel</button>
	  </div>
</div>
