<?php	
	 $vendorModel = new Model_Vendor();
	 $vendorList = $vendorModel->getVendorListByBid($this->bId);
	 $outsideData = $this->outsideData[0];	
?>
<div id="ct_outside_fm_div">
	<span class="form_title">Edit Outside Services Charge(s)</span>	
	<div class="message">
		<span id="success_msg" class="success"></span>
		<span id="error_msg" class="error"></span>
	</div>
	<div id="outside_form_ data">
		 <div class="cw_row">
			 <label>Vendor Name</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_vendor"></span>
				 <select name="vendor" id="vendor">
					 <option value="">-- Select --</option>
					 <?php
					 if($vendorList){ 
					     foreach ($vendorList as  $vl) { ?>
							<option value="<?php echo $vl['vid']; ?>" 
							  <?php echo ($outsideData['vendor']==$vl['vid'])?'selected="selected"':''?>>
								<?php echo $vl['company_name']; ?>
							</option>
					<?php }
					} ?>
				 </select>
			 </div>
		 </div>
		 <div class="cw_row">
			  <label>Job Cost</label>
			  <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_cost"></span>				 
					   <input type="text" name="job_cost" id="job_cost" onkeypress="return isNumber(event)" value="<?php echo $outsideData['job_cost'];?>">			 
			  </div>
		 </div>
		 <div class="cw_row">
			  <label>Markup(%)</label>
			  <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_markup"></span>				 
					   <input type="text" name="markup" id="markup" onkeypress="return isNumber(event)" value="<?php echo $outsideData['markup'];?>">			 
			  </div>
		 </div>		 	 
		 <div class="cw_row">
			 <label>Tax</label>
			 <div class="cw-ibox-row">				 				   
				   <select name="show_tax" id="show_tax" disabled="disabled">
					   <option value="1" <?php echo ($outsideData['tax']=='1')?'selected="selected"':''?>>Yes</option>
					   <option value="0" <?php echo ($outsideData['tax']=='0')?'selected="selected"':''?>>No</option>
				   </select>
				  <input type="hidden" name="tax" id="tax" value="<?php echo $outsideData['tax'];?>"/> 
			 </div>
		 </div>
		 <div class="cw_row">
			  <label class="job_desc_lbl">Job Description/Work Completed(Optional)</label>
			  <div class="cw-ibox-row">
				   <span class="field_error" id="cwerr_job_desc"></span>
				   <textarea name="job_description" id="job_description" rows="5" cols="45"><?php echo $outsideData['job_description'];?></textarea>
					   			 
			  </div>
		 </div>	
	</div>
	<div class="buttons">
				   <button type="button" name="save_outside" id="save_outside" value="Save" onclick="updateOutSideData('<?php echo $this->osId;?>')">Save</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelOutside()">Cancel</button>
	  </div>
</div>
