<?php 
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/material.js');

?>
<div class="container-right" id="add-tenant-data">
<section class="w-48 fr ch-home-form">
<section class="ch-form-header">
	<h3>Add Alternate Vendor</h3>
</section>
			 <div class="vendor-user-data_">
		        <?php if(!empty($this->mid)){
					   if($this->materialData){
						   $mData = $this->materialData[0];
					?>
				  <div class="form_head">
						<span><?php echo $mData['description'];?> </span>
						<div class="atd_success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></div>
						<?php if($this->message && $this->message['msg']!=''){?>
						   <span class="error-msg"><?php echo $this->message['msg'];?></span>
						<?php }?>
				   </div>
				   
					  <form name="addNewVContact" id="addNewVContact" action="<?php echo BASEURL.'material/addvendorcontact/mid/'.$mData['mid'];?>" method="post">
						  <input type="hidden" value="<?php echo $mData['mid'];?>" name="mid" id="mid"/>
						  <input type="hidden" value="<?php echo $mData['buildingId']?>" name="building" id="building"/>		
						  
						  <a href="javascript:void(0)" onclick="cd()">----Add New Service----</a>
			
								   <select id="services" class="status" name="services">				  						  					  						  					  		<?php foreach($this->vendorList as $cb){ ?>

 
									   <option value="<?php echo $cb['vid'];?>"><?php echo $cb['company_name'];?></option>
										<?php 
										   if($servicelist){
												foreach ($servicelist as  $service) {											
													  echo '<option value="'.$service['sid'].'">'.$service['service'].'</option>';
												   
												}
											}
										?>
																			                    
									
						  <?php } ?>						  
						 </select>
						  <div class="row">	
							<label>Vendor Name :<span class="required">*</span></label><span class="field_error" id="vendor_name-error"></span> 	
                            <div class="row_vender_input">
							<input type="text" required="" id="vendor_name" class="" name="vendor_name">
                            </div>
						 </div>	
						<div class="row">	
							
							<label>Contact :<span class="required">*</span></label><span class="field_error" id="contact-error"></span> 	
							
                            <div class="row_vender_input">
                            <input type="text" required="" id="contact" class="" name="contact">
                            </div>
						</div>	
						 <div class="row">
							<label>E-mail :</label> <span class="field_error" id="email-error"></span>
							
                            <div class="row_vender_input">
                            <input type="text" value="" id="email" name="email">
                            </div>
						   </div>	
						<div class="row">	
							
							<label>Phone Number :<span class="required">*</span></label><span class="field_error" id="phone_number-error"></span> 	
							<div class="row_vender_input">
                            <input type="text" id="phone_number"  name="phone_number">
                            </div>
						</div>
						<div class="row">	
							<label>Cell Number :</label>							 		
							
                            <div class="row_vender_input">
                            <input type="text" id="cell_number" class="" name="cell_number" >
                            </div>
						</div>	
						
						<div class="row">
							<label>Vendor Part No. :</label>
							
                            <div class="row_vender_input">
                                 <input type="text" id="part_number" class="" name="part_number" >
                            </div>
						</div>											
							<div class="confirmBtn float_none">
								<input type="reset" value="Reset" name="cancel" class="cancel"/>
								<input type="button" value="Confirm" name="next" class="confirm next" onclick="addVendorContact()"/>
								<input type="button" value="Cancel" name="cancel" class="cancel" onclick="cancelVendorContact()"/>
							</div>
					  </form>
				     <?php }else
				           echo 'Invalid Page URL';
				     } else echo 'Invalid Page URL';?> 
			  </div>
              </section> 
			  </div>
			  

