<?php 
    define('FORGOT_PASSWORD', "FORGOT PASSWORD");
    define('CANT_SIGNIN', "Can't sign in?");
    define('FORGET_YOUR_PASSWORD', "Forgot your password?");
    define('FORGET_PASSWORD_MESSAGE', "Enter your email address below and we 
        will send you password reset instruction");
    define('ENTER_EMAIL_ADDRESS', "Email Address : ");
    define('SPAN_FILTER_NOTE_LABEL', "A note about spam filters");
    define('SPAN_FILTER_NOTE', "If you do not get email from within a few 
        minutes please be sure to check your spam filter. The email will be 
        comming from do-not-reply@xyz.com");
    define('SEND_RESET_INSTRUCTION', "Send me reset instruction");
?>
<script>
$(document).ready(function()
{
	$('#resetsubmit').click(function(){
		var email_id = $('#email-address').val();
		if(email_id=='')
		{
			$('.uemailErr').html("Please enter email-address.");
			$('#email-address').addClass('inputErr');
			$('#email-address').focus();
			return false;	  
		}
		
		if(email_id!=''){			
			if(!validateEmail(email_id)){
				$('.uemailErr').html("Please enter valid email-address.");
				$('#email-address').addClass('inputErr');
				$('#email-address').focus();
				return false;
			}
		}
	});
});

function validateEmail(sEmail) {
	    var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
	    if (filter.test(sEmail)) {
	        return true;
	    }
	    else {
	        return false;
	    }
 }	
</script>
<div class="login_form">
<div class="index_lform">
<h1>FORGOT PASSWORD</h1>      
        <span class="error_msg"><?php if(!empty($this->forgetDetail['message'])){echo $this->forgetDetail['message'];}?></span>
		<span  class="forgot_welcome_text"><?php if(isset($this->forgetDetail['success']) && !empty($this->forgetDetail['success'])){echo $this->forgetDetail['success'];}?></span>
        <form action="" id="forgetpassword" method="post" enctype="multipart/form-data">
			<div>
				<table width="100%" style="margin:0 auto;">
					<tr>
						<td colspan="2"><strong><?php echo CANT_SIGNIN . FORGET_YOUR_PASSWORD;?></strong></td>
					</tr>
					<tr>
						<td colspan="2"><?php echo FORGET_PASSWORD_MESSAGE;?></td>
					</tr>
					<tr>
						<td><?php echo ENTER_EMAIL_ADDRESS;?></td>
						<td>
							 <span class="uemailErr"></span>
							<input type="text" name="email" value="" id="email-address" class="inp_box" placeholder="E-mail Address"/>
						</td>
					</tr>
					<tr>
						<td></td>
						<td class="log_btn">
							
							<input type="submit" name="submit" id="resetsubmit" class="confirm" value="Submit" />
						</td>
					</tr>
					<tr>
						<td colspan="2"><hr></td>
					</tr>
					<tr>
						<td colspan="2"><?php echo SPAN_FILTER_NOTE_LABEL;?></td>
					</tr>
					<tr>
						<td colspan="2"><?php echo SPAN_FILTER_NOTE;?></td>
					</tr>
				</table>
            </div>
        </form>
     </div>
 </div>

