<?php
$wnData = $this->wnData[0];

?>
<div id="ct_note_fm_div">
	<h1>Edit Note Section</h1>	
	<div class="message" style='text-align:center;width:96%;font-weight:bold;color:red;'>
		<span id="success_msg" class="success"></span>
		<span id="error_msg" class="error"></span>
	</div>
	<div id="note_form_ data">
		 <div class="cw_row">
			 <label>Date</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_date"></span>				 
					   <input type="text" name="note_date" id="edit_note_date"  value="<?php echo $wnData['note_date'];?>" readonly="readonly">			 
			  </div>
		 </div>
		 <div class="cw_row">
			 <label>Internal</label>
			 <div class="cw-ibox-row">				 
				   <select name="internal" id="edit_internal">
					   <option value="1" <?php echo ($wnData['internal']=='1')?'selected="selected"':''?>>Yes</option>
					   <option value="0" <?php echo ($wnData['internal']=='0')?'selected="selected"':''?>>No</option>
				   </select>
			 </div>
		 </div>
		 
		  <div class="cw_row">
			 <label>Predefined Notes</label>
			 <div class="cw-ibox-row">
				 <select class='all_select' onchange='FillPredefinedNotes(this)' > 
							<option value=''> Select From Predefined Notes </option>
							<?php  $noteModel = new Model_Notes();
								$noteList = $noteModel->getNotes(); 
								
								foreach($noteList as $noteValue) { 
							?>
							<option value='<?php echo $noteValue['nid']; ?>'> <?php echo $noteValue['notes']; ?>  </option>   
							<?php } ?>
							</select>
			 </div>
		 </div>
		 <div class="cw_row">
			 <label>Note</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="edit_cwerr_note"></span>				 
				   <textarea name="note" id="edit_note" rows="8" cols="45"><?php echo $wnData['note'];?></textarea>
			 </div>
		 </div>
		 
	 </div>
	 <div class="buttons">
	 <input type="hidden" name="woId" id="edit_woId" value="<?php echo $wnData['woId']; ?>">
	                <input type="hidden" id="edittempnotes" value="">
				   <button type="button" name="save_note" id="save_note" value="Save" onclick="updateNote('<?php echo $this->wnId?>')">Save</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelNote()">Cancel</button>
	  </div>
</div>
