<?php
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/multiple-select.css');

$customeAccessmodel = new Model_UserAccess();
$dline_access = $this->acessHelper->checkAccess($this->roleId, $this->dline_location);
/* override access by custom user access if exist */
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->dline_location);
if ($customeAccessmodeld[0]) {
    $dline_access = $customeAccessmodeld[0];
}
$ddetail_access = $this->acessHelper->checkAccess($this->roleId, $this->ddetail_location);
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->ddetail_location);
if ($customeAccessmodeld[0]) {
    $ddetail_access = $customeAccessmodeld[0];
}
$createnew_access = $this->acessHelper->checkAccess($this->roleId, $this->createnew_location);
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->createnew_location);
if ($customeAccessmodeld[0]) {
    $createnew_access = $customeAccessmodeld[0];
}
$closewo_access = $this->acessHelper->checkAccess($this->roleId, $this->closewo_location);
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->closewo_location);
if ($customeAccessmodeld[0]) {
    $closewo_access = $customeAccessmodeld[0];
}

$reportModel = new Model_Report();
$reportDetailLinks = '';
$dashBoardViewsdetails = '';
$dashBoardViews = '';
$woNumberAll = '';
$invoiceAll = '';
$uniqueCostCenterAll = '';
$buildIdReportAll = '';
$batch_number_report = '';
$uniqueCostCenter = '';
$workorderstatus = '';
$workorderallstatus = '';


if ($this->view_type != 'detail') {
    $reportDetailLinks = $reportModel->getReport($this->custID, 2);
    $dashBoardViewsdetails = $reportModel->getReport($this->custID, 27);
} else {
    $reportDetailLinks = $reportModel->getReport($this->custID, 3);
}



if ($this->roleId != '1' && ($dline_access->is_access == 0 || $ddetail_access->is_access == 0)) {
    if ($this->custID != null && $this->custID && $this->companyListing != '' && $this->companyListing != false) {

        $order = $this->order;
        $dir = $this->dir;
        $wdir = 'ASC';
        $bdir = 'ASC';
        $tdir = 'ASC';
        $sdir = 'ASC';
        $cdir = 'ASC';
        $pdir = 'ASC';
        $stdir = 'ASC';
        $ddir = 'ASC';
        $tudir = 'ASC';
        if ($order == 'wo_number')
            $wdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'buildingName')
            $bdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'tenantName')
            $tdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'suite_location')
            $sdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'categoryName')
            $cdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'priorityName')
            $pdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'wo_status')
            $stdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'firstName')
            $tudir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else
            $ddir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        $ssModel = new Model_ScheduleStatus();
        $status_list = $ssModel->getScheduleStatus();
        $status_array = array();
        foreach ($status_list as $sl) {
            if ($sl['ssID'] != 8)
                $status_array[$sl['ssID']] = $sl['title'];
            $workorderallstatus = $workorderallstatus . $sl['ssID'] . ',';
        }

        if (isset($this->statusCookieDetails) && $this->statusCookieDetails != '') {
            foreach ($this->statusCookieDetails as $stvalue) {
                $workorderstatus = $workorderstatus . $stvalue . ',';
            }
        }

        $workorderstatus = rtrim($workorderstatus, ',');
        $workorderallstatus = rtrim($workorderallstatus, ',');
        $color_code = array('00FFFF', 'FF0000', 'FF00FF', '800000', '008000', '800080', '808000', '0000FF', '00FF00', '00008075', 'FFFF00', '808000', '008080', 'FFA500');
        $building_color = array();
        $veiw_type = $this->view_type;
        ?>

        <?php
            $j = 1;

            foreach ($this->companyListing as $cb) {
                if (isset($color_code[$j]))
                    $building_color[$cb['build_id']] = $color_code[$j];
                else {
                    $j = 0;
                    $building_color[$cb['build_id']] = $color_code[$j];
                }
                $j++;
            }
        ?>
           
            <?php
            if ($veiw_type == 'line') {
                $url = BASEURL . 'dashboard/workorder';
            } else {
                $url = BASEURL . 'dashboard/workorder/view_type/detail';
            }
            ?>
               
                   
                        
                            
                                
                                    
                                        <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer">
                                            <thead>
                                                <tr>

                                                    <th><a href="<?php echo $url . '/order/created_at/dir/' . $ddir ?>" 
                                                           class="<?php if ($order == 'created_at')
                                            echo $ddir;
                                        else
                                            echo 'sorting';
                                                           ?>">Date Received</a></th>
                                                    <th>Time Received</th>
                                                    <th><a href="<?php echo $url . '/order/wo_number/dir/' . $wdir ?>" class="<?php if ($order == 'wo_number')
                                            echo $wdir;
                                        else
                                            echo 'sorting';
                                                           ?>">Work Order#</a></th>
                                                    <th><a href="<?php echo $url . '/order/wo_status/dir/' . $stdir ?>"
                                                           class="<?php if ($order == 'wo_status')
                                            echo $stdir;
                                        else
                                            echo 'sorting';
                                                           ?>">Current Status</a></th>
                                                    <th><a href="<?php echo $url . '/order/categoryName/dir/' . $cdir ?>"
                                                           class="<?php if ($order == 'categoryName')
                                            echo $cdir;
                                        else
                                            echo 'sorting';
                                                           ?>">Category</a></th>
                                                    <th><a href="<?php echo $url . '/order/tenantName/dir/' . $tdir ?>"
                                                           class="<?php if ($order == 'tenantName')
                                            echo $tdir;
                                        else
                                            echo 'sorting';
                                                           ?>">Tenant</a></th>
                                                    <th>Work Request</th>
                                                <?php /* <th>Contact Information</th> */ ?>
                                                    <th><a href="<?php echo $url . '/order/buildingName/dir/' . $bdir ?>"
                                                           class="<?php if ($order == 'buildingName')
                                            echo $bdir;
                                        else
                                            echo 'sorting';
                                                ?>">Building Name</a></th>
                                                <?php if ($dashBoardViewsdetails != '') { ?>
                                                        <th>&nbsp;</th>
                                                <?php } ?>
                                                    <th>&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                    <?php
                    //echo date("Y-m-d h:i:s");
                    if ($this->wolist) {
                        
                        $catModel = new Model_Category();

                        $psModel = new Model_Schedule();
                        $wssModel = new Model_WoScheduleStatus();
                        /*             * ********Get notes list ********** */
                        $noteModel = new Model_Notes();
                        $noteList = $noteModel->getNotes();
                        $timezone_Model = new Model_TimeZone();
                        $build_model = new Model_Building();
                        foreach ($this->wolist as $wl) {
                            $tz_build_data = $build_model->getbuildingbyid($wl->building);
                            //echo "<pre>";
                            //print_r($wl);
                            //print_r($tz_build_data[0]['timezone']);
                            if (isset($tz_build_data[0]['timezone']) && $tz_build_data[0]['timezone'] != 0) {
                                $timezone_data = $timezone_Model->getTimeZone($tz_build_data[0]['timezone']);
                                $timezone = $timezone_data[0]['time_value'];
                                if (isset($timezone))
                                    date_default_timezone_set($timezone);
                                //date_default_timezone_get();								
                            }

                            $schedule = $psModel->getWoSchedule($wl->prioritySchedule, $wl->wo_status);
                            $currTime = date("Y-m-d h:i:s A");
                            $lastTime = '';
                            if ($wl->wo_status == '1') {
                                $lastTime = $wl->date_requested . ' ' . $wl->time_requested;
                            } else if ($wl->updated_date != '0000-00-00 00:00:00') {
                                $lastTime = $wl->updated_date;
                            } else
                                $lastTime = $wl->created_date;

                            $lastTime = date("Y-m-d h:i:s A", strtotime($lastTime));
                            $timeDiff = strtotime($currTime) - strtotime($lastTime);

                            $time = $schedule[0]['Time'];
                            $reminderStatus = $wssModel->getReminderStatus($timeDiff, $time, $schedule[0]['length']);
                            //echo "<br>date_default_timezone_get->".date_default_timezone_get();
                            //echo "<br>currTime".$currTime;
                            //echo "<br>lastTime".$lastTime;
                            ?> 
                <tr>
                    <td><?php echo date("m/d/Y", strtotime($wl->date_requested)) ?></td>
                    <td><?php echo $wl->time_requested ?></td>
                    <td> 
                        <?php if ($closewo_access->is_access == 0) { ?>
                            <a href="<?php echo BASEURL . '/complete/workorder/bid/' . $wl->building . '/wnum/' . $wl->wo_number; ?>"><?php echo $wl->wo_number ?></a>
                                                                                          <?php } else { ?>
                            <?php echo $wl->wo_number ?>
                        <?php } ?>	     
                        <?php if ($reminderStatus && ($wl->wo_status != '6' && $wl->wo_status != '7')) echo '&nbsp;&nbsp;<a class="alert tooltip">&nbsp;<span>
                        Time Over
                        </span></a>'; ?>
                    </td>
                    <td><?php echo $status_array[$wl->wo_status]; ?> <?php
        if ($wl->wo_status == 1) {
            $wo_schedule_status = new Model_WoScheduleStatus();
            $wo_scheduledetails = $wo_schedule_status->getCurrentWorkSchedule($wl->woId);
            ?> <?php if ($wo_scheduledetails[0]->ckey != '') { ?> 
                                <button type="button" class="btn btn-danger btn-xs" style="margin-left:10px;" onclick="acknowledgeWorkorder('<?php echo BASEURL . '/workstatus/change/woId/' . $wo_scheduledetails[0]->worder_id . '/sId/' . $wo_scheduledetails[0]->schedule_id . '/ckey/' . $wo_scheduledetails[0]->ckey . '/statusChange/acknowledge/userId/' . $this->userId; ?>')" >Acknowledge</button>

                    <?php }
                }
                ?> </td>
                    <td><?php echo stripslashes($wl->categoryName); ?></td>
                    <td><?php echo stripslashes($wl->tenantName); ?></td>
                    <td style='max-width:120px;'>	 

                <?php
                $descText = strip_tags($wl->work_order_request);
                $descText = str_replace("&nbsp;", ' ', $descText);
                echo substr($descText, 0, 40);
                echo (substr($descText, 50)) ? '...' : '';
                ?>
                    </td>

                            <?php /* <td><?php echo $wl->tenantContact?></td> */ ?>
                    <td><?php echo stripslashes($wl->buildingName); ?></td>
                            <?php
                            if ($dashBoardViewsdetails != '') {
                                $dashBoardViewsdetailsoption = $dashBoardViewsdetails[0]->report_option;
                                $dashBoardViewsdetailsoption = explode(',', $dashBoardViewsdetailsoption);
                                ?>
                        <td><a <?php if ($dashBoardViewsdetails[0]->report_target == 1) { ?> target="_blank"  <?php } ?> href="<?php echo BASEURL; ?>reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_report_key=<?php echo $dashBoardViewsdetails[0]->report_mrt; ?><?php
                                if (in_array('[[++user_id]]', $dashBoardViewsdetailsoption)) {
                                    echo '&User=' . $this->userId;
                                }
                                ?><?php
                                if ((in_array('[[++CostCenterNumber]]', $dashBoardViewsdetailsoption))) {
                                    echo '&Cost_Center_Number=' . $wl->uniqueCostCenter;
                                }
                                ?><?php
                                if ((in_array('[[++KeyBuildingNumber]]', $dashBoardViewsdetailsoption))) {
                                    echo '&buildkey=' . $wl->building;
                                }
                                ?><?php
                                if (in_array('[[++BatchNumber]]', $dashBoardViewsdetailsoption) && $wl->wo_batch != 0) {
                                    echo '&Batch_Number=' . $wl->wo_batch;
                                }
                                ?><?php
                                if ((in_array('[[++WONumber]]', $dashBoardViewsdetailsoption))) {
                                    echo '&WO_Number=' . $wl->wo_number;
                                }
                                ?><?php
                                if ((in_array('[[++InvoiceNumber]]', $dashBoardViewsdetailsoption)) && $wl->billable_opt == 1) {
                                    echo '&Invoice_Number=' . $wl->wo_number;
                                }
                                ?><?php
                                if ((in_array('[[++Status_id]]', $dashBoardViewsdetailsoption))) {
                                    echo '&Status=' . $wl->wo_status;
                                }
                                ?>" ><img src="<?php echo BASEURL . 'public/images/printer.png'; ?>" style="width:20px;"></a></td>
                            <?php }  ?>
                    <td style="background-color:#<?php echo $building_color[$wl->building] ?>">
                            <?php if ($veiw_type == 'line') { ?>
                            <a href="javascript:void(0)" onclick="showWorkOrder('<?php echo $wl->woId ?>')">
                                <i id="plus_<?php echo $wl->woId ?>" class="fa fa-plus blackfont_color plus_min_icon"></i></a>
                                <?php } else echo '&nbsp;'; ?>

                    </td>
                </tr> 
        <?php if ($veiw_type == 'line') { ?>
                    <tr id="workrequest_<?php echo $wl->woId ?>" style="display:none;" class="tr-order">
                        <td colspan="9" id="order_content_<?php echo $wl->woId ?>" class="order-detail"></td>
                    </tr> 
        <?php
                } else {


                    $catlist = $catModel->getBuildingCategoryList($wl->building);
                    $cat_array = array();
                    foreach ($catlist as $cat)
                        $cat_array[$cat['cat_id']] = $cat['categoryName'];
                    ?>
                    <tr>
                        <td colspan="<?php echo ($dashBoardViewsdetails != ''?'9':'8'); ?>">
                            <div class="order-details">
                    <?php
                    $woModel = new Model_WorkOrder();
                    $wodetail = $woModel->getWorkOrderInfo($wl->woId);

                    $woData = $wodetail[0];

                    $ssModel = new Model_ScheduleStatus();
                    $status_list = $ssModel->getScheduleStatus();
                    $status_array = array();
                    foreach ($status_list as $sl) {
                        $status_array[$sl['ssID']] = $sl['title'];
                    }
                    $gplist = array();
                    $gp_names = '';
                    if ($woData->send_email != '') {
                        $egModel = new Model_EmailGroup();
                        $gplist = $egModel->getGroupIds($woData->send_email);
                        foreach ($gplist as $gp) {
                            $gp_names .= ($gp_names != '') ? ',' : '';
                            $gp_names .= $gp['group_name'];
                        }
                    }

                    $wpModel = new Model_WorkOrderUpdate();
                    $cwpData = $wpModel->getCurrentWoUpdate($woData->woId);
                    $work_status = ($cwpData) ? $cwpData[0]['wo_status'] : 0;
                    $internalNote = ($cwpData) ? $cwpData[0]['internal_note'] : '';
                    $pscheduleModel = new Model_Schedule();

                    $schedule_list = $pscheduleModel->getSchedule($woData->pid);
                    $schedule_array = array();
                    if ($schedule_list) {
                        foreach ($schedule_list as $sl) {
                            $schedule_array[] = $sl['start_status'];
                        }
                    }
                    //var_dump($schedule_list);

                    $lenModel = new Model_Length();
                    $lenlist = $lenModel->getLength();
                    ?>   										 
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <?php if ($ddetail_access->is_write == 1) { ?>
                        <?php if ($work_status != '6' && $work_status != '7') { ?>
                        <form name="wcassign-form" id="wcassign-form-<?php echo $woData->woId; ?>">
                            <span id="assign_error_<?php echo $woData->woId; ?>" class="error"></span>
                            <div id="assign_category" class="my_agn_div">
                                <div class="lbl_div"> <label>Assign new category</label> </div>
                                <input type="hidden" name="curr_cat_<?php echo $woData->woId; ?>" id="curr_cat_<?php echo $woData->woId; ?>" value="<?php echo $woData->category; ?>"/>
                                <select name="assign_category_<?php echo $woData->woId; ?>" id="assign_category_<?php echo $woData->woId; ?>" class="my_assign_div">
                                    <option value="">Select Category</option>
                            <?php
                            if ($catlist) {
                                foreach ($catlist as $cat) {
                                    echo '<option value="' . $cat['cat_id'] . '"';
                                    echo ($cat['cat_id'] == $woData->category) ? 'selected' : '';
                                    echo '>' . stripslashes($cat['categoryName']) . '</option>';
                                }
                            }
                            ?>
                                </select>
                                <input type="button" name="assign_button" class="form_btn" value="Assign Category" onClick="reassignCategory('<?php echo $woData->woId; ?>');"/>
                            </div>
                        </form>	
                            <?php } ?>
                        <form name="wo-request-form" id="wo-request-form" action="<?php echo BASEURL . '/dashboard/updateorder/' ?>" method="post">
                            <div class="form_group">
                                <div class="lbl_div">
                                    <label>Work Request</label>
                                </div>
                                <div class="form_field_div my_lbl_div">                
                        <?php
                        echo stripslashes($woData->work_order_request);
                        ?>

                                    <input type="hidden" name="work_order_id_<?php echo $woData->woId; ?>" value="<?php echo $woData->woId; ?>"/>
                                    <input type="hidden" name="priority" id="priority_<?php echo $woData->woId; ?>" value="<?php echo $woData->pid; ?>"/>
                                    <input type="hidden" name="exist_schedule" id="exist_schedule_<?php echo $woData->woId; ?>" value="<?php echo implode(',', $schedule_array); ?>"/>
                                    <input type="hidden" name="current_wstatus_<?php echo $woData->woId; ?>" id="current_wstatus_<?php echo $woData->woId; ?>" value="<?php echo $work_status; ?>"/>
                                </div>
                            </div>
                                            <?php if ($work_status != '7') { ?>
                                <div class="form_group">
                                    <div class="lbl_div">
                                        <label>Update Status To</label>
                                    </div>
                                    <!-- Split button -->
                                    <div class="form_field_div my_work_form_field">
                                        <div class="btn-group work_update_select">
                                            <div id="wstatus_error_<?php echo $woData->woId; ?>" class="wst_error"></div>
                                            <select name="order_status_<?php echo $woData->woId; ?>" id="order_status_<?php echo $woData->woId; ?>" class="all_select" onChange="javascript:checkSchedule('workorder', '<?php echo $woData->woId; ?>');">
                                                <?php foreach ($status_array as $key => $value) { ?>
                                                    <option value="<?php echo $key; ?>" <?php echo ($work_status == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
                                                <?php } ?>  
                                            </select>																                  
                                        </div>
                                        <div id="time_length_div_<?php echo $woData->woId; ?>" class="time_len_my_div" style="display:none">
                                            <div id="schedule_error" class="sch_error"></div>
                                            <div id="time_div" class="time_t_div">
                                                <label>Time <span class="required">*</span></label>
                                                <input type="text" name="Time" id="Time_<?php echo $woData->woId; ?>" maxlength="2" onkeypress="return isNumberKey(event)"/>
                                            </div>
                                            <div id="length_div" class="len_div">
                                                <label>Length <span class="required">*</span></label>
                                                <select name="length" id="length_<?php echo $woData->woId; ?>">
                                    <?php foreach ($lenlist as $ll) { ?>
                                                        <option value="<?php echo $ll['lID'] ?>"><?php echo $ll['title'] ?></option>
    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>






                                        <div class="form_group"><input type="button" class="form_btn float_right" value="Update" onclick="updateWorkorder('<?php echo $woData->woId; ?>')"></div>
                                    <?php } ?>
                                </form>
                                    <?php if ($work_status != '7') { ?>
                                    <div class="form_group note_group">
                                        <div class="lbl_div">
                                            <label>Note</label>
                                            <input type="button" onclick="showNoteForm(<?php echo $woData->woId; ?>)" value="Add Notes" class="form_btn pull-right">
                                            <div class="clear"></div>
                                        </div>
                                        <!-- Split button -->

                                        <div class="form_field_div">
                                        <?php
                                        $wnModel = new Model_WoNote();
                                        $wnList = $wnModel->getWoNoteByWoId($woData->woId);
                                        if ($wnList) {
                                            ?>
                                                <table>
                                                    <tr class='addnotetable'>
                                                        <th >Date/Time </th>   
                                                        <th> Notes/Details</th> 
                                                        <th>Internal(Y/N) </th> 
                                                        <th>Entered By</th> 
                                            <?php if ($this->admin_role_id == 1 || $this->roleId == 2 || $this->roleId == 3 || $this->roleId == 4) { ?> <th>Action</th> <?php } ?>
                                                    </tr>
                                            <?php foreach ($wnList as $wn) { ?>

                                                        <tr> 
                                                            <td><?php
                                                $dateConversion = strtotime($wn['created_at']);
                                                echo date('Y-m-d H:i:s A', $dateConversion);
                                                ?></td> 
                                                            <td><?php echo $wn['note']; ?></td> 
                                                            <td><?php echo ($wn['internal'] == '1') ? 'Yes' : 'No'; ?></td> 
                                                            <td width="120" align="center"> <?php echo $wn['firstName'] . ' ' . $wn['lastName']; ?></td>
                                                <?php if ($this->admin_role_id == 1 || $this->roleId == 2 || $this->roleId == 3 || $this->roleId == 4) { ?>
                                                                <td width="60" align="center">
                                                    <?php if ($this->admin_role_id == 1 || $this->roleId == 2 || $this->roleId == 3 || $this->roleId == 4) { ?>
                                                                        <a class="close_bt_hide_cls" title="Edit" href="javascript:void(0)" onclick="showEditNote('<?php echo $wn['wnId']; ?>')"><img src="<?php echo BASEURL . 'public/images/edit.png' ?>" /></a>
                                                    <?php } ?>
                                                    <?php if ($this->admin_role_id == 1) { ?>
                                                                        <a class="close_bt_hide_cls" href="javascript:void(0);"  title="Delete" onclick="deleteNote('<?php echo $wn['wnId']; ?>', '<?php echo $woData->woId; ?>')"><img src="<?php echo BASEURL . 'public/images/delete.png' ?>" /></a>
                                                    <?php } ?>
                                                                </td>
                                                <?php } ?>


                                            <?php }
                                            ?>


                                                    </tr>
                                                </table>

                                        <?php } ?>
                                            <div class='clearfix'>  &nbsp; </div>
                                        </div>

                                    </div>  <?php } ?>




                                <?php } ?>
                            <div id="progressbarnew">
                                <?php
                                $timezone_Model = new Model_TimeZone();
                                $build_model = new Model_Building();
                                $tz_build_data = $build_model->getbuildingbyid($wl->building);

                                if (isset($tz_build_data[0]['timezone']) && $tz_build_data[0]['timezone'] != 0) {
                                    $timezone_data = $timezone_Model->getTimeZone($tz_build_data[0]['timezone']);
                                    $timezone = $timezone_data[0]['time_value'];
                                    if ($timezone) {
                                        date_default_timezone_set($timezone);
                                    }
                                    //echo "date_default_timezone_get->".date_default_timezone_get();								
                                    //$date = new DateTime(null, new DateTimeZone($timezone));
                                }

                                //echo "<pre>";
                                //print_r($woData);

                                $wsModel = new Model_WoScheduleStatus();
                                $wsList = $wsModel->getWoAllStatus($woData->woId);
                                //$currTime = time();
                                $timezone_Model = new Model_TimeZone();

                                if ($wsList) {
                                    $i = 0;
                                    $tot_width = 0;
                                    $ws_status = '';
                                    $pro_prcentage = 0;
                                    $pro_width = 0;
                                    $pro_msg = '';
                                    $colorCode = '';
                                    $status_title_val = '';
                                    foreach ($wsList as $ws) {
                                        //echo "<pre>";
                                        //print_r($work_status);
                                        if ($ws->current_status == '1' && $ws->parent_priority_status == '1') {
                                            $lastTime = '';
                                            if ($work_status == '1') {
                                                $lastTime = $woData->date_requested . ' ' . $woData->time_requested;
                                            } else
                                                $lastTime = $ws->created_at;

                                            $lastTime = date("Y-m-d h:i:s A", strtotime($lastTime));
                                            $currTime = date("Y-m-d h:i:s A");

                                            $timeDiff = abs(strtotime($currTime) - strtotime($lastTime));
                                            $calTime = $wsModel->getCalculateTime($ws->Time, $ws->length);
                                            if ($calTime == 0) {
                                                $devide_num = number_format((float) (0), 2, '.', '');
                                            } else {
                                                $devide_num = number_format((float) ($timeDiff / $calTime), 2, '.', '');
                                            }
                                            $pro_prcentage = $devide_num * 100;
                                            if ($pro_prcentage > 100) {
                                                $pro_width = 100;
                                                $colorCode = '#f0ad4e';
                                                $pro_msg = ' Time Out';
                                            } else {
                                                $pro_width = $pro_prcentage;
                                                $colorCode = '#5cb85c';
                                                //$pro_msg = $pro_prcentage.' % Time has been passed.';
                                                $pro_msg = $pro_prcentage . '%';
                                            }
                                            /*
                                              if($wl->buildingName=="Test building"){
                                              echo "<br>date_default_timezone_get->".date_default_timezone_get();
                                              echo "<br>currTime".$currTime;
                                              echo "<br>lastTime".$lastTime;
                                              echo "<br>pro_prcentage".$pro_prcentage;
                                              }
                                             */

                                            $status_title_val = $status_array[$ws->start_status] . ' - ' . $ws->Time . ' ' . $ws->length_title;
                                        }
                                        $ws_status .= ($ws_status != '') ? '-> ' : '';
                                        $ws_status .= $status_array[$ws->start_status];
                                        $current_status = $ws->current_status;
                                        $parent_priority_status = $ws->parent_priority_status;
                                        $email_status = $ws->email_status;
                                        $parent_email_status = $ws->parent_email_status;
                                    }
                                    if ($current_status == 1 && $parent_priority_status == 1 && $email_status == 1 && $parent_email_status == 1) {
                                        echo '<span class="ch-status"><strong>Status:</strong> ' . $ws_status . '</span>';
                                        if ($work_status != '6' && $work_status != '7') {
                                            ?>

                                <div class="progress">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
                                         aria-valuemin="0" aria-valuemax="100" style="width:<?php echo $pro_width; ?>%;background-color:<?php echo $colorCode; ?>;">
                                <?php echo $pro_msg; ?>
                                    </div>
                                </div>
                                <label class="status-sval"><?php echo $status_title_val; ?></label>
                                <ul class="indecate">
                                    <li><p>Time is available.</p></li>
                                    <li><p>Time is over.</p></li>
                                </ul>
                            <?php } ?>
                            <?php
                        }
                    }
                    ?>													        
</div>

</div>

<div class="col-lg-4 col-md-4 col-sm-4">
<div class="panel panel-default contact_info_tab">

    <!-- /.panel-heading -->
    <div class="panel-body">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#contact_<?php echo $woData->woId; ?>">Contact Information</a>
            </li>
            <li class=""><a data-toggle="tab" href="#detail_<?php echo $woData->woId; ?>">Details</a>
            </li>																			
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div id="contact_<?php echo $woData->woId; ?>" class="tab-pane fade active in">
                <p><span class="request_span">Requested By :</span>    <span><?php echo stripslashes($woData->firstName) . ' ' . stripslashes($woData->lastName); ?></span></p>
                <p><span class="request_span">Suite/Location :</span>    <span><?php echo stripslashes($woData->tenant_suite); ?></span></p>
                <p><span class="request_span">Email :</span>    <span><?php echo $woData->email; ?></span></p>
                <p><span class="request_span">Phone Number :</span>    <span><?php echo $woData->phoneNumber; ?></span></p>
            </div>


            <div id="detail_<?php echo $woData->woId; ?>" class="tab-pane fade">
                <p><span class="request_span">Email To :</span>    <span>
                                    <?php echo $gp_names; ?>
                    </span></p>
                <p><span class="request_span">Priority :</span> <span><?php echo $woData->priorityName; ?></span></p>
                                    <?php
                                    $fileModel = new Model_WoFiles();
                                    $fileList = $fileModel->getWoFilesByWoId($woData->woId);
                                    if ($fileList) {
                                        ?>
                    <p><span class="request_span">Attachment :</span>
                    <ul>
                                        <?php foreach ($fileList as $fl) { ?>
                            <li>
                                <span><a href="<?php echo BASEURL . 'public/work_order/' . $fl['file_name']; ?>" target="_blank"><?php echo $fl['file_title']; ?></a></span>
                            </li>		
<?php } ?>
                    </ul> 
                    </p>
                            <?php } ?>
                            <?php
                            $whlModel = new Model_WoHistoryLog();
                            $whlList = $whlModel->getWoHistoryLog($woData->woId);
                            if ($whlList) {
                                ?>
                    <p>
                        <span class="request_history_title" id="show_hist_<?php echo $woData->woId; ?>"><a href="javascript:void(0)" onclick="showCatLog('<?php echo $woData->woId; ?>')"> Show Work Order History Log </a></span>
                        <span class="request_history_title" style="display:none" id="hide_hist_<?php echo $woData->woId; ?>"><a href="javascript:void(0)" onclick="hideCatLog('<?php echo $woData->woId; ?>')"> Hide Work Order History Log </a></span>
                    </p>
                    <div id="catlog_<?php echo $woData->woId; ?>" style="display:none">
                        <div class="cat_log_history">
                            <table class="history_log_table">
                                <tr>
                                    <th>Log Type</th>
                                    <th>User</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Changes</th>
                                </tr>
                        <?php foreach ($whlList as $whl) {
                            if ($whl->log_type == 'status' || $whl->log_type == 'category') {
                                ?>
                                <tr>
                                    <td><?php echo ucfirst($whl->log_type); ?></td>
                                    <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                    <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                    <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                    <td>
                                        <?php
                                        if ($whl->log_type == 'category')
                                            echo $cat_array[$whl->current_value] . ' -> ' . $cat_array[$whl->change_value];
                                        else
                                            echo $status_array[$whl->current_value] . ' -> ' . $status_array[$whl->change_value];
                                        ?>
                                    </td>
                                </tr>																										
                            <?php } else if ($whl->log_type == 'Description of Work') { ?>

                                <tr>
                                    <td><?php echo ucfirst($whl->log_type); ?></td>
                                    <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                    <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                    <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                    <td>
                                        <?php
                                        if ($whl->current_value != '') {
                                            $current_value_histoy = json_decode($whl->current_value);
                                            $change_value_history = json_decode($whl->change_value);
                                            ?>
                                            <input type="hidden" id="current_value_<?php echo $whl->whId; ?>" value="<?php echo addslashes($current_value_histoy->description); ?>">
                                            <input type="hidden" id="change_value_<?php echo $whl->whId; ?>" value="<?php echo addslashes($change_value_history->description); ?>">
                                    <?php
                                } else {
                                    $change_value_history = json_decode($whl->change_value);
                                    ?>

                                        <input type="hidden" id="current_value_<?php echo $whl->whId; ?>" value="null">
                                        <input type="hidden" id="change_value_<?php echo $whl->whId; ?>" value="<?php echo addslashes($change_value_history->description); ?>">
<?php } ?>
                                <?php
                                if ($whl->current_value != '') {
                                    echo HiSTORY_TEXT_EDIT;
                                } else {
                                    echo HiSTORY_NEW_TEXT_ADDED;
                                }
                                ?> <a href="javascript:void(0)" onclick='showHistoryDescription(<?php echo $whl->whId; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i> </a>
                                    <a href="#add_new_description_div" id="add_new_description_div_href" class="modalbox" style="display:none;">&nbsp;</a>

                                </td>
                            </tr>

                        <?php } else if ($whl->log_type == 'Labor') { ?>

                            <tr>
                                <td><?php echo ucfirst($whl->log_type); ?></td>
                                <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                <?php $current_value_histoy = ($whl->current_value != '') ? $whl->current_value : 'null' ?>
                                <td><?php
                                    if ($whl->current_value != '' && $whl->change_value != '') {
                                        echo HiSTORY_TEXT_EDIT;
                                    } else if ($whl->change_value == '') {
                                        echo HiSTORY_TEXT_DLETED;
                                    } else {
                                        echo HiSTORY_NEW_TEXT_ADDED;
                                    } $labordecode = json_decode($whl->change_value);
                                    ?> <a href="javascript:void(0)" onclick='historyoflabor(<?php echo $woData->building; ?>, <?php echo $whl->whId; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i></a>
                                    <a href="#add_new_labor_div" id="add_new_labor_div_href" class="modalbox" style="display:none;">&nbsp;</a>

                                </td>
                            </tr><?php } else if ($whl->log_type == 'building services') { ?>
                            <tr>
                                <td><?php echo ucfirst($whl->log_type); ?></td>
                                <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                    <?php $current_value_histoy = ($whl->current_value != '') ? $whl->current_value : 'null' ?>
                                <td><?php
                                    if ($whl->current_value != '' && $whl->change_value != '') {
                                        echo HiSTORY_TEXT_EDIT;
                                    } else if ($whl->change_value == '') {
                                        echo HiSTORY_TEXT_DLETED;
                                    } else {
                                        echo HiSTORY_NEW_TEXT_ADDED;
                                    } $buildingdecode = json_decode($whl->change_value);
                                    ?> <a href="javascript:void(0)" onclick='historyofBuilding(<?php echo $woData->building; ?>, <?php echo $whl->whId; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i> </a>
                                    <a href="#add_history_building_div" id="add_history_building_div_href" class="modalbox" style="display:none;">&nbsp;</a>

                                </td>
                            </tr>
                                <?php } else if ($whl->log_type == 'materials') { ?>
                            <tr>
                                <td><?php echo ucfirst($whl->log_type); ?></td>
                                <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                    <?php $current_value_histoy = ($whl->current_value != '') ? $whl->current_value : 'null' ?>
                                <td><?php
    if ($whl->current_value != '' && $whl->change_value != '') {
        echo HiSTORY_TEXT_EDIT;
    } else if ($whl->change_value == '') {
        echo HiSTORY_TEXT_DLETED;
    } else {
        echo HiSTORY_NEW_TEXT_ADDED;
    } $materialdecode = json_decode($whl->change_value);
    ?> <a href="javascript:void(0)" onclick='historyofMaterial(<?php echo $woData->building; ?>, <?php echo $whl->whId; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i></a>
                                    <a href="#add_history_material_div" id="add_history_material_div_href" class="modalbox" style="display:none;">&nbsp;</a>

                                </td>
                            </tr>
            <?php } else if ($whl->log_type == 'outside service') { ?>  
                            <tr>
                                <td><?php echo ucfirst($whl->log_type); ?></td>
                                <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                <?php $current_value_histoy = ($whl->current_value != '') ? $whl->current_value : 'null' ?>
                                                                                                                        <td><?php
                                if ($whl->current_value != '' && $whl->change_value != '') {
                                    echo HiSTORY_TEXT_EDIT;
                                } else if ($whl->change_value == '') {
                                    echo HiSTORY_TEXT_DLETED;
                                } else {
                                    echo HiSTORY_NEW_TEXT_ADDED;
                                } $outsidedecode = json_decode($whl->change_value);
                                ?> <a href="javascript:void(0)" onclick='historyofoutside(<?php echo $woData->building; ?>, <?php echo $whl->whId; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i></a>
                                        <a href="#add_history_outside_div" id="add_history_outside_div_href" class="modalbox" style="display:none;">&nbsp;</a>

                                    </td>
                                </tr>
                            <?php } else if ($whl->log_type == 'notes') { ?>   
                                <tr>
                                    <td><?php echo ucfirst($whl->log_type); ?></td>
                                    <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                    <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                    <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                            <?php $current_value_histoy = ($whl->current_value != '') ? $whl->current_value : 'null' ?>
                                    <td><?php
                            if ($whl->current_value != '' && $whl->change_value != '') {
                            echo HiSTORY_TEXT_EDIT;
                            } else if ($whl->change_value == '') {
                            echo HiSTORY_TEXT_DLETED;
                            } else {
                            echo HiSTORY_NEW_TEXT_ADDED;
                            } $notesdecode = json_decode($whl->change_value);
                            ?> <a href="javascript:void(0)" onclick='historyofnotes(<?php echo $woData->building; ?>, <?php echo $whl->whId; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i> </a>
                                        <a href="#add_history_notes_div" id="add_history_notes_div_href" class="modalbox" style="display:none;">&nbsp;</a>

                                    </td>
                                </tr>

                            <?php } else if ($whl->log_type == 'Attachment') { ?>   
                                <tr>
                                    <td><?php echo ucfirst($whl->log_type); ?></td>
                                    <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                    <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                    <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                                    <td><?php
                                if ($whl->current_value != '') {
                                    echo "Attachment Deleted";
                                } else {
                                    echo "Attachment Added";
                                }
                                ?> </td>
                                </tr>

                            <?php } else if ($whl->log_type == 'work order') { ?>
                                <tr>
                                    <td><?php echo ucfirst($whl->log_type); ?></td>
                                    <td><?php echo $whl->firstName . ' ' . $whl->lastName; ?></td>
                                    <td><?php echo substr($whl->created_at, 0, 10); ?></td>
                                    <td><?php echo date_format(date_create($whl->created_at), 'g:i A'); ?></td>
                            <?php /* <td>---</td> */ ?>
                                                                                                                        <td><?php
                                $current_value_histoy = ($whl->current_value != '') ? $whl->current_value : 'null';
                                if ($whl->current_value == '') {
                                    echo HiSTORY_NEW_TEXT_ADDED;
                                } else {
                                    echo HiSTORY_TEXT_EDIT;
                                }
                                ?>
                                    <a href="javascript:void(0)" onclick='hostoryofworkorder(<?php echo $woData->building; ?>,<?php echo $woData->woId; ?>, <?php echo $current_value_histoy; ?>, <?php echo $whl->change_value; ?>)' class="vend_tooltip"><i class="fa fa-file-text-o textFile"></i>

                                    </a>

                                    <a href="#add_histroy_workorder_div" id="add_histroy_workorder_div_href" class="modalbox" style="display:none;">&nbsp;</a>	
                                    </td>
                                    </tr>
                                    <?php }
                                    }
                                    ?>
                                    </table>	
                                    </div>
                                    </div> 
                                    <?php } ?>
                                    </div>


                                    </div>
                                    </div>
                                    <!-- /.panel-body -->
                                    </div>
                                    </div>
                                    </div>
                                    </td>
                                    <td style="background-color:#<?php echo $building_color[$wl->building] ?>">&nbsp;</td>
                                    </tr>	
<?php
                }
            }
        } else {
            ?>
                                                    <tr>
                                                        <td colspan="10">No work order created.</td>
                                                    </tr>
        <?php } ?>
                                            </tbody>
                                            <input type="hidden" name="count" id="count" value="<?php echo $this->count; ?>" >
                                        </table>
        
                                   

                                
                                <!-- /.table-responsive --> 
                                <!--Edit Work Order Start-->
                                
                                <!--Edit Work Order End-->
                           
                       
                            
              
      
<?php } } ?>

<script>

    var hash = window.location.hash;
    if (hash != '') {
        hash = hash.replace('#', '');
        showWorkOrder(hash);
    }

    function showHistoryDescription(whId) {
        var current_value_description = $('#current_value_' + whId).val();
        current_value_description = stripslashes(current_value_description);
        var change_value_description = $('#change_value_' + whId).val();
        change_value_description = stripslashes(change_value_description);
        if (current_value_description != 'null' && current_value_description != '') {
            $('#work_current_description').html(current_value_description);
        } else {
            var none = '<?php echo HiSTORY_NONE; ?>';
            $('#work_current_description').html("<p style='text-align:center;'>None</p>");
        }
        $('#work_change_description').html(change_value_description);
        $('#add_new_description_div_href').trigger('click');
    }

    function stripslashes(str) {
        str = str.replace(/\\/g, '')
        return str;
    }
    
    </script>


