	<div class="col-md-11 gutter">
	
					  <div class="form_group">
						 <div class="workorder_error" id="requested_error"></div>
							<label>Request By</label>
						 
							<!-- Split button -->
							<div class="btn-group work_update_select" id="show_tenant_user">
<select name="create_user" id="create_user" class="all_select">
	<option value="">-------Select------</option>	
	<?php if($this->tnuserData!=''){
		 
		   foreach($this->tnuserData as $tud){?>
			   <option value="<?php echo $tud->uid?>"><?php echo stripslashes($tud->lastName).', '.stripslashes($tud->firstName);?></option>
			<?php }?>   
	<?php }?>	
</select>
<input type="hidden" name="suite_location" id="suite_location" value="<?php echo $this->tnData->suite?>"/>



	</div>
						</div>
						</div>
						<div class="col-md-1 requestadimg"><a href="javascript:void(0)" class="vend_tooltip"  onclick="showAddNew()"><img src="<?php echo BASEURL; ?>public/images/user-setting.png" height="30">
						<div class="vend_tooltip_content">Add New User</div>
						</a></div>
						<div class="clearfix"></div>