<!-- Core CSS - Include with every page -->
<?php

echo $this->headScript()->appendFile($this->baseUrl() . '/public/jquery/jquery.multiple.select.js');
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/multiple-select.css');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/dashworkorder.js');
$dline_access = $this->acessHelper->checkAccess($this->roleId,$this->dline_location);
$ddetail_access = $this->acessHelper->checkAccess($this->roleId,$this->ddetail_location);
$createnew_access = $this->acessHelper->checkAccess($this->roleId,$this->createnew_location);
$closewo_access = $this->acessHelper->checkAccess($this->roleId,$this->closewo_location);

if($this->roleId !='1' && ($dline_access->is_access==0 || $ddetail_access->is_access==0)){
       if($this->custID!=null && $this->custID && $this->companyListing!='' && $this->companyListing!=false){
				  
				   $order = $this->order;
				   $dir = $this->dir;
				   $wdir = 'ASC';
				   $bdir = 'ASC';
				   $tdir = 'ASC';
				   $sdir = 'ASC';
				   $cdir = 'ASC';
				   $pdir = 'ASC';
				   $stdir = 'ASC';
				   $ddir = 'ASC';
				   $tudir ='ASC';
				   if($order=='wo_number')
					  $wdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='buildingName')
					  $bdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='tenantName')
					  $tdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='suite_location')
					  $sdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='categoryName')
					  $cdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='priorityName')
					  $pdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='wo_status')
					  $stdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='firstName')
					  $tudir = ($dir=='ASC')?'DESC':'ASC';   
				   else
					  $ddir = ($dir=='ASC')?'DESC':'ASC';
				        $ssModel = new Model_ScheduleStatus();
								$status_list = $ssModel->getScheduleStatus();
								$status_array= array();
								foreach($status_list as $sl){
									if($sl['ssID']!=8)
									$status_array[$sl['ssID']] = $sl['title'];
								}
								
		         $color_code = array('00FFFF','FF0000','FF00FF','800000','008000','800080','808000','0000FF','00FF00','000080','FFFF00','808000','008080','FFA500');						
		         $building_color = array();
		         $veiw_type = $this->view_type;
		  ?>
   
    <!--Body middle Part button start-->
    <div class="row">
		<?php $msg = new Zend_Session_Namespace('message');?>
		<div class="workorder_error" id="message">
					  <?php 
						  echo $msg->error_message;
						  $msg->error_message = '';
					  ?>
				  </div>
				  <div class="workorder_success" id="message">
				       <?php 
						  echo $msg->success_message;
						  $msg->success_message = '';
					  ?>
				  </div>
    </div>
    <div id="fdw">
		<div class="tabmenu my_tabmenu">
        <ul>
			<li style="background-color:#<?php echo $color_code[0]?>"><a href="<?php echo $this->baseUrl().'/dashboard/workorder/'; ?>" <?php if($this->select_build_id=='') echo 'class="resp-tab-active my_resp-tab-active"';?>>Work Order of All Buildings</a></li>
		<?php  
					$j = 1;
					foreach($this->companyListing as $cb){ 
						if(isset($color_code[$j])) $building_color[$cb['build_id']] = $color_code[$j];
						?>
					<li style="background-color:#<?php echo $color_code[$j]?>"><a href="<?php echo $this->baseUrl().'/dashboard/workorder/bid/'.$cb['build_id']; ?>" <?php if($cb['build_id']==$this->select_build_id) echo 'class="resp-tab-active my_resp-tab-active"';?>><?php echo $cb['buildingName']; ?></a></li>
		
				<?php $j++; } ?>         
        
        </ul>
        </div>		
	  </div>
    <div id="my_search_box" style="margin-top: -239.5px; display: block; height: 479px; right: -462px; top: 50%;">
		
      <div id="search_show_form">
                  <span id="my_span" style="margin-top:0px; top:0;"><a href="javascript:void(0)" id="show_hide"><img src="<?php echo BASEURL.'public/images/search_img.png';?>"></a></span>
		<form name="search_form" id="search_form" action="<?php echo $this->url();?>" method="post">  
		<div id="search_field">
			
			 <div class="serach_row">
			     <div class="col-md-12 col-sm-12 col-xs-12 pad searchform_leftpart"><label>Work Order</label> <input class="inputbox" type="text" name="search_wo" id="search_wo" placeholder="Enter work order id" value="<?php echo (isset($_REQUEST['search_wo']))?$_REQUEST['search_wo']:'';?>"></div>
			     <div class="col-md-12 col-sm-12 col-xs-12 pad searchform_rightpart"><label>Category</label> <input class="inputbox" type="text" name="category_name" id="category_name" placeholder="Enter category" value="<?php echo (isset($_REQUEST['category_name']))?$_REQUEST['category_name']:'';?>"></div>
            </div>
            <div class="serach_row">     
			     <div class="col-md-12 col-sm-12 col-xs-12 pad searchform_leftpart"><label>Company Name</label> <input class="inputbox" type="text" name="tenant_name" id="tenant_name" placeholder="Enter company name" value="<?php echo (isset($_REQUEST['tenant_name']))?$_REQUEST['tenant_name']:'';?>"></div>
			     <div class="col-md-12 col-sm-12 col-xs-12 pad searchform_rightpart"> <label>Date Range</label>
			      <span>From:</span><input type="text" name="from_date" id="from_date" placeholder="mm/dd/yyyy" value="<?php echo (isset($_REQUEST['from_date']))?$_REQUEST['from_date']:'';?>" readonly/>
			      <span>To:</span><input type="text" name="to_date" id="to_date" placeholder="mm/dd/yyyy" value="<?php echo (isset($_REQUEST['to_date']))?$_REQUEST['to_date']:'';?>" readonly/></div>
               </div>
               
               <div class="serach_row">
			      <div class="col-md-12 col-sm-12 col-xs-12 pad searchform_leftpart"> <label>Status</label>
			        <div class="min_select_searh1" style="text-align:left; "><label></label>
                       <select id="ms2" multiple="multiple">
					   <?php foreach($status_array as $key=>$value){ ?>
                       <option value="<?php echo $key; ?>" <?php if(isset($this->statusCookieDetails)&&(in_array($key,$this->statusCookieDetails))) echo 'selected'; ?>><?php echo $value; ?></option>
                       <?php } ?>
                       </select>
					    
					   </div>
					   <span class="my_se_icon" >
						<a href="javascript:void(0)" name="submit" onclick="showStatusPop()"><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a></span> 
					  
					</div>
                    
                   </div>
				   <div class="clearfix" >&nbsp;<input type="hidden" name="submitform"> </div>
                   <div class="serach_row">
                    <div class="col-md-12 col-sm-12 col-xs-12 searchform_leftpart">
                           <input class="search_btn" type="submit" name="search" value="Search"/> 
                           <input class="search_btn" type="button" name="reset_search" value="Reset Search" onclick="cancelShowStatus()"/>
                    </div>
                   </div>
				  	
			
		</div>
		
       
        </form>
      </div>
    </div>
    <?php /*<div class="row">
		<div class="creat_work_order_btn">
		    <a href="<?php echo BASEURL.'dashboard/createworkorder'?>">New Order</a> 
		</div>
	 </div>	*/?>
	 
		   <form name="search_mini_form" id="search_mini_form" action="<?php echo $this->url();?>" method="post">
		   <div class="row">
      <div class="middle_btn my_middle_btn">
				<ul>
				  <li>
					   <?php 
					    $param='/bid/';
					    $param_val = ($this->select_build_id!='')?$this->select_build_id:'';
					    $param_build = $param.$param_val;
					    if($ddetail_access->is_access==0){
							   if($veiw_type == 'detail'){
									
									$url = BASEURL.'dashboard/workorder';
									?>
									<a href="<?php echo $url.''.$param_build;?>">Change to line view</a>
									<?php
								 }else
								 {
									 $url = BASEURL.'dashboard/workorder/view_type/detail';
									 ?>
									<a href="<?php echo $url.''.$param_build;?>">Change to detail view</a>
									<?php
									 }
						 }
							?>
					  
					  
					  </li>
				  
				 
				  <li>
                   <span class="ser_sp">Search</span>
					<input type="text" name="search_wo" id="search_wo" placeholder="Work Order Id" value="<?php echo (isset($_REQUEST['search_wo']))?$_REQUEST['search_wo']:'';?>"> <span class="my_se_icon">
						<a href="javascript:void(0)" name="submit" onclick="showStatus()"><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a></span> 
				  </li>
				  
				  <li>
				     
					   <div class="min_select_searh"><label></label>
                       <select id="ms" multiple="multiple">
					   <?php foreach($status_array as $key=>$value){ ?>
                       <option value="<?php echo $key; ?>" <?php if(isset($this->statusCookieDetails)&&(in_array($key,$this->statusCookieDetails))) echo 'selected'; ?>><?php echo $value; ?></option>
                       <?php } ?>
                       </select>
					   </div>
					 <span class="my_se_icon">
						<a href="javascript:void(0)" name="submit" onclick="showStatus()"><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a></span> 
                  
				  <?php /* ?>
					  <select name="search_status"  onchange="showStatus(this.value)" class="selectbox awo-sselect">
							  <option value="">Select</option>
							   <?php foreach($status_array as $key=>$value){?>
									<option value="<?php echo $key;?>" <?php if(isset($_REQUEST['search_status']) && ($_REQUEST['search_status']==$key)) echo 'selected'; ?>><?php echo $value;?></option>
								<?php }?>
					   </select>
					   <?php  */ ?>
				  </li>
				  <?php if($createnew_access->is_write==1){?>
					  <li><a href="<?php echo BASEURL.'dashboard/createworkorder'?>">New Order</a></li>
				  <?php }?>	  
				 
				</ul>
				</div>
    </div>  <?php   /*  
	<div class="row">
      <div class="middle_btn my_middle_btn" >
				<ul class="col-lg-12"> 				
				<?php foreach($status_array as $key=>$value){ ?>
				<li class="statuspchkbox" style="margin-right:5px!important;">
					<ul <?php if(isset($this->statusCookieDetails)&&(in_array($key,$this->statusCookieDetails))) echo 'class="spchkboxul"'; ?>><li>				
						<input type="checkbox" name="search_chkboxstatus[]" style="width:auto!important" class="uncheckstatus" value="<?php echo $key; ?>" <?php if(isset($this->statusCookieDetails)&&(in_array($key,$this->statusCookieDetails))) echo 'checked'; ?> >
					</li>
					<li><?php echo $value ; ?></li>
					</ul>
				</li> 
	<?php } ?>
				<li><a href="javascript:void(0)" name="submit" onclick="showStatus()">Ok</a></li>
				<li><a href="javascript:void(0)" name="submit2" onclick="cancelShowStatus()">Clear</a></li>
				
	 </ul>
	 <div>
	 <div>   */ ?>
	 <input type="hidden" name="submitform">
          </form>
      
	
    <!--Body middle Part button end--> 
    
    <!--Body middle Part tabbed start-->
    <div class="row">
      <div id="parentHorizontalTab" class="datatabed">
      
     <!-- <div id="fdw">
		<div class="tabmenu">
		 <ul>
			<li class="current"><a href="#">home</a></li>
			<li><a href="#">about</a></li>
			<li><a href="#">services</a></li>
			<li><a href="#">portfolio</a></li>
			<li><a href="#">blog</a></li>
			<li><a href="#">contact</a></li>
		</ul>
		</div>		
	  </div>-->
      
      
        <?php 
			if($veiw_type == 'line'){
			    $url = BASEURL.'dashboard/workorder';
		     }else
		     {
				 $url = BASEURL.'dashboard/workorder/view_type/detail';
			 }
			?>
        <div class="resp-tabs-container hor_1">
          <div>
            <div class="row">
              <div class="panel-body padd_order">
                <div class="table-responsive">
                  <div role="grid" class="dataTables_wrapper form-inline" id="dataTables-example_wrapper">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer">
                      <thead>
                        <tr>
						  	
                          <th><a href="<?php echo $url.'/order/created_at/dir/'.$ddir?>" 
                          class="<?php if($order=='created_at') echo $ddir; else echo 'sorting';?>">Date Received</a></th>
                          <th>Time Received</th>
                          <th><a href="<?php echo $url.'/order/wo_number/dir/'.$wdir?>" class="<?php if($order=='wo_number') echo $wdir; else echo 'sorting'; ?>">Work Order#</a></th>
                          <th><a href="<?php echo $url.'/order/wo_status/dir/'.$stdir?>"
                           class="<?php if($order=='wo_status') echo $stdir; else echo 'sorting';?>">Current Status</a></th>
                          <th><a href="<?php echo $url.'/order/categoryName/dir/'.$cdir?>"
                               class="<?php if($order=='categoryName') echo $cdir; else echo 'sorting';?>">Category</a></th>
                          <th><a href="<?php echo $url.'/order/tenantName/dir/'.$tdir?>"
                            class="<?php if($order=='tenantName') echo $tdir; else echo 'sorting';?>">Company</a></th>
                          <th>Work Request</th>
                          <?php /*<th>Contact Information</th>*/?>
                          <th><a href="<?php echo $url.'/order/buildingName/dir/'.$bdir?>"
                           class="<?php if($order=='buildingName') echo $bdir; else echo 'sorting';?>">Building Name</a></th>
                          <th>&nbsp;</th>
                        </tr>
                      </thead>
                      <tbody>
						    <?php 
						    //echo date("Y-m-d h:i:s");
						    if($this->wolist){
								$catModel = new Model_Category();
							    	
							 $psModel = new Model_Schedule();
							 $wssModel = new Model_WoScheduleStatus();
							 /**********Get notes list ***********/ 
							  $noteModel = new Model_Notes();
							  $noteList = $noteModel->getNotes();
							  $timezone_Model	=	new Model_TimeZone();
							  $build_model= new Model_Building();
						    foreach($this->wolist as $wl){
								$tz_build_data = $build_model->getbuildingbyid($wl->building);
								//echo "<pre>";
								//print_r($wl);
								//print_r($tz_build_data[0]['timezone']);
							  if(isset($tz_build_data[0]['timezone']) && $tz_build_data[0]['timezone']!=0){								  
								$timezone_data	=	$timezone_Model->getTimeZone($tz_build_data[0]['timezone']);
								$timezone=$timezone_data[0]['time_value'];			
								if(isset($timezone)) date_default_timezone_set($timezone);								
								//date_default_timezone_get();								
							  }

								$schedule = $psModel->getWoSchedule($wl->prioritySchedule,$wl->wo_status);
								 $currTime = date("Y-m-d h:i:s");								 
								$lastTime = '';	
								if($wl->wo_status=='1'){
									$lastTime = $wl->date_requested.' '.$wl->time_requested;
								}else if($wl->updated_date!='0000-00-00 00:00:00'){
									$lastTime =$wl->updated_date;
								}else
									$lastTime =$wl->created_date;
								
								$lastTime=date("Y-m-d h:i:s",strtotime($lastTime));
								$timeDiff = strtotime($currTime) - strtotime($lastTime);		
								 
								$time = $schedule[0]['Time'];				
								$reminderStatus = $wssModel->getReminderStatus($timeDiff,$time,$schedule[0]['length']);
								//echo "<br>date_default_timezone_get->".date_default_timezone_get();
								//echo "<br>currTime".$currTime;
								//echo "<br>lastTime".$lastTime;
								 
								 ?> 
								<tr>
									
								  <td><?php echo date("m/d/Y",strtotime($wl->date_requested))?></td>
								  <td><?php echo $wl->time_requested?></td>
								  <td> 
									  <?php if($closewo_access->is_access==0){?>
									     <a href="<?php echo BASEURL.'/complete/workorder/bid/'.$wl->building.'/wnum/'.$wl->wo_number;?>"><?php echo $wl->wo_number?></a>
									   <?php }else{?>
										   <?php echo $wl->wo_number?>
									   <?php }?>	     
								     <?php if ($reminderStatus && ($wl->wo_status!='6' && $wl->wo_status!='7')) echo '&nbsp;&nbsp;<a class="alert tooltip">&nbsp;<span>
        Time Over
    </span></a>';?>
								  </td>
								  <td><?php echo $status_array[$wl->wo_status];?></td>
								  <td><?php echo $wl->categoryName?></td>
								  <td><?php echo $wl->tenantName?></td>
								  <td>	 
									  
									  <?php 
									  $descText = strip_tags($wl->work_order_request);
			                          $descText = str_replace("&nbsp;", ' ', $descText);
									  echo substr($descText,0,40); 
									   echo (substr($descText,50))?'...':'';?>
								  </td>
								  <?php /*<td><?php echo $wl->tenantContact?></td>*/?>
								  <td><?php echo $wl->buildingName?></td>
								  <td style="background-color:#<?php echo $building_color[$wl->building]?>">
								  <?php if($veiw_type == 'line'){?>
								  <a href="javascript:void(0)" onclick="showWorkOrder('<?php echo $wl->woId?>')">
								  <i id="plus_<?php echo $wl->woId?>" class="fa fa-plus blackfont_color plus_min_icon"></i></a>
								   <?php }else echo '&nbsp;';?>
								   
								   </td>
								</tr>
								<?php if($veiw_type == 'line'){?>
								<tr id="workrequest_<?php echo $wl->woId?>" style="display:none;" class="tr-order">
									<td colspan="9" id="order_content_<?php echo $wl->woId?>" class="order-detail"></td>
								</tr>
								<?php }else{


									$catlist = $catModel->getBuildingCategoryList($wl->building);
									$cat_array= array();
									   foreach($catlist as $cat)
										 $cat_array[$cat['cat_id']]=$cat['categoryName'];
									?>
								<tr>
									<td colspan="8">
									    <div class="order-details">
											<?php
											    $woModel = new Model_WorkOrder();
												$wodetail = $woModel->getWorkOrderInfo($wl->woId);
												$woData = $wodetail[0];										
												
										        $ssModel = new Model_ScheduleStatus();
												$status_list = $ssModel->getScheduleStatus();
												$status_array= array();
												foreach($status_list as $sl){
												   $status_array[$sl['ssID']] = $sl['title'];
												}
												$gplist = array();
												$gp_names = '';
												if($woData->send_email!=''){
													$egModel = new Model_EmailGroup();
													$gplist = $egModel->getGroupIds($woData->send_email);
													foreach($gplist as $gp){
														$gp_names .= ($gp_names!='')?',':'';
														$gp_names .= $gp['group_name'];
													}
												}
												
											   $wpModel = new Model_WorkOrderUpdate();
											   $cwpData = $wpModel->getCurrentWoUpdate($woData->woId);
											   $work_status = ($cwpData)?$cwpData[0]['wo_status']:0;
											   $internalNote = ($cwpData)?$cwpData[0]['internal_note']:'';
											   $pscheduleModel = new Model_Schedule();
											   
											   $schedule_list = $pscheduleModel->getSchedule($woData->pid);
											   $schedule_array = array();
											   if($schedule_list){
												   foreach($schedule_list as $sl){
													   $schedule_array[] = $sl['start_status'];
												   }
											   }
											   //var_dump($schedule_list);
											   
											   $lenModel = new Model_Length();
											   $lenlist = $lenModel->getLength();
											   
											?>   												 
													<div class="col-lg-8 col-md-8 col-sm-8">
														<?php if($ddetail_access->is_write==1) {?>
														<?php if($work_status =='1'){?>
															<form name="wcassign-form" id="wcassign-form-<?php echo $woData->woId;?>">
															    <span id="assign_error_<?php echo $woData->woId;?>" class="error"></span>
																<div id="assign_category" class="my_agn_div">
																	 <label>Assign new category</label>
																	 <input type="hidden" name="curr_cat_<?php echo $woData->woId;?>" id="curr_cat_<?php echo $woData->woId;?>" value="<?php echo $woData->category; ?>"/>
																	 <select name="assign_category_<?php echo $woData->woId;?>" id="assign_category_<?php echo $woData->woId;?>" class="my_assign_div">
																		 <option value="">Select Category</option>
																		 <?php 
																			if($catlist){
																				foreach($catlist as $cat){
																					echo '<option value="'.$cat['cat_id'].'"';
																					echo  ($cat['cat_id']==$woData->category)?'selected':'';
																					echo '>'.$cat['categoryName'].'</option>';
																			   }	 	
																		   }
																		 ?>
																	 </select>
																	 <input type="button" name="assign_button" class="form_btn" value="Assign Category" onClick="reassignCategory('<?php echo $woData->woId;?>');"/>
																</div>
													        </form>	
													    <?php }?>
													  <form name="wo-request-form" id="wo-request-form" action="<?php echo BASEURL.'/dashboard/updateorder/'?>" method="post">
														<div class="form_group">
														  <div class="lbl_div">
															<label>Work Request</label>
														  </div>
														  <div class="form_field_div my_lbl_div">                
															<?php
																  echo $woData->work_order_request;
															?>
															
															<input type="hidden" name="work_order_id_<?php echo $woData->woId;?>" value="<?php echo $woData->woId;?>"/>
															<input type="hidden" name="priority" id="priority_<?php echo $woData->woId;?>" value="<?php echo $woData->pid;?>"/>
															<input type="hidden" name="exist_schedule" id="exist_schedule_<?php echo $woData->woId;?>" value="<?php echo implode(',',$schedule_array);?>"/>
															<input type="hidden" name="current_wstatus_<?php echo $woData->woId;?>" id="current_wstatus_<?php echo $woData->woId;?>" value="<?php echo $work_status;?>"/>
														  </div>
														</div>
														<?php if($work_status!='7'){ ?>
														<div class="form_group">
														  <div class="lbl_div">
															<label>Update Status To</label>
														  </div>
														  <!-- Split button -->
														  <div class="form_field_div my_work_form_field">
															<div class="btn-group work_update_select">
																<div id="wstatus_error_<?php echo $woData->woId;?>" class="wst_error"></div>
																<select name="order_status_<?php echo $woData->woId;?>" id="order_status_<?php echo $woData->woId;?>" class="all_select" onChange="javascript:checkSchedule('workorder','<?php echo $woData->woId;?>');">
																	   <?php foreach($status_array as $key=>$value){ ?>
																		   <option value="<?php echo $key;?>" <?php echo ($work_status==$key)?'selected':'';?>><?php echo $value;?></option>
																		 <?php }?>  
																</select>																                  
															</div>
															<div id="time_length_div_<?php echo $woData->woId;?>" class="time_len_my_div" style="display:none">
															     <div id="schedule_error" class="sch_error"></div>
																 <div id="time_div" class="time_t_div">
																	 <label>Time <span class="required">*</span></label>
																	 <input type="text" name="Time" id="Time_<?php echo $woData->woId;?>" maxlength="2" onkeypress="return isNumberKey(event)"/>
																 </div>
																 <div id="length_div" class="len_div">
																	 <label>Length <span class="required">*</span></label>
																	  <select name="length" id="length_<?php echo $woData->woId;?>">
																		  <?php foreach($lenlist as $ll){?>
																		      <option value="<?php echo $ll['lID']?>"><?php echo $ll['title']?></option>
																		  <?php }?>
																	  </select>
																 </div>
															</div>
														  </div>
														</div>
														 <div class="form_group">
														  <div class="lbl_div">
															<label>Note</label>
														  </div>
														  <!-- Split button -->
														  <div class="form_field_div my_text_area">															  
															   <?php /*<textarea type="text" rows="5" cols="5" name="internal_note_<?php echo $woData->woId;?>" id="internal_note_<?php echo $woData->woId;?>" class="testarea"></textarea> */?>
																	  <select name="internal_note_<?php echo $woData->woId;?>" id="internal_note_<?php echo $woData->woId;?>">
																		  <option value="">Select Note</option>
																		  <?php 
																			   if($noteList){
																				   foreach($noteList as $nl){
																					   if($nl['status']=='1'){
																						   echo '<option value="'.$nl['nid'].'"';
																						   if($internalNote==$nl['nid'])
																							echo 'selected="selected"';
																						   echo '>'.$nl['notes'].'</option>';
																				      }
																				   }
																			   }
																		  ?>
																	  </select>
														  </div>
														</div>
														
														<div class="form_group"><input type="button" class="form_btn float_right" value="Update" onclick="updateWorkorder('<?php echo $woData->woId;?>')"></div>
														<?php } ?>
													  </form>
													  <?php }?>
													  <div id="progressbarnew">
														    <?php 
																$timezone_Model	=	new Model_TimeZone();
																$build_model= new Model_Building();
																$tz_build_data = $build_model->getbuildingbyid($wl->building);

																if(isset($tz_build_data[0]['timezone']) && $tz_build_data[0]['timezone']!=0){								  
																	$timezone_data	=	$timezone_Model->getTimeZone($tz_build_data[0]['timezone']);
																	$timezone=$timezone_data[0]['time_value'];			
																	date_default_timezone_set($timezone);								
																	//echo "date_default_timezone_get->".date_default_timezone_get();								
																	//$date = new DateTime(null, new DateTimeZone($timezone));
																}
																
																//echo "<pre>";
																//print_r($woData);
															
																$wsModel = new Model_WoScheduleStatus();
														          $wsList = $wsModel->getWoAllStatus($woData->woId);														          
														          //$currTime = time();
																    $timezone_Model	=	new Model_TimeZone();
																  												          
														          if($wsList){
																	  $i=0;
																	  $tot_width=0;
																	  $ws_status = '';
																	  $pro_prcentage=0;
																	  $pro_width = 0;
																	  $pro_msg = '';
																	  $colorCode='';
																	  $status_title_val='';
																	  foreach($wsList as $ws){
																		  //echo "<pre>";
																		  //print_r($work_status);
																		  if($ws->current_status == '1'){
																				 $lastTime ='';
																				if($work_status=='1'){
																					$lastTime = $woData->date_requested.' '.$woData->time_requested;
																				}else
																					$lastTime =$ws->created_at;
																				
																				$lastTime=date("Y-m-d h:i:s A",strtotime($lastTime));
																				$currTime=date("Y-m-d h:i:s A");
																									    
																				 $timeDiff =  abs(strtotime($currTime) - strtotime($lastTime));
																				 $calTime = $wsModel->getCalculateTime($ws->Time,$ws->length);
																				 $devide_num = number_format((float)($timeDiff/$calTime), 2, '.', '');
																				$pro_prcentage = $devide_num*100;
																				if($pro_prcentage>100)
																				 {
																					 $pro_width = 100;
																					 $colorCode='#f0ad4e';
																					 $pro_msg = ' Time Out';
																				 }else{
																					 $pro_width = $pro_prcentage;
																					 $colorCode='#5cb85c';
																					 //$pro_msg = $pro_prcentage.' % Time has been passed.';
																					 $pro_msg = $pro_prcentage.'%';
																				 }
/*
if($wl->buildingName=="Test building"){
echo "<br>date_default_timezone_get->".date_default_timezone_get();
echo "<br>currTime".$currTime;
echo "<br>lastTime".$lastTime;
echo "<br>pro_prcentage".$pro_prcentage;
}
*/
																				 
																				$status_title_val= $status_array[$ws->start_status] .' - '.$ws->Time. ' '.$ws->length_title; 
																			}																	 																		
																		  $ws_status .= ($ws_status!='')?'->':'';
																		  $ws_status .= $status_array[$ws->start_status];
														      
															        
														         }
														         echo '<span class="ch-status"><strong>Status:</strong> '.$ws_status.'</span>';
														         if($work_status!='6' && $work_status!='7'){
																 ?>
														         
                                                                 <div class="progress">
                                                                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
                                                                  aria-valuemin="0" aria-valuemax="100" style="width:<?php echo $pro_width;?>%;background-color:<?php echo $colorCode; ?>;">
                                                                    <?php echo $pro_msg;?>
                                                                  </div>
                                                                </div>
                                                                <label class="status-sval"><?php echo $status_title_val;?></label>
                                                                <ul class="indecate">
                                                                   <li><p>Time is available.</p></li>
                                                                   <li><p>Time is over.</p></li>
                                                                </ul>
																 <?php } ?>
														     <?php   
													          }
													        ?>													        
													  </div>
													 
													</div>
													
													<div class="col-lg-4 col-md-4 col-sm-4">
													<div class="panel panel-default contact_info_tab">
																	
																	<!-- /.panel-heading -->
																	<div class="panel-body">
																		<!-- Nav tabs -->
																		<ul class="nav nav-tabs">
																			<li class="active"><a data-toggle="tab" href="#contact_<?php echo $woData->woId;?>">Contact Information</a>
																			</li>
																			<li class=""><a data-toggle="tab" href="#detail_<?php echo $woData->woId;?>">Details</a>
																			</li>																			
																		</ul>

																		<!-- Tab panes -->
																		<div class="tab-content">
																			<div id="contact_<?php echo $woData->woId;?>" class="tab-pane fade active in">
																				<p><span class="request_span">Requested By :</span>    <span><?php echo $woData->firstName.' '.$woData->lastName;?></span></p>
																				<p><span class="request_span">Suite/Location :</span>    <span><?php echo $woData->tenant_suite;?></span></p>
																				<p><span class="request_span">Email :</span>    <span><?php echo $woData->email;?></span></p>
																				<p><span class="request_span">Phone Number :</span>    <span><?php echo $woData->phoneNumber;?></span></p>
																			</div>
																			
																			
																			<div id="detail_<?php echo $woData->woId;?>" class="tab-pane fade">
																			   <p><span class="request_span">Email To :</span>    <span>
																				   <?php echo $gp_names;?>
																				</span></p>
																				<p><span class="request_span">Priority :</span> <span><?php echo $woData->priorityName;?></span></p>
																				<?php $fileModel = new Model_WoFiles();
																					  $fileList = $fileModel->getWoFilesByWoId($woData->woId);
																					  if($fileList){?>
																				    <p><span class="request_span">Attachment :</span>
																				    <ul>
																				      <?php foreach($fileList as $fl){?>
																						  <li>
																								<span><a href="<?php echo BASEURL.'public/work_order/'.$fl['file_name'];?>" target="_blank"><?php echo $fl['file_title'];?></a></span>
																						   </li>		
																				       <?php } ?>
																				      </ul> 
																				   </p>
																				<?php }?>
																				<?php 
																				    $whlModel = new Model_WoHistoryLog();
																				    $whlList = $whlModel->getWoHistoryLog($woData->woId);
																				    if($whlList){
																				?>
																				    <p>
																						<span class="request_history_title" id="show_hist_<?php echo $woData->woId;?>"><a href="javascript:void(0)" onclick="showCatLog('<?php echo $woData->woId;?>')"> Show Work Order History Log </a></span>
																						<span class="request_history_title" style="display:none" id="hide_hist_<?php echo $woData->woId;?>"><a href="javascript:void(0)" onclick="hideCatLog('<?php echo $woData->woId;?>')"> Hide Work Order History Log </a></span>
																				    </p>
																				     <div id="catlog_<?php echo $woData->woId;?>" style="display:none">
																				         <div class="cat_log_history">
																							 <table class="history_log_table">
																								   <tr>
																									   <th>Log Type</th>
																									   <th>User</th>
																									   <th>Date</th>
																									   <th>Time</th>
																									   <th>Changes</th>
																								   </tr>
																									<?php foreach($whlList as $whl){?>
																										<tr>
																										    <td><?php echo ucfirst($whl->log_type);?></td>
																										    <td><?php echo $whl->firstName.' '.$whl->lastName;?></td>
																										    <td><?php echo substr($whl->created_at,0,10);?></td>
																										    <td><?php  echo date_format(date_create($whl->created_at), 'g:i A');?></td>
																										    <td>
																												<?php 
																												 if($whl->log_type=='category')
																												   echo $cat_array[$whl->current_value].' -> '.$cat_array[$whl->change_value];
																												else
																												  echo $status_array[$whl->current_value].' -> '.$status_array[$whl->change_value];
																											  ?>
																										    </td>
																										</tr>																										
																									<?php }?>
																						      </table>	
																				         </div>
																				     </div> 
																				<?php }?>
																			</div>
																		   
																		  
																		</div>
																	</div>
																	<!-- /.panel-body -->
																</div>
													</div>
											</div>
									</td>
									<td style="background-color:#<?php echo $building_color[$wl->building]?>">&nbsp;</td>
								</tr>	
							  <?php }
							   }
							  
						  }else{
                      ?>
                          <tr>
							  <td colspan="10">No work order created.</td>
                          </tr>
                       <?php }?>
                      </tbody>
                    </table>
                    <?php if(count($this->wolist)>0 && !empty($this->wolist)){
					 echo $this->paginationControl($this->wolist, 'Sliding', 'pagination.phtml'); 
					 }?>
                  </div>
                 
                </div>
                <!-- /.table-responsive --> 
                 <!--Edit Work Order Start-->
                  <div class="row">
					    <div class="editworkorder">

					     </div>
				   </div>
                 <!--Edit Work Order End-->
              </div>
            </div>
          </div>          
        </div>
      </div>
    </div>
 <div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"></div>
  <!-- /#page-wrapper -->
 

 <?php } else{?>
	    You don't have access for this module.
	  <?php }?> 
 
<?php } else{?>
	    You don't have access for this module.
	  <?php }?>
	