<script src="<?php echo BASEURL . 'public/js/account.js'?>"></script>
<?php  
  $from_name = '';
  $from_email = '';
  $bcc_name = '';
  $bcc_email = '';
  $setting_id = '';
  if($this->setData){
	 $setData = $this->setData[0];
	 $from_name = $setData['from_name'];
	 $from_email = $setData['from_email'];
	 $bcc_name = $setData['bcc_name'];
	 $bcc_email = $setData['bcc_email'];
         $contactus_name = $setData['contactus_name'];
         $contactus_email = $setData['contactus_email'];
         $support_name = $setData['support_name'];
         $support_email = $setData['support_email'];
	 $setting_id = $setData['setting_id']; 
  }
?>
<div class="container-right">
   <section style="z-index:9999" class="w-48 fr ch-home-form">
		<section class="ch-form-header ">
		     <h3>Setting </h3>
		</section>
		<div class="gridContainer">
			<div class="tableGrid">
				<div id="accountsetting">
					<form method="post" name="setting_form" id="setting_form" action="<?php echo BASEURL.'account/setting';?>">

							<div id="msg" class="welcome_text"><?php echo $this->msg;?></div>
                             <input type="hidden" name="setting_id" value="<?php echo $setting_id;?>"/>
							<div class="setting-div-field">                
								<div id="fn_div" class="setting_row">
									<label>From Name :<span class="required">*</span></label>
									<div class="setting-dt-box"> 
										<span id="fnErr"  class="field_error"></span>
										<input name="from_name" id="from_name" type="text" value="<?php echo $from_name;?>"/> 
									</div>
							    </div>
								<div id="fe_div" class="setting_row">
								    <label>From Email :<span class="required">*</span></label>
								    <div class="setting-dt-box">
										<span id="feErr" class="field_error"></span>
								        <input name="from_email" id="from_email" type="text" value="<?php echo $from_email;?>">
									</div>
								</div>
								<div id="bn_div" class="setting_row">
								    <label>Bcc Name :</label>
								    <div class="setting-dt-box">
										<span id="bnErr" class="field_error"></span>
								        <input name="bcc_name" id="bcc_name" type="text" value="<?php echo $bcc_name;?>">
									</div>
								</div>
								<div id="be_div" class="setting_row">
								    <label>Bcc Email :</label>
								    <div class="setting-dt-box">
										<span id="beErr" class="field_error"></span>
								        <input name="bcc_email" id="bcc_email" type="text" value="<?php echo $bcc_email;?>">
									</div>
								</div>
                                                                <div id="be_div" class="setting_row">
                                                                    <label>ContactUs Name :</label>
                                                                    <div class="setting-dt-box">
                                                                                <span id="beErr" class="field_error"></span>
                                                                        <input name="contactus_name" id="contactus_name" type="text" value="<?php echo $contactus_name;?>">
                                                                        </div>
                                                                </div>
                                                                <div id="be_div" class="setting_row">
								    <label>ContactUs Email :</label>
								    <div class="setting-dt-box">
										<span id="beErr" class="field_error"></span>
								        <input name="contactus_email" id="contactus_email" type="text" value="<?php echo $contactus_email;?>">
									</div>
								</div>
                                                                <div id="be_div" class="setting_row">
								    <label>Support Name :</label>
								    <div class="setting-dt-box">
										<span id="beErr" class="field_error"></span>
								        <input name="support_name" id="support_name" type="text" value="<?php echo $support_name;?>">
									</div>
								</div>
                                                                <div id="be_div" class="setting_row">
								    <label>Support Email :</label>
								    <div class="setting-dt-box">
										<span id="beErr" class="field_error"></span>
								        <input name="support_email" id="support_email" type="text" value="<?php echo $support_email;?>">
									</div>
								</div>
							</div> 
							<div class="add-comp-but">
								<input type="button" class="confirm" name="confirm" value="Save" onclick="settingValidation()">
								 	
							</div>
					</form>
				</div>
			</div>		
		</div>
   </section>
</div>
