<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/coilist.js');
$reportModel = new Model_Report();
$reportDetailLinks = '';
$dashboard_menu = array(50);
$reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);

$dashboard_menu2 = array(52);
$vTTemplateNameLinks = $reportModel->getReport($this->custID, $dashboard_menu2);

$dashboard_menu3 = array(53);
$vTTypeDesignationNameLinks = $reportModel->getReport($this->custID, $dashboard_menu3);


    $moduleMapper = new Model_UserBuildingModule();
	//print_r($this->select_build_id);
    $moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 4);
	
    $buildhasAccess = array();
    if ($moduleAccess) {
            foreach ($moduleAccess as $moduleAccessVal) {
                    $buildhasAccess[] = $moduleAccessVal->module_id;
            }
    }
?>




<style>
.bs-example{
        margin: 20px;
    }
.coi-footer-button{
margin: 34px -14px -14px -13.5px;
    text-align: left;
}
.coi-footer-button > input {
    background-color: #2ecc71;
    padding: 10px 23px;
    border: none;
}
th{
	text-align:center;
}
tbody {
	text-align:center;
}
</style>
<div class="container-right " >

<ol id="toc">
            <?php
            foreach ($this->companyListing as $cb) {
                if ($cb['build_id'] == $this->select_build_id) {
                    $uniqueCostCenter = $cb['uniqueCostCenter'];
                }
            ?>
                <li>
                    <a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>" href="<?php echo $this->baseUrl() . '/coilist/index/bid/' . $cb['build_id']; ?>">
                        <span>
                            <?php echo $cb['buildingName']; ?>
                        </span>
                    </a>
                </li>
            <?php } ?>
        </ol>
<br/>
<br/>
   <?php if (in_array(4, $buildhasAccess)) { ?>
            <ul class="nav nav-tabs">
                <li class="nav-item active">
                <a href="#home" class="nav-link" data-toggle="tab">Tenants COI's</a>
                </li>
                <li class="nav-item">
                <a href="#profile1" class="nav-link" data-toggle="tab">Vendor COI's</a>
                </li>        
            </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="home">
                <div id="page" class="content">                              
                    <div class="row-limit" style="float: left;margin-top: 12px;">
                        Show:
                            <select id="show_limit" onchange="showlimit();" dir="rtl">
                                <option value="10" <?php echo ($this->show==10?"selected":"");?> >10</option>
                                <option value="25" <?php echo ($this->show==25?"selected":"");?>>25</option>
                                <option value="50" <?php echo ($this->show==50?"selected":"");?>>50</option>
                                <option value="100" <?php echo ($this->show==100?"selected":"");?>>100</option>
                                <option value="all" <?php echo ($this->show=='all'?"selected":"");?>>All</option>
                            </select>
                    </div>
                    <div id="vendor_search_div">
                        <div id="search_form_div">
                            <div id="search_message"></div>
                                <form name="search_form" id="search_form" action="<?php echo BASEURL.'coilist/index/bid/'.$this->select_build_id;?>" method="post">
                                    <div id="form_field">
									    <div style='float:left;'>
                                            <label class='labelcenter' >Search Tenant Name</label>
                                        </div>
                                        <div class="text-select-div">
                                            <div id="search_txt" ><input type="text" name="search_value" id="search_value" value="<?php echo stripslashes(htmlentities($service_value)); ?>"/></div>
                                        </div>
                                    </div>
									<div class="form-button">
									    <input type="submit" name="search" id="search" value="Search"/>
                                        <input type="button" name="reset" id="reset" value="Reset" onclick="window.location.href='<?php echo BASEURL.'coilist/index/bid/'.$this->select_build_id;?>'"/>
                                    </div>  
                                </form>
                            </div>
                        </div>
					     <div class="service_message" id="service_message">
							<span id="service_success" class="success"></span>
							<span id="service_error" class="error"></span>
						</div>
					    <div id="service_grid_div">
							<table id="service_data_table" class="building_table_grid" width="100%">
								<tr>
								    <th>Tenant Name</th>
								    <th>Status</th>
								    <th>Expiration Date</th>
								    <th>Coi uploaded</th>
								    <th></th>
								    <th></th>
								</tr>
                                <?php if($this->bsList){
										foreach($this->bsList as $bs){
											
								?>								
								<tr>
								    <td><?php echo stripslashes($bs->tenantName);?></td>
									
									<?php if(!empty($bs->coi_au_date_to)) { 
									        
									    $date1 = date_create(date('Y-m-d'));
                                        $date2 = date_create($bs->coi_au_date_to);

                                        //difference between two dates
                                        $diff = date_diff($date1,$date2);
									    $cout = $diff->format("%a");
									    if($cout >= 0 && $cout <= 30 ){ 
										$color = '#ffe92c';
                                        $value = 'Expires - '.$cout.' day';										
										}
									    if($cout >= 31 && $cout <= 60 ){ 
										$color = '#d3dad682';
                                        $value = 'Expires - '.$cout.' day';									
										}
										if($cout >= 61 && $cout <= 90 ){ 
										$color = '#b9f95e'; 
										$value = 'Expires - '.$cout.' day';
										}
										if($cout > 90 ){ 
										$color = '#2cc56d';
                                        $value = 'Current';										
										}
										
										$agoCD = $date1 < $date2;									
										if($agoCD != '1'){
										  $diff = date_diff($date1,$date2);
									      $cout = $diff->format("%a");	
										  $color = '#f9052c';
                                          $value = 'Expires - '.$cout.' day ago';
										}
										
									?>
									<td style="background:<?php echo $color; ?>"><?php echo $value ; ?></td>									
									<?php } else { ?>
									<td style="background: #ffc508;">No COI</td>
									<?php } ?>
									<?php if(!empty($bs->coi_au_date_to)) { ?>
									<td><?php echo date("m/d/Y", strtotime($bs->coi_au_date_to));?></td>
									<?php }else{?>
									<td>--</td>
									<?php }?>
									<?php if(!empty($bs->coi_au_pdf_upload)) { ?>
									<td>Yes</td>
									<?php }else{?>
									<td>No</td>
									<?php }?>
									<td>
									<?php if(empty($bs->coi_au_tenant_id)) { ?>
									<a title="add" href="javascript:void(0);" onclick="showAddCoiTenant('<?php echo $bs->id;?>')"><img src="<?php echo $this->baseUrl() ?>/public/images/edit.png"></a>
						            <?php }else{?>
									<a title="Edit" href="javascript:void(0);" onclick="showEditCoi('<?php echo $bs->coi_au_tenant_id;?>')"><img src="<?php echo $this->baseUrl() ?>/public/images/edit.png"></a>
									<?php }?>
									<?php if(empty($bs->coi_au_tenant_id)) { ?>
									<a href="javascript:void(0);" title="When You will add the Expiration date.then Delete functionality is working" onclick="#"><img src="<?php echo $this->baseUrl() ?>/public/images/delete.png"></a>
						            <?php }else{?>
									<a href="javascript:void(0);" title="Delete" onclick="deleteCoiList('<?php echo $bs->coi_au_tenant_id;?>')"><img src="<?php echo $this->baseUrl() ?>/public/images/delete.png"></a>
						            <?php }?>
									</td>
									<td>
									<a class="dyn" href="#"><img src="<?php echo $this->baseUrl() ?>/public/images/task.png"></a>
									<a href="#"><img src="<?php echo $this->baseUrl() ?>/public/images/printer.png" style="width:18px;"></a></td>
								</tr>
								<?php  }}else{
								  ?>
								  <tr>
									  <td colspan="6">No Record Exist.</td>
								  </tr>
                                                                  
								  <?php }?>
															  
                                <?php
                                    if(count($this->bsList) > 0 && !empty($this->bsList)) {
                                        echo '<tr><td colspan="6">';
                                        echo $this->paginationControl($this->bsList, 'Sliding', 'pagination.phtml');
                                        echo '</td></tr>';                  
                                    }
                                ?>
								  
							  </table>
					     </div>
						<div class="form-button coi-footer-button">               
                            <input type="button" style="background-color: #3088e4" name="all" id="all" value="All (<?php echo $this->ListAll->total;?>)" onclick="#">
							<input type="button" style="background-color: #2ecc7" name="current" id="current" value="current (17)" onclick="#">
							<input type="button" style="background-color: #a2d657" name="expires" id="expires" value="Expires 60 - 90 (4)" onclick="#">
							<input type="button" style="background-color: #d3dad6" name="expires" id="expires" value="Expires 30 - 60 (11)" onclick="#">
							<input type="button" style="background-color: #e1ff1f" name="expires" id="expires" value="Expires 0 - 30 (2)" onclick="#">
							<input type="button" style="background-color: #f9052c" name="expires" id="expires" value="Expires (<?php echo $this->listAgoAll->total;?>)" onclick="#">
                            <input type="button" style="background-color: #ffc508" name="no-coi" id="no-coi" value="No COI's (21)" onclick="#">
						</div>
					 </div>
            <div id="popup_form" style="display:none" class="service_popup_form">
					 <a href="#add_service_form" id="add_service_form_href" class="modalbox">&nbsp;</a>					
					 <div id="add_service_form" class="bd-dft-cls"  style="display:none"></div>
					 <a href="#edit_service_form" id="edit_service_form_href" class="modalbox">&nbsp;</a>					
					 <div id="edit_service_form" class="bd-dft-cls"  style="display:none"></div>
					 <a href="#service_template_form" id="service_template_form_href" class="modalbox">&nbsp;</a>					
					 <div id="service_template_form" class="bd-dft-cls" style="display:none"></div>					
				</div>
        </div>
      

    </div>
	<?php
    } else {
        echo '<div class="clearfix"> </div>';
        echo 'This Building does not have the access of this module.';
    }
    ?>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
        <script>
            function showlimit(){
                var data = $("#show_limit").val();
                window.location =baseUrl+"coilist/index/show/"+data;
            }
            </script>

