<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/report.js');

?>
<style>
    .wrap {
        width: 90%;
        min-height: 200px;
        border: 1px solid;
        padding: 10px 10px 40px;
        margin-top: 20px;
        word-break: break-word;
    }
    td, th { 
   vertical-align: top;
   }
</style>
<div class="content active tenantcoi" id="contents">
    <div class="coi-title">
        <h3>Certificate of Insurance</h3>
    </div>
    <div class="row coi_table_row">
        <div class="col" style="overflow:auto">
            <div class="report_table_scroll">
                <table class="table table-bordered">
                    <tr class="coi_thead ">
                        <!--<th colspan="6" class="thead_heading">Existing Reports <?php echo $this->layout()->whatever; ?></th>-->
                    <tr>
                    <tr class="coi_thead">
                        <th>Current Status </th>
                        <th><strong>Expirtation Date </strong></th>
                        <th>COI on File</th>
                        <th>Number of Days untill COI Expires </th>
                    </tr>
                    <?php if (isset($this->reportDetails) && !empty($this->reportDetails)) { ?>

                        <tr class="create_report_table">
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td></td>
                        </tr>
                    <?php } else { ?>
                        <tr>
                            <td colspan='6' style="text-align:center;"> No Report Exists </td>
                        </tr>
                    <?php } ?>

                    <tr>
                        <td colspan='6' style="text-align:left;"> <strong>Requirements</strong> </td>

                    </tr>
                    <tr>
                        <td>
                            <table>
                                <tr>
                                    <th> General Liability</th>
                                    <th> &nbsp;</th>
                                </tr>
                                <?php
                                if (!empty($this->templatedetails)) {
                                    foreach ($this->templatedetails as $val) { ?>
                                        <tr>
                                            <td><?php echo $val->coi_vt_default_description; ?></td>
                                            <td style="text-align: right;"><?php echo preg_replace("/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/i", "$1,", $val->coi_au_defaults_Tenant); ?></td>
                                        </tr>
                                <?php  }
                                }
                                ?>
                    </tr>
                </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <th> Automobile Liability</th>
                            <th> &nbsp;</th>
                        </tr>
                        <?php
                        if (!empty($this->templatedetailsseconnd)) {
                            foreach ($this->templatedetailsseconnd as $valst) { ?>
                                <tr>
                                    <td><?php echo $valst->coi_vt_default_description; ?></td>
                                    <td style="text-align: right;"><?php echo preg_replace("/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/i", "$1,", $valst->coi_au_defaults_Tenant); ?></td>
                                </tr>
                        <?php  }
                        }
                        ?>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <th> Umbrella Liability</th>
                            <th> &nbsp;</th>
                        </tr>
                        <?php
                        if (!empty($this->templatedetailsseconnd)) {
                            foreach ($this->templatedetailsseconnd as $valst) { ?>
                                <tr>
                                    <td><?php echo $valst->coi_vt_default_description; ?></td>
                                    <td style="text-align: right;"><?php echo preg_replace("/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/i", "$1,", $valst->coi_au_defaults_Tenant); ?></td>
                                </tr>
                        <?php  }
                        }
                        ?>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <th>Workers Compensation</th>
                            <th> &nbsp;</th>
                        </tr>
                        <?php
                        if (!empty($this->templatedetailsthird)) {
                            foreach ($this->templatedetailsthird as $ute) { ?>
                                <tr>
                                    <td><?php echo $ute->coi_vt_default_description; ?></td>
                                    <td style="text-align: right;"><?php echo preg_replace("/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/i", "$1,", $ute->coi_au_defaults_Tenant); ?></td>
                                </tr>
                        <?php  }
                        }
                        ?>
                        </tr>
                    </table>
                </td>
                </tr>
                <tr>
                    <td colspan="4">
                        <table>
                            <tr>
                            <th>Certificate Holder</th>
                            <th>DESCRIPTION OF OPERATIONS/LOCATIONS/VEHICLES</th>
                            <th>Send Certificate To</th>
                            </tr>               
                                <td>                                    
                                    <div class="wrap">
                                        <div>
                                        <?php echo $this->coiDetails[0]->coi_au_details_holder; ?>
                                       </div>
                                    </div>                                            
                                </td>
                                <td>                                    
                                    <div class="wrap">
                                       <div>
                                        <?php echo $this->coiDetails[0]->coi_au_details_specialterms; ?>
                                      </div>
                                    </div>                                            
                                </td>
                                <td>                                    
                                    <div class="wrap">
                                    <div>
                                        <?php echo $this->coiDetails[0]->coi_au_details_send_certificate_to; ?>
                                    </div>
                                    </div>                                            
                                </td>
                                
                                           
                                        </tr>
                                    </table>

            </div>
        </div>
    </div>
</div>


<a href="#show_Edit_Report_div" id="show_Edit_Report_div_href" class="modalbox"> </a>
<div id="show_Edit_Report_div" class="show_Edit_Report_div" style="display:none"></div>

<script>
    function showNewPop(url) {
        CheckForSessionpop(baseUrl);
        //$('form#first_form input#tenantName').trigger('click');
        $('a[href="#showNewPop"]').fancybox({
            type: 'iframe',
            href: url,
            width: 750,
            height: 600,
            'beforeClose': function() {
                $('.loader').hide();
            },
            'afterLoad': function() {
                $.fancybox.hideLoading();
                $('.loader').show();
                setInterval(function() {
                    $('.loader').hide();
                }, 5000);
            },
            afterShow: function() {

            }
        });
    }
</script>