<?php
//echo "<pre>";
//$multiUserList = $this->multiUserList;
// echo '<pre>';
// //print_r($multiUserList);
// echo 'test';
// print_r($this->finalResultArr);
// die;
$multiUserList = $this->finalResultArr;
// echo '<pre>';
// print_r($multiUserList);
?>

<div class="table-responsive">         
                            <table id="air_handling-unit" class="table table-bordered">
                                <?php foreach($multiUserList as $rec){
                                    $user = $rec['data']['allowed_user_data'];
                                
                                    ?>
                                <tbody><tr class="colorblue"><td>&nbsp;<a href="#<?php echo $user->auTenantOptionID;?>" class="show_hide" onclick="plusminus(this.id);" id="plus2"><i class="fa fa fa-minus-circle" aria-hidden="true"></i></a>&nbsp;<?php echo $user->User_EMail ;?> | <?php echo $user->User_First_Name;?></td></tr>
                                <tr class="collapseall" id="xyzplus2" style="display: table-row;">
                                    <td class="td-bg-clr" id="mno2">
                                        <div class="tble-left-gp">
                                            <table class="table table-bordered text-center">
                                                <thead>
                                                    <tr>
                                                        <th class="w_180">Email Address<span><a href="#<?php echo $user->auTenantOptionID;?>" ></th>
                                                        <th class="w_180">Building Name<span><a href="#<?php echo $user->auTenantOptionID;?>" ></th>
                                                        <th class="w_180">Tenant Name<span><a href="<?php echo $user->auTenantOptionID;?>" ></th>
                                                        <th class="w_180">Location</th>
                                                        <th class="w_130">Deleted</th>                                                       
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach($rec['data']['list'] as $tenant){?>                  
                                                <tr>
                                                                <td><?php echo $tenant->email ;?></td>
                                                                <td><?php echo $tenant->buildingName;?></td>
                                                                <td><?php echo $tenant->tenantName;?></td>
                                                                <td><?php echo $tenant->billAddress;?></td>
                                                                <td>                                                      
                                                                    <a class="dyn" href="#">

                                                                                                                                                </a></td>
                                                               
                                                            </tr>
                
                                                  <?php } ?>                                                  
                
                                                                                                       

                                                </tbody>
                                            </table>      
                                        </div>                                            
                                    </td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                     </div>  
