<style>   
    /*//////////////////////////////////////////////////////////////////
    [ Table ]*/
    table {
        width: 100%;
        background-color: #fff;
    }

    th, td {
        font-weight: unset;
        padding-right: 10px;
    }



    /*==================================================================
    
    [ Ver2 ]*/
    .table100.ver2 td {
        font-size: 14px;
        color: #808080;
        line-height: 2.4;
    }

    .table100.ver2 th {
        font-size: 12px;
        color: #fff;
        line-height: 1.4;
        text-transform: uppercase;
        background-color: #3bc95e;
    }

    .table100.ver2 .row100:hover td {

    }

    .table100.ver2 .hov-column-ver2 {

    }

    .table100.ver2 .hov-column-head-ver2 {
        background-color: #484848 !important;
    }

    .table100.ver2 .row100 td:hover {

    }

    .eqpment-box
    {
        margin-top: 30px;
        margin-bottom: 30px;	
    }

    /*==================================================================
    [ Ver2 ]*/

    .table100.ver2 td {
        color: #000;
        line-height: 1.4;

    }

    .table100.ver2 th {

        color: #000;
        line-height: 1.4;
        text-transform:none;
        background-color: #2a6496;
        border-right: 1px solid #ccc;
    }

    .table100.ver2 .row100:hover td {

    }

    .table100.ver2 .hov-column-ver2 {
        background-color: #83d160;
        color: #fff;
    }

    .table100.ver2 .hov-column-head-ver2 {
        background-color: #484848 !important;
    }

    .table100.ver2 .row100 td:hover {

    }

    .heading-main-equipmnt
    {
        background-color: #34495e;
        color: #fff;
        padding: 9px 8px;
        border-bottom: 0px solid #ccc;
    }

    .heading-sub-equipmnt
    {
        background-color: #2a6496;
        color: #fff;
        padding: 5px 3px;
    }

    .btn-csttm
    {
        border-radius:0px;
        font-style: italic;

    }


    .search-box-main-row
    {
        padding-bottom: 20px !important;
    }

    .bttons-view-right
    {
        text-align: right;
        right: 0px;
        padding-right: 0px;
    }

    .input-csttm
    {
        border-radius:0px;	
    }

    .serch-text-style
    {
        font-weight:600;
    }

    .border-left-gray
    {
        border-left: 1px solid #ccc;
    }

    .border-left-0
    {
        border-left: 0px solid #ccc;
    }


    .border-right-0
    {
        border-right:0px;
    }

    .border-bottom-0
    {
        border-bottom:0px;
    }

    .fa-icon i
    {
        font-size:16px;
        padding-right: 8px;
    }

    .row100 th {
        padding: 10px;
        text-align: center;
    }

    .background-collr
    {

    }

    .padd-0{
        padding:0px !important;
    }

    .sub-bg-bckgrnd
    {
        background-color:#92cddc;
    }

    .sub-bg-bckgrnd-light
    {
        background-color:#dbeef3;
    }

    .border-corner
    {
        border-left: 0 !important;
        border-top: 0 !important;
        border-bottom: 0 !important;
    }

    .border-corner-1
    {
        border-right: 0 !important;
        border-top: 0 !important;
        border-bottom: 0 !important;
    }

    .heading-tr
    {
        background-color: #fff !important;  
    }

    .input-csttm-padd-0
    {
        margin:0px !important; 
    }

    .heading-sub-equipmnt .arrow-shrting{

    }
    .arrow-shrting
    {
        color:#fff;
        padding-left: 10px;
    }

    .colm-new01
    {
        width:4%;  
    }

    .colm-new02
    {
        width:5%;  
    }

    .colm-new03
    {
        width:10%;  
    }

    .colm-new04
    {
        width:10%;  
    }

    .colm-new05
    {
        width:10%;  
    }

    .colm-new06
    {
        width:25%;  
    }

    .colm-new07
    {
        width:25%;  
    }

    .colm-new03-th
    {
        width: 15%;    
    }

    .table100.ver2 td {
        padding:2px 0px;
    }

    .equp-sub-box
    {
        width: 12% !important;   
    }

    .blue-bg
    {
        background-color: #92cddc !important; 
    }
    .right-x{
        border: 1px solid #ccc;;
    }
    .common-wrap input[type="text"]{
        width: 100%;
    }
    .common-wrap  select {
        width: 100%;
    }
    .common-btn { text-align: left; }
    .modified_btn button{ background: #06af8f; color:#000; font-weight: bold;  padding: 3px 10px; border-radius: 3px; box-shadow: 2px 2px 5px #ccc; 
                          border: none; font-size: 16px !important; line-height: 1;}
    a.dyn img {
        width: 18px;
    }
    @media screen and (max-width: 1500px) {
        .bttons-view-right .btn { display: block;
                                  width: 100%;
                                  margin-bottom: 5px; }

    }
    @media screen and (max-width: 767px) {
        #page-wrapper { margin: 0px; }

    }

</style>
<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/pm-workorder.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/emails.js');


$reportModel = new Model_Report();
$reportDetailLinks = '';
$dashBoardViewsdetails = '';
$dashBoardViews = '';
$woNumberAll = '';
$invoiceAll = '';
$uniqueCostCenterAll = '';
$buildIdReportAll = '';
$batch_number_report = '';
$uniqueCostCenter = '';
$batch_number_reportallbuilding = '';
$buildId= $this->select_build_id;

$woNumberAllbuilding = '';
$invoiceAllbuilding = '';
$batch_number_reportall = '';
$reportDetailLinks = $reportModel->getReport($this->custID, 14);
$roleMapper = new Model_Role();
$roleDetail = $roleMapper->getRole();
$role_data = array();
foreach ($roleDetail as $rd) {
    $role_data[$rd['roleID']] = $rd['title'];
}

$tenantAccess = $this->acesshelper->checkAccess($this->roleId, $this->tenant_location);
/* override access by custom user access if exist */
$customeAccessmodel = new Model_UserAccess();
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->tenant_location);
if ($customeAccessmodeld[0]) {
    $tenantAccess = $customeAccessmodeld[0];
}
/* end overriding access */

$search_by = '';
	$service_value = '';
	if(!empty($this->search) && isset($this->search['search_by'])){
			$search_by = $this->search['search_by'];
			$service_value=$this->search['search_value']; 
	} 
$userRoleID = Zend_Auth::getInstance()->getStorage()->read()->role_id;
$userId = Zend_Auth::getInstance()->getStorage()->read()->uid;
$customeAccessmodelll = new Model_UserAccess();
$actionnHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('Access');
$accarray =array(2,3,4,6);
$WorkOrders = true;
if(in_array($userRoleID, $accarray)){
    $WorkOrdersss =  $actionnHelper->checkAccess($userRoleID, 27);
    $customeAccessmodeld = $customeAccessmodelll->getUserCustomAccess($userId, 27);
    if ($customeAccessmodeld[0]) {
        $WorkOrdersss = $customeAccessmodeld[0];
    }
    if($WorkOrdersss->is_write == 0){
        $WorkOrders = false;
    }
}
//echo $WorkOrders;
$reportModel = new Model_Report();
$reportDetailLinks = '';

$equipment = new Model_PmTemplate();
$moduleMapper = new Model_UserBuildingModule();
$moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 3);
$buildhasAccess = array();
if ($moduleAccess) {
    foreach ($moduleAccess as $moduleAccessVal) {
        $buildhasAccess[] = $moduleAccessVal->module_id;
    }
}


$dashboard_menu = array(38);
if (in_array(3, $buildhasAccess)) {
    $reportDetailLinks = $reportModel->getReport($this->custID, $dashboard_menu);
} else {
    $reportDetailLinks = false;
}

$dashboard_menu = array(39);
if (in_array(3, $buildhasAccess)) {
    $printerLinks = $reportModel->getReport($this->custID, $dashboard_menu);
} else {
    $printerLinks = false;
}

function unique_multidim_array($array, $key) {
    $temp_array = array();
    $i = 0;
    $key_array = array();

    foreach ($array as $val) {
        if (!in_array($val[$key], $key_array)) {
            $key_array[$i] = $val[$key];
            $temp_array[$i] = $val;
        }
        $i++;
    }
    return $temp_array;
}
?>
<div class="fdw" id="access-matrix">

<ol id="toc" class="pm-work-order-toc-list">
<?php
foreach ($this->companyListing as $cb) {
    if ($cb['build_id'] == $this->select_build_id) {
        $uniqueCostCenter = $cb['uniqueCostCenter'];
    }
    ?>
            <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/tenant/tenantoptions/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>
            <?php /*
              if ($reportDetailLinks != '') {
              if ($cb['build_id'] == $this->select_build_id) {
              $uniqueCostCenter = $cb['uniqueCostCenter'];
              $batchDetails = $woBatch->showBatch($cb['build_id']);
              $batch_number_report = '';
              if ($batchDetails != '') {
              foreach ($batchDetails as $bd) {
              $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
              }
              }
              $order = 'woId';
              $dir = 'DESC';
              $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
              $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
              if ($wolist != '') {
              foreach ($wolist as $woNumber) {
              $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
              }
              }
              if ($invoicelist != '') {
              foreach ($invoicelist as $invoiceNumber) {
              $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
              }
              }
              }
              } */
            ?> 
            </li>

<?php } ?>
    </ol>
   

    <!-- Report Link -->
<?php if ($reportDetailLinks != '') { ?> <div class="tabmenu" style="display:none;" ><ul style="padding:0px;list-style: none;"><?php
    foreach ($reportDetailLinks as $reportvalue) {
        if ($reportvalue->Report_Type == 'Flash') {
            $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
        } else {
            $report_type = 'vnsreports/index.php?';
        }
        $reportOption = explode(',', $reportvalue->report_option);
        ?> <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php
            if (in_array('[[++user_id]]', $reportOption)) {
                echo '&User=' . $this->userId;
            }
            ?><?php
                    if ((in_array('[[++CostCenterNumber]]', $reportOption)) && $uniqueCostCenter != '') {
                        echo '&Cost_Center_Number=' . $uniqueCostCenter;
                    }
                    ?><?php
                    if ((in_array('[[++KeyBuildingNumber]]', $reportOption)) && $this->select_build_id != '') {
                        echo '&buildkey=' . $this->select_build_id;
                    }
                    ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>

        <?php if (in_array(3, $buildhasAccess)) {  ?>
        
        <div class="pull-right pm-work-order-option" style="display:none;"><!--<a href="#" class="btn btn-csttm btn-success">PM Work Order Options</a>-->
        <?php if($this->email_group){ ?>
            <a class="modalbox create_conf " id="add_equp" onclick="javascript:editNewDisGroup('<?php echo BASEURL . 'emails/editemailgroup/gid/' . $this->email_group[0]['id'] . '/buildingId/' . $this->select_build_id; ?>');" href="#editNewDisGroup"> 
                <button class="confirm">PM Work Order Email Template</button>
            </a>
        <?php }else{?>
            <a class="modalbox" onclick="javascript:addNewDisGroup('<?php echo $this->baseUrl() . '/emails/addemailgroup/bid/' . $this->select_build_id; ?>/controllerName/PM');" href="#addNewDisGroup"> 
                      <button class="confirm">PM Work Order Email Template</button>
            </a>
        <?php } ?>
            <a class="modalbox create_conf " id="add_equp" onclick="javascript:pmSetupAndOption('<?php echo $this->baseUrl() . '/pm/pmsetupoptions/buiild_id/' . $this->select_build_id; ?>');" href="#CreateNewMultiCon"> 
                <button class="confirm">PM Work Order Options</button>
            </a>
        </div>

        <!-- Main part of Equipment List start --> 
        <div class="eqpment-box">

            <div class="row search-box-main-row">
            <h4>Tenant Options:</h4>
               
                <div id="user_contact_info" style="display:none;">
                        <div class="">
                            <h4 style="text-align:left;">Contact Information:</h4>
                       
            
            <div class="controls bttons-view-left pull-left">
                    <form onsubmit="return false">                       
                        <table>
                            <tbody>
                                <tr>                                    
                                    <td class="serch-text-style">
                                        <p>Search Email Address</p>
                                    </td>                                  
                                    <td class="common-wrap">
                                        <input type="text" name="email_address1" list="typehintvalue" id="email_address1" value="<?php echo (isset($_COOKIE['multiuser_search_email']))?$_COOKIE['multiuser_search_email']:'';?>" class="form-control input-csttm input-csttm-padd-0" autocomplete="off">
                                        <datalist id="typehintvalue"></datalist>
                                    </td>
                                    <td class="common-btn">       
                                        <!-- <a id="btn-login" href="/veinc/pm/pmworkorder" class="btn btn-csttm btn-success">Reset</a> -->
                                        <!--<input class="btn btn-csttm btn-success" type="button" onclick="resetForm()" value="Reset">-->
                                        <!--<a id="btn-fblogin" href="#" class="btn btn-csttm btn-success">Search</a>-->
                                        
                                        <input type="button" class="btn btn-csttm btn-success" onclick="defualtResults();" value="Search"> 
                                        <input type="button" name="reset" id="reset1" value="Reset" class="btn btn-csttm btn-success"  onclick="window.location.href='<?php echo BASEURL. 'tenant/resettenantoptionfilter'; ?>'" >
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form> 
                </div>
                <div class="clearfix"></div>
                <div class="clearfix"></div>
                <br/>
            <!-- Add new Tenant option wrapper class ---->
            <table id="user_contact_tbl" class="table100 ver3 m-b-110 user_contact_info" width="100%"></table>

<!---search results-->
             <div class="row" id="by_quipment" >
                <div class="table100 ver2 m-b-110">
                    <div class="heading-main-equipmnt">Multi-User Allowed List</div>
                    <div class="heading-sub-equipmnt">Listed by User (A-Z)<span><a href="javascript:void(0);" id="sortingid" onclick="sortingmultiusername();"><span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvalue" id="sortingvalue"></a></span></div>
                    <div class="clearfix"></div>
                    <div id="pm-work-cta-1" class="pm-work-tbl">

                    
  <!---search results-->
                                                   

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="row">
	         <div class="pagination_link">
		
		 </div>
        <!-- <div class="pagination_info">Page 1 of 172 </div> -->
 </div>	
  
            </div>
             
                    
         </div>
        </form>
            </div>
         </div>
        
         <table id="filter-tenant-option"></table>

         <div class="row" id="filer_multiuser" style="display:none;">
                <div class="table100 ver2 m-b-110">
                    <div class="heading-main-equipmnt">Multi User List</div>
                 </div>           
        </div>            
               
            </div>
            <div class="row" id="by_quipment" style="display:none">
                
                        <div class="clearfix"></div>
             </div>
                </div>
               
            </div>

    <?php
} else {
    echo '<div class="clearfix"> </div>';
    echo 'This Building does not have the access of this module.';
}
?>
        <!-- Main part of Equipemtn List End -->
    </div>

    <div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>">
        <script>
        function showlimit() {        
        var limit = $("#show_limit").val();
        window.location = baseUrl + 'pm/pmworkorder/show/' + limit;
    }
   
    function chckTenantBuildingInfo(){
        $.ajax({
                type: "POST",
                url: baseUrl + 'tenant/checktenaninfo',
                data: {
                    email: $("#email_address1").val(),
                    bid: '<?php echo $buildId;?>'
                   
                },
                success: function (data) {
                    var bid = '<?php echo $buildId;?>';
                    bid = parseInt(bid);
                    
                    var finalData =  JSON.parse(data);
                    console.log(finalData);
                    if(parseInt(finalData.BuildingId) !== bid){
                        //$('#user_contact_tbl').hide();
                       // alert(finalData.BuildingId +'========='+bid);
                        $('#user_contact_tbl').hide();
                    }
                 
                // if(finalData.BuildingId == bid){          
                //     $('#upperform').show();
                //     $('#user_contact_tbl').show();     
                // }else{
                //     $('#upperform').hide();
                //     $('#user_contact_tbl').hide(); 
                // }
                
                }
            });

    }

    function checktenantallow(){
            $.ajax({
                type: "POST",
                url: baseUrl + 'tenant/checkmultiusers',
                data: {
                    email: $("#email_address1").val(),
                    bid: '<?php echo $buildId;?>'
                   
                },
                success: function (data) {
                    var finalData =  JSON.parse(data);
                    console.log(finalData);

                if(finalData.UserID){   
                           
                    $('#upperform').hide();
                    $('#user_contact_tbl').hide();     
                }else{
                    $('#upperform').show();
                    $('#user_contact_tbl').show();
                }
                
                }
            });
    }


    function defualtResults(){
        var email_address = $("#email_address1").val().trim();;
      
         $.ajax({
          type: "POST",
          url: baseUrl + 'tenant/checkuseremail',
          data: {email: email_address},
          success: function (data) {
            if(data =="1"){
         
                  $.ajax({
                      type: "POST",
                      url: baseUrl + 'tenant/checktenantuseremail',
                      data: {
                        email: $("#email_address1").val(),
                        bid: '<?php echo $buildId;?>'
                    },
                      success: function (data) {
                         
                          $('.loader').hide();
                          $('#user_contact_info').show();
                          $('#user_contact_tbl').html(data);

                        

                         var checkAccess =  checktenantallow();
                         $.ajax({
                            type: "POST",
                            url: baseUrl + 'tenant/sortmultiuser',
                            data: {email: $("#email_address1").val(),
                                  bid: <?php echo $buildId;?>                         
                              },
                            success: function (data) {
                                if(data){
                                // $('#user_contact_tbl').hide();                               
                                  $('#pm-work-cta-1').html(data);
                                  //chckTenantBuildingInfo();
                                }
                               
                            }
                        });
  
                          
                      }
                  });
  
               //   alert('test1');
               //   $('#pm-work-cta').show();
                //  $('#user_contact_info').show();
             
            }else{
              //$('#user_contact_info').hide();
             // $('#user_contact_tbl').html('');
              jAlert('Email Address <strong>'+email_address+'</strong> has not been found in our system',
              'information',function(){
                  $('#email_address').focus();
                 
              });
            }
                
              $('.loader').hide();
              //$('#pmcompletewo').html(data);
          }
      });


    }
    function searchEmailData() {
       var email_address = $("#email_address").val().trim();;
      
    //var pmreadingtask = $("#pmreadingtask").val().trim();
    if (email_address=="") {                
                $("#email_address").focus();
                $("#email_address").addClass('error-border');
                return false;
            } else {                
                $("#email_address").removeClass('error-border');
                $('.loader').show();
            }
    $.ajax({
        type: "POST",
        url: baseUrl + 'tenant/checkuseremail',
        data: {email: email_address},
        success: function (data) {
          if(data =="1"){
        
                $.ajax({
                    type: "POST",
                    url: baseUrl + 'tenant/checktenantuseremail',
                    data: {email: $("#email_address").val()},
                    success: function (data) {
                       
                        $('.loader').hide();
                        $('#user_contact_info').show();
                        $('#user_contact_tbl').html(data);
                       var checkAccess =  checktenantallow();

                      
                       $.ajax({
                            type: "POST",
                            url: baseUrl + 'tenant/sortmultiuser',
                            data: {email: $("#email_address1").val(),
                                  bid: <?php echo $buildId;?>                         
                              },
                            success: function (data) {
                                if(data){
                                  
                                // $('#user_contact_tbl').hide();
                                 $('#pm-work-cta-1').html(data);
                                // $('#email_address1').val($("#email_address").val());
                                }
                               
                            }
                        });
                        filterData();

                        
                    }
                });

             //   alert('test1');
             //   $('#pm-work-cta').show();
              //  $('#user_contact_info').show();
           
          }else{
            $('#user_contact_info').hide();
            $('#user_contact_tbl').html('');
            jAlert('Email Address <strong>'+email_address+'</strong> has not been found in our system',
            'information',function(){
                $('#email_address').focus();
               
            });
    }
    
          
            console.log(data);
            $('.loader').hide();
            $('#pmcompletewo').html(data);
        }
    });
}




function addTenantOption(bid,uid,tid){

    $.ajax({
            type: "POST",
            url: baseUrl + 'tenant/addtenantoption',
            data: {bid: bid,
                uid:uid,
                tid:tid
            },
            success: function (data) {
                $('#addtenantOption').hide();
                $('#byequipment').hide();
                filterData();
                $('#user_contact_tbl').hide();                    
            }
        });


}


function filterData() {
   
    $.ajax({
        type: "POST",
        url: baseUrl + 'tenant/sortmultiuser',
        data: {email: $("#email_address1").val(),
            bid: <?php echo $buildId;?>
        
        },
        success: function (data) {
            //console.log(data);
            $('#pm-work-cta-1').html(data);
        }
    });

}


function filterResults() {

    var email_address = $("#email_address1").val().trim();;
      
      //var pmreadingtask = $("#pmreadingtask").val().trim();
      
      $.ajax({
          type: "POST",
          url: baseUrl + 'tenant/checkuseremail',
          data: {email: email_address},
          success: function (data) {
            if(data =="1"){
          
                  $.ajax({
                      type: "POST",
                      url: baseUrl + 'tenant/checktenantuseremail',
                      data: {email: $("#email_address1").val()},
                      success: function (data) {
                         
                          $('.loader').hide();
                          $('#user_contact_info').show();
                          $('#user_contact_tbl').html(data);
                         var checkAccess =  checktenantallow();
  
                        
                         $.ajax({
                              type: "POST",
                              url: baseUrl + 'tenant/sortmultiuser',
                              data: {email: $("#email_address1").val(),
                                    bid: <?php echo $buildId;?>                         
                                },
                              success: function (data) {
                                  if(data){
                                  // $('#user_contact_tbl').hide();
                                
                                   $('#email_address1').val($("#email_address").val());
                                  }
                                 
                              }
                          });
                          
                          
                      }
                  });
  
               //   alert('test1');
               //   $('#pm-work-cta').show();
                //  $('#user_contact_info').show();
             
            }else{
              $('#user_contact_info').hide();
              $('#user_contact_tbl').html('');
              jAlert('Email Address <strong>'+email_address+'</strong> has not been found in our system',
              'information',function(){
                  $('#email_address1').focus();
                 
              });
            }
      
            
              $('.loader').hide();
              $('#pmcompletewo').html(data);
          }
      });

}


function sortingmultiusername() {
    var x = $("#sortingvalue").val();
    if (x == 1) {
        $("#sortingid").html('<span class="glyphicon glyphicon-sort-by-attributes-alt arrow-shrting"></span><input type="hidden" value="0" name="sortingvalue" id="sortingvalue">');
        id = $("#sortingvalue").val();
    } else {
        $("#sortingid").html('<span class="shorting-icon-white glyphicon glyphicon-sort-by-attributes arrow-shrting"></span><input type="hidden" value="1" name="sortingvalue" id="sortingvalue">');
        id = $("#sortingvalue").val();
    }

    // $.ajax({
    //     type: "POST",
    //     url: baseUrl + 'pm/sortequipmentname',
    //     data: {id: id},
    //     success: function (data) {
    //         console.log(data);
    //         $('#sortequipmentname').html(data);
    //     }
    // });
    $.ajax({
        type: "POST",
        url: baseUrl + 'tenant/sortmultiuser',
        data: {email: $("#email_address1").val(),
            id: id,
            bid: "<?php echo $cbbuildId;?>"
        },
        success: function (data) {
            //console.log(data);
            $('#pm-work-cta-1').html(data);
        }
    });

}
function editNewUser(url) {
    CheckForSessionpop(baseUrl);
    $('a[href="#editNewUser1"]').fancybox({
        type: 'iframe',
        href: url,
        width: 750,
        height: 600,
        'beforeClose': function () {
            $('.loader').hide();
        },
        'afterLoad': function () {
            $.fancybox.hideLoading();
            $('.loader').show();
            setInterval(function () {
                $('.loader').hide();
            }, 5000);
        }
    });
}

function editTenant(url) {
    CheckForSessionpop(baseUrl);
    $('a[href="#editTenant"]').fancybox({
        type: 'iframe',
        href: url,
        width: 750,
        height: 600,
        'beforeClose': function () {
            $('.loader').hide();
        },
        'afterLoad': function () {
            $.fancybox.hideLoading();
            $('.loader').show();
            setInterval(function () {
                $('.loader').hide();
            }, 5000);
        }
    });
}

function deleteTenantOptionUser(tuId, uId, cnt) {
    var check_delete = 'YES';    
    if (tuId) {
        jPrompt('For Deleting Tenant User, Enter Yes in Capital letters.', '', 'Tenant Option', function (r) {
            if (r != null) {
                if (check_delete === r) {
                   // alert('test');
                   $.ajax({
                        url: baseUrl + "tenant/removetenantlocation",
                        type: "post",
                        datatype: 'json',
                        data: {
                            tuId: tuId, uId: uId
                        },
                        success: function (result) {
                            $('.loader').hide();
                            //data = result;
                            var data = $.parseJSON(result);
                            //alert(data.msg);
                            if (data.msg == 'true') {
                                $('.message').html('Tenant user deleted successfully.');
                            } else {
                                $('.error-txt').html('Some error occurred.');
                            }
                            filterData();
                           // window.location.href = baseUrl + 'tenant/tenantoptions/';
                            
                        }
                    });

                   
                } else {
                    //$('.error-txt').html('You have entered wrong word.');
                    jAlert('You have entered wrong word.');
                }
            }
        });

    }
}

function recoverTenantOptionUser(tuId, uId, cnt) {
    var check_delete = 'YES';    
    if (tuId) {
        jPrompt('For Recover Tenant User Location, Enter Yes in Capital letters.', '', 'Tenant Option', function (r) {
            if (r != null) {
                if (check_delete === r) {
                   // alert('test');
                   $.ajax({
                        url: baseUrl + "tenant/recoverytenantlocation",
                        type: "post",
                        datatype: 'json',
                        data: {
                            tuId: tuId, uId: uId
                        },
                        success: function (result) {
                            $('.loader').hide();
                            //data = result;
                            var data = $.parseJSON(result);
                            //alert(data.msg);
                            if (data.msg == 'true') {
                                $('.message').html('Tenant user reovered successfully.');
                            } else {
                                $('.error-txt').html('Some error occurred.');
                            }
                            filterData();
                           // window.location.href = baseUrl + 'tenant/tenantoptions/';
                            
                        }
                    });

                   
                } else {
                    //$('.error-txt').html('You have entered wrong word.');
                    jAlert('You have entered wrong word.');
                }
            }
        });

    }
}

function editTenantUserLocation(url) {
    CheckForSessionpop(baseUrl);
    $('a[href="#editNewUser"]').fancybox({
        type: 'iframe',
        href: url,
        width: 750,
        height: 600,
        'beforeClose': function () {
            $('.loader').hide();
        },
        'afterLoad': function () {
            $.fancybox.hideLoading();
            $('.loader').show();
            setInterval(function () {
                $('.loader').hide();
            }, 5000);
        }
    });
}

function sortingalloweduser(){
    $.ajax({
        type: "POST",
        url: baseUrl + 'tenant/sortmultiuser',
        data: {email: $("#email_address1").val()},
        success: function (data) {
            //console.log(data);
            $('#pm-work-cta-1').html(data);
        }
    });
}

// A $( document ).ready() block.
$( document ).ready(function() {
    
    $('#upperform').hide();
    if($('#email_address').val()){
        searchEmailData();
    }else{
        defualtResults();
       
    }
});
    </script>
    <style>
.table100.ver2 th {
  color: #000;
  line-height: 2.4;
  text-transform: none;
  background-color: #3bc95e;
  border-right: 1px solid #ccc;
}
.table100.ver3 th {
  color: #000;
  line-height: 2.4;
  text-transform: none;
  background-color: #3bc95e;
  border-right: 1px solid #ccc;
  padding:0px 3px;
}
.table100.ver2 td{
    text-align:left;
}
.tntopt-btn-section{
    padding:5px 0px;
}

    </style>



