<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/public/tabs.css');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/tenant.js');
?>

<?php
$reportModel = new Model_Report();
$reportDetailLinks = '';
$dashBoardViewsdetails = '';
$dashBoardViews = '';
$woNumberAll = '';
$invoiceAll = '';
$uniqueCostCenterAll = '';
$buildIdReportAll = '';
$batch_number_report = '';
$uniqueCostCenter = '';
$batch_number_reportallbuilding = '';
$buildIdReport = $this->select_build_id;
$woNumberAllbuilding = '';
$invoiceAllbuilding = '';
$batch_number_reportall = '';
$reportDetailLinks = $reportModel->getReport($this->custID, 14);
?>
<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap-editable.css');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap-editable.js');
?>
<?php
$roleMapper = new Model_Role();
$roleDetail = $roleMapper->getRole();
$role_data = array();
foreach ($roleDetail as $rd) {
    $role_data[$rd['roleID']] = $rd['title'];
}

$tenantAccess = $this->acesshelper->checkAccess($this->roleId, $this->tenant_location);
/* override access by custom user access if exist */
$customeAccessmodel = new Model_UserAccess();
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->tenant_location);
if ($customeAccessmodeld[0]) {
    $tenantAccess = $customeAccessmodeld[0];
}
/* end overriding access */

$search_by = '';
	$service_value = '';
	if(!empty($this->search) && isset($this->search['search_by'])){
			$search_by = $this->search['search_by'];
			$service_value=$this->search['search_value']; 
	} 
?>
<div class="container-right" id="userinfo-data">
    <?php
   
    if ($this->roleId != 1 && $tenantAccess->is_access == 0 && $tenantAccess->is_read == 1) {
        if ($this->custID != null && $this->custID && $this->companyListing != '' && $this->companyListing != false) {
            ?>

            <!-- All Report link -->
            <?php
            if ($reportDetailLinks != '') {
                $woReport = new Model_Report();
                $woBatch = new Model_WoBatch();
                foreach ($this->companyListing as $cb) {
                    $uniqueCostCenterAll = $uniqueCostCenterAll . $cb['uniqueCostCenter'] . ',';
                    $buildIdReportAll = $buildIdReportAll . $cb['build_id'] . ',';
                    $batchDetails = $woBatch->showBatch($cb['build_id']);
                    if ($batchDetails != '') {
                        foreach ($batchDetails as $bd) {
                            $batch_number_reportallbuilding = $batch_number_reportallbuilding . $bd['batch_number'] . ',';
                        }
                    }


                    $order = 'woId';
                    $dir = 'DESC';
                    $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                    $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                    if ($wolist != '') {
                        foreach ($wolist as $woNumber) {
                            $woNumberAllbuilding = $woNumberAllbuilding . $woNumber->wo_number . ',';
                        }
                    }
                    if ($invoicelist != '') {
                        foreach ($invoicelist as $invoiceNumber) {
                            $invoiceAllbuilding = $invoiceAllbuilding . $invoiceNumber->wo_number . ',';
                        }
                    }

                    $batchDetails = $woBatch->showBatch($cb['build_id']);

                    if ($batchDetails != '') {
                        foreach ($batchDetails as $bd) {
                            $batch_number_reportall = $batch_number_reportall . $bd['batch_number'] . ',';
                        }
                    }
                }
            }
            ?>

            <!-- End all report Link -->
            <div id="contents">
                <ol id="toc">
                        <?php
                        //echo $this->select_build_id;
                        $j = 1;
                        foreach ($this->companyListing as $cb) {
                            ?>					
                        <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/tenant/users/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>
                            <!-- selected report Link -->
                            <?php
                            if ($reportDetailLinks != '') {
                                if ($cb['build_id'] == $this->select_build_id) {
                                    $uniqueCostCenter = $cb['uniqueCostCenter'];
                                    $batchDetails = $woBatch->showBatch($cb['build_id']);
                                    $batch_number_report = '';
                                    if ($batchDetails != '') {
                                        foreach ($batchDetails as $bd) {
                                            $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
                                        }
                                    }
                                    $order = 'woId';
                                    $dir = 'DESC';
                                    $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                                    $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                                    if ($wolist != '') {
                                        foreach ($wolist as $woNumber) {
                                            $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
                                        }
                                    }
                                    if ($invoicelist != '') {
                                        foreach ($invoicelist as $invoiceNumber) {
                                            $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
                                        }
                                    }
                                }
                            }
                            ?> 
                        </li>

                                <?php $j++;
                            } ?>         
                </ol>




                <!-- Report Link -->
        <?php if ($reportDetailLinks != '') { ?> <div class="clearfix"></div><div class="tabmenu report_tab_menus" ><ul><?php foreach ($reportDetailLinks as $reportvalue) {
                if ($reportvalue->Report_Type == 'Flash') {
				     $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
                }else{
                     $report_type = 'vnsreports/index.php?';
                }
                     $reportOption = explode(',', $reportvalue->report_option); ?> 
                <li class="report_text" ><a   <?php if ($reportvalue->report_target == 1) { ?> target='_blank' <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $reportvalue->report_mrt; ?><?php if (in_array('[[++user_id]]', $reportOption)) {
                    echo '&User=' . $this->userId;
                } ?><?php if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && $uniqueCostCenterAll != '') {
                        echo '&Cost_Center_Number=' . rtrim($uniqueCostCenterAll, ',');
                    } else if ((in_array('[[++CostCenterNumber]]', $reportOption)) && $uniqueCostCenter != '') {
                        echo '&Cost_Center_Number=' . $uniqueCostCenter;
                    } ?><?php if ((in_array('[[++KeyBuildingAllBuildings]]', $reportOption)) && $buildIdReportAll != '') {
                        echo '&buildkey=' . rtrim($buildIdReportAll, ',');
                    } else if ((in_array('[[++KeyBuildingNumber]]', $reportOption)) && $buildIdReport != '') {
                        echo '&buildkey=' . $this->select_build_id;
                    } ?><?php if (in_array('[[++BatchNumber]]', $reportOption)) {
                        if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && (in_array('[[++CostCenterAllBuildings]]', $reportOption))) {
                            echo '&Batch_Number=' . rtrim($batch_number_reportall, ',');
                        } else {
                            echo '&Batch_Number=' . rtrim($batch_number_report, ',');
                        }
                    } ?><?php if ((in_array('[[++WONumber]]', $reportOption))) {
                        if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && (in_array('[[++CostCenterAllBuildings]]', $reportOption))) {
                            echo "&WO_Number=" . rtrim($woNumberAllbuilding, ',');
                        } else {
                            echo "&WO_Number=" . rtrim($woNumberAll, ',');
                        }
                    } ?><?php if ((in_array('[[++InvoiceNumber]]', $reportOption))) {
                        if ((in_array('[[++CostCenterAllBuildings]]', $reportOption)) && (in_array('[[++CostCenterAllBuildings]]', $reportOption))) {
                            echo '&Invoice_Number=' . rtrim($invoiceAllbuilding, ',');
                        } else {
                            echo '&Invoice_Number=' . rtrim($invoiceAll, ',');
                        }
                    } ?>" ><?php echo $reportvalue->report_name; ?> </a> </li> <?php } ?> </ul></div>	<?php } ?>	


                <div class="content" id="page">
                    <span class="vendor-heading"><h1>Tenant Information</h1></span>
                    <div id="vendor_search_div">
                                <div id="search_form_div">
                                        <div id="search_message"></div>
                                        <form name="search_form" id="search_form" action="<?php echo BASEURL.'tenant/users/bid/'.$this->select_build_id;?>" method="post">
                                                <div id="form_field"><div style='float:left;'>
                                                       <label class='labelcenter' >Search For</label>
                                                       </div>
                                                       <select name="search_by" id="search_by" onchange="showServiceDropdown(this)">
                                                               <option value="tenantName" <?php echo ($search_by=='tenantName')?'selected':''?>>Tenant Name</option>
                                                               <option value="last_name" <?php echo ($search_by=='last_name')?'selected':''?>>Last Name</option>
                                                               <option value="first_name" <?php echo ($search_by=='first_name')?'selected':''?>>First Name</option>
                                                               <option value="email" <?php echo ($search_by=='email')?'selected':''?>>Email</option>
                                                       </select>
                                                       <div class="text-select-div">
                                                       <div id="search_txt" ><input type="text" name="search_value" id="search_value" value="<?php echo  stripslashes(htmlentities($service_value)); ?>"/></div>

                                                       </div>
                                                 </div>
                                                 <div class="form-button">
                                                          <input type="submit" name="search" id="search" value="Search"/>
                                                          <input type="button" name="reset" id="reset" value="Reset" onclick="window.location.href='<?php echo BASEURL.'tenant/users/bid/'.$this->select_build_id;?>'"/>
                                                 </div>  
                                        </form>

                                </div>
                        </div>
                    <div id="msg">
                        <span class="message">
                            
                    <?php
                    $tm = new Zend_Session_Namespace('tenant_message');
                    echo $tm->msg;
                    $tm->setExpirationSeconds(1);
                    ?>
                        </span>
                        <span class="error-txt" style="color:red;"></span>
                    </div>
                    <div class="row1">
                        Show:
                        <select id="show_limit" onchange="showlimit();" dir="rtl">
                            <option value="10" <?php echo ($this->show==10?"selected":"");?> >10</option>
                            <option value="25" <?php echo ($this->show==25?"selected":"");?>>25</option>
                            <option value="50" <?php echo ($this->show==50?"selected":"");?>>50</option>
                            <option value="100" <?php echo ($this->show==100?"selected":"");?>>100</option>
                            <option value="all" <?php echo ($this->show=='all'?"selected":"");?>>All</option>
                        </select>
                    </div>
                    <div class="tenant-data">
                        <table width="100%" border="1" id="tenantusers">
                            <tr>
                                <th width="4%">&nbsp;</th>
                                <th>Tenant Name</th> 
                            </tr>
        <?php
        
        if (!empty($this->tenantList)) {
            foreach ($this->tenantList as $uinfo) {
               
                ?>
                    <tr>
                        <td><div class="open_plus" id="open_div_<?php echo $uinfo->id; ?>">
                                <a href="javascript:void(0);" id="<?php echo $uinfo->id; ?>" onClick="loadTenantUser(<?php echo $uinfo->id; ?>)";><?php echo '&nbsp;&nbsp;'; ?></a>
                            </div></div>
                            <div class="open_close" id="close_div_<?php echo $uinfo->id; ?>" style="display:none">
                                <a href="javascript:void(0);" id="<?php echo $uinfo->id; ?>" onClick="hideTenantUser(<?php echo $uinfo->id; ?>)";><?php echo '&nbsp;&nbsp;'; ?></a>
                            </div></div>
                        </td>
                        <td><?php echo stripslashes($uinfo->tenantName); ?></td> 
                    </tr>
                    <tr id="trId_<?php echo $uinfo->id; ?>" class="trtenant-class" style="display:none">
                        <td>&nbsp;</td>
                        <td id="loadtenant_<?php echo $uinfo->id; ?>" class="tdtenant-class"></td>
                    </tr>
            <?php } ?>
              <?php
                if (count($this->crDetails) > 0 && !empty($this->crDetails)) {
                    echo '<tr><td colspan="5">';
                    echo $this->paginationControl($this->crDetails, 'Sliding', 'pagination.phtml');
                    echo '</td></tr>';                  
                }

                ?>      
        <?php } else {
            ?>
                                <tr>
                                    <td colspan="2"> Not found in this building.</td>
                                </tr>
                                <?php
        /*
          pagination code.
         */
        ?>   
        <?php
        if (count($this->tenantList) > 0 && !empty($this->tenantList)) {
            echo $this->paginationControl($this->tenantList, 'Sliding', 'pagination.phtml');
        }
        ?>
        <?php } ?>	 
                        </table>
        <?php if ($tenantAccess->is_write == 1) { ?>
                            <div class="add-new-div">
                                <div class="new-tenant-button" style="float:none;">		 
                                    <a class="modalbox" onclick="javascript:addNewTenant('<?php echo $this->baseUrl() . '/tenant/index/bid/' . $this->select_build_id; ?>');" href="#addNewTenant">Add New Tenant Wizard </a>
                                </div> 		  
                            </div>
        <?php } ?> 
                    </div>				   
                    <input type="hidden" name="building_id" id="building_id" value="<?php echo $this->select_build_id; ?>"/>   
    <?php
    } else {
        echo 'No Building has assign to you.';
    }
} else {
    ?>
                You don't have access for this module.
<?php } ?>
        </div>
<?php if ($this->tId) { ?>
            <script type="text/javascript">
                loadTenantUser('<?php echo $this->tId; ?>');
            </script>	
<?php } ?>
        <div class="messageBox"></div>
        <div class="loader" style="display:none;" > <img src="<?php echo BASEURL . 'public/images/loader.gif'; ?>"><div>

                <script>
                        function showlimit(){
                            //alert(12);
                            var data = $("#show_limit").val();
                            window.location =baseUrl+"tenant/users/show/"+data;
                            //return;
                        }
                </script>