<?php 
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/tenant.js');
$roleMapper = new Model_Role();
$roleDetail = $roleMapper->getRole();
$sendMapper = new Model_SendAs();
$sendDetail = $sendMapper->getSendAs();
//var_dump($this->tuserDetial);
?>
<div class="container-right" id="add-tenant-data">
	<span id="page_heading" class="tu-heading"><h3>Tenant User (EDIT)</h3></span>
			 <div class="tenant-user-data">
		
				  <div class="form_head">
						<span><?php echo $this->tenantData->tenantName;?> </span>
						<?php if($this->message && $this->message['msg']!=''){?>
						   <span class="error-msg"><?php echo $this->message['msg'];?></span>
						<?php }?>
				   </div>
				   <section class="w-48 fr ch-home-form">
					  <form name="editUser" id="editUser" action="<?php echo BASEURL.'tenant/edittuser/tuId/'.$this->tuserDetial->uid;?>" method="post">
						  <input type="hidden" value="<?php echo $this->tenantId;?>" name="tenantId" id="tenantId"/>
						  <input type="hidden" value="<?php echo $this->tenantData->buildingId;?>" name="building" id="building"/>
						  <input type="hidden" value="<?php echo $this->tuserDetial->uid;?>" name="uid" id="uid"/>
						  <input type="hidden" value="<?php echo $this->tuserDetial->id;?>" name="id" id="id"/>		
						  <input type="hidden" value="<?php echo $this->roleId;?>" name="role_id" id="role_id"/>
						  <div class="left">				  					  						  					  						  					  
							  <div class="row">
								  <label>User Name :<span class="required">*</span></label> <span class="unameErr" id="uname-error"></span>
                                  <div class="tt-input-div">
								  <input type="text"  id="userName" name="userName" value="<?php echo $this->tuserDetial->userName;?>">
                                  </div>
							   </div>
							  <div class="row">
								<label>E-mail :<span class="required">*</span></label> <span class="uemailErr" id="email-error"></span>
                                <div class="tt-input-div">
								<input type="text" id="email" name="email" value="<?php echo $this->tuserDetial->email;?>">
                                </div>
							   </div>	
							  <div class="row">	
								<label>First name :<span class="required">*</span></label><span class="ufirstErr" id="firstname-error"></span>
                                <div class="tt-input-div"> 	
								<input type="text" required="" id="firstname" class="" name="firstname" value="<?php echo $this->tuserDetial->firstName;?>">
                                </div>
							 </div>	
							<div class="row">	
								
								<label>Last Name :<span class="required">*</span></label><span class="ulastErr" id="lastname-error"></span>
                                <div class="tt-input-div"> 	
								<input type="text" required="" id="lastname" class="" name="lastname" value="<?php echo $this->tuserDetial->lastName;?>">
                                </div>
							</div>	
							<!--<div class="row">	
								<label>Title :</label>		
								<input type="text" required="" id="title" class="" name="title">
							</div>-->
							<div class="row">	
							
							<label>Suite/Location :<span class="required">*</span></label><span class="usuiteErr" id="suite-error"></span> 
                            <div class="tt-input-div">	
							<input type="text" required="" id="suite_location" class="" name="suite_location" value="<?php echo $this->tuserDetial->suite_location;?>">
                            </div>
						</div>
							<div class="row">	
								<label>Office Phone :<span class="required">*</span></label>
								<span class="uofficeErr" id="office-phone-error"></span> 		
                                <div class="tt-input-div">
								<input type="text" id="phone" class="" name="phone" value="<?php echo $this->tuserDetial->phoneNumber;?>" >
                                </div>
							</div>	
							<div class="row">	
								<label>Access :</label>
                                <div class="tt-input-div">
								<select required id="access" class="status" name="access">
									<?php 
									   $selectedRole = array(5, 7);
										foreach ($roleDetail as $ker => $role) {
											if(in_array($role['roleID'], $selectedRole)){
											  echo '<option value="'.$role['roleID'].'"';
											  echo  ($role['roleID']==$this->tuserDetial->role_id)?'selected':'';
											  echo '>'.$role['title'].'</option>';
										   }
										}
									?>                    
								</select>
                                </div>
							</div>	
							<div class="row">
								<label>Send As :</label>
                                <div class="tt-input-div">
								<select name="send_as" id="send_as">
									<?php foreach($sendDetail as $sd){ ?>
										<option value="<?php echo $sd['sid'];?>" <?php echo  ($sd['sid']==$this->tuserDetial->send_as)?'selected':'';?>><?php echo $sd['title'];?></option>
									<?php } ?>	
								</select>
                                </div>
							</div>
							<div class="row">
								<label>Complete Notification :</label>
                                <div class="tt-input-div">
								<select name="complete_notification" id="complete_notification">
									<option value="0" <?php echo  ('0'==$this->tuserDetial->complete_notification)?'selected':'';?>>No</option>
									<option value="1" <?php echo  ('1'==$this->tuserDetial->complete_notification)?'selected':'';?>>Yes</option>
								</select>
                                </div>
							</div>
							<div class="row">
								<label>CC Enable :</label>
                                <div class="tt-input-div">
								<select name="cc_enable" id="cc_enable">
									<option value="0" <?php echo  ('0'==$this->tuserDetial->cc_enable)?'selected':'';?>>No</option>
									<option value="1" <?php echo  ('1'==$this->tuserDetial->cc_enable)?'selected':'';?>>Yes</option>
								</select>
                                </div>
							</div>
							<div class="row">
								<label>Active :</label>
                                <div class="tt-input-div">
								<select name="status" id="status">
									<option value="1" <?php echo  ('1'==$this->tuserDetial->status)?'selected':'';?> >Yes</option>
									<option value="0" <?php echo  ('0'==$this->tuserDetial->status)?'selected':'';?>>No</option>
								</select>
                                </div>
							</div>
							<div class="row">
								<label>Resend Welcome Letter Now :</label>
                                <div class="tt-input-div">
								<select name="welcome_letter" id="welcome_letter">
									<option value="0">No</option>
									<option value="1">Yes</option>
								</select>
                                </div>
							</div>						
								
						</div>
						<div class="right">
							<div id="auto_generate">
								<div class="row">
									<label>Password</label> <span class="passwordErr" id="password-error"></span>
                                    <div class="tt-input-div">
									<input type="password" required="" id="password" class="" name="password" value="">
                                    </div>
								</div>

								<div class="row">
									<label>Confirm Password</label>
                                    <div class="tt-input-div">
									<input type="password" required="" id="confirm_password" class="" name="confirm_password" value="">
                                    </div>
								</div>
							</div>

						 	<div class="row">
								<label>Auto Generate</label>
                                <div class="tt-input-div">
								<input style="width:15px" type="checkbox" value="1" id="auto" class="" name="auto">
                                </div>
							</div>
						</div>		
                        <div class="confirmBtn">								
							<input type="button" value="Confirm" name="next" class="confirm next" onclick="checkUserName()"/>
							<input type="button" value="Cancel" name="cancel" class="cancel" onclick="cancelUser()"/>
					    </div>
					  </form>
				   </section>    
			  </div>
			  </div>
			  
<script type="text/javascript">
	 $("#phone").mask("999.999.9999")
</script>
