<?php
$roleMapper = new Model_Role();
$roleDetail = $roleMapper->getRole();
$role_data = array();
foreach($roleDetail as $rd){
	$role_data[$rd['roleID']] = $rd['title'];
}

$sendMapper = new Model_SendAs();
$sendDetail = $sendMapper->getSendAs();
$send_data = array();
foreach($sendDetail as $sd){
	$send_data[$sd['sid']] = $sd['title'];
}
$uinfo = $this->tenantData[0];
//var_dump($this->tenantData);
$tenantAccess = $this->acesshelper->checkAccess($this->roleId,$this->tenant_location);
?>
<div>
  <?php if($tenantAccess->is_access == 0){
	    if($tenantAccess->is_write == 1){
	  ?>	
   <div class="tenant-info-div">
	    <div id="left_section">                                  
			  <div class="field_edit_popup">
				<li class="required">&nbsp;</li><label>Tenant Name</label> <span>:</span>
				 <?php //echo (!empty($uinfo->tenantName))?$uinfo->tenantName:''; ?>
				<a href="#" class="tenantName" id="tenantName-<?php echo $uinfo->id; ?>" ><?php echo (!empty($uinfo->tenantName))?$uinfo->tenantName:''; ?></a>
				<input type="hidden" name="role_id" id="role_id" value="9"/>
			  </div>
			  <div class="field_edit_popup">
				<li class="required">&nbsp;</li><label>Tenant Contact</label> <span style="float:left;">:</span>
				 <a style="display:table-cell; padding: 0 0 0 3px;" href="#" class="tenantContact" id="tenantContact-<?php echo $uinfo->id; ?>" data-type="text" data-pk="<?php echo $uinfo->id; ?>" data-url="<?php echo $this->baseUrl().'/tenant/updatetenant';?>" data-title="Enter Tenant Contact" data-placeholder="Required" data-name="tenantContact"><?php echo (!empty($uinfo->tenantContact))?$uinfo->tenantContact:''; ?></a>										
			  </div>
			  <div class="field_edit_popup">
				<li class="required">&nbsp;</li><label>Address </label> <span style="float:left;">:</span>
                <div class="tu-address-div">
				 <span style="padding: 0 0 0 3px;"><?php echo $uinfo->address1;?></span>
				 <span style="padding: 0 0 0 3px;"><?php echo $uinfo->address2;?></span>											 
                 </div>
			  </div>	  

			  <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label>Suite</label> <span style="float:left;">:</span>
				 <a style="display:table-cell; padding: 0 0 0 3px;" href="#" class="suite" id="suite-<?php echo $uinfo->id; ?>" data-type="text" data-pk="<?php echo $uinfo->id; ?>" data-url="<?php echo $this->baseUrl().'/tenant/updatetenant';?>" data-title="Enter suite" data-placeholder="Required" data-name="suite"><?php echo (!empty($uinfo->suite))?$uinfo->suite:''; ?></a>										
			  </div>
			   <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label>City,State,Postal Code</label> <span style="float:left;">:</span>
				 <span style="display:table-cell; padding: 0 0 0 3px;"><?php echo $uinfo->city.',  '.$uinfo->state.',  '.$uinfo->postalCode;?></span>										
			  </div>
			  <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label>Phone Number</label> <span style="float:left;">:</span>
				 <a style="display:table-cell; padding: 0 0 0 3px;" href="#" class="phoneNumber" id="phoneNumber-<?php echo $uinfo->id; ?>" data-type="text" data-pk="<?php echo $uinfo->id; ?>" data-url="<?php echo $this->baseUrl().'/tenant/updatetenant';?>" data-title="Enter Phone number" data-placeholder="Required" data-name="phoneNumber"><?php echo (!empty($uinfo->phoneNumber))?$uinfo->phoneNumber:''; ?></a>										
			  </div>
		 </div> 
		 <div id="right_section">
			  <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label class="tnt_baddress">Bill to Address</label> <span style="float:left;">:</span>
				<a style="display:table-cell;" href="#" class="billtoAddress" id="billtoAddress-<?php echo $uinfo->id; ?>" data-type="textarea" data-pk="<?php echo $uinfo->id; ?>" data-url="<?php echo $this->baseUrl().'/tenant/updatetenant';?>" data-title="Enter Bill to Address" data-placeholder="Required" data-name="billtoAddress"><?php echo nl2br((!empty($uinfo->billtoAddress))?$uinfo->billtoAddress:''); ?></a>										
			 
              </div>
			  <div class="field_edit_popup">
					 <li class="not_required">&nbsp;</li><label>Active </label> <span>:</span>
					 <span><?php echo ($uinfo->status)?'Yes':'No';?></span>													 										 
			  </div>
			  <div class="field_edit_popup">
					 <li class="not_required">&nbsp;</li><label>Remove Tenant </label> <span>:</span>
			 <span><a href="javascript:void(0);"  title="Delete" onclick="deleteTenant('<?php echo $this->tenantId;?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a></span>													 										 
			  </div>
			  <div class="field_edit_popup">
					 <li class="not_required">&nbsp;</li><label>Send Welcome letter all Users </label> <span>:</span>
			 <span><a title="Send" onClick="return sendtenantemail('<?php echo $this->tenantId;?>');" href="javascript:void(0);"><img src="<?php echo BASEURL . 'public/images/send-email.png'?>" /></a></span>													 										 
			  </div>
		 </div> 	
    </div>
	<div class="tuser-list">
		<table width="100%" class="building_table_grid">
			<tr>
				<th>Last Name</th>
				<?php /*<th>First Name</th>	*/?>		
				<th>E-mail Address</th>
				<th>Cc Enabled</th>
				<th>Send As</th>
				<th>Access</th>
				<th>Complete Notification</th>
				<th>Status</th>
				<th style="border:none;">Action</th>
			</tr>
			<?php if($this->tenantuser){
					 foreach($this->tenantuser as $tuser){
						 //var_dump($tuser);
				 ?>
				 <tr>
					 <td><?php echo $tuser->lastName;?></td>
					 <?php /*<td><?php echo $tuser->firstName;?></td>*/?>				 
					 <td><?php echo $tuser->email;?></td>
					 <td><?php echo ($tuser->cc_enable)?'Yes':'No';?></td>
					 <td><?php echo $send_data[$tuser->send_as];?></td>
					 <td><?php echo $role_data[$tuser->role_id]?></td>
					 <td><?php echo ($tuser->complete_notification)?'Yes':'No';?></td>
					 <td><?php echo ($tuser->status)?'Yes':'No';?></td>
					 <td>
						 <a title="Edit" href="<?php echo BASEURL.'tenant/edittuser/tuId/'.$tuser->uid;?>" ><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						 <a href="javascript:void(0);"  title="Delete" onclick="deleteTenantUser('<?php echo $this->tenantId;?>','<?php echo $tuser->uid;?>','<?php echo count($this->tenantuser); ?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						 <a title="Send" onClick="return sendemail('<?php echo $this->tenantId;?>','<?php echo $tuser->uid;?>');" href="javascript:void(0);"><img src="<?php echo BASEURL . 'public/images/send-email.png'?>" width="25" height="25"/></a>
					 </td>
				 </tr>
				 
			<?php    }
				 }else{
					echo '<tr><td colspan="8"> No Tenant User </td></tr>'; 
				 }
			?>
			<tr>
				<td class="add_record" style="border-right:1px solid #848484;" colspan="8"> 
					<a href="<?php echo BASEURL.'tenant/addtuser/tId/'.$uinfo->id; ?>">Add New User </a>
				</td>
			</tr>			
		</table>
	 </div>
	 <?php }else {?>
		    <div class="tenant-info-div">
	    <div id="left_section">                                  
			  <div class="field_edit_popup">
				<li class="required">&nbsp;</li><label>Tenant Name</label> <span>:</span>
				 <?php //echo (!empty($uinfo->tenantName))?$uinfo->tenantName:''; ?>
				<span style="padding: 0 0 0 3px;"><?php echo (!empty($uinfo->tenantName))?$uinfo->tenantName:''; ?></span>
				<input type="hidden" name="role_id" id="role_id" value="9"/>
			  </div>
			  <div class="field_edit_popup">
				<li class="required">&nbsp;</li><label>Tenant Contact</label> <span style="float:left;">:</span>
				 <span style="padding: 0 0 0 3px;"><?php echo (!empty($uinfo->tenantContact))?$uinfo->tenantContact:''; ?></span>										
			  </div>
			  <div class="field_edit_popup">
				<li class="required">&nbsp;</li><label>Address </label> <span style="float:left;">:</span>
                <div class="tu-address-div">
				 <span style="padding: 0 0 0 3px;"><?php echo $uinfo->address1;?></span>
				 <span style="padding: 0 0 0 3px;"><?php echo $uinfo->address2;?></span>											 
                 </div>
			  </div>	  

			  <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label>Suite</label> <span style="float:left;">:</span>
				 <span style="padding: 0 0 0 3px;"><?php echo (!empty($uinfo->suite))?$uinfo->suite:''; ?></span>										
			  </div>
			   <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label>City,State,Postal Code</label> <span style="float:left;">:</span>
				 <span style="display:table-cell; padding: 0 0 0 3px;"><?php echo $uinfo->city.',  '.$uinfo->state.',  '.$uinfo->postalCode;?></span>										
			  </div>
			  <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label>Phone Number</label> <span style="float:left;">:</span>
				 <span style="padding: 0 0 0 3px;"><?php echo (!empty($uinfo->phoneNumber))?$uinfo->phoneNumber:''; ?></span>										
			  </div>
		 </div> 
		 <div id="right_section">
			  <div class="field_edit_popup">
				 <li class="required">&nbsp;</li><label class="tnt_baddress">Bill to Address</label> <span style="float:left;">:</span>
				<span style="padding: 0 0 0 3px;"><?php echo nl2br((!empty($uinfo->billtoAddress))?$uinfo->billtoAddress:''); ?></span>										
			 
              </div>
			  <div class="field_edit_popup">
					 <li class="not_required">&nbsp;</li><label>Active </label> <span>:</span>
					 <span><?php echo ($uinfo->status)?'Yes':'No';?></span>													 										 
			  </div>			  
		 </div> 	
    </div>
	<div class="tuser-list">
		<table width="100%" class="building_table_grid">
			<tr>
				<th>Last Name</th>
				<?php /*<th>First Name</th>	*/?>		
				<th>E-mail Address</th>
				<th>Cc Enabled</th>
				<th>Send As</th>
				<th>Access</th>
				<th>Complete Notification</th>
				<th>Status</th>
				<?php /*<th style="border:none;">Action</th>*/?>
			</tr>
			<?php if($this->tenantuser){
					 foreach($this->tenantuser as $tuser){
						 //var_dump($tuser);
				 ?>
				 <tr>
					 <td><?php echo $tuser->lastName;?></td>
					 <?php /*<td><?php echo $tuser->firstName;?></td>*/?>				 
					 <td><?php echo $tuser->email;?></td>
					 <td><?php echo ($tuser->cc_enable)?'Yes':'No';?></td>
					 <td><?php echo $send_data[$tuser->send_as];?></td>
					 <td><?php echo $role_data[$tuser->role_id]?></td>
					 <td><?php echo ($tuser->complete_notification)?'Yes':'No';?></td>
					 <td><?php echo ($tuser->status)?'Yes':'No';?></td>
					 <?php /*<td>
						 <a title="Edit" href="<?php echo BASEURL.'tenant/edittuser/tuId/'.$tuser->uid;?>" ><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						 <a href="javascript:void(0);"  title="Delete" onclick="deleteTenantUser('<?php echo $this->tenantId;?>','<?php echo $tuser->uid;?>','<?php echo count($this->tenantuser); ?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						 <a title="Send" onClick="return sendemail('<?php echo $this->tenantId;?>','<?php echo $tuser->uid;?>');" href="javascript:void(0);"><img src="<?php echo BASEURL . 'public/images/send-email.png'?>" width="25" height="25"/></a>
					 </td>
					 */ ?>
				 </tr>
				 
			<?php    }
				 }else{
					echo '<tr><td colspan="8"> No Tenant User </td></tr>'; 
				 }
			?>						
		</table>
	 </div>
	    <?php }?>	 
	<?php }else{
	           echo 'You don\'t have access for this module.';
		   }
	     ?> 
</div>
<script type="text/javascript">
	var checkTenaant = '';
$( document ).ready(function() {
	
	$.fn.editable.defaults.mode = 'popup';
	/*$('.tenantName').editable({
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
           if(value!=''){
			   checkExistTenant(value);
			   alert(checkTenaant);
			   if(!checkExistTenant(value))return 'This tenant is already in use.';
		   }
        }
	});*/
	$('.tenantName').editable({
	        validate: function(value) {
               if($.trim(value) == '') return 'This field is required';
            },
		    type: 'text',
			url: baseUrl+'tenant/updatetenantname/building/'+'<?php echo $uinfo->buildingId; ?>',    
			pk: '<?php echo $uinfo->id; ?>',
			name:'tenantName',    
			title: 'Enter tenant name',						
			success: function(response, newValue) {				
				if(!response) {
					return "Unknown error!";
				}          
				
				if(response === 'true') {
					 return "This tenant is already in use.";
				}
			}
    });    
    

	$('.tenantContact').editable({
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
        }
	});
	
	
	$('.phoneNumber').editable({
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
           var isValid = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/.test(value);
			if (!isValid){
				return 'The \'Phone Number\' in the xxx.xxx.xxxx format';
			}

        }
	});
		

	$('.suite').editable({
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
        }
	});

	$('.city').editable({
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
        }
	});
	

	$('.billtoAddress').editable({
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
        }
	});
});

function checkExistTenant(tName){
	//var tenantName = $('#tenantName').val();
	var building = '<?php echo $uinfo->buildingId; ?>';
	var tId = '<?php echo $uinfo->id; ?>';
	if(tName!=''){
		 $.ajax({
                url         : baseUrl+"tenant/checkexisttenant",
                type        : "post",
                //datatype    : 'json',
                data        : {tenantName:tName,building:building,tId:tId},
                success     : function( data ) {									
                   if(data == 'false'){
					 checkTenaant = 'new val';                       
                   }else{                    
					 checkTenaant = 'ntrue';  
                   }
                }                
	        });
       }   
	   
}
</script>
