<?php    $this->headLink()->appendStylesheet($this->baseUrl() . '/public/tabs.css');
   echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/tenant.js');      
 ?>
<?php

$this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap-editable.css');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap-editable.js');

?>
<?php
$roleMapper = new Model_Role();
$roleDetail = $roleMapper->getRole();
$role_data = array();
foreach($roleDetail as $rd){
	$role_data[$rd['roleID']] = $rd['title'];
}

$tenantAccess = $this->acesshelper->checkAccess($this->roleId,$this->tenant_location);
?>
<div class="container-right" id="userinfo-data">
    <?php 
       if($this->roleId!=1 && $tenantAccess->is_access == 0 && $tenantAccess->is_read == 1){ 
    if($this->custID!=null && $this->custID && $this->companyListing!='' && $this->companyListing!=false){?>
		<div id="contents">
			<ol id="toc">
				<?php 
					$j = 1;
					foreach($this->companyListing as $cb){ ?>					
					<li><a href="<?php echo $this->baseUrl().'/tenant/users/bid/'.$cb['build_id']; ?>" <?php if($cb['build_id']==$this->select_build_id) echo 'class="active"';?>><span><?php echo $cb['buildingName']; ?></span></a></li>
				<?php $j++; } ?>
			</ol>					
			<div class="content" id="page">
			 <span id="page_heading"><h3>Tenant Information</h3></span>
			 <div id="msg">
				 <span class="message">
					 <?php $tm = new Zend_Session_Namespace('tenant_message'); 
						 echo $tm->msg;
						$tm->setExpirationSeconds(1);
					 ?>
				 </span>
		         <span class="error-txt" style="color:red;"></span>
		       </div>
			 <div class="tenant-data">
				 <table width="100%" border="1">
					 <tr>
						<th width="4%">&nbsp;</th>
						<th>Tenant Name</th> 
					 </tr>
					 <?php
					      if(!empty($this->tenantList)){									
							 foreach($this->tenantList as $uinfo){
					 ?>
					 <tr>
						<td><div class="open_plus" id="open_div_<?php echo $uinfo->id;?>"><a href="javascript:void(0);" id="<?php echo $uinfo->id;?>" onClick="loadTenantUser(<?php echo $uinfo->id;?>)";><?php echo '&nbsp;&nbsp;';?></a></div></div>
						    <div class="open_close" id="close_div_<?php echo $uinfo->id;?>" style="display:none"><a href="javascript:void(0);" id="<?php echo $uinfo->id;?>" onClick="hideTenantUser(<?php echo $uinfo->id;?>)";><?php echo '&nbsp;&nbsp;';?></a></div></div>
						</td>
						<td><?php echo $uinfo->tenantName;?></td> 
					 </tr>
					 <tr id="trId_<?php echo $uinfo->id; ?>" class="trtenant-class" style="display:none">
					     <td>&nbsp;</td>
					     <td id="loadtenant_<?php echo $uinfo->id; ?>" class="tdtenant-class"></td>
					 </tr>
					 <?php }
					 }else{?>
						 <tr>
						<td colspan="2"> No User is listed for this building.</td>
					 </tr>
					 <?php }?>	 
				 </table>
				 <?php if($tenantAccess->is_write == 1){?>
				 <div class="add-new-div">
		            <div class="new-tenant-button" style="float:none;">		 
		               <a href="<?php echo $this->baseUrl().'/tenant/index/bid/'.$this->select_build_id;?>">Add New Tenant Wizard </a>
					</div> 		  
				  </div>
				 <?php }?> 
			 </div>				   
	  <input type="hidden" name="building_id" id="building_id" value="<?php echo $this->select_build_id;?>"/>   
   <?php }
	   else{
		   echo 'No Building has assign to you.';
	   }  
	  }else{?>
	    You don't have access for this module.
	  <?php }?>
</div>
<?php if($this->tId){?>
<script type="text/javascript">
	loadTenantUser('<?php echo $this->tId;?>');
</script>	
<?php }?>
<div class="messageBox"></div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
