<?php    $this->headLink()->appendStylesheet($this->baseUrl() . '/public/tabs.css');
         $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap.css');
         $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/bootstrap-editable.css');
 ?>
<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/user_info.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap.js');
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bootstrap-editable.js');

// to check the read,write and no access
$user_info = $this->acessHelper->checkAccess($this->roleId,$this->user_info_id); 
/*
 * users info section
 */
?>
<?php
$roleMapper = new Model_Role();
$roleDetail = $roleMapper->getRole();
//var_dump($roleDetail);
$role_data = array();
foreach($roleDetail as $rd){
	$role_data[$rd['roleID']] = $rd['title'];
}
?>
<div class="container-right" id="userinfo-data">
    <?php 
       if($this->roleId!=1){ 
    if($this->custID!=null && $this->custID){?>
		<div id="contents">		
			<section id="first" class="w-48 fr ch-home-form" style="z-index:9999">
				<div class="ch-form-header ">
					<h3>User Information</h3>
				</div>
				<div class="content-page" id="content">
				     <div id="accordion-info">
				       <?php							
							if(!empty($this->select_build_id)){
								$userList = $this->tuserlist;//$companyModel->getUserByBuildingId($buildId);
								$user_write = 1;
								if($userList){
									foreach($userList as $uinfo){	
                                        //var_dump($uinfo);
                                       // exit;
									 if($uinfo){									 
								?>
									 <h3><?php echo $uinfo->lastName.', '.$uinfo->firstName;?></h3>
									 <div>
									 <?php if($user_write==1){ ?>
										  <div class="field_edit_popup">
											 <label>First Name</label><span>:</span>
									         <a href="#" class="firstName" id="firstName-<?php echo $uinfo->uid; ?>" data-type="text" data-pk="<?php echo $uinfo->uid; ?>" data-url="<?php echo $this->baseUrl().'/company/updateuser';?>" data-title="Enter User's First Name" data-placeholder="Required" data-name="firstName"><?php echo (!empty($uinfo->firstName))?$uinfo->firstName:''; ?></a>
									       </div>
											
										  <div class="field_edit_popup">
											 <label>Last Name</label> <span>:</span>
										     <a href="#" class="lastName" id="lastName-<?php echo $uinfo->uid; ?>" data-type="text" data-pk="<?php echo $uinfo->uid; ?>" data-url="<?php echo $this->baseUrl().'/company/updateuser';?>" data-title="Enter User's Last Name" data-placeholder="Required" data-name="lastName"><?php echo (!empty($uinfo->lastName))?$uinfo->lastName:''; ?></a>										
										  </div>
										  <div class="field_edit_popup">
											 <label>Title</label> <span>:</span>
										     <a href="#" class="title" id="title-<?php echo $uinfo->uid; ?>" data-type="text" data-pk="<?php echo $uinfo->uid; ?>" data-url="<?php echo $this->baseUrl().'/company/updateuser';?>" data-title="Enter User's Title" data-placeholder="Required" data-name="Title"><?php echo (!empty($uinfo->Title))?$uinfo->Title:''; ?></a>										
										  </div>
										  <div class="field_edit_popup">
											 <label>Phone Number</label> <span>:</span>
										     <a href="#" class="phone" id="phone-<?php echo $uinfo->uid; ?>" data-type="text" data-pk="<?php echo $uinfo->uid; ?>" data-url="<?php echo $this->baseUrl().'/company/updateuser';?>" data-title="Enter User's Phone Number" data-placeholder="Required" data-name="phoneNumber"><?php echo (!empty($uinfo->phoneNumber))?$uinfo->phoneNumber:''; ?></a>										
										    </div>
										    <div class="field_edit_popup"> 
										      <label>Ext</label> <span>:</span>
										     <a href="#" class="phoneExt" id="phoneExt-<?php echo $uinfo->uid; ?>" data-type="text" data-pk="<?php echo $uinfo->uid; ?>" data-url="<?php echo $this->baseUrl().'/company/updateuser';?>" data-title="Enter User's Phone Ext"  data-name="phoneExt"><?php echo (!empty($uinfo->phoneExt))?$uinfo->phoneExt:''; ?></a>
										  </div>
										  <div class="field_edit_popup">
											  <label>Email</label> <span>:</span>
											  <?php echo (!empty($uinfo->email))?$uinfo->email:''; ?>
										  </div>
										   <div class="field_edit_popup">
											 <label>User Access</label> <span>:</span>
										     <?php echo $role_data[$uinfo->role_id]; ?>
										  </div>
										  <?php }
										  else{
										   ?>

										  <div class="field_edit_popup">
											 <label>First Name</label><span>:</span>
									         <?php echo (!empty($uinfo->firstName))?$uinfo->firstName:'Empty'; ?>
									       </div>
											
										  <div class="field_edit_popup">
											 <label>Last Name</label> <span>:</span>
										     <?php echo (!empty($uinfo->lastName))?$uinfo->lastName:'Empty'; ?>										
										  </div>
										  <div class="field_edit_popup">
											 <label>Title</label> <span>:</span>
										     <?php echo (!empty($uinfo->Title))?$uinfo->Title:'Empty'; ?>										
										  </div>
										  <div class="field_edit_popup">
											 <label>Phone Number</label> <span>:</span>
										     <?php echo (!empty($uinfo->phoneNumber))?$uinfo->phoneNumber:'Empty'; ?>										
										    </div>
										    <div class="field_edit_popup"> 
										      <label>Ext</label> <span>:</span>
										     <?php echo (!empty($uinfo->phoneExt))?$uinfo->phoneExt:'Empty'; ?>
										  </div>
										  <div class="field_edit_popup">
											  <label>Email</label> <span>:</span>
											  <?php echo (!empty($uinfo->email))?$uinfo->email:'Empty'; ?>
										  </div>
										   <div class="field_edit_popup">
											 <label>User Access</label> <span>:</span>
										     <?php echo $role_data[$uinfo->role_id]; ?>									
										  </div>
										  <?php } ?>
									 </div>
									 
							<?php 	}
							        }
							      }else{
									  echo 'No User is listed for this building';
								  }
								 }
							 ?>
							 
				     </div>
				</div>	
				</section>	
	  </div>
	  <div class="add-new-div">
		    <div class="new-tenant-button">		 
		      <a href="<?php echo $this->baseUrl().'/tenant/createuser/bid/'.$this->select_build_id;?>">Add New User >></a>
		    </div> 		  
	  </div>     
   <?php }
	   else{
		   echo 'No Building has assign to you.';
	   }  
	  }else{?>
	    You don't have access for this module.
	  <?php }?>
</div>

<div class="messageBox"></div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
<script src="http://blixt.org/media/a/1/tabs-js/activatables.js" type="text/javascript"></script>
<script type="text/javascript">	
	$(function() {		
			$( "#accordion-info" ).accordion({
				heightStyle: "content",
				animate: 1000,
				collapsible: true
			});
		
		$('.access').editable({
		source: [
		<?php foreach($roleDetail as $role){
			if($role['roleID']!='1' && $role['roleID']!=9){
			?>
        {value: <?php echo $role['roleID']?>, text: '<?php echo $role['title']?>'},       
        <?php }
        }?>
       ],
		validate: function(value) {
           if($.trim(value) == '') return 'This field is required';
        }
	});		
	});	
</script>
