<?php
	$companyModel = new Model_Company();
	$nottenant = 1; // this for not listing the tenant user here.
	$users = $companyModel->getUserByBuildingId($this->bId,$nottenant);
	$blModel = new Model_BillLabor();
	$blList = $blModel->getActiveBillLaborByBId($this->bId);
	
	 $brModel = new Model_BillRate();
	 $brList = $brModel->getActiveBillRateByBId($this->bId);
	 
	 $job_time = '00:00'; 
	 
	$wpModel = new Model_WoParameter();
	$wpDetails = $wpModel->getWoParameterByBid($this->bId);
	
	if($wpDetails){
		$time_charge = $wpDetails[0]['time_min_charge'];
		$time_fact = explode(" ",$time_charge);
		$time_fact_measure=trim($time_fact[1]);
		$time_fact_minute=trim($time_fact[0]);
		if($time_fact_measure=='Minutes') { $job_time = '00:'.$time_fact[0]; } else { $job_time = $time_fact[0].':00';  }
	}
	
	$laborData = $this->laborData[0];
?>
<script type="text/javascript">
	var labor_user = [];
	var labor_charge = [];
	var default_lcharge = [];
	<?php if($blList){
		  foreach($blList as $bl){
			  if($bl['assign_to']!=''){
				  $bl_users = explode(",",$bl['assign_to']);
				  foreach($bl_users as $buser){					  
					  ?>
					  if(!labor_user['<?php echo $buser?>']){
						  labor_user['<?php echo $buser?>'] = '<?php echo $bl['blid'];?>';
					  }
				 <?php	  
				  }
		      }
		      
		      if($bl['set_default']=='1'){
				  ?>
				  default_lcharge['dft_charge'] = '<?php echo $bl['charge_hour'];?>';
				  default_lcharge['dft_labor'] = '<?php echo $bl['blid'];?>';
				 <?php 
			  }
		      ?>
		      labor_charge['<?php echo $bl['blid'];?>'] = '<?php echo $bl['charge_hour'];?>';
		   <?php 
		   }		
		}?>
	
</script>
<div id="ct_labor_fm_div" class="bd-dft-cls">
	<h1>Edit Labor Charges</h1>
	<span>Enter Employee Informations</span>
	<div class="message">
		<span id="success_msg" class="success"></span>
		<span id="error_msg" class="error"></span>
	</div>
	<div id="labor_form_ data">
		 <div class="cw_row">
			 <label>Employee</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_emp"></span>
				 <select name="emp_id" id="edit_emp_id" onchange="setCharge(this.value)">
					 <option value="">-- Select --</option>
					 <?php
					 if($users){ 
					     foreach ($users as $key => $value) { ?>
							<option value="<?php echo $value->uid; ?>"
							  <?php if($laborData['emp_id']==$value->uid) echo 'selected="selected"';?>	>
								<?php echo stripslashes($value->lastName).','. stripslashes($value->firstName); ?>
							</option>
					<?php }
					} ?>
				 </select>
			 </div>
		 </div>
		 <div class="cw_row">
			  <label>Charge/Hour($)</label>
			  <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_charge"></span>
				 <div class="charge_field">
					   <input type="text" name="charge_hour" id="edit_charge_hour" value="<?php echo $laborData['charge_hour'];?>" onkeypress="return isNumber(event)">
					   <span class="field_error" id="cwerr_charge1"></span>
					   <select name="labor_charge" id="edit_labor_charge" onchange="setLaborCharge(this.value)">
							 <option value="">-- Select --</option>
							 <?php
							 if($blList){ 
								 foreach ($blList as $bl) { ?>
									<option value="<?php echo $bl['blid']; ?>"
									   <?php if($laborData['bl_id']==$bl['blid']) echo 'selected="selected"';?>>
										<?php echo $bl['description']; ?>
									</option>
							<?php }
							} ?>
						</select>
				 </div>	 
			  </div>
		 </div>
		 <div class="cw_row">
			 <label>Rate Charge</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_rate"></span>
				 <select name="rate_charge" id="edit_rate_charge">
					 <option value="">-- Select --</option>
					 <?php
							 if($brList){ 
								 foreach ($brList as $br) { ?>
									<option value="<?php echo $br['brid']; ?>"
									 <?php if($laborData['rate_charge']==$br['brid']) echo 'selected="selected"';?>>
										<?php echo $br['description']; ?>
									</option>
							<?php }
							} ?>
				 </select>
	 		 </div>
		 </div>
		 <div class="cw_row">
			 <label>Job Time (HH:MM)</label>
			 <div class="cw-ibox-row">
				 <span class="field_error" id="cwerr_job"></span>
				 <input type="text" name="job_time" id="edit_job_time" value="<?php echo $laborData['job_time'];?>" onkeypress="return isTime(event)" maxlength="5" onkeydown="return isOldValuee(event)"/>
			 </div>
		 </div>
	</div>
	<div class="buttons">
	                <input type="hidden" id="edittemplabor" value="">
	                <input type="hidden" id="edit_historywoId" value="<?php echo $this->laborData[0]['woId']; ?>">
				   <button type="button" name="save_labor" id="save_labor" value="Save" onclick="updateLaborDataTemp('<?php echo $this->lid;?>')">Save</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelLaborFormEdit()">Cancel</button>
	  </div>
</div>

<script>
    var edit_old_job_time=$("#edit_job_time").val();
	function isOldValuee() {
	edit_old_job_time=$("#edit_job_time").val();
	}
    $('#edit_job_time').bind('input', function() {
        var edit_job_time= $("#edit_job_time").val();
		
        var edit_job_time_split = edit_job_time.split(":");
		if(edit_job_time_split.length == 2) {
		    if(edit_job_time_split[1].length <= 2 && edit_job_time_split[0].length <= 2 ) {
               if(parseInt(edit_job_time_split[1]) < 60 || isNaN(parseInt(edit_job_time_split[1]))) {
				  if(parseInt(edit_job_time_split[0])!=0) {
				  if(isNaN(parseInt(edit_job_time_split[0]))) {
				   $("#edit_job_time").val('00'+':'+edit_job_time_split[1]);
				  } else{
				     $("#edit_job_time").val(parseInt(edit_job_time_split[0])+':'+edit_job_time_split[1]);
					 }
					 }
		        } else {
				     var edit_old_job_time_split = edit_old_job_time.split(":");
					 if(parseInt(edit_old_job_time_split[0])!=0) {
				     $("#edit_job_time").val(parseInt(edit_old_job_time_split[0])+':'+edit_old_job_time_split[1]);
					 } else {
					 $("#edit_job_time").val(edit_old_job_time);
					 }
				}		
		
				} else { 
					//return false;  
					}
		
			} else {
				
				//return false; 
			} 
    }); 
</script>