<table class="table table-striped table-responsive">
		<tr class="invoice_tab_heading"> 
		<td>
		List of Billable Invoices</div>
	</td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	</tr>
		<tr>
			<td>Invoice Number</td>
			<td>Tenant Name</td>
			<td>Description</td>
			<td>Invoice Date</td>
			<td>Batch Invoice Number</td>
		</tr>
		<?php foreach($this->wolist as $value) { ?>
		<tr>
			<td><input type="checkbox"/> <span><?php echo $value->wo_number; ?></span></td>
			<td><?php echo $value->tenantName; ?></td>
			<td><?php echo $value->categoryName; ?></td>
			<td>September 20151</td>
			<td></td>
		</tr>
		<?php } ?>
	
			
	</table>
	