<?php	
	 $materialModel = new Model_Material();
	 $materialList = $materialModel->getActiveMaterialByBId($this->bId);
	 	
?>

<h1>Material</h1>
			   <div id="lab_tab" class="tab_content cwo_content">
			   <div class="grid_content" style="height:180px;">
											  <table name="labor_grid" class="cw_table_grid" width="100%">
												  <tr>
													  <th>Description</th>
													  <th>Cost</th>
													  <th>Quantity</th>
													  <th>Mark-Up(%)</th>
													  <th>Tax</th>
												  </tr> 
												   <tr><?php if($this->current_value!='null' && $this->current_value!='') { ?><td><?php 
										        if($materialList){ 
					                                foreach ($materialList as  $ml) { if($this->current_value['material_id']==$ml['mid']) {echo stripslashes($ml['description']); }} } ?></td>
												
												<td><?php echo $this->current_value['cost'];?></td>
												<td><?php echo $this->current_value['quantity'];?></td>
												<td><?php echo $this->current_value['markup'];?></td>
												<td><?php if($this->current_value['tax']=='1'){ echo "Yes"; } else { echo "No"; }?></td>
											<?php } else { ?>
											<td colspan=5 style="text-align:center"><?php echo HiSTORY_NONE; ?></td>
											<?php } ?>
											</tr>
												  
												 
												<tr style="background:none"> <td colspan="5" > 
											<div style="text-align:center">	<span style="font-size:20px; font-weight:bold;"><i class="fa fa-arrow-circle-down big-arrow"></i>
</span>  </div>
											</td>
											</tr>
												  
												 <?php if($this->change_value!='') { ?>
												
												  <tr>
													<tr><td><?php 
										        if($materialList){ 
					                                foreach ($materialList as  $ml) { if($this->change_value['material_id']==$ml['mid']) {echo stripslashes($ml['description']); }} } ?></td>
												
												<td><?php echo $this->change_value['cost'];?></td>
												<td><?php echo $this->change_value['quantity'];?></td>
												<td><?php echo $this->change_value['markup'];?></td>
												<td><?php if($this->change_value['tax']=='1'){ echo "Yes"; } else { echo "No"; }?></td>
													
											
											 
												  <?php }  else { ?>
											<td colspan=5 style="text-align:center"><?php echo HiSTORY_NONE; ?></td>
											<?php } ?>
											</tr>
												  </table>
												  </div> </div>
												  <div class="buttons">
		<button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelWoDesc()">Cancel</button>
	    </div> 