<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/complete_workorder.js');
$closewo_access = $this->acessHelper->checkAccess($this->roleId,$this->closewo_location);
if($this->roleId !='1' && $closewo_access->is_access==0){
?>
<div class="wo-container">
	<div class="cmp_order_container" id="fdw">
		 <div id="building_options" align="right" class="opt-btn">
			  <button type="button" name="build_opt" id="build_opt" onclick="showParameter('<?php echo $this->select_build_id;?>')">Building Options</button>
		 </div>
		 <div class="building-list tabmenu my_tabmenu">
			 <ul>
				 <?php  
					  $color_code = array('00FFFF','FF0000','FF00FF','800000','008000','800080','808000','0000FF','00FF00','000080','FFFF00','808000','008080','FFA500');
						$j = 1;
						foreach($this->companyListing as $cb){ 
							//$building_color[$cb['build_id']] = $color_code[$j];
							?>
						<li style="background-color:#<?php echo $color_code[$j]?>"><a href="<?php echo $this->baseUrl().'/complete/workorder/bid/'.$cb['build_id']; ?>" <?php if($cb['build_id']==$this->select_build_id) echo 'class="resp-tab-active my_resp-tab-active"';?>><?php echo $cb['buildingName']; ?></a></li>
			
				 <?php $j++; } ?>  
			</ul>
		 </div>
		 <div class="workorder-info">
			  <h1>Complete Work Orders</h1>
			  <div class="search-row">
				   <div class="wo-search">
					   <label> Work Order Number:</label>
					   <div id="cw_wo_search">
						   <span class="field_error" id="wd_err"></span>
					       <input type="text" name="work_order" id="work_order" onkeypress="return isNumber(event)"/>
							<span class="my_se_icon">
								<a href="javascript:void(0)" name="submit" onclick="showWorkOrder('<?php echo $this->select_build_id;?>')"><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a>
							 </span>
						</div> 
				   </div>
				   <div class="cw_message" id="cw_message">
							<span id="cw_success" class="success"></span>
							<span id="cw_error" class="error"></span>
				   </div>
				   <div class="chk-div">
					   <label><input type="checkbox" name="billable_opt" id="billable_opt" value="1"/> Billable</label>
					   <label><input type="checkbox" name="tenant_mail" id="tenant_mail" value="1" /> E-Mail Tenant When Completed </label>
				   </div>  
			  </div>
			  <?php if($this->woData!=''){ 
					$workOrder = $this->woData;
					 $wpModel = new Model_WorkOrderUpdate();
					 $cwpData = $wpModel->getCurrentWoUpdate($workOrder->woId);
					 $work_status = ($cwpData)?$cwpData[0]['wo_status']:0;
					 
					  $catModel = new Model_Category();
					   $catlist = $catModel->getBuildingCategoryList($workOrder->building);
					   $cat_array= array();
					   foreach($catlist as $cat)
						 $cat_array[$cat['cat_id']]=$cat['categoryName'];
					 
					$ssModel = new Model_ScheduleStatus();
					$status_list = $ssModel->getScheduleStatus();
					$status_array= array();
					foreach($status_list as $sl){
					   $status_array[$sl['ssID']] = $sl['title'];
					}
					
					$default_data = array('status_closed'=>1, 'billable'=>'', 'inc_tnt_rqt'=>'', 'email_tenant'=>'',
                        'sale_tax'=>'0','auto_charge'=>'0','dft_markup'=>'15','override_markup'=>'0',
                         'time_in_start'=>'8:00 AM', 'time_in_incmt'=>'30 Minutes','time_min_charge'=>'30 Minutes');
                         
					$wpModel = new Model_WoParameter();
					$wpDetails = $wpModel->getWoParameterByBid($this->select_build_id);
			        $wpData = ($wpDetails)?$wpDetails[0]:$default_data;
			        $work_desc='';
			        $wdModel = new Model_WorkDescription();
			        $wdDetails = $wdModel->getDescByWoId($workOrder->woId);
			        if($wdDetails){
						$work_desc=$wdDetails[0]['description'];
					}
			        //print_r($wpData);
				  ?>
				  <script type="text/javascript">
					  <?php if($wpData['billable']=='1'){?>
						  $('#billable_opt').prop('checked', true);
					  <?php }?>	 
					   <?php if($wpData['email_tenant']=='1'){?>
						  $('#tenant_mail').prop('checked', true);
					  <?php }?> 
				  </script>
				  <?php if($work_status=='7'){?>					  
				    <div id="wo_closed_info_div" class="wclose_alert_txt">
						<span>********* Work Order is Closed ********</span>
				    </div>
				  <?php }?>
			  <div class="view-detial-row">
				  <div class="view-column">
					  <label class="red_head_bg">Work Order (<?php echo $status_array[$work_status]; ?>)</label>
					  <div class="view-info-div">
						  <ul>
							   <li>
								   <span>WO Number :</span> <?php echo $workOrder->wo_number?>
							   </li>
							   <li>
								   <span>Company :</span>  <?php echo $workOrder->tenantName?>
							   </li>
							   <li>
								   <span>Date Received :</span> <?php echo date("m/d/Y",strtotime($workOrder->date_requested))?>
							   </li>
							   <li>
								   <span>Time Received :</span> <?php echo $workOrder->time_requested?>
							   </li>
							   <li>
								   <span>Priority :</span> <?php echo $workOrder->priorityName?>
							   </li>
							   <li>
								   <span>Requested By :</span> <?php echo $workOrder->firstName.' '.$workOrder->lastName; ?>
							   </li>
							   <li>
								   <span>Suite/Location :</span> <?php echo $workOrder->tenant_suite?>
							   </li>
							   <li>
								   <span>Email :</span> <?php echo $workOrder->email?>
							   </li>
							   <li>
								   <span>Phone Number :</span> <?php echo $workOrder->phoneNumber?>
							   </li>
							   <li>
								   <span>Category :</span> <?php echo $workOrder->categoryName?>
							   </li>
						  </ul>
					  </div>
					  <div class="wrequest-div">
						  <span>Work Order Request</span>
						  <div class="request-content">
							  <?php echo nl2br($workOrder->work_order_request)?>
						  </div>
					  </div>
					  <div class="button">
						  <button type="button" name="edit" class="close_bt_hide_cls" value="Edit" onclick="showEditForm('<?php echo $workOrder->woId?>')">Edit</button>
					  </div>
				  </div>
				  <div class="detail-column">
					  <label class="red_head_bg">Work Order Details</label>
					  <div class="detial-div">						    
						  <div class="time-status">
							   <div id="date-in-div" class="date-in-div">
								    <?php 
									        $time_factor = explode(" ",$wpData['time_min_charge']);
											$charge_time = $time_factor[0];
									        $curr_date = strtotime(date('Y-m-d'))+$charge_time;
									        $curr_date = ($curr_date!='')?$curr_date:strtotime(date('Y-m-d'));
									   ?>
								   <?php
								       $date_cp_in =date('m/d/Y');
								       $date_cp_out=date('m/d/Y');
								       $time_in ='';
								       $time_out ='';
								       $wcId='';
								       $cw_status='';
								       $wcModel = new Model_WoComplete();
								       $wcData = $wcModel->getWoCompleteByWoId($workOrder->woId);								       
								       if($wcData){
										   $wcInfo = $wcData[0];
										   $date_in = ($wcInfo['date_cp_in']!='0000-00-00')?$wcInfo['date_cp_in']:date('Y-m-d');
										   $date_out = ($wcInfo['date_cp_out']!='0000-00-00')?$wcInfo['date_cp_out']:date('Y-m-d');
										   $date_cp_in = date('m/d/Y',strtotime($date_in));
										   $date_cp_out= date('m/d/Y',strtotime($date_out));
										   $time_in =$wcInfo['time_in'];
										   $time_out =$wcInfo['time_out'];
										   $cw_status = $wcInfo['wo_status'];
										   $wcId = $wcInfo['wcId'];										   
									   }else{
										   $date_cp_in = date('m/d/Y');
										   $date_cp_out= date('m/d/Y',$curr_date);
										   $time_in =$wpData['time_in_start'];
										   $time_out = '';
										   $cw_status = ($wpData['status_closed']=='1')?'7':'';										  
									   }
								       
								   ?>
								   <div class="date-comp">
									   <span>Date Completed:</span>
									   <input type="text" name="date_cp_in" id="date_cp_in" value="<?php echo $date_cp_in;?>" readonly="true" class="close_fd_dsbl"/>
									   <input type="hidden" name="wcId" id="wcId" value="<?php echo $wcId;?>"/>
								   </div>
								   <div class="time">
									   <span>Time In</span>
									   <select name="time_in" id="time_in" class="close_fd_dsbl">
									   <?php
									  
											$start = strtotime($wpData['time_in_start']);
											$end = strtotime('11:59pm');
											$time_factor = explode(" ",$wpData['time_in_incmt']);
											$inc_time = $time_factor[0];
											$increment = $inc_time*60;
											for( $i = $start; $i <= $end; $i += $increment) 
											{
												$selected = ( $time_in == date('g:i A', $i)) ? ' selected="selected"' : '';
												echo '<option value="'. date('g:i A', $i) .'" '.$selected.'>' . date('g:i A', $i) . '</option>';
											}
									   
									   ?>
									   </select>
								   </div>
							   </div>
							   <div id="date-out-div" class="date-out-div">
								   <div class="date-comp">
									   <span>Date Completed:</span>
									  
									   <input type="text" name="date_cp_out"  id="date_cp_out" class="close_fd_dsbl" value="<?php echo $date_cp_out;?>" readonly="true"/>
								   </div>
								   <div class="time">
									   <span>Time Out</span>
									   <select name="time_out" id="time_out" class="close_fd_dsbl">
									   <?php 
											//$start = strtotime('12:00am');
											$start = strtotime($wpData['time_in_start']);
											
											$statTime = $start + ($charge_time*60);
											$end = strtotime('11:59pm');
											for( $i = $statTime; $i <= $end; $i += 900) 
											{
												$selected = ( $time_out == date('g:i A', $i)) ? ' selected="selected"' : '';
												echo '<option value="'. date('g:i A', $i) .'" '.$selected.'>' . date('g:i A', $i) . '</option>';
											}
									   
									   ?>
									   </select>
								   </div>
							   </div>
							   <div class="wd-status">
								   <span>Status</span>
								   <?php 
								       $select_status = $cw_status;// ($wpData['status_closed']=='1')?'7':'';
								   ?>
								   <select name="wo_status" id="wo_status" class="close_fd_dsbl">
									   <option value=""> Select </option>
									   <?php
											foreach($status_array as $key=>$value){
												if($key!='1'){
													echo '<option value="'.$key.'"';
													echo  ($key==$select_status)?'selected="selected"':'';
													echo '>'.$value.'</option>';
												}
											}
									   ?>
								   </select>
							   </div>
						  </div>
						  <div id="order-info-tab" class="order-info-tabb cwo-tabs-section">
							   <div id="tabs">
									  <ul class="com_ord_tab">
										<li><a href="#desc_tab">Description of Work</a></li>
										<li><a href="#lab_tab">Labor</a></li>
										<li><a href="#bs_tab">Building Service</a></li>
										<li><a href="#mat_tab">Materials</a></li>
										<li><a href="#os_tab">Outside Service</a></li>
										<li><a href="#note_tab">Notes</a></li>
									  </ul>
									  <div id="desc_tab" class="tab_content">
										  <span><a href="javascript:void(0)" onclick="showDescription('<?php echo $workOrder->woId?>')" class="close_bt_hide_cls">Click to Add/Modify</a></span>
										<p><?php echo nl2br($work_desc); ?></p>
										
									  </div>
									  <div id="lab_tab" class="tab_content cwo_content">
										  <div class="grid_content">
											  <table name="labor_grid" class="cw_table_grid" width="100%">
												  <tr>
													  <th>Employee Name</th>
													  <th>Charge/Hour</th>
													  <th>Rate Charge</th>
													  <th>Job Time (HH:MM)</th>
													  <th>Action</th>
												  </tr>
												  <?php 
												     $total_labor_charge = 0.00;
													 $laborModel = new Model_Labor();
													 $laborList = $laborModel->getLaborByWoId($workOrder->woId);
													 if($laborList){
														 foreach($laborList as $ll){
															 /****start calculation of total labor charge ***/
															 $lab_charge = 0;
															 $time = explode(":",$ll->job_time);
															 $jb_min = (isset($time[1]))?$time[1]:'00';
															 $jb_time = $time[0]*60+$jb_min;
															 $lab_charge = number_format(($ll->charge_hour/60)*$ll->multiplier*$jb_time,'2','.','');
															 $total_labor_charge = $total_labor_charge + $lab_charge;
															 /******end calculation of total labor charge *******/
															 
															 ?>
															 <tr>
																 <td><?php echo $ll->firstName.', '.$ll->lastName;?></td>
																 <td><?php echo '$'.$ll->charge_hour;?></td>
																 <td><?php echo $ll->description;?></td>
																 <td><?php echo $ll->job_time;?></td>
																 <td>
																	 <a href="#labor_form" id="labor_form_href" class="modalbox">&nbsp;</a>	
																	 <a title="Edit" href="javascript:void(0)" onclick="showEditLabor('<?php echo $ll->lid;?>','<?php echo $workOrder->building?>')" class="close_bt_hide_cls"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						                                            <a href="javascript:void(0);"  title="Delete" onclick="deleteLaborCharge('<?php echo $ll->lid;?>')" class="close_bt_hide_cls"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						                                          </td>
															 </tr>
														<?php	 
														 }
													 }else{
														 echo '<tr><td colspan="5">No Record Exist</td></tr>';
													 }
												  ?>
												  
											  </table>
										  </div>
										  <div class="footer_tab">
											   <div class="add_link_cls">
												    <a href="javascript:void(0)" class="close_bt_hide_cls" onclick="showLaborForm('<?php echo $workOrder->building?>','<?php echo $workOrder->woId?>')">Add New Labor Charge</a>
												    &nbsp;
											   </div>
											   <div class="total_cls">
												    <?php echo '$'.$total_labor_charge;?>
											   </div>
										  </div>
									  </div>
									  <div id="bs_tab" class="tab_content cwo_content">
										<div class="grid_content">
											  <table name="bdservice_grid" class="cw_table_grid" width="100%">
												  <tr>
													  <th>Service Name</th>
													  <th>Charge</th>
													  <th>Unit of Measure</th>
													  <th>Amount Requested</th>
													  <th>Comments</th>
													  <th>Action</th>
												  </tr>
												  <?php 
												     $total_bs_charge = 0.00;
													 $bserviceModel = new Model_BuildingService();
													 $bserviceList = $bserviceModel->getBuildingServiceByWoId($workOrder->woId);
													 if($bserviceList){
														 foreach($bserviceList as $bl){
															 /****start calculation of total labor charge ***/
															 $bs_charge = 0;
															 $bs_charge = number_format(($bl->charge * $bl->amount_requested),'2','.','');
															 $total_bs_charge = $total_bs_charge + $bs_charge;
															 /******end calculation of total labor charge *******/
															 
															 ?>
															 <tr>
																 <td><?php echo $bl->service_name;?></td>
																 <td><?php echo '$'.$bl->charge;?></td>
																 <td><?php echo $bl->unit_measure;?></td>
																 <td><?php echo $bl->amount_requested;?></td>
																 <td><?php echo $bl->comment;?></td>
																 <td>
																	 <a class="close_bt_hide_cls" title="Edit" href="javascript:void(0)" onclick="showEditBService('<?php echo $bl->bsId;?>','<?php echo $workOrder->building?>')"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						                                            <a class="close_bt_hide_cls" href="javascript:void(0);"  title="Delete" onclick="deleteBservice('<?php echo $bl->bsId;?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						                                          </td>
															 </tr>
														<?php	 
														 }
													 }else{
														 echo '<tr><td colspan="6">No Record Exist</td></tr>';
													 }
												  ?>
												  
											  </table>
										  </div>
										  <div class="footer_tab">
											   <div class="add_link_cls">
												    <a href="javascript:void(0)" class="close_bt_hide_cls" onclick="showBServiceForm('<?php echo $workOrder->building?>','<?php echo $workOrder->woId?>')">Add New Building Service Charge</a>
												    &nbsp;
											   </div>
											   <div class="total_cls">
												    <?php echo '$'.$total_bs_charge;?>
											   </div>
										  </div>
									  </div>
									  <div id="mat_tab" class="tab_content cwo_content">
										  <div class="grid_content">
											  <table name="material_grid" class="cw_table_grid" width="100%">
												  <tr>
													  <th>Description</th>
													  <th>Cost</th>
													  <th>Quantity</th>
													  <th>Mark-Up(%)</th>
													  <th>Tax</th>
													  <th>Action</th>
												  </tr>
												  <?php 
												     $total_material_charge = 0.00;
												     $tot_material_tax= 0;
												     $tot_mat_mkp = 0;
													 $mcModel = new Model_MaterialCharge();
													 $materialList = $mcModel->getMaterialChargeByWoId($workOrder->woId);
													 if($materialList){
														 foreach($materialList as $mcl){
															 /****start calculation of total labor charge ***/
															 $mcharge = 0;
															 $mat_mkp = 0;
															 $mat_tax = 0;
															 $mcharge = ($mcl->cost * $mcl->quantity);
															 $mat_mkp = number_format(($mcharge*$mcl->markup)/100,2,'.','');
															 $total_material_charge = $total_material_charge + $mcharge;
															 $tot_mat_mkp = $tot_mat_mkp + $mat_mkp;
															 if($mcl->tax=='1'){
															   $mat_tax = number_format((($mcharge + $mat_mkp)*$wpData['sale_tax'])/100,2,'.','');
														      }
															 
															 $tot_material_tax = $tot_material_tax +$mat_tax;
															 
															 /******end calculation of total labor charge *******/
															 
															 ?>
															 <tr>
																 <td><?php echo $mcl->description;?></td>
																 <td><?php echo '$'.$mcl->cost;?></td>
																 <td><?php echo $mcl->quantity;?></td>
																 <td><?php echo $mcl->markup;?></td>
																 <td><?php echo ($mcl->tax=='1')?'Yes':'No';?></td>
																 <td>
																	 <a class="close_bt_hide_cls" title="Edit" href="javascript:void(0)" onclick="showEditMaterial('<?php echo $mcl->mcId;?>','<?php echo $workOrder->building?>')"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						                                            <a class="close_bt_hide_cls" href="javascript:void(0);"  title="Delete" onclick="deleteMaterial('<?php echo $mcl->mcId;?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						                                          </td>
															 </tr>
														<?php	 
														 }													 
														 
													 }else{
														 echo '<tr><td colspan="6">No Record Exist</td></tr>';
													 }
												  ?>
												  
											  </table>
										  </div>
										  <div class="footer_tab">
											   <div class="add_link_cls">
												    <a href="javascript:void(0)" class="close_bt_hide_cls" onclick="showMaterialForm('<?php echo $workOrder->building?>','<?php echo $workOrder->woId?>')">Add New Material Charge</a>
												    &nbsp;
											   </div>
											   <div class="total_cls">
												    <?php echo '$'.$total_material_charge;?>
											   </div>
										  </div>
									  </div>
									  <div id="os_tab" class="tab_content cwo_content">
										<div class="grid_content">
											  <table name="outside_grid" class="cw_table_grid" width="100%">
												  <tr>
													  <th>Vendor Name</th>
													  <th>Job Description/Work Completed</th>
													  <th>Job Cost $</th>
													  <th>Mark-Up(%)</th>
													  <th>Tax</th>
													  <th>Action</th>
												  </tr>
												  <?php 
												     $total_outside_charge = 0.00;
												     $tot_outside_tax= 0;
												     $tot_outside_mkp = 0;
													 $outModel = new Model_OutsideService();
													 $outsideList = $outModel->getOutsideServiceByWoId($workOrder->woId);
													 if($outsideList){
														 foreach($outsideList as $osl){
															 /****start calculation of total outside service charge ***/
															 $mcharge = 0;
															 $os_mkp = 0;
															 $osl_tax = 0;
															 $osl_cost = $osl->job_cost;
															 $os_mkp = number_format(($osl_cost*$osl->markup)/100,2,'.','');
															 $total_outside_charge = $total_outside_charge + $osl_cost;
															 $tot_outside_mkp = $tot_outside_mkp + $os_mkp;
															 if($osl->tax=='1'){
															   $osl_tax = number_format((($osl_cost + $os_mkp)*$wpData['sale_tax'])/100,2,'.','');
														      }
															 
															 $tot_outside_tax = $tot_outside_tax +$osl_tax;
															 
															 /******end calculation of total labor charge *******/
															 
															 ?>
															 <tr>
																 <td><?php echo $osl->company_name;?></td>
																 <td><?php echo $osl->job_description;?></td>
																 <td><?php echo '$'.$osl->job_cost;?></td>
																 <td><?php echo $osl->markup;?></td>
																 <td><?php echo ($osl->tax=='1')?'Yes':'No';?></td>
																 <td>
																	 <a class="close_bt_hide_cls" title="Edit" href="javascript:void(0)" onclick="showEditOutside('<?php echo $osl->osId;?>','<?php echo $workOrder->building?>')"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						                                            <a class="close_bt_hide_cls" href="javascript:void(0);"  title="Delete" onclick="deleteOutside('<?php echo $osl->osId;?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						                                          </td>
															 </tr>
														<?php	 
														 }													 
														 
													 }else{
														 echo '<tr><td colspan="6">No Record Exist</td></tr>';
													 }
												  ?>
												  
											  </table>
										  </div>
										  <div class="footer_tab">
											   <div class="add_link_cls">
												    <a href="javascript:void(0)" class="close_bt_hide_cls" onclick="showOutsideForm('<?php echo $workOrder->building?>','<?php echo $workOrder->woId?>')">Add New Outside Service Charge</a>
												    &nbsp;
											   </div>
											   <div class="total_cls">
												    <?php echo '$'.$total_outside_charge;?>
											   </div>
										  </div>
									  </div>
									  <div id="note_tab" class="tab_content cwo_content">
										<div class="grid_content">
											  <table name="note_grid" class="cw_table_grid" width="100%">
												  <tr>
													  <th>Date</th>
													  <th width="60%">Notes</th>
													  <th>Internal</th>
													  <th>Action</th>													  
												  </tr>
												  <?php 												     
													 $wnModel = new Model_WoNote();
													 $wnList = $wnModel->getWoNoteByWoId($workOrder->woId);
													 if($wnList){
														 foreach($wnList as $wn){											
															 
															 ?>
															 <tr>
																 <td><?php echo date('m/d/Y',strtotime($wn['note_date']));?></td>
																 <td width="60%"><?php echo $wn['note'];?></td>																 
																 <td><?php echo ($wn['internal']=='1')?'Yes':'No';?></td>
																 <td>
																	 <a class="close_bt_hide_cls" title="Edit" href="javascript:void(0)" onclick="showEditNote('<?php echo $wn['wnId'];?>')"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						                                            <a class="close_bt_hide_cls" href="javascript:void(0);"  title="Delete" onclick="deleteNote('<?php echo $wn['wnId'];?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						                                          </td>
															 </tr>
														<?php	 
														 }													 
														 
													 }else{
														 echo '<tr><td colspan="6">No Record Exist</td></tr>';
													 }
												  ?>
												  
											  </table>
										  </div>
										  <div class="footer_tab">
											   <div class="add_link_cls">
												    <a href="javascript:void(0)" class="close_bt_hide_cls" onclick="showNoteForm('<?php echo $workOrder->woId?>')">Add New Note</a>
												    &nbsp;
											    </div>
											   <div class="total_cls">
												    &nbsp;
											   </div>
										  </div>
									  </div>
								</div>
						  </div>
						   <?php 
										$whlModel = new Model_WoHistoryLog();
										$whlList = $whlModel->getWoHistoryLog($workOrder->woId);
										
									?>
						   <div id="history-section" class="history-sectionn">
							   <label class="red_head_bg">History</label>
							   <table>
									<tr>
									  <th>Log Type</th>
									  <th>Date</th>
									  <th>Time</th>									  
									  <th>Employee Name</th>
									  <th>Updated By</th>
									  <?php /*<th>Notes</th> */?>
									  <th>Changes</th>								  
								  </tr>
								  <?php if($whlList){
								  foreach($whlList as $whl){?>
									  <tr>
										  <td><?php echo ucfirst($whl->log_type);?></td>
										  <td><?php echo substr($whl->created_at,0,10);?></td>
										  <td><?php  echo date_format(date_create($whl->created_at), 'g:i A');?></td>
										  <td><?php echo $whl->firstName.' '.$whl->lastName;?></td>
										  <td><?php echo $whl->role_title;?></td>
										  <?php /*<td>---</td> */?>
										  <td><?php 
												 if($whl->log_type=='category')
												   echo $cat_array[$whl->current_value].' -> '.$cat_array[$whl->change_value];												   
												else
												  echo $status_array[$whl->current_value].' -> '.$status_array[$whl->change_value];
											  ?>
									     </td>
									 </tr>
								  <?php }?>
								   <?php }else{
									?>
									<tr>
										<td colspan="7">
											No History Record Exists.
										</td>
									</tr>
									<?php
									   }?> 
							   </table>
						  </div>
						
					  </div>
					  <div class="right-column">
						   <div class="cwo-buttons">
								<div class="print-wo-inovice">
									<button type="button" name="print_wo" value="Print Work Order">Print Work Order</button>
									<button type="button" name="print_invoice" value="Print Invoice">Print Invoice</button>
								</div>
								<?php if($closewo_access->is_write==1){ ?>
								<div  class="changes">
									<?php if($work_status=='7'){?>
									<button type="button" name="edit_wwork_order" id="edit_wwork_order" value="Edit Work Order" onclick="showAlertBox()">Edit Work Order</button>
									<?php }?>
									<button type="button" name="save_changes" class="close_bt_hide_cls" id="save_changes" value="Save Changes" onclick="saveCompleteChanges('<?php echo $workOrder->woId;?>')">Save Changes</button>
									
									<?php /*<button type="button" name="discard_changes" value="Discard Changes">Discard Changes</button>*/?>
								</div>
								<?php }?>
								<div class="memorize">
									 <button type="button" name="memorize" value="Memorize">Memorize</button>	
								</div>
						   </div>
						   <div class="billable-attached">
								<div class="billable">
									<label class="red_head_bg">Work Order Billable Totals</label>
									<ul>
										<li><span>Labor Cost:</span> <?php echo '$'.$total_labor_charge;?></li>
										<li><span>Building Services</span> <?php echo '$'.$total_bs_charge;?></li>
										<li><span>Cost of Materials:</span> <?php echo '$'.$total_material_charge;?></li>
										<li><span>Outside services:</span> <?php echo '$'.$total_outside_charge;?></li>
										<li><span>Mark-up:</span> <?php echo '$'.($tot_mat_mkp+$tot_outside_mkp);?></li>
										<li><span>Tax:</span> <?php echo '$'.($tot_material_tax+$tot_outside_tax);?></li>
										<li>&nbsp;</li>
										<li><span>Totals:</span> 
										   <?php
										        $total_charge = ($total_labor_charge + $total_bs_charge +$total_material_charge+ $total_outside_charge);
										        $total_markup = ($tot_mat_mkp+$tot_outside_mkp);
										        $total_tax =  ($tot_material_tax+$tot_outside_tax);
										        $total_sum = ($total_charge + $total_markup + $total_tax);
										        echo $total_sum;										   
										   ?>
										
										</li>
									</ul>
								</div>
								<div>
									<label class="red_head_bg">Attached Files</label>
									<ul>
										<?php
										      $fileModel = new Model_WoFiles();
										      $fileList = $fileModel->getWoFilesByWoId($workOrder->woId);
										      if($fileList){
												  foreach($fileList as $fl){
												 ?>
												 <li>
													 <span><a href="<?php echo BASEURL.'public/work_order/'.$fl['file_name'];?>" target="_blank"><?php echo $fl['file_title'];?></a></span>
													 <a class="close_bt_hide_cls" href="javascript:void(0)" class="delete_wo_file" onclick="deleteFiles('<?php echo $fl['wfId'];?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
												 </li>										
												<?php	  
												  }
											  }
										?>
										
									</ul>
									<div class="upload_file_link">
										<span><a class="close_bt_hide_cls" href="javascript:void(0)" onclick="showUploadForm('<?php echo $workOrder->building?>','<?php echo $workOrder->woId?>','<?php echo $workOrder->wo_number?>')">Upload Attachment Files</a></span>
									</div>
								</div>
						   </div>
					  </div>
				  </div>
			  </div>
			  <?php if($work_status=='7' || $closewo_access->is_write!=1){?>
				     <script type="text/javascript">						 
						 $('.close_bt_hide_cls').hide();
						 $('.close_fd_dsbl').attr('disabled','disabled');
				     </script>
				  <?php }?>
			  <?php }else{
				  echo $this->msg;
				  }?>
		 </div>	
	</div>
    <a href="#edit_wo_form" id="edit_wo_form_href" class="modalbox">&nbsp;</a>	
	<div class="fade_edit_wo" id="editwo_div" style="display:none">
		<div id="edit_wo_form" class="edit-wo-class">
		</div>
	</div>
	
	<div class="fade_default_opt" id="fd_dft_div" style="display:none">	
		 <a href="#bd_dft_fm" id="bd_dft_fm_href" class="modalbox">&nbsp;</a>	
		 <div id="bd_dft_fm" class="bd-dft-cls" style="display:none"></div>
         <a href="#wo_desc" id="wo_desc_href" class="modalbox">&nbsp;</a>	
		 <div id="wo_desc" style="display:none"></div>
         <a href="#labor_form" id="labor_form_href" class="modalbox">&nbsp;</a>	
		 <div id="labor_form" style="display:none"></div>
         <a href="#bservice_form" id="bservice_form_href" class="modalbox">&nbsp;</a>	
		 <div id="bservice_form" class="bd-dft-cls" style="display:none"></div>
         <a href="#material_form" id="material_form_href" class="modalbox">&nbsp;</a>	
		 <div id="material_form" class="bd-dft-cls" style="display:none"></div>
         <a href="#outside_form" id="outside_form_href" class="modalbox">&nbsp;</a>	
		 <div id="outside_form" class="bd-dft-cls" style="display:none"></div>
         <a href="#note_form" id="note_form_href" class="modalbox">&nbsp;</a>	
		 <div id="note_form" class="bd-dft-cls" style="display:none"></div>
         <a href="#file_form" id="file_form_href" class="modalbox">&nbsp;</a>	
		 <div id="file_form" class="bd-dft-cls" style="display:none"></div>
         <a href="#alert_wo_edit" id="alert_wo_edit_href" class="modalbox">&nbsp;</a>	
		 <div id="alert_wo_edit" class="cwo_alert_wo" style="display:none">
			 <div class="txt-alert">
				 <span>Work Order has been closed, Do you want to modified it? </span>
			 </div>
			 <div class="alert_button">
				 <button name="at_cancel" class="cancel_btn" id="at_cancel" onclick="cancelWoEdit();">Cancel</button>
				 <button name="at_yes" class="yes_btn" id="at_yes" onclick="showWoEdit();">Yes</button>
			 </div>
		 </div>
	</div>
</div>
 <div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"></div>
<script type="text/javascript">
	var rdr_bid = '<?php echo $this->select_build_id?>';
	var rdr_wnum = '<?php echo $this->wnum?>';
</script>
<?php } else{?>
	    You don't have access for this module.
	  <?php }?>
