<?php echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/conference.js'); ?>

<?php
	$month = $this->month; 
	$lastdays = $this->lastdate; 
	$nextdays = $this->lastdate + 6; 
	$year = $this->year;
	$m = $month;
	$y = $year;
	$monthName = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
	$mName = date("F");
	$Mn=$m;
	$yp = $year;
	$yn = $year;
	$ch = $m;
	
	$todays = date('t', mktime(0, 0, 0, $m, 1, $y));
	
	if (!empty($nextdays) && $nextdays > $todays) {
		$nextdays = $nextdays - $todays;
		$Mn=$Mn+1;
		if($Mn > 12){
			$Mn=1;
		}
	}
	if ($lastdays <= 7) {
		$ldate = (date('t', mktime(0, 0, 0, $m - 1, 1, $y)) + $lastdays);
		if($m < 1){
			$ch = 12;
			$yp=$year-1;
		}
		if($ldate > $todays){
			$ldate=$ldate - 7;
			$ch=$ch-1;
		}
	} else {
		$ldate = $lastdays - 7;
		if($m < 1){
			$ch = 12;
		}
	}
	if($ch < 1){
		$yp=$year - 1;
		$ch = 12;
	}
	$from_date = $y . '-' . $m . '-' . $lastdays;
	$to_date = $y . '-' . $Mn . '-' . $nextdays;

	$cscheduleMapper = new Model_ConferenceSchedule();
	$bookingDetails = $cscheduleMapper->getBookingEvent($from_date, $to_date, $this->select_build_id);

	if (!empty($bookingDetails))
		foreach ($bookingDetails as $bookingDetailsVal) {
			//print_r($bookingDetailsVal); 
			$index = date('Y-m-d', strtotime($bookingDetailsVal->requested_date));
			$booking_arr[$index] = $bookingDetailsVal;
		}
	?>

	<?php
	/* draws a calendar */

	/* draw table */
	$calendar = '<table cellpadding="0" cellspacing="0" class="calendar">';

	/* table headings */
	$headings = array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
	$calendar.= '<tr class="calendar-row calender-row2"><td class="calendar-day-head"></td><td class="calendar-day-head">' . implode('</td><td class="calendar-day-head">', $headings) . '</td></tr>';

	/* days and weeks vars now ... */
	$running_day = date('w', mktime(0, 0, 0, $month, 1, $year));
	$days_in_month = $lastdays + 6; //date('t', mktime(0, 0, 0, $month, 1, $year));
	$days_in_this_week = 1;
	$day_counter = 0;
	$dates_array = array();

	/* row for week one */
	$calendar.= '<tr class="calendar-row" valign="top">';
        
        $calendar.= '<td class="calendar-day-head1" valign="top"><div class="day-number"></div>';

            for ($i = 0; $i <= 23; $i++) {
                $fDate = date("h:i A", strtotime($i . ':00'));
                $calendar.= '<div class="'.str_replace(" ","_",$fDate).'">'.$fDate.'</div>';
                //$calendar.= ; 
            } 
        $calendar.= '</td>';

        
	/* keep going with days.... */
        $k=1;
	for ($list_day = $lastdays; $list_day <= $days_in_month; $list_day++):
		//echo $day_counter;
                $loop_check=0;
                $check_time=1;
		if($day_counter==0 || $day_counter==6 ){
			$calendar.= '<td class="calendar-day1 weekday">';
		}else{
			$calendar.= '<td class="calendar-day1">';
		}              
                
		//$calendar.= '<td class="calendar-day">';
		$list_days = $list_day;
		if ($list_day > $todays) {
			$list_days = $list_day - $todays;
		}
		$calendar.= '<div class="day-number">' . $list_days . '</div>';
				
                if($this->page == 'auser') {
                    $url = "'" . $this->baseUrl() . '/conference/createbooking/month/' . $month . '/year/' . $year . '/bid/' . $this->select_build_id . '/day/' . $list_day . "'";
                } else {
                    $url = "'" . $this->baseUrl() . '/tenant/createbooking/month/' . $month . '/year/' . $year . '/bid/' . $this->select_build_id . '/day/' . $list_day . "'";
                }
		$num_padded = sprintf("%02d", $list_days);
		$index2 = $year . '-' . $month . '-' . $num_padded;
                
		if (!empty($bookingDetails)){
			//$calendar.= '<div class="">';
                    $cr_ck=false;
                   
                    foreach ($bookingDetails as $bookingDetailsVal) {                        
                            $index = date('Y-m-d', strtotime($bookingDetailsVal->requested_date));
                            if ($index == $index2) {
                              if(!$cr_ck)
                                  {
                                    $calendar.='<div class="booking_overflowcon">';
                                    $calendar.='<div class="booking_overcon ch_width'.$k.'">';
                                   
                                  }
                                $loop_check++;
                                
                                $calendar.="<div class='outer_date_time'>";
                                //$calendar.='<div>' . $bookingDetailsVal->room_name . ' - ' . $bookingDetailsVal->start_time . ' ' . $bookingDetailsVal->end_time . '</div>';
                                // $calendar.="<div class='time_".str_replace(" ","_",$bookingDetailsVal->start_time)."'>";
                                // $calendar.="</div>";
                                // $calendar.="<div class='two'></div>";
                                $edit_url = "'" . $this->baseUrl() . '/conference/editbooking/month/' . $month . '/year/' . $year . '/bid/' . $this->select_build_id .'/day/'. $list_day . '/crid/'.$bookingDetailsVal->crid."'";
                                
                                $dteStart = new DateTime($index." ".$bookingDetailsVal->start_time); 
                                $dteEnd   = new DateTime($index." ".$bookingDetailsVal->end_time);
                                $dteDiff  = $dteStart->diff($dteEnd);
                                $totime=$dteDiff->format("%H:%I");
                                $ck=explode(":", $totime);
                                if($ck[1]=="30"){
                                    $totime=$ck[0].".50";
                                }
                                $check=0;
                                $check_hr=0;
                                $check_half=0;
                                for ($i = 0; $i <= 23; $i++) {
                                    $fDate = date("h:i A", strtotime($i . ':00'));
                                    $sDate = date("h:i A", strtotime($i . ':30'));
                                   // echo "<hr>".$fDate."<hr><hr>".$bookingDetailsVal->start_time."<hr>";
                                    
                                    if( $fDate == $bookingDetailsVal->start_time){
                                        $calendar.= '<span class="start_selection time_schedyle'.$check_time.'">';
                                        $check_hr=1;
                                    }
                                    if($check_half==0 && $check_hr==0 )
                                    {
                                        $calendar.= '<div class="full_time"></div>';
                                        
                                    }
                                    if($sDate == $bookingDetailsVal->start_time){
                                        $calendar.= '<span class="start_selection time_schedyle'.$check_time.'">';
                                        $check_half=1;
                                    }                                    
                                    if($check_half==0 && $check_hr==0)
                                    {
                                        $calendar.= '<div class="half_time"></div>';
                                    }
                                    if( $fDate == $bookingDetailsVal->end_time){
                                        $tnModel = new Model_Tenant();
                                        $tndetail = $tnModel->getTenantNameById($bookingDetailsVal->tenant);
                                        $calendar.= '<div  class="tooltip-vcm  book_week" style="height:'.(($totime)*50).'px;">';
                                        $calendar.= "  ".$bookingDetailsVal->room_name.'</div>';
                                        $calendar.= '<span>';//.$bookingDetailsVal->room_name . ' - ' . $bookingDetailsVal->start_time . ' ' . $bookingDetailsVal->end_time ;
                                        
                                        //$calendar.= '<spam class="book_det_container book-details-'.$i.' book_hot_schedule'.$i.'"></spam';
                                        $calendar.= '<spam class="t_name">'.$tndetail[0]->tenantName.'</spam><br>';
                                        $calendar.= '<spam class="r_name">'.$bookingDetailsVal->room_name.'</spam><br>';
                                        $calendar.='<spam>'. $bookingDetailsVal->start_time . ' - ' . $bookingDetailsVal->end_time . '</spam><br>';
                                        $calendar.='<a href="#editbookroom" class="editCat" onclick="editbookroom('.$edit_url.')">'
                                                 . '<img src="'.BASEURL . 'public/images/edit.png'.'"></a>';
                                        $calendar.='<a href="javascript:void(0);" onclick="deleteCrRoom('.$bookingDetailsVal->crid.')" class="delCat" data-id="" title="Delete">'
                                                 . '<img src="'.BASEURL . 'public/images/delete.png'.'"></a>';                                  
                                        $calendar.= '</span></div></span>';
                                        $calendar.= '<div class="half_time"></div>';
                                        $check=0;
                                        $check_hr=0;
                                        $check_half=0;
                                    }
                                    if($sDate == $bookingDetailsVal->end_time ){
                                        $tnModel = new Model_Tenant();
                                        $tndetail = $tnModel->getTenantNameById($bookingDetailsVal->tenant);
                                        $calendar.= '<div  class="tooltip-vcm  book_week" style="height:'.(($totime)*50).'px;">';//.$bookingDetailsVal->room_name . ' - ' . $bookingDetailsVal->start_time . ' ' . $bookingDetailsVal->end_time ;
                                        $calendar.= '<spam class="tname">'.substr($tndetail[0]->tenantName,0,12).'</spam>';
                                        $calendar.= '<span>';//.$bookingDetailsVal->room_name . ' - ' . $bookingDetailsVal->start_time . ' ' . $bookingDetailsVal->end_time ;
                                        $calendar.= '<spam class="t_name">'.$tndetail[0]->tenantName.'</spam><br>';
                                        $calendar.= '<spam class="r_name">'.$bookingDetailsVal->room_name.'</spam><br>';
                                        $calendar.='<spam>'. $bookingDetailsVal->start_time . ' - ' . $bookingDetailsVal->end_time . '</spam><br>';
                                        $calendar.=''
                                               . '<a href="#editbookroom" class="editCat" onclick="editbookroom('.$edit_url.')">'
                                               . '<img src="'.BASEURL . 'public/images/edit.png'.'"></a>';
                                        $calendar.=''
                                                . '<a href="javascript:void(0);" onclick="deleteCrRoom('.$bookingDetailsVal->crid.')" class="delCat" data-id="" title="Delete">'
                                                . '<img src="'.BASEURL . 'public/images/delete.png'.'"></a>';                                  
                                        $calendar.= '</div></span>';                                        
                                        $check=0;
                                        $check_hr=0;
                                        $check_half=0;
                                    }
                                }
                                
                                
                                /*
                                /$tnModel = new Model_Tenant();
                                $tndetail = $tnModel->getTenantNameById($bookingDetailsVal->tenant);
                                $calendar.= '<div class="book_det_container book-details-'.$i.' book_hot_schedule'.$i.'">';
                                $calendar.= '<div class="t_name">'.$tndetail[0]->tenantName.'</div>';
                                $calendar.= '<div class="r_name">'.$bookingDetailsVal->room_name.'</div>';
                                $calendar.='<div>'. $bookingDetailsVal->start_time . ' - ' . $bookingDetailsVal->end_time . '</div>';
                                $edit_url = "'" . $this->baseUrl() . '/conference/editbooking/month/' . $month . '/year/' . $year . '/bid/' . $this->select_build_id .'/day/'. $list_day . '/crid/'.$bookingDetailsVal->crid."'";
                                $calendar.='<div class="edit_del_room"><div class="edit_broom">'
                                            . '<a href="#editbookroom" class="editCat" onclick="editbookroom('.$edit_url.')">'
                                    . '<img src="'.BASEURL . 'public/images/edit.png'.'"></a></div>';
                                $calendar.='<div class="delete_broom">'
                                            . '<a href="javascript:void(0);" onclick="deleteCrRoom('.$bookingDetailsVal->crid.')" class="delCat" data-id="" title="Delete">'
                                    . '<img src="'.BASEURL . 'public/images/delete.png'.'"></a></div></div><div class="clearfix"></div>';                                                       

                                $calendar.= '</div>';
                                 $i++;*/
                                $cr_ck=true;
                                
                                $check_time++;
                                $calendar.= '</div>';
                            }
                           
                    }
                               
                 $calendar.= '</div>';
                }
                
                
                
                //echo $check_time;
                if($loop_check < 3){
                    
                    for ($i = 0; $i <= 23; $i++) {
                       $fDate = date("h:i A", strtotime($i . ':00'));
                       $sDate = date("h:i A", strtotime($i . ':30'));
                       // echo "<hr>".$fDate."<hr><hr>".$bookingDetailsVal->start_time."<hr>";
                       $calendar.= '<div class="full_time"></div>';
                       //$calendar.= $fDate; 
                       $calendar.= '<div class="half"></div>';
                       //$calendar.= $sDate; 
                   }
                }
                $calendar.='</div>';                
                $calendar.='</div>';
		//echo date_default_timezone_get();
		//if( (date("m") <= $m && date("d") <= $list_day) || date("m") < $m){
		//	$calendar.= '<div class="conbooking"><a href="#createBooking" onclick="createBooking(' . $url . ')">+</a> </div>';
		//}
		if(date("Y") < $year){
                    //$calendar.= '<div class="conbooking"><a href="#createBooking" onclick="createBooking(' . $url . ')">+</a> </div>';
		}else if(date("Y")==$year){
                    if(date("m") < $m){
                       // $calendar.= '<div class="conbooking"><a href="#createBooking" onclick="createBooking(' . $url . ')">+</a> </div>';
                    }else if(date("m") == $m && date("d") <= $list_day){
                       // $calendar.= '<div class="conbooking"><a href="#createBooking" onclick="createBooking(' . $url . ')">+</a> </div>';
                    }
		}
                
                // time maker
                
               
		//$calendar.= '<div><a href="#createBooking" onclick="createBooking(' . $url . ')">+</a> </div>';

		/** QUERY THE DATABASE FOR AN ENTRY FOR THIS DAY !!  IF MATCHES FOUND, PRINT THEM !! * */
		$calendar.= str_repeat('<p> </p>', 2);
		$calendar.= '</td>';
		$running_day++;
		$day_counter++;
               // echo 'ch_width'.$k.$check_time;
               // echo "<hr>";
                if($check_time > 1)
                    echo '<script>$(".ch_width'.$k.' .outer_date_time").attr("style","width:'.(218/($check_time-1)).'px")</script>';
                $k++;
	endfor;
        
	if ($list_day > $todays) {
		$m = $m + 1;
		$m = ($m > 9 ? $m:"0".$m);
		if($m > 12){
			$m = 1;
			$yn=$year + 1;
		}
		if($m < 1){
			$m = 12;
			$yp=$year - 1;
		}
		
	}

	if($nextdays + 1 > $todays ){
		$ndate=($nextdays+1)-$todays;
	}else{
		$ndate =$nextdays + 1;
	}
	

	/* final row */
	$calendar.= '</tr>';
        
        
	/* end the table */
	$calendar.= '</table>';
	?>

	<div id="calender_change">
		<div style='text-align:center;'>
			<h2>
				<?php 	echo $monthName[$month - 1]." ".$year; ?>
				<a href="#" onclick="changeweekly('<?php echo $yp; ?>','<?php echo $ch; ?>', '<?php echo $ldate; ?>', '<?php echo $this->page; ?>')">
					< 
				</a>
				<?php  echo $monthName[$month - 1]." ".$lastdays . ' - ' . $monthName[$m - 1]." ".$nextdays; ?>
				<a href="#" onclick="changeweekly('<?php echo $yn; ?>','<?php echo $m; ?>', '<?php echo $ndate; ?>', '<?php echo $this->page; ?>')">
					>
				</a>
			</h2>
		</div>
	</div>
	<?php
	/* all done, return result */
	echo $calendar;

	/* sample usages */
	?>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>



