<?php

$etemplateAccess = $this->acessHelper->checkAccess($this->roleId, $this->etemplate_location);
/* override access by custom user access if exist */
$customeAccessmodel = new Model_UserAccess();
$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, $this->etemplate_location);
if ($customeAccessmodeld[0]) {
    $etemplateAccess = $customeAccessmodeld[0];
}

$moduleMapper = new Model_UserBuildingModule();
$moduleAccess = $moduleMapper->getModuleByBuildingId($this->select_build_id, 2);
/* end overriding access */ 

/* override access by custom user access if exist */
    $customeAccessmodel = new Model_UserAccess();
    $customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($this->userId, 26);
    if ($customeAccessmodeld[0]) {
            $croom_access = $customeAccessmodeld[0];
    }
   /* 
    print_r($croom_access);
    echo $croom_access->is_access;
    echo $croom_access->is_read;
    echo $croom_access->is_write;
    * */
   
    
?>
<div class="container-right" id="contents">
    <ol id="toc">
 <?php
                $j = 1;

                foreach ($this->companyListing as $cb) {
                    ?>
                    <li><a class="<?php if ($cb['build_id'] == $this->select_build_id) echo 'active'; ?>"  href="<?php echo $this->baseUrl() . '/conference/conflist/bid/' . $cb['build_id']; ?>" ><span><?php echo $cb['buildingName']; ?></span></a>
                        <?php
                        if ($reportDetailLinks != '') {
                            if ($cb['build_id'] == $this->select_build_id) {
                                $uniqueCostCenter = $cb['uniqueCostCenter'];
                                $batchDetails = $woBatch->showBatch($cb['build_id']);
                                $batch_number_report = '';
                                if ($batchDetails != '') {
                                    foreach ($batchDetails as $bd) {
                                        $batch_number_report = $batch_number_report . $bd['batch_number'] . ',';
                                    }
                                }
                                $order = 'woId';
                                $dir = 'DESC';
                                $wolist = $woReport->getWorkOrderByBuilding($cb['build_id'], $order, $dir);
                                $invoicelist = $woReport->invoiceByBatch($cb['build_id'], $order, $dir);
                                if ($wolist != '') {
                                    foreach ($wolist as $woNumber) {
                                        $woNumberAll = $woNumberAll . $woNumber->wo_number . ',';
                                    }
                                }
                                if ($invoicelist != '') {
                                    foreach ($invoicelist as $invoiceNumber) {
                                        $invoiceAll = $invoiceAll . $invoiceNumber->wo_number . ',';
                                    }
                                }
                            }
                        }
                        ?> 
                    </li>

                <?php } ?>
            </ol>
            <!-- Report Link -->


    <?php  //if ($this->roleId == 2 || $this->roleId == 3 || $this->roleId == 4 || $this->roleId == 6) {
  if(!empty($moduleAccess)){
      
        if ($this->roleId == 4 || $this->roleId == 5 || $this->roleId == 9 || $croom_access->is_read==1) {
            ?>
            <section style="z-index:9999" class="w-48 fr ch-home-form">
                <section class="ch-form-header ">
                    <h3>List of Email Template </h3>
                </section>
                <div class="message" style="color: red;">
                    <?php
                        $em = new Zend_Session_Namespace('etemp_message');
                        echo $em->msg;
                        $em->setExpirationSeconds(1);
                    ?>
                </div>
                <div id="email_list">
                    <?php if ($this->emailData) { ?>
                        <table width="98%" class="priority-list">
                            <tr>
                                <th>Title</th>
                                <th>Subject</th>
                                <th>Status</th>
                                <th>Type</th>
                                <th>Action</th>
                            </tr>
                            <?php foreach($this->emailData as $edata) { ?>
                                <tr>
                                    <td><?php echo $edata['email_title']; ?></td>
                                    <td><?php echo $edata['email_subject']; ?></td>
                                    <td><?php echo ($edata['status']) ? 'Active' : 'Deactive'; ?></td>
                                    <td><?php echo (!$edata['type']) ? 'Add/Edit' : 'Delete'; ?></td>
                                 <?php if($this->roleId == 4 || $this->roleId == 5 || $this->roleId == 9 || $croom_access->is_write==1): ?>   
                                    <td>
                                        <div class="col02 coladdlastcol lastcol edit_delete_icon">
                                            <a href="<?php echo BASEURL . 'emails/editemail/id/' . $edata['id']; ?>"  title="Edit"><img src="<?php echo BASEURL . 'public/images/edit.png' ?>" /></a> 
                                            <?php //if($edata['system_generated']=='0'){ ?>
                                            <a href="javascript:void(0);"  title="Delete" onclick="javascript:deleteEmailList('<?php echo BASEURL . 'emails/deleteemail/id/' . $edata['id'] .'/email_location/9'; ?>')"><img src="<?php echo BASEURL . 'public/images/delete.png' ?>" /></a>
                                            <?php //}?>
                                        </div>
                                    </td>
                                <?php endif; ?>
                                </tr>
                            <?php } ?> 

                        </table>
                        <?php /*  pagination code.  */  ?>   
                        <?php
                        if (count($this->emailData) > 0 && !empty($this->emailData)) {
                            echo $this->paginationControl($this->emailData, 'Sliding', 'pagination.phtml');
                        }
                    } else {
                        echo 'No email template added.';
                        ?>	
                    <?php } ?>
                    
                    <?php if($this->roleId == 4 || $this->roleId == 5 || $this->roleId == 9 || $croom_access->is_write==1): ?>
                        <section class="ch-form-header ">
                            <h3>
                                <a class='addnewtemp' href="" onclick="return validate(<?php echo $this->select_build_id; ?>,'')">Add Email Template</a>
                                <a class='addnewtemp' href="" onclick="return validate(<?php echo $this->select_build_id?>,'delete')">Add Delete Email Template</a>
                            </h3>
                        </section>
                    <?php endif; ?>
<?php //echo BASEURL . 'conference/contempcreate/bid/'.$this->select_build_id.'/type/delete/'; ?>
<?php //echo BASEURL . 'conference/contempcreate/bid/'.$this->select_build_id; ?>
                </div>
            </section>
    <?php } else { 
                echo "You don't have access for this module.";
           }
  }else{
      echo "This Building does not have the access of this module.";
  }
    ?>
</div>
<script type="text/javascript">
    function deleteEmailList(url) {
        jConfirm('Are you sure to delete this email template?', 'Vision Work Orders', function (r) {
            if (r == true) {
                window.location.href = url;
            }
        });
    }
    
    function validate(bid,type){
        //window.location.href = url;
        
        $.ajax({
		type: "POST",
		datatype: 'json',
		url: baseUrl + 'conference/vetemp',
		data: {bid:bid,type:type},
		success: function (data) {
                    var response = JSON.parse(data);
                    if(response.status =='sucess'){
                        console.log("sanjay");
                        window.location.href = baseUrl + 'conference/contempcreate/bid/'+bid+"/type/"+type;
                        //return true;
                    }else{
                        $(".message").html(response.msg);
                        return false;
                    }
		}
	}); 
        return false;
    }
    
    
</script>
