<div id="edit_rate_div">
	<span>Edit Rate Charges</span>
	<?php if($this->rateData) { 
		  $rate = $this->rateData[0];		  
		?>
	<div class="message">
		<span id="success_msg" class="success"></span>
		<span id="error_msg" class="error"></span>
	</div>
	<div class="rate_row">
		  <label>Rate Name:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="rerror_name"></span>
			   <input type="text" name="rate_name" id="rate_name" value="<?php echo $rate['rate_name']?>"/>
		  </div>			
	</div>
	<div class="rate_row">
		  <label>Description:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="rerror_desc"></span>
			   <input type="text" name="description" id="description" value="<?php echo $rate['description']?>"/>
		  </div>			
	</div>
	<div class="rate_row">
		 <label>Active:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="rerror_status"></span>
			   <select name="status" id="status">
				   <option value="1" <?php echo ($rate['status']==1)?'selected="selected"':'';?>>Yes</option>
				   <option value="0" <?php echo ($rate['status']==0)?'selected="selected"':'';?>>No</option>
			   </select>
		  </div>
	</div>
	<div class="rate_row">
		  <label>Multiplier:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="rerror_multiplier"></span>
			   <input type="text" name="multiplier" id="multiplier" onkeypress="return isNumber(event)" maxlength="6" value="<?php echo $rate['multiplier']?>"/>
		  </div>			
	</div>	
	<div class="rate_row">
		 <label>Set as Default:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="rerror_default"></span>
			   <select name="set_default" id="set_default">
				   <option value="1" <?php echo ($rate['set_default']==1)?'selected="selected"':'';?>>Yes</option>
				   <option value="0" <?php echo ($rate['set_default']==0)?'selected="selected"':'';?>>No</option>
			   </select>
		  </div>
	</div>	
	<div class="buttons">
				   <button type="button" name="save_rate" id="save_rate" value="Save" onclick="updateRateCharge('<?php echo $rate['brid']?>','<?php echo $this->bId;?>')">Confirm</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelEditRate()">Cancel</button>
			  </div>
	 <?php 
   }else{
	   echo 'Invalid URL';
   }
	 ?>				  
</div>
