<?php
echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/bill.js');
$bill_access = $this->acessHelper->checkAccess($this->roleId,$this->bill_location);
?>
<div class="container-right" id="userinfo-data">
	 <?php 
       if($this->roleId!=1 && $bill_access->is_access == 0){ 
           if($this->custID!=null && $this->custID && $this->companyListing!='' && $this->companyListing!=false){
			      $order = $this->order;
				   $dir = $this->dir;
				   $grid = $this->grid;
				   $ddir= 'ASC';
				   $cdir = 'ASC';
				   $tdir = 'ASC';
				   $adir = 'ASC';
				   $rdir = 'ASC';
				   $mdir = 'ASC';				   
				  if($order=='description')
					  $ddir = ($dir=='ASC')?'DESC':'ASC';
			     else if($order=='charge_hour')
					  $cdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='global_template')
					  $tdir = ($dir=='ASC')?'DESC':'ASC';
				   else if($order=='assign_to')
					  $adir = ($dir=='ASC')?'DESC':'ASC';
				else if($order=='rate_name')
					  $rdir = ($dir=='ASC')?'DESC':'ASC';
			    else if($order=='multiplier')
					  $mdir = ($dir=='ASC')?'DESC':'ASC';		  	  				   
			   	$url = BASEURL.'bill/index/bid/'.$this->select_build_id;	  
			   ?>
			  <div id="contents">
					<ol id="toc">
						<?php
						    $sarray = array();
						    $servModel = new Model_Services();
						    $serviceList = $servModel->getServices();
						    foreach($serviceList as $sl){
								$sarray[$sl['sid']]=$sl['service'];
							}
							$j = 1;
							foreach($this->companyListing as $cb){ ?>					
							<li><a href="<?php echo $this->baseUrl().'/bill/index/bid/'.$cb['build_id']; ?>" <?php if($cb['build_id']==$this->select_build_id) echo 'class="active"';?>><span><?php echo $cb['buildingName']; ?></span></a></li>
						<?php $j++; } ?>
					</ol>
					<div id="page" class="content">
					     <span class="bill-heading"><h1>Bill Back Console</h1></span>
					     <div class="bill_message" id="bill_message">
							<span id="bill_success" class="success"></span>
							<span id="bill_error" class="error"></span>
						</div>
					     <div id="labor_grid_div">
							  <table id="labor_data_table" class="building_table_grid" width="100%">
								  <tr>
									  <td class="bill_head" colspan="4">Labor Charges</td>
									  <td class="gt_heading" colspan="2"><?php if($bill_access->is_write==1){?><a href="javascript:void(0)" onclick="importLaborTemplate('<?php echo $this->select_build_id;?>')">Import Global Template</a><?php }?>&nbsp;</td>
								  </tr>
								  <tr>
									<th><a href="<?php echo $url.'/grid/labor/order/charge_hour/dir/'.$cdir?>" 
                          class="<?php if($order=='charge_hour') echo $cdir; else echo 'sorting';?>">Charge/Hour $</a></th>
									  <th><a href="<?php echo $url.'/grid/labor/order/description/dir/'.$ddir?>" 
                          class="<?php if($order=='description' && $grid=='labor') echo $ddir; else echo 'sorting';?>">Description</a></th>
									  <th><a href="<?php echo $url.'/grid/labor/order/assign_to/dir/'.$adir?>" 
                          class="<?php if($order=='assign_to') echo $adir; else echo 'sorting';?>">Assigned To</a></th>
									  <th><a href="<?php echo $url.'/grid/labor/order/global_template/dir/'.$tdir?>" 
                          class="<?php if($order=='global_template' && $grid=='labor') echo $tdir; else echo 'sorting';?>">Template</a></th>
                                      <th>Imported</th>
									 <?php if($bill_access->is_write==1){?>	  <th>Action</th> <?php }?>
								  </tr>
								  <?php
								      if($this->blList){
										  foreach($this->blList as $bl){
											 ?>
										<tr>
											<td><?php echo '$'.$bl['charge_hour'];?></td>
											<td><?php echo $bl['description'];?></td>
											<td><?php echo ($bl['assign_to']!='')?'Assigned':'Not Assigned';
											          echo  ($bl['set_default']=='1')?'(Default)':'';											
											?></td>
											<td><?php echo ($bl['global_template']==1)?'Yes':'No';?></td>
											<td><?php echo ($bl['import_template']=='1')?'Yes':'No';?></td>
											<?php if($bill_access->is_write==1){?><td><a title="Edit" href="javascript:void(0);" onclick="showEditLabor('<?php echo $bl['blid'];?>','<?php echo $bl['building'];?>')"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						 <a href="javascript:void(0);"  title="Delete" onclick="deleteLaborCharge('<?php echo $bl['blid'];?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a></td>
						                       <?php } ?> 
											
										</tr>	 
									 <?php		  
										  }
										  
								     }else{
								  ?>
								  <tr>
									  <td colspan="6">No Record Exist.</td>
								  </tr>
								  <?php }?>
								  <?php if($bill_access->is_write==1){?>
								  <tr>
									  <th colspan="6"><a href="javascript:void(0)" onclick="showAddLabor('<?php echo $this->select_build_id;?>')">Add New</a></th>
								  </tr>
								  <?php }?>
							  </table>
							  
					     </div>
					     <div id="rate_grid_div">
							 <table id="rate_data_table" class="building_table_grid" width="100%">
								  <tr>
									  <td class="bill_head" colspan="4">Rate Charge</td>
									  <td class="gt_heading" colspan="2"><?php if($bill_access->is_write==1){?><a href="javascript:void(0)" onclick="importRateTemplate('<?php echo $this->select_build_id;?>')">Import Global Template</a><?php }?>&nbsp;</td>
								  </tr>
								  <tr>
									  <th><a href="<?php echo $url.'/grid/rate/order/rate_name/dir/'.$rdir?>" 
                          class="<?php if($order=='rate_name') echo $rdir; else echo 'sorting';?>">Rate Name</a></th>
									  <th><a href="<?php echo $url.'/grid/rate/order/description/dir/'.$ddir?>" 
                          class="<?php if($order=='description' && $grid=='rate') echo $ddir; else echo 'sorting';?>">Description</a></th>
									  <th><a href="<?php echo $url.'/grid/rate/order/multiplier/dir/'.$mdir?>" 
                          class="<?php if($order=='multiplier') echo $mdir; else echo 'sorting';?>">Multiplier</a></th>
									  <th><a href="<?php echo $url.'/grid/rate/order/global_template/dir/'.$tdir?>" 
                          class="<?php if($order=='global_template' && $grid=='rate') echo $tdir; else echo 'sorting';?>">Template</a></th>
                                      <th>Imported</th>
									  <?php if($bill_access->is_write==1){?><th>Action</th><?php }?>
								  </tr>
								 <?php 
								      if($this->brList){
										  foreach($this->brList as $br){
											 ?>
										<tr>
											<td><?php echo $br['rate_name'];?></td>
											<td><?php echo $br['description'];?></td>
											<td><?php echo $br['multiplier'];
											     echo  ($br['set_default']=='1')?'(Default)':'';
											?></td>
											<td><?php echo ($br['global_template']=='1')?'Yes':'No';?></td>
											<td><?php echo ($br['import_template']=='1')?'Yes':'No';?></td>
											<?php if($bill_access->is_write==1){?>
											<td>
												<a title="Edit" href="javascript:void(0)" onclick="showEditRate('<?php echo $br['brid'];?>','<?php echo $br['building'];?>')"><img src="<?php echo BASEURL . 'public/images/edit.png'?>" /></a>
						                        <a href="javascript:void(0);"  title="Delete" onclick="deleteRateCharge('<?php echo $br['brid'];?>')"><img src="<?php echo BASEURL . 'public/images/delete.png'?>" /></a>
						                    </td>
						                    <?php }?>
											
										</tr>	 
									 <?php		  
										  }
										  
								     }else{
								  ?>
								  <tr>
									  <td colspan="6">No Record Exist.</td>
								  </tr>
								  <?php }?>
								  <?php if($bill_access->is_write==1){?>
								  <tr>
									  <th colspan="6"><a href="javascript:void(0)" onclick="showAddRate('<?php echo $this->select_build_id;?>')">Add New</a></th>
								  </tr>
								  <?php }?>
							  </table>
					     </div>
					 </div>    					
				</div>
				<div id="popup_form" style="display:none" class="labor_popup_form">
					 <div id="add_labor_form" style="display:none"></div>
					 <div id="edit_labor_form" style="display:none"></div>
					 <div id="labor_template_form" style="display:none"></div>
					 <div id="add_rate_form" style="display:none"></div>
					 <div id="edit_rate_form" style="display:none"></div>
					 <div id="rate_template_form" style="display:none"></div>
				</div>
			<?php }
		   else{
			   echo 'No Building has assign to you.';
		   }  
		  }else{?>
			You don't have access for this module.
		  <?php }?>
</div>        			
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
