<div id="add_rate_div" style='text-decoration:none'>
	<h1>Import Template Rate Charges</h1>
	<div class="message" style='text-align:center;'>
		<span id="success_msg" class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></span>
		<span id="error_msg" class="success_message" style="text-align:center;width:100%;font-weight:bold;color:red;"></span>
	</div>
	<div class="rate_row">
		  <label>Select Template From List:</label>
		  <div class="rate_ibox_row">
			   <span class="field_error" id="lerror_desc"></span>
			   <select name="select_template" id="select_template" onchange="setRateTemplate(this.value)">
				   <option value="">Select Template</option>
				   <?php
				        if($this->rcList){
							foreach($this->rcList as $rcl){
							  echo '<option value="'.$rcl->brid.'">'.$rcl->description.'</option>';
						   }
						}
				   ?>
			   </select>
		  </div>			
	</div>
	<div id="load_global_tmp_div">
		<div class="rate_row">
			  <label>Rate Name:</label>
			  <div class="rate_ibox_row">
				   <span class="field_error" id="rerror_name"></span>
				   <input type="text" name="rate_name" id="rate_name"/>
			  </div>			
		</div>
		<div class="rate_row">
			  <label>Description:</label>
			  <div class="rate_ibox_row">
				   <span class="field_error" id="rerror_desc"></span>
				   <input type="text" name="description" id="description"/>
			  </div>			
		</div>
		<div class="rate_row">
			 <label>Active:</label>
			  <div class="rate_ibox_row">
				   <span class="field_error" id="rerror_status"></span>
				   <select name="status" id="status">
					   <option value="1" selected="selected">Yes</option>
					   <option value="0">No</option>
				   </select>
			  </div>
		</div>
		<div class="rate_row">
			  <label>Multiplier:</label>
			  <div class="rate_ibox_row">
				   <span class="field_error" id="rerror_multiplier"></span>
				   <input type="text" name="multiplier" id="multiplier" onkeypress="return isNumber(event)" maxlength="6"/>
			  </div>			
		</div>	
		<div class="rate_row">
			 <label>Set as Default:</label>
			  <div class="rate_ibox_row">
				   <span class="field_error" id="rerror_default"></span>
				   <select name="set_default" id="set_default">
					   <option value="1">Yes</option>
					   <option value="0" selected="selected">No</option>
				   </select>
			  </div>
		</div>
	</div>
	<input type="hidden" name="global_template" id="global_template" value="0"/>		
	<div class="buttons">
				   <button type="button" name="save_rate" id="save_rate" value="Save" onclick="saveRateCharge('<?php echo $this->bId;?>')">Save</button>
				   <button type="button" name="cancel" id="cancel" value="Cancel" onclick="cancelRateTemplate()">Cancel</button>
			  </div>
</div>
<div class="loader" style="display:none;" > <img src="<?php echo BASEURL.'public/images/loader.gif';?>"><div>
