<div class="container-right" id="woListData1" style="display:none">
<?php if($this->roleId=='5' || $this->roleId=='7'){
   

?>

   <?php
	echo $this->headScript()->appendFile($this->baseUrl() . '/public/jquery/jquery.multiple.select.js');
	echo $this->headLink()->appendStylesheet($this->baseUrl() . '/public/css/multiple-select.css');
	echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/dashworkorder.js');

$actionnTenantHelper=Zend_Controller_Action_HelperBroker::getStaticHelper('Tenantaccess'); 
    $tenantLocationArr = $actionnTenantHelper->checkTenantaccess();


$color_code = array('00FFFF','FF0000','FF00FF','800000','008000','800080','808000','0000FF','00FF00','000080','FFFF00','808000','008080','FFA500');						
$building_color = array();


$j = 1;
foreach($tenantLocationArr as $tenantcompany){ 
    // echo '<pre>';
    // print_r($tenantcompany->id);
    $building_color[$tenantcompany->id] = $color_code[$j];
    ?>

<?php $j++; }        
//print_r($building_color);


        $order = $this->order;
        $dir = $this->dir;
        $wdir = 'ASC';
        $bdir = 'ASC';
        $tdir = 'ASC';
        $sdir = 'ASC';
        $cdir = 'ASC';
        $pdir = 'ASC';
        $stdir = 'DESC';
        $ddir = 'DESC';
        $tudir = 'DESC';
        if ($order == 'wo_number')
            $wdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'buildingName')
            $bdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'tenantName')
            $tdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'suite_location')
            $sdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'categoryName')
            $cdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'priorityName')
            $pdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'wo_status')
            $stdir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else if ($order == 'firstName')
            $tudir = ($dir == 'ASC') ? 'DESC' : 'ASC';
        else
            $ddir = ($dir == 'ASC') ? 'DESC' : 'ASC';
    $ssModel = new Model_ScheduleStatus();
    $status_list = $ssModel->getScheduleStatus();
    $status_array = array();
    foreach ($status_list as $sl) {
        if ($sl['ssID'] != 8)
            $status_array[$sl['ssID']] = $sl['title'];
        $workorderallstatus = $workorderallstatus . $sl['ssID'] . ',';
    }

    if (isset($this->statusCookieDetails) && $this->statusCookieDetails != '') {
        foreach ($this->statusCookieDetails as $stvalue) {
            $workorderstatus = $workorderstatus . $stvalue . ',';
        }
    }


    $reportModel = new Model_Report();
    $reportDetailLinks = '';
    $dashBoardViewsdetails = '';
if ($this->view_type != 'detail') {
    $reportDetailLinks = $reportModel->getReport($this->custID, 2);
    $dashBoardViewsdetails = $reportModel->getReport($this->custID, 27);
} else {
    $reportDetailLinks = $reportModel->getReport($this->custID, 3);
}
	?>
	 <!--Body middle Part button start-->
     <div class="row">
            <?php $msg = new Zend_Session_Namespace('message'); ?>
            <div class="workorder_error" id="message">
                <?php
                echo $msg->error_message;
                $msg->error_message = '';
                ?>
            </div>
            <div class="workorder_success" id="message">
                <?php
                echo $msg->success_message;
                $msg->success_message = '';
                ?>
            </div>
        </div>
        <form name="search_mini_form" id="search_mini_form" action="<?php
        echo $this->baseUrl() . '/workorder/index/';
        if ($this->select_build_id != '') {
            echo 'bid/' . $this->select_build_id . '/';
        }if ($this->view_type == 'detail') {
            echo 'view_type/detail';
        }
        ?>" method="post">
            <div class="row">
                <div class="middle_btn my_middle_btn">
                    <div id="dashboard_search_error" class="workorder_error"></div>
                    <ul>
                        <li>
                            <?php
                            $param = '/bid/';
                            $param_val = ($this->select_build_id != '') ? $this->select_build_id : '';
                            $param_build = $param . $param_val;
                            if ($ddetail_access->is_access == 0) {
                                if ($veiw_type == 'detail') {
                                    $url = BASEURL . 'dashboard/workorder';
                                    ?>
                                    <?php
                                } else {
                                    $url = BASEURL . 'dashboard/workorder/view_type/detail';
                                    ?>
                                    <?php
                                }
                            }
                            ?>
                        </li>
                        <li>
                            <span class="ser_sp">Search</span>
                            <input type="text" name="search_wo" id="search_wo" placeholder="Work Order Id" onkeypress="return isNumberKey(event)" value="<?php echo (isset($_REQUEST['search_wo'])) ? $_REQUEST['search_wo'] : ''; ?>"> <span class="my_se_icon">
                                <a href="javascript:void(0)" name="submit" id="btn_search_wo"><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a></span> 
                        </li>
                        <li>
                            <span class="ser_sp">Show</span>
                            <select id="show_limit"  name="show_limit" style="width:100px !important;" >
                                <option value="10" <?php echo ($this->show == 10 ? "noselected" : ""); ?> >10</option>
                                <option value="25" <?php echo ($this->show == 25 ? "selnoselectedected" : ""); ?>>25</option>
                                <option value="50" <?php echo ($this->show == 50 ? "noselected" : ""); ?>>50</option>
                                <option value="100" <?php echo ($this->show == 100 ? "noselected" : ""); ?>>100</option>
                                <!--<option value="all" <?php //echo ($this->show == 1000 ? "selected" : "");    ?>>All</option>-->
                            </select>
                        </li>

                        <li style='width:205px;'>
                            <div class="min_select_searh"><label></label>
                                <select id="ms" multiple="multiple">
                                    <?php foreach ($status_array as $key => $value) { ?>
                                        <option value="<?php echo $key; ?>" <?php if (isset($this->statusCookieDetails) && (in_array($key, $this->statusCookieDetails))) echo 'selected'; ?>><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <span class="my_se_icon">
                              <!-- <a href="javascript:void(0)" name="submit" id="searchBystatus" ><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a>                                     -->

                                <a href="javascript:void(0)" name="submit" onclick="showStatusValidation()"><span aria-hidden="true" class="glyphicon glyphicon-search"></span></a>                                    
                            </span>
                            <?php /* ?>
                              <select name="search_status"  onchange="showStatus(this.value)" class="selectbox awo-sselect">
                              <option value="">Select</option>
                              <?php foreach($status_array as $key=>$value){?>
                              <option value="<?php echo $key;?>" <?php if(isset($_REQUEST['search_status']) && ($_REQUEST['search_status']==$key)) echo 'selected'; ?>><?php echo $value;?></option>
                              <?php }?>
                              </select>
                              <?php */ ?>
                        </li>
                        <li><a href="#" onclick="resetStatus()">Reset</a></li>
                        <?php if ($createnew_access->is_write == 1) { ?>
                            <li><a href="<?php echo BASEURL . 'dashboard/createworkorder' ?>">New Order</a></li>
                        <?php } ?>	  

                    </ul>
                </div>
            </div>  
            <input type="hidden" name="submitform">
        </form>

        <!--Body middle Part tabbed start-->
        <div class="row" >
            <div id="parentHorizontalTab" class="datatabed">
                <?php
                if ($veiw_type == 'line') {
                    $url = BASEURL . 'workorder/index';
                } else {
                   // $url = BASEURL . 'workorder/view_type/detail';
                   $url = BASEURL . 'workorder/index';
                }
                ?>

<table id="myTable1" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Date Received</th>
                            <th>Time Received</th>
                            <th>Work Order#</th>
                            <th>Current Status</th>
                            <th>Category</th>                            
                            <th>Work Request</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
    </table>
                <div class="resp-tabs-container hor_1" >
                    <div>
                        <div class="row">
                            <div class="panel-body padd_order">
                                <div class="table-responsive">
                                    <div role="grid" class="dataTables_wrapper form-inline" id="dataTables-example_wrapper">
                                        <div id="reloadworkorder" stlye="display:none;">
                                            
                                        
                                        
                                        <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" style="display:none;">
                                                <thead>
                                                    <tr>

                                                        <th><a href="<?php echo $url . '/order/created_at/dir/' . $ddir ?>" 
                                                               class="<?php
                                                               if ($ddir == 'created_at')
                                                                   echo $ddir;
                                                               else
                                                                   echo 'sorting';
                                                               ?>">Date Received</a></th>
                                                        <th>Time Received</th>
                                                        <th><a href="<?php echo $url . '/order/wo_number/dir/' . $wdir ?>" class="<?php
                                                            if ($wdir == 'wo_number')
                                                                echo $wdir;
                                                            else
                                                                echo 'sorting';
                                                            ?>">Work Order#</a></th>
                                                        <th><a href="<?php echo $url . '/order/wo_status/dir/' . $stdir ?>"
                                                               class="<?php
                                                               if ($stdir == 'wo_status')
                                                                   echo $stdir;
                                                               else
                                                                   echo 'sorting';
                                                               ?>">Current Status</a></th>
                                                                <th><a href="<?php echo $url . '/order/categoryName/dir/' . $cdir ?>"
                                                               class="<?php
                                                               if ($cdir == 'categoryName')
                                                                   echo $cdir;
                                                               else
                                                                   echo 'sorting';
                                                               ?>">Category</a></th>
                                                        
                                                        <th>Work Request</th>
                                                        <?php /* <th>Contact Information</th> */ ?>
                                                        <th>&nbsp;</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    //echo date("Y-m-d h:i:s");
                                                    if ($this->wolist) {
                                                        $catModel = new Model_Category();

                                                        $psModel = new Model_Schedule();
                                                        $wssModel = new Model_WoScheduleStatus();
                                                        /*                                                         * ********Get notes list ********** */
                                                        $noteModel = new Model_Notes();
                                                        $noteList = $noteModel->getNotes();
                                                        $timezone_Model = new Model_TimeZone();
                                                        $build_model = new Model_Building();
                                                        foreach ($this->wolist as $wl) {
                                                            $tz_build_data = $build_model->getbuildingbyid($wl->building);
                                                              if (isset($tz_build_data[0]['timezone']) && $tz_build_data[0]['timezone'] != 0) {
                                                                $timezone_data = $timezone_Model->getTimeZone($tz_build_data[0]['timezone']);
                                                                $timezone = $timezone_data[0]['time_value'];
                                                                if (isset($timezone))
                                                                    date_default_timezone_set($timezone);
                                                            }

                                                            $schedule = $psModel->getWoSchedule($wl->prioritySchedule, $wl->wo_status);
                                                            $currTime = date("Y-m-d h:i:s A");
                                                            $lastTime = '';
                                                            if ($wl->wo_status == '1') {
                                                                $lastTime = $wl->date_requested . ' ' . $wl->time_requested;
                                                            } else if ($wl->updated_date != '0000-00-00 00:00:00') {
                                                                $lastTime = $wl->updated_date;
                                                            } else
                                                                $lastTime = $wl->created_date;

                                                            $lastTime = date("Y-m-d h:i:s A", strtotime($lastTime));
                                                            $timeDiff = strtotime($currTime) - strtotime($lastTime);

                                                            $time = $schedule[0]['Time'];
                                                            $reminderStatus = $wssModel->getReminderStatus($timeDiff, $time, $schedule[0]['length']);
                                                            ?> 
                                                            <tr>
                                                                <td><?php echo date("m/d/Y", strtotime($wl->date_requested)) ?></td>
                                                                <td><?php echo $wl->time_requested ?></td>
                                                                <td> 
                                                                    <?php if ($closewo_access->is_access == 0) { ?>
                                                                        <?php echo $wl->wo_number ?>
                                                                    <?php } else { ?>
                                                                        <?php echo $wl->wo_number ?>
                                                                    <?php } ?>	     
                                                                    <?php if ($reminderStatus && ($wl->wo_status != '6' || $wl->wo_status != '7')) echo '&nbsp;&nbsp;
                        '; ?>
                                                                </td>
                                                                <td><?php echo $status_array[$wl->wo_status]; ?> <?php
                                                                    if ($wl->wo_status == 1) {
                                                                        $wo_schedule_status = new Model_WoScheduleStatus();
                                                                        $wo_scheduledetails = $wo_schedule_status->getCurrentWorkSchedule($wl->woId);
                                                                        ?> <?php if ($wo_scheduledetails[0]->ckey != '') { ?> 
                                                                            <?php
                                                                        }
                                                                    }
                                                                    ?> </td>
                                                                <td><?php echo stripslashes($wl->categoryName); ?></td>
                                                                <td style='max-width:100px;'>	 
                                                                
                                                                <div class="center">
<div class="text">
<?php
 $descText = strip_tags($wl->work_order_request);
 $descText = str_replace("&nbsp;", ' ', $descText);
 echo substr($descText, 0, 25);
 echo (substr($descText, 30)) ? '...' : '';
?></div>
<?php 
if(strlen($descText)>=30){ ?>
<div class="text-tooltip " ><?php echo $descText;?></div>
<?php } ?>
</div>
                                                             
                                                              
                                                                </td>

                                                                <?php /* <td><?php echo $wl->tenantContact?></td> */ ?>
                                                                <?php
                                                                if ($dashBoardViewsdetails != '') {
                                                                    $dashBoardViewsdetailsoption = $dashBoardViewsdetails[0]->report_option;
                                                                    $dashBoardViewsdetailsoption = explode(',', $dashBoardViewsdetailsoption);
                                                                    
                                                                if ($dashBoardViewsdetails[0]->Report_Type == 'Flash') {
                                                                    $report_type = 'reports/VisionReportEngine/index.php?stimulsoft_client_key=ViewerFx&stimulsoft_';
                                                                }else {
                                                                    $report_type = 'vnsreports/index.php?';
                                                                }
                                                            }
                                                                ?>
                                                                <td><a <?php if ($dashBoardViewsdetails[0]->report_target == 1) { ?> target="_blank"  <?php } ?> href="<?php echo BASEURL; ?><?php echo $report_type; ?>report_key=<?php echo $dashBoardViewsdetails[0]->report_mrt; ?><?php
                                                                        if (in_array('[[++user_id]]', $dashBoardViewsdetailsoption)) {
                                                                            echo '&User=' . $this->userId;
                                                                        }
                                                                        ?><?php
                                                                        if ((in_array('[[++CostCenterNumber]]', $dashBoardViewsdetailsoption))) {
                                                                            echo '&Cost_Center_Number=' . $wl->uniqueCostCenter;
                                                                        }
                                                                        ?><?php
                                                                        if ((in_array('[[++KeyBuildingNumber]]', $dashBoardViewsdetailsoption))) {
                                                                            echo '&buildkey=' . $wl->building;
                                                                        }
                                                                        ?><?php
                                                                        if (in_array('[[++BatchNumber]]', $dashBoardViewsdetailsoption) && $wl->wo_batch != 0) {
                                                                            echo '&Batch_Number=' . $wl->wo_batch;
                                                                        }
                                                                        ?><?php
                                                                        if ((in_array('[[++WONumber]]', $dashBoardViewsdetailsoption))) {
                                                                            echo '&WO_Number=' . $wl->wo_number;
                                                                        }
                                                                        ?><?php
                                                                        if ((in_array('[[++InvoiceNumber]]', $dashBoardViewsdetailsoption)) && $wl->billable_opt == 1) {
                                                                            echo '&Invoice_Number=' . $wl->wo_number;
                                                                        }
                                                                        ?><?php
                                                                        if ((in_array('[[++Status_id]]', $dashBoardViewsdetailsoption))) {
                                                                            echo '&Status=' . $wl->wo_status;
                                                                        }
                                                                        ?>" ><img src="<?php echo BASEURL . 'public/images/printer.png'; ?>" style="width:20px;"></a></td>                                                                                                                                    
                                                                
                                                                <?php
                                                                if(isset($_COOKIE['tenant_version']) 
                                                                 && $_COOKIE['tenant_version']=="23.01" ){
                                                                   
                                                                    ?>
                                                                <td style="background-color:#<?php echo $building_color[$wl->tenant] ?>">
                                                                   
                                                                   <a href="javascript:void(0)" onclick="showWorkOrder('<?php echo $wl->woId ?>')">
                                                                       <i id="plus_<?php echo $wl->woId ?>" class="fa fa-plus blackfont_color plus_min_icon"></i></a>
                                                              
                                                                </td>
                                                              <?php } ?>

                                                            </tr> 
                                                                <tr id="workrequest_<?php echo $wl->woId ?>" style="display:none;" class="tr-order">
                                                                    <td colspan="9" id="order_content_<?php echo $wl->woId ?>" class="order-detail"></td>
                                                                </tr> 
                                                                <?php

                                                        }
                                                    } else {
                                                        ?>
                                                        <tr>
                                                            <td colspan="10">No work order created.</td>
                                                        </tr>
                                                    <?php } ?>
                                                </tbody>
                                                <input type="hidden" name="count" id="count" value="<?php echo $this->count; ?>" >
                                            </table>
                                        </div>
                                        <?php
                                        //if (count($this->wolist) > 0 && !empty($this->wolist)) {
                                        //if ($this->records > 9) {
                                        $params = array();
                                        $params['page'] = '';
                                        if (isset($this->tenant_name) && $this->tenant_name != '') {
                                            $params['tenant_name'] = stripslashes($this->tenant_name);
                                        }
                                        if (isset($this->category_name) && $this->category_name != '') {
                                            $params['category_name'] = stripslashes($this->category_name);
                                        }
                                        if (isset($this->from_date) && $this->from_date != '') {
                                            $params['from_date'] = $this->from_date;
                                        }
                                        if (isset($this->to_date) && $this->to_date != '') {
                                            $params['to_date'] = $this->to_date;
                                        }

                                        //echo $this->paginationControl($this->wolist, 'Sliding', 'pagination.phtml', $params);
                                        // $pageno = $this->pageno;
                                        // $total_pages = $this->total_pages;
                                        // This is for first and previous disabled class
                                        // if ($pageno <= 1) {
                                        //     $disFirstPre = 'disabled';
                                        // } else {
                                        //     $disFirstPre = '';
                                        // }
                                        // // This is for Next and last disabled class
                                        // if ($pageno >= $total_pages) {
                                        //     $disNextLast = 'disabled';
                                        // } else {
                                        //     $disNextLast = '';
                                        // }
                                        ?>
                                      
                                        <?php
                                        //}
                                        //echo $this->count;
                                        ?>
                                    </div>

                                </div>
                                <!-- /.table-responsive --> 
                                <!--Edit Work Order Start-->
                                <div class="row">
                                    <div class="editworkorder">

                                    </div>
                                </div>
                                <!--Edit Work Order End-->
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->
<script>

  


 

// $.ajax({
//                     type: "POST",
//                     url: baseUrl + 'workorder/getdtData',
//                     data: {
//                         tid: '721,725,730',
//                         tenant_buiding:tenant_buiding
                        
//                     },
//                     datatype: 'json',
//                     contentType: "text/plain",
//                     success: function (msg) {                      
                       
                     
                      
//                        // alert(obj.tenant);
//                     }
//         });


    // when page load; for getting las work order
    var tenant_buiding = $('.fdw').attr('bid');
    var tenant_location_info = $('#tenant_data').attr('tenant_location_info');
    $.ajax({
                    type: "POST",
                    url: baseUrl + 'workorder/ajaxworkordernotify',
                    data: {tenant_buiding: tenant_buiding,
                        tenant_location_info:tenant_location_info
                    },
                    datatype: 'json',
                    success: function (msg) {                      
                       
                        obj = JSON.parse(msg);                      
                        $('.fdw').attr('last_work_order',obj.wo_number);
                      
                       // alert(obj.tenant);
                    }
        });


 function reloadPage() {   
        //window.location.reload();
        var tenant_buiding = $('.fdw').attr('bid');
        var tenant_location_info = $('#tenant_data').attr('tenant_location_info');
        console.log(tenant_buiding);
        $.ajax({
                    type: "POST",
                    url: baseUrl + 'workorder/ajaxworkordernotify',
                    data: {tenant_buiding: tenant_buiding,
                        tenant_location_info:tenant_location_info
                    },
                    datatype: 'json',
                    success: function (msg) {

                       var last_work_order_id =  $('.fdw').attr('last_work_order');
                       last_work_order_id = parseInt(last_work_order_id);
                       
                        var obj = JSON.parse(msg);
                        // console.log(obj.tenant);
                        // console.log(obj.wo_number);
                        // console.log(obj.woId);
                        var current_work_order_id = obj.wo_number;
                        current_work_order_id = parseInt(current_work_order_id);
                        if(current_work_order_id != last_work_order_id){
                            //new work order created
                            console.log('new order id '+ current_work_order_id);
                            console.log(current_work_order_id);
                            console.log('last order id '+ last_work_order_id);
                            $('.fdw').attr('last_work_order',current_work_order_id);
                            tenant_location = obj.tenant;
                            $('ul.tenant_tabs li').each(function(){
                             var loc = $(this).attr('tid');
                             if($(this).attr('tid') == obj.tenant){
                                $(this).trigger('click');
                             }

                            });
                        }else{
                            $('.tenant_tabs .resp-tab-active').trigger('click');

                        }
                       // alert(obj.tenant);
                    }
        });

    }
    function scheduleReload(s) {    
        setInterval(reloadPage, s); 

    }
    scheduleReload(15000);// 30000 milliseconds = 30 sec
 </script>   
<?php } else { ?>
    You don't have access for this module.
<?php } ?>

</div>

<script>

    var hash = window.location.hash;
    if (hash != '') {
        hash = hash.replace('#', '');
        showWorkOrder(hash);
    }
</script>

<script>

    function showHistoryDescription(whId) {
        var current_value_description = $('#current_value_' + whId).val();
        current_value_description = stripslashes(current_value_description);
        var change_value_description = $('#change_value_' + whId).val();
        change_value_description = stripslashes(change_value_description);
        if (current_value_description != 'null' && current_value_description != '') {
            $('#work_current_description').html(current_value_description);
        } else {
            var none = '<?php echo HiSTORY_NONE; ?>';
            $('#work_current_description').html("<p style='text-align:center;'>None</p>");
        }
        $('#work_change_description').html(change_value_description);
        $('#add_new_description_div_href').trigger('click');
    }

    function stripslashes(str) {
        str = str.replace(/\\/g, '')
        return str;
    }

   
    function showlimit() {
        var veiw_type = '<?php echo $veiw_type; ?>';
        var limit = $("#show_limit").val();
        if (veiw_type == 'detail') {
            window.location = baseUrl + 'workorder/index/show/view_type/detail/show/' + limit;
        } else {
            //console.log(document.URL);
            window.location = baseUrl + 'workorder/index/show/' + limit;
        }
    }
   // $('#page-wrapper').fadeOut();
    $( document ).ready(function() {
        
     
       setTimeout(function(){ 
        $('.container-right').css('max-width','100%');
        $('.container-right').show(); }, 600);

        
   });

    //$('.container-right').css('max-width','100%');
    
    //Fixed the responsive design issue with Tenant Admin - By Dadhi Vallabh
    //setTimeout(function(){ $('.container-right').css('max-width','100%'); }, 600);
   
    var hash = window.location.hash;
    if (hash != '') {
        hash = hash.replace('#', '');
        showWorkOrder(hash);
    }
</script>

