<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://gmpg.org/xfn/11">
<title>Administrator</title>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/css/jquery-ui.css"/>
<script src="<?php echo BASEURL.'/public'?>/js/jquery-1.9.1.min.js" id="jquery1"></script>
<link href="<?php echo BASEURL.'/public'?>/css/mediaqueries.css" rel="stylesheet">
<script>
var baseUrl='<?php echo $this->baseUrl() ?>';
</script>
<script src="<?php echo BASEURL.'/public'?>/js/jquery-ui.js"></script>
<?php    $this->headLink()->appendStylesheet($this->baseUrl() . '/public/thickbox.css') ?>	
<?php  echo $this->headLink()->appendStylesheet($this->baseUrl() . '/public/style.css') ?>	
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/js/thickbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/js/admin.js"></script>
</head>
<body>
