<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://gmpg.org/xfn/11">
    <?php echo $this->render('new_header.phtml'); ?>
</head>
<body>
<div class='overlay' style='display:none' ></div>
<div id="popup_container" style="display:none" class="ui-draggable alertstyle"><h1 id="popup_title" class="ui-draggable-handle" style="cursor: move;">Vision Work Orders</h1><div id="popup_content" class="alert"><div id="popup_message">Session Time expired1</div><div id="popup_panel">&nbsp;</div></div></div>


<!-- popup code -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" id="error-pop" data-target="#myModaldesign" style="display:none!important;">Open Modal</button>

<!-- Modal -->
<div id="myModaldesign" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false" style="display:none!important;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" onclick="closepop();" class="close" data-dismiss="modal">&times;</button>
        <h2 class="modal-title">Vision Work Order</h2>
      </div>
      <div class="modal-body">
          <p><b>You have been logged out of the Vision System because your login name is being used on another computer.</b></p><br>
        <p><b>NOTE:</b> Vision only allows a login name to be in use by one user at a time. If you have given your credentials to another person, you will need to create a new user for that person.<br>
            If you have not given your user name and password to another user, please change your password.</p>
      </div>
      <div class="modal-footer">
          <center><button type="button" class="btn btn-default" onclick="closepop();" data-dismiss="modal">OK</button></center>
      </div>
    </div>

  </div>
</div>

<!-- second -->


<button type="button" class="btn btn-info btn-lg" data-toggle="modal" id="error-pop1" data-target="#myModaldesign1" style="display:none!important;">Open Modal</button>

<!-- Modal -->
<div id="myModaldesign1" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false" style="display:none!important;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" onclick="closepop();" class="close" data-dismiss="modal">&times;</button>
        <h2 class="modal-title">Vision Work Order</h2>
      </div>
      <div class="modal-body">
          <p><b>Your login will expire in 1 minute, click `Yes`  if you want remain logged in</b></p><br>        
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" onclick="yespop();" data-dismiss="modal">Yes</button>
           <button type="button" class="btn btn-default" onclick="closepop();" data-dismiss="modal">No</button>
      </div>
    </div>

  </div>
</div>



<script type="text/javascript">
jQuery(document).ready(function() { 
	
	var windowHeight = jQuery(window).height() ;
    jQuery('#page-wrapper').css('min-height',( windowHeight - 90 ));
});
</script>
	<?php 
	 
		$userRoleID=Zend_Auth::getInstance()->getStorage()->read()->role_id;
		$firstName =Zend_Auth::getInstance()->getStorage()->read()->firstName;
		$lastName =Zend_Auth::getInstance()->getStorage()->read()->lastName;
		$userId=Zend_Auth::getInstance()->getStorage()->read()->uid;
		


		$logo_image = '';
		if($userRoleID!=1){
			$custId=Zend_Auth::getInstance()->getStorage()->read()->cust_id;
			$acModel = new Model_Account();
			if($custId){
			 $companyDetail = $acModel->getcompany($custId);	 
			 $logo_image = $companyDetail[0]['company_logo'];
		   }
		}
		$img_src='';
		if($logo_image!=''){
			$logo_path = BASE_PATH.'public/images/clogo/'.$logo_image;
			if(file_exists($logo_path))
			{
				$img_src = BASEURL.'public/images/clogo/'.$logo_image;
			}else{
				$img_src = BASEURL.'public/images/logo.png';
			}
		}else{
				$img_src = BASEURL.'public/images/logo.png';
			}
			
	$roleModel = new Model_Role();
    $roleData =  $roleModel->getRole($userRoleID);
	$rData = $roleData[0];
	?>
     <!--<div id="dvLoading"><div class="lod">Loading...</div></div>-->
     <div class="wrapper" id="div_content_load" >     
		 <nav class="navbar navbar-default navbar-fixed-top header" role="navigation" style="margin-bottom: 0">
         
			  <div class="navbar-header avtar">
              <button data-target=".sidebar-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
              <img src="<?php echo $img_src;?>" class="logo img-responsive"/>
			  </div>
			  <ul class="nav navbar-top-links navbar-right my_mid_nav">
			  	<?php if ($rData['title'] == 'VT Admin'){?>
			  	<li><span aria-hidden="true" class="glyphicon glyphicon-user"></span> <label class="my_nw_lb"><?php echo $rData['title'];?> </label></li>
				<?php }else{ ?>
                   <li><span aria-hidden="true" class="glyphicon glyphicon-user"></span> <label class="my_nw_lb"><?php echo stripslashes($firstName).' '.stripslashes($lastName);?> </label> <span class="sec_sp"><?php echo $rData['title'];?>
				   <?php if($userRoleID!=1 && $userRoleID!=9 ){					
					 ?><div class='open_plus popup-plus'><a href="<?php echo ($userRoleID==5 ||$userRoleID==7 )?BASEURL.'tenant/myaccountsetting':'javascript:void(0);'?>" id='myaccount'></a> </div>
				    <?php } ?> </span>  </li>
                <?php } ?>
                   <li><a title="Log Out" href="<?php echo BASEURL.'index/logout/redirect/redirect'?>"><span aria-hidden="true" class="glyphicon glyphicon-log-out"></span> Logout</a></li>
              </ul>
           		 
          <div class="navbar-default navbar-static-side" role="navigation">
                <div class="show-collapes"><i class="glyphicon glyphicon-circle-arrow-right"></i></div> 
                <div class="hide-collapes"><i class="glyphicon glyphicon-circle-arrow-left"></i></div>
              <div class="sidebar-collapse">							
							<?php echo $this->render('new_left.phtml') ?>
				</div>
      <!-- /.sidebar-collapse --> 
    </div>
    <!-- /.navbar-static-side --> 
  </nav>
  <div id="page-wrapper"> 
    <!--Body Top Part start-->
	<!----------Tenant Admin and User Tab Conatiner---->
	<?php echo $this->render('tenant_headertabs.phtml'); ?>
	<!----------Tenant Admin and User Tab Conatiner Added By DVK On 26th Feb 2024---->

							 <?php echo $this->layout()->content ?>
					<div class="clearfix"></div>	                 
                   </div>
             
     <div class="footer">
		  <?php echo $this->partial('new_footer.phtml');?>
     </div>
</div>

<!-- login top right corner pop up for tenant user START -->
<?php  

$myaccount ='';
$myprourl = '';
if($userRoleID!=1 && $userRoleID!=9 ){ 
	if($userRoleID != 5 &&  $userRoleID != 7) {
	$customeAccessmodel = new Model_UserAccess();   
	$accessModel = new Model_Access();
	$material_access = $accessModel->getUserAccessForModule($userRoleID,7);
	$customeAccessmodeld = $customeAccessmodel->getUserCustomAccess($userId,7);
	if($customeAccessmodeld[0]) { 
		$material_access = $customeAccessmodeld[0];
	}
}
$usrModel = new Model_User();
$compModel = new Model_Account();
$usrDetails = $usrModel->getUserById($userId);
$usrDetails = $usrDetails[0];
$compDetails = $compModel->getUserById($usrDetails->cust_id);
$img_url ='';
if($usrDetails->user_img!='') {
	$img_url = BASEURL ."public/user_img/".$usrDetails->user_img;
} else {
	$img_url = BASEURL ."public/user_img/user_128.png";
}
$myaccount = "<div><div class='popup-left'>".stripslashes($usrDetails->firstName).''.stripslashes($usrDetails->lastName)."<br>". $rData['title']. "<br>". $usrDetails->email . "<br>". $compDetails['companyName']. "</div><div class='popup-right'><img src='".$img_url."' alt='User Pic'> </div>";
if($userRoleID == 5 ||  $userRoleID == 7 ) {
	$myaccount .= "<div><button class='popup-btn'  onclick='myaccountinfo()'>My Account</button></div>";
} else {
	if($material_access->is_read == 1) {
		$myaccount .= "<div><button class='popup-btn'  onclick='myaccountinfo()'>My Account</button></div>";
	}
}
$myaccount .="</div>"; 
if($userRoleID == 5 ||  $userRoleID == 7) {
	$myprourl = BASEURL."tenant/tenantuser";
} else {
	$myprourl = BASEURL."company/users";
}
}  



?>


 <script>
var tenanturl= "<?php echo $myprourl; ?>";
var content = "<?php echo $myaccount; ?>"; 
$(document).ready(function(){
    $('#myaccount').popover({content: content, html: true, placement: "bottom"}); 
});

function myaccountinfo() {
	window.location.assign(tenanturl)
}
</script>
<!-- Login Top right corner pop end -->





<script>
/*$(window).load(function() {
	$("#div_content_load").fadeIn("slow");
	$("#dvLoading").fadeOut("slow");
})*/
</script> 
<!-- Page-Level Plugin Scripts - Tables --> 
<script src="<?php echo BASEURL.'/public'?>/js/plugins/dataTables/jquery.dataTables.js"></script> 
<script src="<?php echo BASEURL.'/public'?>/js/plugins/dataTables/dataTables.bootstrap.js"></script>

<!--Plug-in Initialisation--> 

</body>
</html>
