<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://gmpg.org/xfn/11">
    <?php echo $this->render('new_header.phtml'); ?>
</head>
<body style="padding-top:0px;">
	<?php 
	 
		$userRoleID=Zend_Auth::getInstance()->getStorage()->read()->role_id;
		$firstName =Zend_Auth::getInstance()->getStorage()->read()->firstName;
		$lastName =Zend_Auth::getInstance()->getStorage()->read()->lastName;
		


		$logo_image = '';
		if($userRoleID!=1){
			$custId=Zend_Auth::getInstance()->getStorage()->read()->cust_id;
			$acModel = new Model_Account();
			if($custId){
			 $companyDetail = $acModel->getcompany($custId);	 
			 $logo_image = $companyDetail[0]['company_logo'];
		   }
		}
		$img_src='';
		if($logo_image!=''){
			$logo_path = BASE_PATH.'public/images/clogo/'.$logo_image;
			if(file_exists($logo_path))
			{
				$img_src = BASEURL.'public/images/clogo/'.$logo_image;
			}else{
				$img_src = BASEURL.'public/images/logo.png';
			}
		}else{
				$img_src = BASEURL.'public/images/logo.png';
			}
			
	$roleModel = new Model_Role();
    $roleData =  $roleModel->getRole($userRoleID);
	$rData = $roleData[0];
	?>
     <!--<div id="dvLoading"><div class="lod">Loading...</div></div>-->
     <div class="wrapper" id="div_content_load" >     
  <div id="page-wrapper_"> 
    <!--Body Top Part start-->
    
							 <?php echo $this->layout()->content ?>
						                 
                   </div>
             
</div>
<script>
/*$(window).load(function() {
	$("#div_content_load").fadeIn("slow");
	$("#dvLoading").fadeOut("slow");
})*/
</script> 
<!-- Page-Level Plugin Scripts - Tables --> 
<script src="<?php echo BASEURL.'/public'?>/js/plugins/dataTables/jquery.dataTables.js"></script> 
<script src="<?php echo BASEURL.'/public'?>/js/plugins/dataTables/dataTables.bootstrap.js"></script>

<!--Plug-in Initialisation--> 
<script> 
$(function() { 
	$('.paginate_button').click(function(){ 
	parent.CheckForSessionpop(baseUrl);   
}); 
	$("input, select, textarea, radio, checkbox").change(function(){
		parent.CheckForSessionpop(baseUrl);
    });  
});

</script>
</body>
</html>
