<body>
    <p>Hi <?php echo $this->firstname; ?> <?php echo $this->lastname; ?>,</p>
    <p>A password reset request has been received for your login at <?php echo $this->email; ?>.</p>
    <p>To reset your password, please follow this link: 
	<div id ="check">
        <a href="<?php echo BASEURL."index/resetpassword/id/".$this->passkey;?>" target = "blank" mc:disable-tracking> 
            <?php  echo BASEURL."index/resetpassword/id/".$this->passkey; ?>
        </a>
		</div>
    </p>
    <p>Thanks!</p>
</body>
