<?php
$img_src = ($this->companyLogo) ? $this->companyLogo : 'nologo.png';
$view_image_path = BASEURL . 'public/images/clogo/' . $img_src;
?>
<body>
    <div class="reset-password-wrap">
    <div class="companyLogo"><img src="<?php echo $view_image_path; ?>"></div>
    <span class="title-name"><p>Hi <?php echo $this->firstname; ?> <?php echo $this->lastname; ?>,</p></span>
    <p>Account Users</p>
    <P>User Name : <?php echo $this->userName; ?></P>
    <p>E-mail    : <?php echo $this->email; ?></p>
    <p>A password reset request has been received for your login at <?php echo $this->email; ?>.</p>
    <p>To reset your password, please follow this link: 
    <div id ="check" class="check-wrap">
        <a href="<?php echo BASEURL . "index/resetpassword/id/" . $this->passkey; ?>" target = "blank" mc:disable-tracking> 
            <?php //echo BASEURL . "index/resetpassword/id/" . $this->passkey; ?><button class="btn reset">Click here to reset your password</button>
        </a>
    </div>
</p>
<span class="thanks-wrap"><p>Thanks!</p></span>
</div>
    <style>
        .companyLogo { text-align: center; }
        .reset-password-wrap { max-width: 425px; }
        .companyLogo img { max-width: 150px; }
        .check-wrap .btn { background-color: green; color: white; padding: 15px; text-align: center; width: 100%; border: 0px;  margin-top: 20px;  cursor: pointer !important; }
        .check-wrap a { text-decoration: none; }
        .title-name p { font-weight: 600;
    margin-bottom: 30px;
    margin-top: 20px; }
        .reset-password-wrap p { font-size: 14px; margin: 8px 0px; }
        .thanks-wrap p { font-weight: 600;  margin-top: 50px; }
    </style>
</body>
